[40122] Various E-Mail clients don't support embedded images
opf/openproject pull request #10027
Opened 2022-01-10 12:55 UTC by HDinger

Use inline attachments instead of embedded images in mails for better support. It seems like the inline attachments have a better support for Gmail, but are worse in other clients (e.g mac mail). It my be worth to merge nevertheless, but I propose to test it properly. 

[OP#40122](https://community.openproject.org/projects/openproject/work_packages/40122/activity)

2022-01-12 14:48 UTC, ulferts requested changes
The support for the inline attachment base approach does not seem to be better compared to the embedded approach based on what I tested.

While testing however, I played around with png (opposed to svg) images which seem to be supported way better by the web clients at least:

![image](https://user-images.githubusercontent.com/617519/149162642-dfeadcbb-d0cb-4962-b27e-8df7386bd3ff.png)

The one on top has an inline svg, the one on the bottom an inline png. So this might be something to investigate further.

2022-04-07 15:46 UTC, cbliard commented
Sorry, I think I did a mistake... I rebased on dev and forced push.

2022-04-07 15:54 UTC, cbliard commented
I fixed my mistake

2022-04-07 16:04 UTC, cbliard commented
I just tested it with GMail and the image is still not displayed properly.

![image](https://user-images.githubusercontent.com/176055/162246470-73c80eda-66cd-45fc-aa29-8b9d9b1419e4.png)

I'll set the work package to "test failed"

2022-04-12 08:55 UTC, HDinger commented
Closing in favour of https://github.com/opf/openproject/pull/10478

2022-04-12 08:55 UTC, closed without merging