Redirect to first saved team planner if any
opf/openproject pull request #10076
Opened 2022-01-20 08:58 UTC by oliverguenther

2022-01-20 12:19 UTC, oliverguenther commented on frontend/src/app/shared/components/modals/save-modal/save-query.modal.ts
> +    $event.preventDefault();
I stumbled upon this by testing. The regular form is still submitted and causes a navigation change, but that is usually cancelled by ui-router.

2022-01-21 08:21 UTC, HDinger requested changes
I found only one issue: When I create a new team planner und modify it without saving, all changes are gone as soon as I reload because I get redirected to the first team planner.

2022-01-25 08:25 UTC, oliverguenther commented
@HDinger fixed that one issue. It should be sufficient to check for existence of query_props or a query_id to avoid the redirect.

2022-02-02 06:54 UTC, HDinger approved these changes

2022-02-02 21:33 UTC, merged