Some API fixes discovered while experimenting with OpenAPI Generator generated client library
opf/openproject pull request #10175
Opened 2022-02-13 05:07 UTC by gohrner

While playing with the OpenProject API spec and the OpenAPI Generator for the last one or two months, I stumbled across quite a few problems with the API spec.

Some of the issues meanwhile have already been ironed out upstream - in these cases I was too slow to push my adjustments - but several of the problems still persist.

Please show some patience, as I'm not yet very experienced with OpenAPI V3.

See also: https://community.openproject.org/topics/14323

2022-02-14 15:02 UTC, Kharonus requested changes
Many thanks again for your dedicated work. I have added some comments and requested some changes.

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/paths/work_packages.yml
>            example:
you can remove the example here, too. There is an example defined in `work_package_model.yml`, and due to the `$ref` any siblings are ignored nevertheless.

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/paths/work_package.yml
>            example:
same here, please remove example.

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/paths/work_package_activities.yml
> -            "$ref": "../components/schemas/work_package_activities_model.yml"
nesting the ref in a collection here is wrong, as the `work_package_activities_model.yml` is already meant to be a collection. (Even if it is currently still an object without schema, only with example.) Please revert.

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/components/schemas/link.yml
> +    type: object
Can you provide an example endpoint, where we actually do return an object here in payload?

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
>        attachments:
`attachments` is indeed no collection of links, but just a single link to the attachments collection, please revert

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
>        watchers:
`watchers` is no collection of links, but a single link that points to a collection ressource, please revert.

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
> +              Array of all visible children of the work package
the description no longer matches. It should instead be s.th. like 

`A visible child work package of the current work package.`

conditions are the same, resource is `WorkPackage`

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
> +              Array of all visible ancestors of the work package, with the root node being the first element
the description no longer matches. It should instead be s.th. like

A visible ancestor work package of the current work package.

conditions are the same, resource is WorkPackage

2022-02-14 15:02 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
> +          - description: Collection of predefined changes that can be applied to the
the description no longer matches. It should instead be s.th. like

A predefined action that can be applied to the work package.

**Resource**: CustomAction

2022-02-20 20:48 UTC, gohrner commented on docs/api/apiv3/components/schemas/link.yml
> +    type: object
The "problem" is that in many cases, structured JSON objects are contained, not "naked" JSON strings, which would be what's expected with type "string".

One example taken from https://www.openproject.org/docs/api/endpoints/work-packages/#create-work-package :


```json
"payload": {
   "user": {
      "href": "/api/v3/users/{user_id}"
   }
},
```

2022-02-21 07:55 UTC, Kharonus commented on docs/api/apiv3/components/schemas/link.yml
> +    type: object
you're absolutely right. checked that code in production, too. payload must be `object`

2022-03-22 16:04 UTC, Kharonus requested changes
Formatting and a small improvement plea.

2022-03-22 16:04 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
>            - "$ref": "./link.yml"
Please check your formatter for `yaml` files. While it is not needed for yaml syntax, I try to harmonize most of our yaml files to one style. and within this style, a list should be indented by 2 spaces from its parent. Applying here on the `allOf` objects.

2022-03-22 16:04 UTC, Kharonus commented on docs/api/apiv3/paths/work_packages.yml
> +          "$ref": "../components/schemas/work_package_model.yml"
can you replace the response body with the `$ref`, too, please?

Just, FYI: I started on file links with introducing a separation of read and write models. This will eventually take place here, too. But for now, we just reference the `work_package_model.yml` for the request and the response body.

2022-03-23 19:07 UTC, gohrner commented on docs/api/apiv3/components/schemas/work_package_model.yml
>            - "$ref": "./link.yml"
Actually all the files were manually formatted, as my yaml editor simply messes up the existing formatting. :-/

Which editor do you use / can you recommend?

Anyway, formatting should be better now (I hope).

2022-03-23 19:11 UTC, gohrner commented on docs/api/apiv3/paths/work_packages.yml
> +          "$ref": "../components/schemas/work_package_model.yml"
Mh, not quite sure what you're referring to - all schemas the `responses` section already are `$ref`s, as far as I can tell. (There are verbose `examples` included there, are you referring to these?)

I also could not find a `responseBody` in the OpenAPI documentation, in contrast to `requestBody`.

2022-03-28 07:46 UTC, Kharonus commented on docs/api/apiv3/components/schemas/work_package_model.yml
>            - "$ref": "./link.yml"
I can recommend the JetBrains tools, but they are not OpenSource or free to use. They do have a some subscriptions for free, e.g. if you are a student, teacher or working for non-commercial OpenSource projects.

This should not be some advertising, hence I won't link to their pricing page in one of our public PRs. ;) But as you asked me, what I can recommend, I find their IDEs the most intuitive and powerful ones. And they have in-built formatting support for all relevant formats, which can read `.editorconfig` and overwrite it locally, too.

If you want to go really specialized, you can of course run VS Code (MIT-License, completely free and OpenSource), and configure it to the right job for you. This editor is one of the most popular, for good reason.

2022-03-28 07:50 UTC, Kharonus commented on docs/api/apiv3/paths/work_packages.yml
> +          "$ref": "../components/schemas/work_package_model.yml"
you are right, I was apparently too tired that day, to see, that the whole clutter is just the example. response bodies in OpenAPI are what is defined in https://swagger.io/specification/#response-object > content/[mime-type]/schema.

2022-03-28 07:52 UTC, Kharonus approved these changes
LGTM

2022-03-28 07:53 UTC, merged