Task/40984 add cards view to work packages view
opf/openproject pull request #10171
Opened 2022-02-11 17:36 UTC by JanKeppler

2022-02-13 10:34 UTC, birthe commented on docs/user-guide/gantt-chart/README.md
> +| [Create a new element]( #create-a-new-element-in-the-gantt-chart) | How to add a new item to the Gantt chart?                    |
remove space in fron ot #

2022-02-13 10:36 UTC, birthe commented on docs/user-guide/work-packages/README.md
The # in front of the links need to be removed since they don't link to a bookmark on the same page but to a child page.

2022-02-13 11:21 UTC, birthe requested changes
Hi @JanKeppler, thanks for adding this topic. I have added a few comments and suggestions. Please have a look. It should be ready to merge then.

2022-02-13 11:21 UTC, birthe commented on docs/user-guide/work-packages/work-package-relations-hierarchies/README.md
> +- **Duplicates / Duplicated by** - This option indicates that the work package A duplicates a work package B in one way or another, for example both address the same task. This can be useful if you h
Is this really correct? If I add a relation duplicates or duplicated by, also the status won't be changed automatically, isn't it? Could you please check this?

2022-02-13 11:23 UTC, birthe commented
HI @JanKeppler also, these changes can go directly in the Relase branch since they are already productive. You can change the base branch by clicking Edit on top right next to the PR name.

2022-03-15 11:55 UTC, as-op requested changes

2022-03-15 11:55 UTC, as-op commented on docs/user-guide/work-packages/work-package-views/README.md
> +<video src="/Users/jankeppler/Desktop/Bildschirmaufnahme 2022-02-11 um 18.11.56.mov"></video>
This video is only on your computer and it will not work in many browsers, since mov is not supported by many. Please create animated gifs.

2022-03-24 09:46 UTC, closed without merging