Added a feature test for ProjectStorage to check deletion of FileLinks
opf/openproject pull request #10213
Opened 2022-02-23 11:20 UTC by fraber

2022-02-23 11:25 UTC, wielinde commented on modules/storages/spec/features/delete_project_storage_and_file_links_spec.rb
> +  let(:admin) { create(:admin) }
Better to check with a real member of the project with a role having and not having the needed permissions so that this integration test also covers the contracts.

2022-02-23 11:26 UTC, wielinde commented on modules/storages/spec/features/delete_project_storage_and_file_links_spec.rb
> +  let(:file_link) { create(:file_link, storage: storage, container_id: work_package.id) }
```suggestion
  let(:file_link) { create(:file_link, storage: storage, container: work_package) }
```
Does the same but looks somewhat nicer.

2022-02-23 11:27 UTC, wielinde commented on modules/storages/spec/features/delete_project_storage_and_file_links_spec.rb
> +    # The objects defined by let(...) above are lazy instantiated, so we need
```suggestion
    # The objects defined by let(...) above are lazily instantiated, so we need
```

2022-02-25 18:09 UTC, Kharonus requested changes
just some small amendments needed

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/controllers/storages/admin/projects_storages_controller.rb
> +
Handle failure case in service.

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/controllers/storages/admin/projects_storages_controller.rb
Error handling?

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/services/storages/project_storages/create_service.rb
> +# Copyright (C) 2012-2021 the OpenProject GmbH
2022

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/services/storages/project_storages/delete_service.rb
> +# Copyright (C) 2012-2021 the OpenProject GmbH
2022

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/services/storages/project_storages/delete_service.rb
> +#-- encoding: UTF-8
not needed

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/services/storages/project_storages/delete_service.rb
> +      # Delete associated FileLinks
obsolete comment

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/services/storages/project_storages/set_attributes_service.rb
> +# Copyright (C) 2012-2021 the OpenProject GmbH
2022

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/app/services/storages/project_storages/update_service.rb
> +# Copyright (C) 2012-2021 the OpenProject GmbH
2022

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/spec/contracts/storages/project_storages/create_contract_spec.rb
> +#-- encoding: UTF-8
remove

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/spec/contracts/storages/project_storages/create_contract_spec.rb
> +# Copyright (C) 2012-2021 the OpenProject GmbH
2022

2022-02-25 18:09 UTC, Kharonus commented on modules/storages/spec/features/create_and_delete_project_storage_spec.rb
> +  let(:user) { create(:admin) }
user is still created as admin

2022-03-01 15:19 UTC, Kharonus approved these changes
LGTM

2022-03-01 15:20 UTC, merged