[#39450] Custom Field User Not available in Filter
opf/openproject pull request #10450
Opened 2022-04-06 14:34 UTC by fraber

https://community.openproject.org/work_packages/39450

I've re-enabled custom fields of type "User" to act as filters in global work_packages 
report:

Custom fields of type "User" and "Version" were excluded in 2018 by Jens from
appearing in the global work_packages reports. I guess that's because their values
are set per-project.
However, it seems that the current "principal" endpoint now returns the global list of
users in this case, so that a filter of type "User" works correctly, at least on my dev
installation.

2022-04-07 08:36 UTC, fraber commented
I've checked with a simple user, and this user also gets the list of all users in the system as options for the filter value.

2022-04-07 15:16 UTC, ulferts requested changes
Should be working @fraber. I am a bit hesitant when it comes to the implication of potentially loading 1000 users through this field but that is something we have the tools to handle later on by now.

What is missing is a feature spec. Add that and I will merge the PR.

2022-04-19 15:16 UTC, fraber commented
Hi @ulferts, added the feature spec. I hope I wasn't too verbose with the comments...

2022-04-27 13:59 UTC, ulferts requested changes
Since I reviewed #10552 before, I checked for the same scenario and this feature now suffers from the same bug. In this case, the change needs to be made in https://github.com/opf/openproject/blob/dev/app/models/custom_field.rb#L295 where again the `.visible` scope needs to be used.

2022-05-05 09:11 UTC, fraber commented
Hi @ulferts, I've included the new scope for user-ranging custom fields as you proposed.
I was able to reproduce the issue as described here:
https://community.openproject.org/projects/openproject/work_packages/41934/activity
I confirm that this error message has gone after changing the scope to .visible.

2022-05-05 09:27 UTC, fraber commented
Writing a spec now to test for regression.

2022-10-10 12:37 UTC, closed without merging