[#40196] check and update the notifications api documentation
opf/openproject pull request #10468
Opened 2022-04-11 09:20 UTC by Kharonus

- https://community.openproject.org/work_packages/40196
- renamed collection model
- reworked examples and object definitions
- small refactorings to remove linter warnings (#paths/projects_work_packages)

The file `docs/api/apiv3/paths/project_work_packages.yml` was only reworked to harmonize style and remove linter warnings. No functional changes were made.

2022-04-12 08:17 UTC, cbliard requested changes
There are things missing:
- api endpoints documentation to update read/unread status of notifications:
  - `post /api/v3/notifications/{id}/readIAN`
  - `post /api/v3/notifications/{id}/unreadIAN`
  - `post /api/v3/notifications/readIAN` (bulk update)
  - `post /api/v3/notifications/unreadIAN` (bulk update)
- links in `NotificationModel`
  - `unreadIAN` is missing, and is present when notification is read
  - `readIAN` is in required category, but in fact it will be absent if notification is read. Not sure how it should translate in openapi.

Apart from that, it looks good. I like that you ordered the keys in the yml to make the name of parameters first, or the description, summary, operationId and tags first. It makes the yml easier to read :+1:

2022-04-12 08:27 UTC, cbliard commented
and I wonder if `docs/api/apiv3/tags/notifications.yml` should be updated too to add the `read` and `unread` links in the "Actions" section.

2022-04-12 16:03 UTC, cbliard requested changes

2022-04-12 16:03 UTC, cbliard commented on docs/api/apiv3/paths/notifications.yml
> +  operationId: Get_Notification_Collection
For consistency with other operations on other resources, it should be `List_Notifications`

2022-04-12 16:03 UTC, cbliard commented on docs/api/apiv3/paths/notification.yml
> +  operationId: Get_Notification
For consistency with other operation names, `operationId` should be `View_notification`

2022-04-12 16:03 UTC, cbliard commented on lib/api/v3/notifications/notification_representer.rb
> -        property :subject
This broke some unit tests testing for `subject` presence.

2022-04-13 09:31 UTC, Kharonus commented on lib/api/v3/notifications/notification_representer.rb
> -        property :subject
fixed, and readded self link, but without title

2022-04-13 11:31 UTC, Kharonus commented on docs/api/apiv3/paths/notification.yml
> +  operationId: Get_Notification
fixed

2022-04-13 11:39 UTC, Kharonus commented on docs/api/apiv3/paths/notifications.yml
> +  operationId: Get_Notification_Collection
fixed

2022-04-13 11:39 UTC, Kharonus commented
@cbliard so, lets see, if I finally can satisfy you ;)

2022-04-13 13:57 UTC, cbliard approved these changes
Perfect 👌

2022-04-13 13:57 UTC, merged