[41718] Filter query filter values in the frontend
opf/openproject pull request #10490
Opened 2022-04-13 07:05 UTC by oliverguenther

If we loaded all values in the first run, filter them in the frontend. The backend does not provide queries and typeahead filters for all resources, and we can avoid additional requests if we just filter them here.

Note that if more than the max API size items are returned, and the backend does not provide any filtering, this will result in all items being shown at all times.

https://community.openproject.org/wp/41718

2022-04-13 07:08 UTC, oliverguenther commented
Hi @ulferts , this quickfixes the query filters from a frontend perspective. The full solution would be to extend the backend to provide typeahead filters as well. But this might not be feasible in 12.1 for some of the resources such as categories, as they do not even have a query yet. Yet, we should keep the linked bug open for that edge case.

2022-04-13 11:00 UTC, HDinger requested changes
It does some filtering when typing a search text. However, the results seem to have nothing to do with the text I searched for.

<img width="952" alt="Bildschirmfoto 2022-04-13 um 12 59 57" src="https://user-images.githubusercontent.com/7457313/163166369-f5bd03e5-cdb1-434b-bc14-a8128d12a1de.png">

2022-04-14 08:16 UTC, oliverguenther commented
@HDinger I reverted back to non-fuzzy search

2022-04-19 08:12 UTC, HDinger approved these changes
👍

2022-04-19 08:12 UTC, merged