[41942] Comment numbers are cut off on mobile
opf/openproject pull request #10512
Opened 2022-04-18 06:12 UTC by bsatarnejad

Increase the value of right, so when the screen size is reduces, it won't be affected.

2022-04-19 09:35 UTC, bsatarnejad commented
The test is red here on PR, but when i test it locally it is green.

2022-04-19 11:15 UTC, HDinger requested changes
I am not quite sure whether changing the position of the number is the right approach here. It looks more like the whole content is a bit too far to the right. There is also a separate ticket for that, so maybe you can catch both errors in one run..
https://community.openproject.org/projects/openproject/work_packages/42031/activity

2022-04-19 11:15 UTC, HDinger commented on frontend/src/global_styles/content/work_packages/tabs/_activities.sass
> +  right: 5px
This affects the desktop screen sizes as well, resulting in the numbers being not aligned with the sub-headers any more:
<img width="65" alt="Bildschirmfoto 2022-04-19 um 13 07 07" src="https://user-images.githubusercontent.com/7457313/163990690-33cf5600-9135-44c7-80ac-5f6479c93152.png">

2022-04-20 07:02 UTC, HDinger commented
Removing the the padding from the `content-wrapper` does't work either, because that results in some elements having no spacings at all:
<img width="290" alt="Bildschirmfoto 2022-04-20 um 09 01 54" src="https://user-images.githubusercontent.com/7457313/164169723-6a8d80e7-6359-4780-8771-95abe1750204.png">


I am therfore closing this in favour of https://github.com/opf/openproject/pull/10521

2022-04-20 07:02 UTC, closed without merging