[40930] Use lft column for ordering projects
opf/openproject pull request #10562
Opened 2022-04-26 20:14 UTC by oliverguenther

https://community.openproject.org/work_packages/40930

2022-04-27 11:02 UTC, dombesz commented
@oliverguenther The sub-projects are ordered correctly now, but the main projects seem to be out of order. (Ordered by id)
Project picker:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/83396/165504191-15b20738-5684-4480-9538-9bfb23807711.png">


Projects: (not ok)
<img width="484" alt="image" src="https://user-images.githubusercontent.com/83396/165503825-f4d0aaba-f64d-4c0e-a20b-6721f796b8d9.png">


Sub-projects: (are ok)

<img width="527" alt="image" src="https://user-images.githubusercontent.com/83396/165504330-c58266a5-7b69-4b06-8090-31c0bf105129.png">

2022-04-27 11:03 UTC, dombesz requested changes, later dismissed
@oliverguenther The sub-projects are ordered correctly now, but the main projects seem to be out of order. (Ordered by id)
Project picker:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/83396/165504191-15b20738-5684-4480-9538-9bfb23807711.png">


Projects: (not ok)
<img width="484" alt="image" src="https://user-images.githubusercontent.com/83396/165503825-f4d0aaba-f64d-4c0e-a20b-6721f796b8d9.png">


Sub-projects: (are ok)

<img width="527" alt="image" src="https://user-images.githubusercontent.com/83396/165504330-c58266a5-7b69-4b06-8090-31c0bf105129.png">

2022-04-27 12:00 UTC, oliverguenther commented
Hi @dombesz , the PR does not take care of any existing project sorts. There is a migration though that will correct this when upgrading to 12.1.

You can simply redo that migration by running `Projects::ReorderChildrenJob.perform_now`

Best
Oliver

2022-04-29 07:47 UTC, ulferts commented
:+1: looks good

@dombesz thanks for the thorough testing.

2022-04-29 07:47 UTC, merged