[#38672] Project members shown repetitively in member page if a group filter is active
opf/openproject pull request #10599
Opened 2022-04-29 09:26 UTC by fraber

https://community.openproject.org/work_packages/38672

… (and the user is in several groups that have a membership role).

Added a "select distinct * from (...)" around the results of MemberQuery in order to eliminate multiple rows returned by the group filter in MemberQuery if a user belongs to multiple groups.
Also added a brand new spec for MemberQuery testing the happy path and the regression of this bug.

2022-05-04 14:39 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +      member.save
`.save` should not be necessary

2022-05-04 14:41 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +        expect(instance.results.to_sql).to eql base_scope.to_sql
hmm, you are comparing one intransparent magic with another intransparent magic. The test is not obvious. I am not a big fan of comparing SQL here. Can't we simply check what the results are and in which order they appear, etc.?

2022-05-04 14:42 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +  let(:base_scope) { Member.from(Member.all.distinct, :members).order(id: :desc) }
Can we find a better name for `base_scope`? Or drop the idea of comparing SQL all together?

2022-05-04 14:43 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +        expect(instance.results.count).to eq 1
maybe adding another `expect` to check that the expected user is part of the result set?

2022-05-04 14:46 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +      member.save
no need for `.save`

2022-05-04 14:47 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +      Groups::UpdateService.new(user: admin, model: group1).call(user_ids: Array(admin.id))
```suggestion
      Groups::UpdateService.new(user: admin, model: group1).call(user_ids: [admin.id])
```

2022-05-04 14:47 UTC, wielinde commented on spec/models/queries/members/member_query_spec.rb
> +      Groups::UpdateService.new(user: admin, model: group2).call(user_ids: Array(admin.id))
same as above

2022-05-04 14:49 UTC, wielinde requested changes
@fraber Please find may comments in the code. You propably also want Jens to review this PR.

2022-05-06 10:52 UTC, fraber commented
Hi @ulferts , Wieland mentioned it would be a good idea if you could have a look at this PR.

2022-05-06 15:50 UTC, ulferts commented
Hi @fraber applying `DISTINCT` to a query has the disadvantage in PostgreSQL that every field listed in the `ORDER BY` of the query will have to appear in the list that is checked DISTINCT on (e.g. `SELECT DISTINCT id FROM members ORDER BY created_at` will break). Applying a distinct will in my experience result in added complexity when one tries to either remove the distinct again to get around the limitation or one tries to manipulate to projection part.

In this case, the fix might be simpler though I don't know if anything will break:  
In my very brief test, removing all of https://github.com/opf/openproject/blob/dev/app/models/queries/members/filters/group_filter.rb#L32-L39 fixed the problem. I assume (don't know any more since it has been a while) that the included `Queries::Filters::Shared::GroupFilter` used to be implemented differently. The uselessly overwritten `joins` method strongly suggests that.

2022-07-20 21:09 UTC, jngrb commented
@wielinde, @fraber, @ulferts, as creator of the bug report [OPENPROJECT 38672](https://community.openproject.org/projects/openproject/work_packages/38672), I would like to know if this PR is ready to be merged or if there are still changes to be made.

2022-07-21 07:24 UTC, wielinde commented
@jngrb No, unfortunately it is not ready to merge. The review feedback from @ulferts is valid and needs to be addressed first by @fraber.

2022-07-22 17:20 UTC, fraber commented
@jngrb , sorry, vacation time has started. I'd expect me/us to finish the issue in about 3-4 weeks (mid-August).

2022-08-19 08:07 UTC, fraber commented
@ulferts , I implemented [your proposed change](https://github.com/opf/openproject/pull/10599#issuecomment-1119760161) for Queries::Members::Filters::GroupFilters above. Your suggestions successfully fixed the reported issue in the /projects/<id>/members page.

Then I did quite a bit of manual testing in all places where GroupFilter was used and found that your proposed change broke the API call /api/v3/memberships when using with filters=[{"group":{"operator":"=","values":["17"]}}]:
```
PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "users"
LINE 1: SELECT COUNT(*) FROM "members" WHERE (users.id IN (SELECT "u...
```

So I've added the required **.joins(:principal)** back to Queries::Members::Filters::GroupFilter,
together with the other options from the base class to handle from, joins and left_outer_joins (not sure about this...)

I did another round of testing to make sure that both the breaking API and the regression case are covered by specs (spec/models/queries/members/member_query_spec.rb).

After a rebase to current dev I got an issue manually testing in /projects/<id>/members with the same error message as in the API call above. The .joins(:principal) fixed this in the same way as it did with the API call. However, this issue disappeared after a while, so I couldn't write a spec for it. I understand the issue would be detected by the spec/feature/members/ suite.

2022-10-10 12:37 UTC, closed without merging