OAuth settings of Nextcloud in OpenProject
opf/openproject pull request #10602
Opened 2022-04-29 14:58 UTC by wielinde

- Added storages.oauth_client_id and _secret and improved host checking error handling
- Storage form with JS to enable OAuth2 client_secret on demand
- update base_contract

https://community.openproject.org/projects/openproject/work_packages/40375

2022-05-24 11:46 UTC, Kharonus requested changes
a few change requests and some questions.

2022-05-24 11:46 UTC, Kharonus commented on app/contracts/oauth_clients/concerns/manage_storages_guarded.rb
> +    module ManageStoragesGuarded
maybe that name is misleading? No storage permission checked in here at all. It just checks for the user to be an active admin.

2022-05-24 11:46 UTC, Kharonus commented on app/contracts/oauth_clients/create_contract.rb
> +    include ::OAuthClients::Concerns::ManageStoragesGuarded
same include as in line 32. usually I prefer the more specific namespace definition, that starts with root.

2022-05-24 11:46 UTC, Kharonus commented on modules/storages/app/controllers/storages/admin/storages_controller.rb
>        .require(:storages_storage)
why is this such a weird double named symbol?

2022-05-24 11:46 UTC, Kharonus commented on modules/storages/app/models/storages/storage.rb
> +  # A storage authenticates at a storage via OAuth.
confusing comment: more like `A storage authenticates at its remote origin via OAuth.` You can elaborate even a bit more, to make clear, what is "our" storage and what is "the remote storage".

2022-05-24 11:46 UTC, Kharonus commented on app/models/oauth_client.rb
> +  belongs_to :integration, polymorphic: true
is this relation optional?

2022-05-25 14:01 UTC, wielinde commented on app/contracts/oauth_clients/create_contract.rb
> +    include ::OAuthClients::Concerns::ManageStoragesGuarded
Well spotted. Tx.

2022-05-25 14:01 UTC, wielinde commented on app/contracts/oauth_clients/concerns/manage_storages_guarded.rb
> +    module ManageStoragesGuarded
You are right.

2022-05-25 14:02 UTC, wielinde commented on modules/storages/app/controllers/storages/admin/storages_controller.rb
>        .require(:storages_storage)
I believe that is due to the name spacing in the routes.

2022-05-31 09:46 UTC, Kharonus approved these changes
code LGTM

2022-06-01 15:43 UTC, merged