Project autocompleter with hierarchy
opf/openproject pull request #10674
Opened 2022-05-12 12:10 UTC by b12f

Closes https://community.openproject.org/projects/openproject/work_packages/40286/activity

2022-05-13 11:03 UTC, HDinger reviewed
The approach is fine for me, but since I was part of the development I'd say we let @oliverguenther have a look as well.

2022-05-16 16:42 UTC, oliverguenther commented
Can we internally make use of `op-autocompleter` again as the component we wrap, and pass in templates like we do in other places? https://github.com/opf/openproject/blob/dev/frontend/src/app/features/user-preferences/notifications-settings/inline-create/notification-setting-inline-create.component.html#L23

This avoids us applying fixes already fixed in op-autocompleter, such as initially triggering the typeahead to search and repositioning during opening the dropdown.

2022-06-16 09:18 UTC, HDinger requested changes
There are some things not working as specified:

- [x] The current search term is not highlight in the results
- [x] Changing the project of a work package on a work package list column is not working
- [x] Two of the project filters (on boards) find too many results. They should only find subprojects of the current project
  - [x] "including subprojects"
  - [x] "only subproject"
- [x] In the invite user modal, the dropdown is misplaced
- [x] All of the autocompleters in the "admin -> users" sections find too many results. Those projects that are already selected, should not be selectable again
  - [x] Specific User > Projects: New project selection
  - [x] Placeholder users > Specific placeholder users > Projects: New project selection
  - [x] Groups > Specific groups > Projects: New project selection
- [x] In Administration > Work Packages > Custom actions
  - [x] Changing the project in the preconditions is not saved
  - [x] In the action field "project", the old autocompleter is used
- [x] In cost reports
  - [x] adding multiple projects and saving that, results in a crash after reload
  - [x] Freshly adding a project filter, shows the old project field

2022-06-20 09:00 UTC, HDinger approved these changes

2022-06-20 11:18 UTC, merged