add a setting:list_env rake task to list overridable env var names
opf/openproject pull request #10682
Opened 2022-05-16 09:18 UTC by cbliard

Each environment variable name is listed with its default value. 

For instance:
```
OPENPROJECT_ACTIVITY__DAYS__DEFAULT (default=30)
OPENPROJECT_ADDITIONAL__FOOTER__CONTENT (default=nil)
OPENPROJECT_AFTER__FIRST__LOGIN__REDIRECT__URL (default=nil)
OPENPROJECT_AFTER__LOGIN__DEFAULT__REDIRECT__URL (default=nil)
...
```

2022-05-16 15:01 UTC, ulferts requested changes
@cbliard please see my comments below. The additional output is definitely debatable, though. Functionality itself seems to be working find.

2022-05-16 15:01 UTC, ulferts commented on lib/tasks/setting.rake
> +      puts "#{Settings::Definition.possible_env_names(definition).first} (default=#{definition.default.inspect})"
This leads to having subsequent underscores in the output which suggests that this is the preferred way. e.g. `OPENPROJECT_SHOW__STORAGE__INFORMATION`. If we want to switch to the more readable single underscore variant long term, we should print that.

2022-05-16 15:01 UTC, ulferts commented on lib/tasks/setting.rake
> +  task list_env: :environment do
I propose to have a different name here just to have a better support the use case. With the current name, it could also be interpreted to mean "the envs that are currently active". Name that come to mind would be `available_envs`. OR, we switch the output to also show the effective value at least in case it differs from the default value in which case the name could be reflect that. OR, we switch the output to something like this:

```
NAME         ENV                       DEFAULT           VALUE
app_title    OPENPROJECT_APP_TITLE     OpenProject       MyOpenProject
...
```

And potentially the description once we have that in the system.

2022-05-16 15:31 UTC, cbliard commented on lib/tasks/setting.rake
> +      puts "#{Settings::Definition.possible_env_names(definition).first} (default=#{definition.default.inspect})"
Indeed. I mimicked the output on https://www.openproject.org/docs/installation-and-operations/configuration/environment/#supported-environment-variables

So should I change it to use single underscore? @machisuji

2022-05-16 15:38 UTC, cbliard commented on lib/tasks/setting.rake
> +  task list_env: :environment do
I struggled with the name :) so I picked a short one I had in mind as a starter. I agree with your view on `setting:list_env`. `setting:available_envs` is better.

For the output, I'd like to make it more complete (listing all possible env vars, displaying value, displaying where the value was read from, ...), but for now I think it does most of the job and should help Adam with support requests.

So `available_envs`?

2022-05-16 16:37 UTC, oliverguenther commented on lib/tasks/setting.rake
> +      puts "#{Settings::Definition.possible_env_names(definition).first} (default=#{definition.default.inspect})"
Having the double underscore notation is still recommended for use with e.g., deeply nested keys. For consistency, I would then recommend we always use this approach, even though for flat keys, we could deduce the correct key name.

2022-05-17 06:32 UTC, ulferts commented on lib/tasks/setting.rake
> +  task list_env: :environment do
👍

2022-05-17 07:22 UTC, cbliard commented on lib/tasks/setting.rake
> +      puts "#{Settings::Definition.possible_env_names(definition).first} (default=#{definition.default.inspect})"
ok, we'll keep it like this. Consistency beats everything.

2022-05-17 07:22 UTC, cbliard commented on lib/tasks/setting.rake
> +  task list_env: :environment do
Done

2022-05-17 14:09 UTC, ulferts approved these changes
:+1:

2022-05-17 14:09 UTC, merged