Adding an OAuthClients::ConnectionManager to save, refresh and use OAuthClientTokens
opf/openproject pull request #10708
Opened 2022-05-23 15:29 UTC by wielinde

- Added storages.oauth_client_id and _secret and improved host checking error handling
- Storage form with JS to enable OAuth2 client_secret on demand
- Fixed RuboCop issues and moved JS to storage_form.js
- Explicit edit mode for OAuth client secret
- Rough round trip for adding OAuth client credentials to storage
- Add spec for OAuthClients::CreateContract
- Improve ABC size in Storages::Admin::OAuthClientsController create method
- Contract specs for OAuthClient together with Wieland
- OAuthClient services and specs
- Fixed feature spec testing storage admin without OAuthClient.
- Improve flow and guidance for setting up a file storage
- Added spec to test OAuthClient GUI logic with Create/Reset
- Consolidate two feature specs into one
- WIP trying to copy/refactor the OAuth2 prototype to product
- WIP starting to reorganize ConnectionManager
- WIP: First specs for connection manager.

2022-06-08 12:33 UTC, Kharonus requested changes
Looks already quite great. Some open questions remain.

2022-06-08 12:33 UTC, Kharonus commented on app/models/oauth_client_token.rb
> +  validates :user, uniqueness: { scope: :oauth_client }
So, the plan is to replace tokens and not store old ones? As every user can have only one token per oauth client?

2022-06-08 12:33 UTC, Kharonus commented on app/services/oauth_clients/connection_manager.rb
> +    def rack_oauth_client(options = {})
why is the rack client created for every request? sounds like something that could be created together with the connection manager and just getting customized with refresh and auth tokens, when needed?

2022-06-08 12:33 UTC, Kharonus commented on app/services/oauth_clients/connection_manager.rb
> +      l10n_key = "oauth_client.errors.rack_oauth2.#{rack_oauth2_client_exception.message}"
why is the variable named `l10n_key`? not `i18n_key`? we do use internationalization, not only localization. And the key is constructed on our side.

2022-06-08 12:33 UTC, Kharonus commented on app/services/oauth_clients/connection_manager.rb
> +      state
hmm, that statement is not true, is it? `state` comes in from the `ApplicationController`, and if I read it correctly it contains the complete URL, i.e. including query params and fragments. Query params are fine for oauth redirect uris, but fragments are not allowed. Hence, the state must get sanitized here.

2022-06-08 12:33 UTC, Kharonus commented on app/controllers/oauth_clients_controller.rb
> +      redirect_to state
I think, this brakeman issue is serious. we need validation or sanitation of the input here to avoid the risk of phishing.

2022-06-09 07:59 UTC, wielinde commented on app/models/oauth_client_token.rb
> +  validates :user, uniqueness: { scope: :oauth_client }
Yes, that was the idea. Is that bad? I thought that a OAuth client is unique, as it has one ID. A user of that client exists only once. So, I thought that it makes sense to only have one token per client and user.

2022-06-09 14:06 UTC, wielinde commented on app/services/oauth_clients/connection_manager.rb
> +    def rack_oauth_client(options = {})
I see your point. Unfortunately the gem `::Rack::OAuth2::Client` does not allow to use the setter methods `authorization_code` and `refresh_token` to reset their values. I don't see a way how to reuse such a client object. However, I don't think that creating that client is expensive. Also, we will rarely run into the situation where we could actually benefit from that optimization.

2022-06-10 11:21 UTC, Kharonus commented on app/services/oauth_clients/connection_manager.rb
> +    def rack_oauth_client(options = {})
Alright, seems legit. ;)

2022-06-10 11:22 UTC, Kharonus commented on app/models/oauth_client_token.rb
> +  validates :user, uniqueness: { scope: :oauth_client }
As discussed in the chat, this seems to be the right constraint.

2022-06-10 16:24 UTC, wielinde commented on app/services/oauth_clients/connection_manager.rb
> +      state
Now, any redirect URI is valid that shares the same application origin.

2022-06-13 07:38 UTC, Kharonus reviewed
New changes LGTM, just have a question popping out. And I will spend some time now to test it a bit.

2022-06-13 07:38 UTC, Kharonus commented on app/controllers/oauth_clients_controller.rb
> +  def set_redirect_uri
this is a before_action, so, if I understand this correctly, the route on this controller will always toasts an error, if it is opened without a cookie set?

2022-06-13 10:32 UTC, wielinde commented on app/controllers/oauth_clients_controller.rb
> +  def set_redirect_uri
That's correct. As discussed, I'll set that to "resolved".

2022-06-13 10:34 UTC, merged