Prevent toasts on loading errors from notifications
opf/openproject pull request #10718
Opened 2022-05-25 07:49 UTC by oliverguenther

https://community.openproject.org/wp/40506

2022-05-25 13:56 UTC, ulferts requested changes
Error handling works fine. Stopping the server will lead to the number vanishing and starting the server again - the number reappears.

One of the requirements that were discussed didn't make it into the description and that is the change to the behaviour in case the user has more than 99 notifications. In this case, the [output is to be changed to "99+"](https://community.openproject.org/projects/openproject/work_packages/40506/activity#activity-16)

2022-05-30 13:48 UTC, oliverguenther commented
Good point @ulferts. It's not really related to the bugfix, but I've added it anyway

2022-05-31 07:51 UTC, ulferts requested changes
Thanks for the extra effort, @oliverguenther. Functionality is looking fine now.

Unfortunately that change seems to lead to two requests to the `notifications` endpoint being issued for every update (one shortly behind the next). I assume this is due to Angular's change detection being triggered by the change to the `[textContent]` and the piping which is really unexpected.

2022-05-31 08:06 UTC, ulferts approved these changes
:+1:

2022-05-31 08:34 UTC, merged