Allow partial overriding of settings from file in test env
opf/openproject pull request #10842
Opened 2022-06-23 08:45 UTC by cbliard

When Rails environment is test, overriding definition values from file is still not possible from default section, and becomes possible from the test section.

For instance with this `config/configuration.yml` file:

    default:
      edition: bim
    test:
      log_level: debug

In tests, log level will be debug but the edition will NOT be bim.

I use this to enable debug logging and set the web timeout to a big value in tests.

2022-06-24 08:16 UTC, cbliard commented
The failing test is flickering and has been fixed on another PR: https://github.com/opf/openproject/pull/10833/commits/b5eba2141d7320349846c0caba625e9efd14db85

2022-06-27 08:32 UTC, ulferts requested changes
Change is fine except for a tiny comment that need to be moved.

2022-06-27 08:32 UTC, ulferts commented on config/constants/settings/definition.rb
>          # The test setup should govern the configuration
This comment is now misplaced.

2022-06-28 06:28 UTC, cbliard commented on config/constants/settings/definition.rb
>          # The test setup should govern the configuration
Yep, fixed. Thanks

2022-06-28 06:30 UTC, merged