[#21754] Log time for other users
opf/openproject pull request #10879
Opened 2022-06-29 11:13 UTC by DmitryBash

2022-07-05 08:02 UTC, ulferts commented
Just a remark thrown over the fence before I forget:

What we'll also need to do is fill the added `logged_by_id` column for all the existing time entries. They should all have that column filled by their respective `user_id` field as that is what has happened.

2022-07-08 09:27 UTC, ulferts requested changes
Please see my comments within the code. On top of that:

* [x] I am uncertain whether the check for the `edit_own_time_entries` permission in the [UpdateContract](https://github.com/opf/openproject/blob/dev/modules/costs/app/contracts/time_entries/update_contract.rb#L55) is correct. It checks the `user` property so a user having the `edit_own_time_entries` permission is allowed to edit all time entries where the user is the one logged time **for**. A different interpretation is possible now: That permission could also mean that the user is allowed to alter all time entries that she/he booked, so where the `logged_by` property matches the current user.  I [raised a question](https://community.openproject.org/projects/openproject/work_packages/21754#activity-87) to have that answered.
* [x] Groups are currently selectable us the 'Resource'. Only users should be:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/617519/177960258-5fabc609-5465-4b8f-84cc-4d4cd278094c.png">. So using `available_assignees` for the path returns too many options.
Adding a `type` filter to the path with a 'User' value should do the trick.
* [x] The field is called "Resource" when it should be called "User" according to the specification (Admittedly, the technical specification says "Resource" but the acceptance criteria state "User")
* [ ] Unit and request specs for the added functionality as well as a feature spec are missing.

2022-07-08 09:27 UTC, ulferts commented on app/policies/work_package_policy.rb
> +      hash[project] = user.allowed_to?(:log_own_time, project)
I believe this method can be removed altogether as it does not appear to be referenced any more. I'll give it a try in a separate PR.

2022-07-08 09:27 UTC, ulferts commented on lib/api/v3/work_packages/work_package_representer.rb
> +             cache_if: -> { current_user_allowed_to(:log_own_time, context: represented.project) } do
This link is what we call an "action"-link. As opposed to links referencing another resource, they link to a change in the server side state. In this case, that state is the creation of another time entry. 

For a client, on top of describing the location of the action, the mere presence or absence of the action link also indicate whether an action can be carried out.

A user now needs to have one of two permissions to log time: `log_time` or `log_own_time`. Because of that, this check also needs to check for both permissions. This can currently only be done by two checks: 
```
current_user_allowed_to(:log_time, context: represented.project) || current_user_allowed_to(:log_own_time, context: represented.project)
```

2022-07-08 09:27 UTC, ulferts commented on lib/api/v3/work_packages/work_package_representer.rb
> +             cache_if: -> { current_user_allowed_to(:log_own_time, context: represented.project) } do
I was going to write that you should add the second permission to the `logTime` [action link documentation](https://github.com/opf/openproject/blob/dev/docs/api/apiv3/tags/work_packages.yml#L7-L17) but that link is missing from it completely. 

Can you please add it now and when doing so have `log_time` or `low_own_time` as permission conditions?

2022-07-08 09:27 UTC, ulferts commented on app/policies/work_package_policy.rb
> +      hash[project] = user.allowed_to?(:log_own_time, project)
#10933 removes the method

2022-07-08 09:27 UTC, ulferts commented on frontend/src/app/shared/components/time_entries/form/form.component.ts
> +    readonly apiV3Service:ApiV3Service) {
I don't see a reason for adding this.

2022-07-08 09:27 UTC, ulferts commented on modules/costs/app/contracts/time_entries/base_contract.rb
> +    attribute :logged_by_id
This property should not be turned writable as it is always to be the current user. Simply removing the `attribute` declaration however will lead to errors. Those errors can be avoided by wrapping the assignment to `logged_by` in the `SetAttributesService` in a `model.change_by_system` block.

2022-07-08 09:27 UTC, ulferts commented on modules/costs/app/services/time_entries/set_attributes_service.rb
> +      model.logged_by = user
The user registered as the one performing the time logging will always be the current user. Because of that, it is an action carried out by the system and as such should be wrapped in a `model.change_by_system` block.

At the same time, when editing a time entry, the logged_by user might have to change to reflect that user. Again, that change is carried out by the system.

So a change to the logged_by needs to be done by the system both when creating and when updating a time entry. Doing it as part of the `set_default_attributes` method will only do it on creation.

Additionally, if some client would attempt to set the property, it should be prevented (done by removing the `attribute :logged_by_id` from the contract), but an error method is to be returned. Using `model.logged_by = user` will overwrite whatever value was passed in.

In total:
* Move the call to the `set_logged_by` method from the `set_default_attributes` method to the  `set_attributes` method
* Wrap the method body in `model.change_by`
* Assign a value only if no value was provided. Either by checking whether the property changed or by checking inside the `attributes` param of the `set_attributes` method.

2022-07-08 09:27 UTC, ulferts commented on modules/costs/app/contracts/time_entries/create_contract.rb
> -      errors.add :user_id, :not_current_user if model.user != user
A check just like this is still required for the `logged_by` user. But as this can now happen both in the edit as well as in the create case, the check can be moved to the `BaseContract`

2022-07-08 09:27 UTC, ulferts commented on modules/costs/lib/api/v3/time_entries/available_projects_api.rb
> +                          .where(id: Project.allowed_to(User.current, :log_own_time))
Projects where the user is allowed to `log_time` also need to be within the scope, which is why another 
```
.or(Project.where(id: Project.allowed_to(User.current, :log_time)))
```
is needed

2022-07-08 09:27 UTC, ulferts commented on modules/costs/lib/api/v3/time_entries/available_work_packages_on_create_api.rb
> +            WorkPackage.where(project_id: Project.allowed_to(User.current, :log_own_time))
Same as above

2022-07-08 09:27 UTC, ulferts commented on modules/costs/lib/api/v3/time_entries/create_form_api.rb
> +            authorize :log_own_time, global: true
Basically same as above. The user needs to have the `log_time` or the `log_own_time` permission. to that end, there is the [`authorize_any` method](https://github.com/opf/openproject/blob/dev/lib/api/root_api.rb#L161-L178)

2022-07-08 09:27 UTC, ulferts commented on modules/costs/lib/api/v3/time_entries/time_entry_collection_representer.rb
> +          next unless current_user.allowed_to_globally?(:log_own_time)
Again, both permissions need to be checked.

2022-07-08 09:27 UTC, ulferts commented on modules/costs/lib/api/v3/time_entries/time_entry_collection_representer.rb
> +          next unless current_user.allowed_to_globally?(:log_own_time)
And again, both permissions need to be checked :)

2022-07-08 09:42 UTC, ulferts commented on modules/costs/app/contracts/time_entries/create_contract.rb
> +      errors.add :base, :error_unauthorized
I think this is misformulated. Currently, whenever the time entry lacks either the user or the project an `error_unauthorized` is thrown, which explains the failing request and I'd assume also the feature specs.

Changing it to:
```
    def user_allowed_to_add
       return unless model.project && model.user
       return if allowed_to_log_for_others?
       return if allowed_to_log_to_himself?
       
       errors.add :base, :error_unauthorized
    end   
```   

should work

2022-07-19 15:22 UTC, closed without merging

2022-07-19 15:22 UTC, oliverguenther commented
Continuing in https://github.com/opf/openproject/pull/10996