[40774] Unify Enterprise Edition pages
opf/openproject pull request #10914
Opened 2022-07-05 16:25 UTC by bsatarnejad

[X] change the URL of contact us button
[X] replace the team planner animation
[X] improve style of animation/image box in EE pages

2022-07-07 12:42 UTC, bsatarnejad commented
As mentioned on the comments of WP, It is not an easy task to change the team planner animation. So the second to-do part won't be done.

2022-07-08 07:26 UTC, HDinger requested changes
Since there is no URL change in the code, I assume that it has been correct beforehand, right @bsatarnejad ?

Further some of the styles don't match the specification, for example the mobile specific parts are missing completely.

2022-07-08 07:26 UTC, HDinger commented on frontend/src/global_styles/content/_enterprise.sass
> -    width: 100%
Since the image and the video share exactly the same styles, they can be combined.

2022-07-08 08:01 UTC, HDinger approved these changes

2022-07-08 09:19 UTC, merged