[#43323] Nextcloud: Validate :host to be HTTPS or localhost
opf/openproject pull request #10999
Opened 2022-07-20 08:54 UTC by fraber

2022-07-20 09:25 UTC, Kharonus commented on modules/storages/app/validator/nextcloud_secure_host_validator.rb
> +    return if ['localhost', '127.0.0.1'].include?(uri.host) # localhost is always safe
Not sure if this matching suffices. Usually a host is considered secure for `127.0.0.0/8` or `::1/128`, and of course for the host names `localhost` and `localhost.`, or if they end with `.localhost` or `.localhost.`.

2022-07-20 12:58 UTC, wielinde commented on modules/storages/app/validator/nextcloud_secure_host_validator.rb
> +    return if ['localhost', '127.0.0.1'].include?(uri.host) # localhost is always safe
Adding to it: If you make the list allowed hosts a constant then that list gets easily patchable in case somebody needs to add another exception, let's say by building a OpenProject plugin.

2022-07-20 14:32 UTC, wielinde commented on modules/storages/app/validator/nextcloud_secure_host_validator.rb
> +class NextcloudSecureHostValidator < ActiveModel::EachValidator
I believe this validator does not hold anything Nextcloud specific. Or am I wrong?
```suggestion
class SecureHostValidator < ActiveModel::EachValidator
```

2022-07-20 15:34 UTC, wielinde commented on modules/storages/app/validator/nextcloud_secure_host_validator.rb
> +    return if uri.scheme == 'https' # https is always safe
```suggestion
    return if uri.scheme == 'https' # https is always safe
    return if uri.host == 'localhost' # Simple localhost
    return if uri.host =~ /\.localhost\.?$/ # i.e. 'foo.localhost' or 'foo.localhost.'
    return if (IPAddr.new(uri.host).loopback? rescue false) # Constructor throws an exception for non IP addresses. Those are invalid. And if the host is an IP address then we can check if it as loopback
```

2022-07-20 15:36 UTC, wielinde commented on modules/storages/app/validator/nextcloud_secure_host_validator.rb
> +    return if ['localhost', '127.0.0.1'].include?(uri.host) # localhost is always safe
```suggestion
    ```suggestion
    return if uri.host == 'localhost' # Simple localhost
    return if uri.host =~ /\.localhost\.?$/ # i.e. 'foo.localhost' or 'foo.localhost.'
    return if (IPAddr.new(uri.host).loopback? rescue false) # Constructor throws an exception for non IP addresses. Those are invalid. And if the host is an IP address then we can check if it as loopback
```
```

2022-07-22 08:04 UTC, wielinde commented on modules/storages/app/validator/nextcloud_secure_host_validator.rb
> +  # A "secure" Nextcloud host is either a host via https or
@fraber Please correct the comment here and add the link to the specification of Secure Context https://w3c.github.io/webappsec-secure-contexts/

2022-07-22 14:34 UTC, fraber commented on app/validators/secure_context_uri_validator.rb
> +    return false if uri.host =~ /\.localhost\.?$/ # i.e. 'foo.localhost' or 'foo.localhost.'
This regex looks like redundant (with the IPAddr.new below), but it isn't, IPAddr.new doesn't get these cases.

2022-07-22 15:40 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +          # expect(subject.errors.include?(:host)).to be_truthy
Comment line...

2022-07-22 15:40 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +      def self.model_name
I have no idea why this is necessary. Any explanation?

2022-07-22 15:40 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +        ActiveModel::Name.new(self, nil, "temp")
What does this line do?

2022-07-22 15:42 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +    ['https://www.example.com', 'http://localhost', 'http://.localhost', 'http://foo.localhost.'].each do |uri|
I believe 'http://foo.localhost' is missing in the list

2022-07-22 15:43 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +      describe "when URI is ''#{uri}''" do
Can't we use propper double quotes:
`describe "when URI is \"#{uri}\"' do`

2022-07-22 15:46 UTC, wielinde commented on app/validators/secure_context_uri_validator.rb
> +      contract.errors.add(attribute, :host_not_https_or_localhost)
IMHO a better name for `:host_not_https_or_localhost` would be `:uri_not_secure_context`

2022-07-22 15:48 UTC, wielinde commented on app/validators/secure_context_uri_validator.rb
> +# localhost to be secure.
.... to provide a secure context.

2022-07-22 15:49 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +      describe "when URI is ''#{uri}''" do
again, can't we simply use escaped double quotes? `\"` instead of two single ticks?

2022-07-22 15:50 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +  describe 'secure URI' do
`describe` is the wrong term here. It is a `context`.

2022-07-22 15:50 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +  describe 'empty URI' do
`describe` is the wrong term here. It is a `context`.

2022-07-22 15:50 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +      describe "when URI is #{uri}" do
`describe` is the wrong term here. It is a `context`.

2022-07-22 15:51 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +  describe 'secure IPV6 URI' do
`describe` is the wrong term here. It is a `context`.

2022-07-22 15:52 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +  # There are alternative forms of apparently valid IPV6 localhost
The comment here is not correct. `http://::1` is not a valid URI. I bet `http://0001:0000:0000:0000:0000:0000:0000:0000` neither.

2022-07-22 15:53 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +          subject.host = uri
These two lines are the same for every example. They can get extracted to a `before` block

2022-07-22 15:55 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +  # There are alternative forms of apparently valid IPV6 localhost
What is `0001:0000:0000:0000:0000:0000:0000:0000` actually? It doesn't seem to be a loopback address.

2022-07-22 15:58 UTC, wielinde commented on app/validators/secure_context_uri_validator.rb
> +    return false if uri.host =~ /\.localhost\.?$/ # i.e. 'foo.localhost' or 'foo.localhost.'
Correct, `IPAddr` only handles IP addresses and not URIs.

2022-07-22 16:02 UTC, wielinde commented on app/validators/secure_context_uri_validator.rb
> +    if uri.nil? || uri.host.nil?
`uri&.host.present?` would do the trick. Not sure if that would improve readability by much.

2022-07-22 16:04 UTC, wielinde requested changes
Cool, that you have a explicit spec for the validator that tests all nitty gritty details. This reduces nicely what needs to be tested in contracts using the validator.

Before merging it needs a couple of improvements, though. Please checkout my comments.

2022-07-22 16:46 UTC, fraber commented on spec/validator/secure_context_uri_validator_spec.rb
> +      def self.model_name
ActiveModel::Errors needs the name of the class in order to format the error messages used below. With this model_name the error messages won't appear.
The alternative would be to use a non-anonymous class.

2022-07-22 16:48 UTC, fraber commented on spec/validator/secure_context_uri_validator_spec.rb
> +        ActiveModel::Name.new(self, nil, "temp")
see above, the line belongs to def self.model_name. It produces the class name "temp", which is appropriate :-)

2022-07-22 17:03 UTC, fraber commented on spec/validator/secure_context_uri_validator_spec.rb
> +          subject.host = uri
Unfortunately this doesn't work out because it's not lazy evaluated. We'd have to reformulate using let(:...).

2022-07-25 07:43 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +        ActiveModel::Name.new(self, nil, "temp")
Ah, I got off railed as class names in Ruby start with a capital letter. So we better rename it to
```suggestion
        ActiveModel::Name.new(self, nil, "TempModel")
```

2022-07-25 07:45 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +          subject.host = uri
Ok, what stops us?

2022-07-26 11:43 UTC, wielinde commented
I reworked the spec a bit to also cover those cases where a URI was parsable but not providing a Secure Context.

2022-07-26 11:44 UTC, wielinde commented on app/validators/secure_context_uri_validator.rb
> +    if uri.nil? || uri.host.nil?
I hope my latest changes make it easier to read.

2022-07-26 11:45 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +          subject.host = uri
I changed it so that every generated context simply sets the `host` and nothing else.

2022-07-26 11:46 UTC, wielinde commented on spec/validator/secure_context_uri_validator_spec.rb
> +        ActiveModel::Name.new(self, nil, "temp")
I finally renamed it to `ValidatedModel`

2022-07-27 08:56 UTC, Kharonus reviewed
code wise this looks good to me, I will make a test now

2022-07-27 08:56 UTC, Kharonus commented on modules/storages/spec/contracts/storages/storages/shared_contract_examples.rb
> +      end
Can we add a positive and negative example with ipv6? This has two reasons: 

- we check if it works, also for future changes on the validator
- there are a minority of users, who check tests for usage examples. So they could check, how an ipv6 addr can be provided (it must have the brackets, mustn't it?)

UPDATE:
just saw, that we have those test cases directly for the validator. this suffices in my opinion

2022-07-27 09:22 UTC, Kharonus requested changes
If I now run this test, I get a rails error: `NoMethodError`

specifically this is about the call in line 48 in `secure_context_uri_validator`

can you verfiy that? Can't figure, how this could be related to my setup?

2022-07-27 10:31 UTC, wielinde commented
@Kharonus It was a bug in my code. That spec now passes locally. Let's see what CI is saying, now.

2022-07-27 11:48 UTC, Kharonus commented
@wielinde : seems to have fixed the bug, but there is an expectation in that unit test, that still fails.

2022-07-27 16:29 UTC, merged