Add background color to focused spot-list-items
opf/openproject pull request #11075
Opened 2022-08-02 09:39 UTC by b12f

Closes https://community.openproject.org/projects/openproject/work_packages/43482/activity

2022-08-08 07:43 UTC, Kharonus commented
Tested it, looks quite fine in the project selector. Just the question: "focusing" here means focus with our arrow key selection? ❓ Because the browser "focus" does not change background color.

I have some more questions though regarding this menu behaviour, even with those not blocking this very PR (maybe lets mention them to product team in the meeting?). This was just seen while testing it.

![image](https://user-images.githubusercontent.com/38206611/183364630-7d91ed21-1d0a-4c34-ba67-bd5d7abe26ed.png)

1) When I have a search and a nested project matches, the preselection is on the (not selectable) parent.

2) If I use tab to switch focus, the focus outline does not affect the "background selected" item, hence I get a state of two different "selected" items.

I think, those artifacts are shown by trying to put too much convenience into the component (with having the arrow key navigation while focusing the input, selection with enter while focusing the input, etc.). We should be clear, what drawbacks we are ready to take for convenience/consistency.

2022-08-08 08:54 UTC, Kharonus reviewed
From code perspective I have no major issues. There is no new bugs introduced, as far as I can tell. The rework seems legit.

Nevertheless there are the mentioned issues still open with the selection/focus behavior of both lists.

2022-08-08 08:54 UTC, Kharonus commented on frontend/src/app/shared/components/header-project-select/list/header-project-select-list.component.ts
> +  selector: '[op-header-project-select-list]',
can we disable this linter rule? We already agreed using components as attributes is fine for us.

2022-08-08 08:54 UTC, Kharonus commented on frontend/src/app/shared/components/header-project-select/header-project-select.component.html
> -            op-project-list
I see, that you replaced it, but was `op-project-list` deleted? Or is it still used elsewhere?

2022-08-08 08:54 UTC, Kharonus commented on frontend/src/app/shared/components/header-project-select/header-project-select.component.html
> -            op-project-list
nvm: `op-project-list` was renamed to `op-project-include-list`

2022-08-08 08:54 UTC, Kharonus commented on frontend/src/app/shared/components/project-include/project-include.component.html
>        class="op-project-list-modal--loading"
Why do we need a css class? Does it change somehow the behaviour of the standard `op-loading-project-list`?

2022-08-09 07:37 UTC, Kharonus requested changes
Just noticed, that those issues about focus vs. arrow-key-selection are introduced by this very PR, hence we do need to fix those here. :/ If you need help in reproducing them, please contact me.

2022-08-10 09:33 UTC, b12f commented on frontend/src/app/shared/components/project-include/project-include.component.html
>        class="op-project-list-modal--loading"
`frontend/src/global_styles/content/_project_list_modal.sass` sets some styles here, yes.

2022-08-10 14:00 UTC, oliverguenther approved these changes
There's a lot of linting errors due to formatting (indent etc.), but I haven't found any functional or code style issues so merging this to get it deployed on community.

I'll open a separate PR with some linting

2022-08-10 14:00 UTC, merged