[#43158] Impossible to deselect all days when choosing days to receiv…
opf/openproject pull request #11133
Opened 2022-08-10 17:40 UTC by DmitryBash

…e mail reminders

2022-08-10 17:40 UTC, DmitryBash commented on frontend/src/app/features/user-preferences/state/user-preferences.store.ts
> -import { Injectable } from '@angular/core';
linter

2022-08-11 07:28 UTC, oliverguenther requested changes
The change is correctly saved, but if I remove all days and click save, they pop back in the UI until I reload the page. This only happens when I remove all days.

![Peek 2022-08-11 09-27](https://user-images.githubusercontent.com/459462/184084449-01a3eab4-4303-4405-aba1-67d9cbaa4977.gif)

Also a feature spec addition to spec/features/notifications/settings/reminder_email_settings_spec.rb would be nice, I can help with that if you need guidance

2022-08-22 20:58 UTC, DmitryBash commented
@oliverguenther about the feature spec, maybe you mentioned the wrong file? I've added some additional spec in spec/features/notifications/settings/workdays_settings_spec.rb . Correct me if I'm wrong

2022-08-23 06:22 UTC, oliverguenther approved these changes
I can't reproduce the above issue anymore. LGTM :+1:

2022-08-23 06:22 UTC, merged

2022-08-23 06:23 UTC, oliverguenther commented
Related WP: https://community.openproject.org/wp/43158