[43638] Update team planner and calendar for duration and non-working days
opf/openproject pull request #11361
Opened 2022-09-27 13:26 UTC by bsatarnejad

- [ ] The work package's duration should be reflected when dragging a work package with only duration into the team planner.

> Selecting a range of days that includes a non-working day, but such as start/finish dates are not non-working

- [ ] the work package will be scheduled for that date range

- [ ] "Include non-working days" will not be enabled in the date picker (working days only toggle is on)

> Selecting a range of days such that start/finish dates are non-working

- [ ] the work package will be scheduled for that date range

- [ ] "Include non-working days" will be enabled in the date picker  (working days only toggle is off)

2022-10-04 07:11 UTC, oliverguenther requested changes
> Moving a work package (where the "include non-working days checkbox is NOT selected) to a start date that is a non-working day is blocked visually (similar to the permission-based blocking)
> - This will look the same as when you try to drag a parent card in the GANTT chart.
> - To move this card to a non-working start date, the user has to open the date picker and select "Include non-working days"

This does not appear to work. Moving a weekday-only ticket to a weekend day will result in it being moved and reduced in duration. 

![Peek 2022-10-04 09-08](https://user-images.githubusercontent.com/459462/193757047-aa5c21bd-89f4-4130-966f-709fb3adbcdd.gif)

2022-10-04 10:02 UTC, bsatarnejad commented
> > Moving a work package (where the "include non-working days checkbox is NOT selected) to a start date that is a non-working day is blocked visually (similar to the permission-based blocking)
> > 
> > * This will look the same as when you try to drag a parent card in the GANTT chart.
> > * To move this card to a non-working start date, the user has to open the date picker and select "Include non-working days"
> 
> This does not appear to work. Moving a weekday-only ticket to a weekend day will result in it being moved and reduced in duration.
> 
> ![Peek 2022-10-04 09-08](https://user-images.githubusercontent.com/459462/193757047-aa5c21bd-89f4-4130-966f-709fb3adbcdd.gif) [ ![Peek 2022-10-04 09-08](https://user-images.githubusercontent.com/459462/193757047-aa5c21bd-89f4-4130-966f-709fb3adbcdd.gif) ](https://user-images.githubusercontent.com/459462/193757047-aa5c21bd-89f4-4130-966f-709fb3adbcdd.gif) [ ](https://user-images.githubusercontent.com/459462/193757047-aa5c21bd-89f4-4130-966f-709fb3adbcdd.gif)

Hi @oliverguenther If I'm not mistaken, At the time of implementation, we decided to highlight the non-working days in calendar when moving a weekday-only WP to a non-working day. Is there anything else to do in this case?

2022-10-04 12:25 UTC, oliverguenther commented
:warning: please rebase onto `release/12.3` and change the target branch

2022-10-05 11:51 UTC, oliverguenther approved these changes

2022-10-05 11:51 UTC, merged