Ensure we get the current group user IDs instead of a cached one
opf/openproject pull request #11383
Opened 2022-09-29 13:35 UTC by oliverguenther

When first removing a user, that updates group_users, but `group.user_ids` is still cached by rails.

This results in re-adding the just-removed user to the group again.

https://community.openproject.org/wp/41256

2022-09-29 13:37 UTC, oliverguenther commented on modules/ldap_groups/app/models/ldap_groups/synchronized_group.rb
> +        .call(user_ids: current_user_ids - user_ids)
This line caused the bug, we used `group.user_ids` which is cached IF it was used above in removing a user from the group.

2022-09-29 14:16 UTC, machisuji requested changes
Tested this locally and it works as expected. 👍 

I suggested one addition to the migration but other than that it looks all good to me!

2022-09-29 14:16 UTC, machisuji commented on db/migrate/20220929114423_add_unique_index_to_ldap_groups_membership.rb
> +    add_index :ldap_groups_memberships, %i[user_id group_id], unique: true
However unlikely it may be, I would make sure to delete any possible duplicates before the `add_index`. Otherwise, if there any, the migration will fail.

2022-09-30 07:54 UTC, machisuji approved these changes

2022-09-30 07:58 UTC, machisuji commented
There's a single spec failing (`./spec/models/queries/days/day_query_spec.rb:83`) but that cannot be related to the changes from the PR. Hence, I'm going to merge this anyway.

2022-09-30 07:58 UTC, merged