[43842] Re-design and small changes to modal dialogues (DS) for coherence- fixing qa issues
opf/openproject pull request #11393
Opened 2022-10-04 10:29 UTC by bsatarnejad

Fixing spaces and font-size in 
on-boarding video modal,
attribute help text modal,
save query modal,
response body modal in webhooks.

2022-10-04 11:20 UTC, Kharonus requested changes
Only a small thing about style placement, rest looks fine!

2022-10-04 11:20 UTC, Kharonus commented on frontend/src/app/spot/styles/sass/common/container.sass
> +    padding-bottom: 0
I think, we shouldn't put any "legacy" classes into our spot classes. this should go to `container-overrides.sass`

2022-10-04 12:24 UTC, oliverguenther commented
:warning: please rebase onto `release/12.3` and change the target branch

2022-10-06 10:52 UTC, b12f requested changes
Three small changes, then we're good to merge

2022-10-06 10:52 UTC, b12f commented on modules/webhooks/app/cells/views/response_body.erb
> +     <h1 class="spot-subheader-big spot-subheader-big_bold"> <%= log_entry.class.human_attribute_name('response_body') %> </h1>
I think headers are bold by default, so you don't need the extra class

2022-10-06 10:52 UTC, b12f commented on modules/webhooks/app/cells/views/response_body.erb
> +      <h2 class="spot-body-big spot-body-big_bold">Headers</h2>
`spot-subheader-extra-small` is all you need here and below

2022-10-06 11:19 UTC, b12f approved these changes
LGTM!

2022-10-10 11:48 UTC, merged