fix orphaned tokens migration for some MySQL imported schemas
opf/openproject pull request #11502
Opened 2022-10-25 13:33 UTC by machisuji

2022-10-25 14:00 UTC, ulferts requested changes
Almost done, @machisuji. Please see below for details.

I was surprised about the `down` path not reverting the foreign key constraint but that is outside of the change of this PR.

2022-10-25 14:00 UTC, ulferts commented on db/migrate/20221017073431_remove_orphaned_tokens.rb
> +    make_bigint! :users, :id
This will turn the id column into a `bigint` (from `integer`) but not the sequence attached to it. Do this by calling
`ALTER SEQUENCE users_id_seq AS bigint;`

We have something similar in https://github.com/opf/openproject/blob/dev/db/migrate/20220408080838_bigint_primary_key_on_relations.rb

2022-10-26 11:30 UTC, machisuji commented on db/migrate/20221017073431_remove_orphaned_tokens.rb
> +    make_bigint! :users, :id
Good catch. Added that.

2022-10-26 11:56 UTC, ulferts approved these changes
:+1: for extracting it into a `Util` will come in handy later on.

2022-10-26 12:01 UTC, merged