[44481]Expandable Enterprise Edition banners
opf/openproject pull request #11503
Opened 2022-10-25 14:22 UTC by bsatarnejad

Make enterprise edition banner component extendible:
There is an input named collapsible, if you set it to true while using the component anywhere it will be extendible, if you don't set any value to it, it will work as before without collapsing button.

2022-10-26 08:48 UTC, b12f requested changes

2022-10-26 08:48 UTC, b12f commented on frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
> +        <op-icon icon-classes="button--icon icon-medal"></op-icon>
always use spot icons from now on
```suggestion
        <span class="spot-icon spot-icon_medal"></span>
```

2022-10-26 08:48 UTC, b12f commented on frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.html
> +                aria-hidden="true">
Same goes for thsi one, of course

2022-10-26 08:48 UTC, b12f commented on frontend/src/app/shared/components/enterprise-banner/enterprise-banner.component.ts
> +  collapse():void {
I'd call this `toggleCollapse` or something since it works both ways.

2022-10-27 12:49 UTC, b12f approved these changes
LGTM

2022-10-27 13:59 UTC, bsatarnejad commented
Hi @marcalcobe, I replaced the new extendible EE banner with the previous one in any places that I thought it would look better, Could you please let me know if any change was not necessary and should be reverted? Or if is there any place missing?

1- WP table view configuration:
![wp-table-configuration](https://user-images.githubusercontent.com/62008897/198303435-23cfd213-c43a-48df-9257-7f54592bc2e4.png)

2- WP settings for highlighting:
![wp-highlighting-mode](https://user-images.githubusercontent.com/62008897/198303756-b9310a13-a95c-495a-be32-193743b0520a.png)

3- WP filters:
![wp-filters](https://user-images.githubusercontent.com/62008897/198303913-aa96a9ee-d353-4e2e-80bf-cda40895d276.png)

4- Boards filter:
![board-filters](https://user-images.githubusercontent.com/62008897/198304055-229060b1-4d39-4fcf-ab0b-b12c927e8456.png)

5- Projects settings:
![projects-settings](https://user-images.githubusercontent.com/62008897/198304196-c0d6699b-3275-41a3-9af7-fe2557fa454a.png)

6- New status definition in WP settings:
![new-statu-swp-settings](https://user-images.githubusercontent.com/62008897/198304401-bd281af0-2d2c-4b8f-944a-07e6e3795711.png)

7- Multi-select custom fields:
![multi-select-custom-field](https://user-images.githubusercontent.com/62008897/198304561-f6f69767-a100-405b-a938-ce11e07e9e7d.png)

8- WP form configurations:
![form-configurations](https://user-images.githubusercontent.com/62008897/198304754-c7705e74-f01e-472b-b8fe-e647899f1ce1.png)

9- Custom fields for WPs:
![custom-fields-wp-admin-settings](https://user-images.githubusercontent.com/62008897/198304930-8ffef853-0d3e-4d15-a3bb-5c244358a38e.png)

10- Custom fields for projects:
![custom-fields-projects-admin-settings](https://user-images.githubusercontent.com/62008897/198305233-8a913269-0402-488e-9766-82c7037c725e.png)

11- Add widget modal:
![add-widget-modal](https://user-images.githubusercontent.com/62008897/198305354-e0f852b0-f64c-450c-8817-3ddee3c00516.png)

2022-11-01 09:18 UTC, marcalcobe commented
Hi @bsatarnejad, sorry for the late response. I would suggest to not make it expandable in this cases as it is not really taking space from other content:

1- WP table view configuration 
3- WP filters
4- Boards filter
11- Add widget modal

In regards to any missing page, I only can think of the new date alerts but I think that ones are tackled in a different PR.

2022-11-01 13:36 UTC, merged