[#44414] Add the Enterprise Edition guard on date alerts settings
opf/openproject pull request #11569
Opened 2022-11-04 11:59 UTC by dombesz

https://community.openproject.org/work_packages/44414

2022-11-07 14:46 UTC, cbliard requested changes
It is working almost as expected. 

With API, all ok: with enterprise token, it's possible to update date alerts notification settings, and without enterprise token, it's not possible

But with GUI, it does not work that well: with enterprise token it works, but without it, when saving user preferences from the user notifications settings page, it displays an error: "is only available in the OpenProject Enterprise Edition".
![image](https://user-images.githubusercontent.com/176055/200329380-e2e7171c-c425-45a7-b4cc-dca370fb6cc0.png)

- the error message should not be displayed as I did not submit anything related to date alerts.
  I can see the paragraph "Date alerts" but there are no checkboxes or drop down.
- the error message is missing a subject.

Also the error message are not very helpful when using the API, as it only states `"Wrong value for Start date, Due date, or Overdue."` without telling if it's a global setting or project setting, or which property, but I think it's still good enough.

2022-11-07 14:46 UTC, cbliard commented on app/contracts/user_preferences/params_contract.rb
> +      (NotificationSetting.date_alert_settings & notifications.flat_map(&:keys)).any?
Can you extract it in a method so that it explains the intent? something like `date_alert_notifications_provided?`

2022-11-07 20:12 UTC, dombesz commented
@cbliard, fixed the issue of displaying the error message while saving the notification settings. I also added the feature nam e into the message.

2022-11-08 13:06 UTC, cbliard approved these changes

2022-11-09 16:38 UTC, cbliard approved these changes
Nice :raised_hands:

2022-11-09 16:38 UTC, merged