[45055] stop showing OP notifications as NC notifications
opf/openproject pull request #11753
Opened 2022-12-05 10:47 UTC by individual-it

As described in https://community.openproject.org/projects/nextcloud-integration/work_packages/45055 it does not really make sense to duplicate the notifications of OP to Nextcloud.

The support for that functionality has been removed from the integration app in https://github.com/nextcloud/integration_openproject/pull/282

This PR updates the documentation accordingly.

2022-12-06 13:20 UTC, ulferts requested changes, later dismissed
@individual-it I haven't looked at the contents of the PR. But since the functionality was removed in 12.4, this doc change should target the `release/12.4` branch. That way, the change is reflected on the website right away.

2022-12-09 10:38 UTC, individual-it commented
@ulferts I'm happy to make an other PR to the 12.4 branch, but just to clarify: this is not a change in OpenProject but in the integration app: https://github.com/nextcloud/integration_openproject/
The version of the integration app that has this change is not release yet, but when released it will work with any OpenProject version starting from 12.2

2022-12-13 13:26 UTC, ulferts commented
Sure, @individual-it it is only the documentation. But if you want to have that documentation out as soon as this is merged, then it has to target `release/12.4`. If it can wait until 12.5 is released, it should target `dev`. I was of the opinion, possibly wrongfully, that it is supposed to be the former.

2022-12-16 08:24 UTC, individual-it commented
@ulferts I've now changed the base branch to `release/12.4`

2023-07-13 18:27 UTC, oliverguenther commented
@wielinde @individual-it is this PR still relevant?

2023-07-14 11:46 UTC, wielinde approved these changes
@oliverguenther Thank you, yes, relevant.

2024-01-17 09:32 UTC, as-op commented
ping @wielinde :)

2024-05-07 07:35 UTC, mrmir commented
Bump @wielinde

2025-02-13 09:34 UTC, ulferts commented
@wielinde ping. Otherwise, I think this should be closed.

2026-03-23 10:35 UTC, ulferts commented
@wielinde feel free to reopen if this is still relevant.

2026-03-23 10:35 UTC, closed without merging