Bypass self registration for omniauth users
opf/openproject pull request #11887
Opened 2023-01-09 09:42 UTC by oliverguenther

https://community.openproject.org/wp/42390

2023-01-10 11:05 UTC, cbliard requested changes

2023-01-10 11:05 UTC, cbliard commented on spec/features/auth/omniauth_spec.rb
> +      it 'still automatically activates the omniauth accou' do
```suggestion
      it 'still automatically activates the omniauth account' do
```

2023-01-10 11:05 UTC, cbliard commented on spec/controllers/concerns/omniauth_login_spec.rb
> +        it 'shows a notice about the activated account', :aggregate_failures do
Yay! Faster specs!

2023-01-10 11:16 UTC, cbliard commented
(Sorry, I clicked the button "request changes" before leaving a comment.)

As we discussed, it works well in the nominal case, and the code looks good.
There is one edge case that does not work as expected and for people already using OAuth with self-registration being "account activation by email" or "manual account activation" can experience:

**Reproduction steps**

- Before applying this PR (from `dev` branch for instance)
  - in Administration > Authentication, ensure self-registration is set to "account activation by email" or "manual account activation"
  - register a new user through OAuth.
    - this user will be notified that activating his account requires email activation or manual approval by admin
    - do not activate that user
- Now that the PR is applied (like if a customer did an upgrade to 12.5)
  - login with the same user through OAuth (the user exists and is not activated yet)
  - an error message will be displayed

![image](https://user-images.githubusercontent.com/176055/211536652-63de627a-3bbf-458f-9c30-ac62ee1cf018.png)

**Expected behavior**

The user should be automatically activated, even if it was in a "pending activation" state before

I have not tested with LDAP to see if this can occur too, and I have not tested in combination with PR #11891 (a user self register through GUI with manual activation, then this user authenticates with OAuth => should activate the user, even if the account already exists and is pending activation).

2023-01-10 13:01 UTC, oliverguenther commented
@cbliard I've addressed the edge case in f4762607ec50b36d459469259fb6d677d4b55017

2023-01-11 12:45 UTC, cbliard approved these changes
The edge case works now :+1: 

Nice that you `compact_blank`ed the fields from the provider

2023-01-11 12:46 UTC, merged

2023-01-11 12:48 UTC, oliverguenther commented
> Nice that you `compact_blank`ed the fields from the provider

Except for configuration errors, this likely won't happen for external authentication providers, but it's good to not have it override with invalid values anyway!