Improve message when confirming totp device with potential clock skew
opf/openproject pull request #11978
Opened 2023-01-25 10:08 UTC by oliverguenther

When registering a new device, and the confirmation fails, this might often be due to the clocks being out of sync. In this case, improve the error message

https://community.openproject.org/wp/45586

2023-02-08 11:06 UTC, cbliard requested changes
Codewise, it looks good and covers the initial bug about having clock drift when registering the device.

But it does not cover the sign in case: if the registering was ok, and later on there is a clock drift with the device, and the user is trying to sign in by entering an OTP token from the time-drifted device, then the message will still be "Invalid one-time password." without any hint about clock drift.

Shouldn't it be fixed too? (I'm marking as "request changes" just for the question)

2023-02-08 11:06 UTC, cbliard commented on modules/two_factor_authentication/config/locales/en.yml
> +        otp_invalid_drift_notice: "Invalid one-time password. If this happens repeatedly, please make sure your device clock is in sync. Current server time in your zone is %{time}"
```suggestion
        otp_invalid_drift_notice: "Invalid one-time password. If this happens repeatedly, please make sure your device clock is in sync. Current server time in your zone is %{time}."
```

2023-02-08 12:24 UTC, oliverguenther commented
Hi @cbliard , that's a good point but one that we discussed with product team. Back then it was decided to not show that extended message for every login attempt. Pinging @psatyal for confirmation

2023-02-08 17:12 UTC, psatyal commented
Hi @oliverguenther, I don't quite recall this discussion (it's possible I might just need more context). Let's discuss it on our front-end daily tomorrow.

2023-02-09 09:21 UTC, closed without merging

2023-02-15 09:45 UTC, cbliard commented
@oliverguenther the enhancement of the error message on OTP registration was not merged finally?