add non null constraints on data_id/type polymorphic foreign key
opf/openproject pull request #12211
Opened 2023-03-06 08:42 UTC by ulferts

An OP instance reported a lot of records where both are null. It is still unclear how this has happened. Having an explicit not null is not as good has having a proper foreign key constraint, which however cannot be modelled on polymorphic relations in SQL. And the invalid records reported by the instance should at least be prevented.

https://community.openproject.org/wp/46278

2023-03-06 15:06 UTC, cbliard requested changes
That will not work if there are invalid journals in the database.

There needs to be something like `DELETE FROM journals WHERE data_id IS NULL or data_type IS NULL` before adding the constraint.

Here is the error if there are journals with null `data_type` and `data_id`:

```
$ rails db:migrate
== 20230306083203 NonNullDataReferenceOnJournals: migrating ===================
-- change_column_null(:journals, :data_id, false)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "data_id" of relation "journals" contains null values
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:3:in `change'
/home/cbliard/code/opf/openproject/bin/rails:9:in `<main>'

Caused by:
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  column "data_id" of relation "journals" contains null values
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:3:in `change'
/home/cbliard/code/opf/openproject/bin/rails:9:in `<main>'

Caused by:
PG::NotNullViolation: ERROR:  column "data_id" of relation "journals" contains null values
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:3:in `change'
/home/cbliard/code/opf/openproject/bin/rails:9:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

2023-03-07 08:07 UTC, ulferts commented
Good point @cbliard. 

Since I am still looking for the root cause of how those invalid journals got there in the first place: Did you happen to have such journals in your database while testing or did you just think it through?

2023-03-07 08:18 UTC, cbliard commented
> Good point @cbliard.
> 
> Since I am still looking for the root cause of how those invalid journals got there in the first place: Did you happen to have such journals in your database while testing or did you just think it through?

Sadly I did not happen to have such journals. I changed a journal entry to have null values to see how it would behave.

2023-03-07 08:22 UTC, cbliard commented
@ulferts it still fails, because the journal entry is referenced in the table `notifications`. Not sure if that correctly reflects what happens in production for the user who reported the bug, but maybe consider adding a `CASCADE`.

error is:
```
== 20230306083203 NonNullDataReferenceOnJournals: migrating ===================
-- execute("DELETE FROM journals WHERE data_id IS NULL or data_type IS NULL")
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::ForeignKeyViolation: ERROR:  update or delete on table "journals" violates foreign key constraint "fk_rails_595318131c" on table "notifications"
DETAIL:  Key (id)=(479) is still referenced from table "notifications".
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:4:in `block (2 levels) in change'
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:4:in `block in change'
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:3:in `change'
/home/cbliard/code/opf/openproject/bin/rails:9:in `<main>'

Caused by:
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "journals" violates foreign key constraint "fk_rails_595318131c" on table "notifications"
DETAIL:  Key (id)=(479) is still referenced from table "notifications".
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:4:in `block (2 levels) in change'
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:4:in `block in change'
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:3:in `change'
/home/cbliard/code/opf/openproject/bin/rails:9:in `<main>'

Caused by:
PG::ForeignKeyViolation: ERROR:  update or delete on table "journals" violates foreign key constraint "fk_rails_595318131c" on table "notifications"
DETAIL:  Key (id)=(479) is still referenced from table "notifications".
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:4:in `block (2 levels) in change'
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:4:in `block in change'
/home/cbliard/code/opf/openproject/db/migrate/20230306083203_non_null_data_reference_on_journals.rb:3:in `change'
/home/cbliard/code/opf/openproject/bin/rails:9:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

2023-03-07 10:46 UTC, ulferts commented
@cbliard I added the cascading deletion. I would assume that it cannot happen on production since the notification creation will fail without the data object being referenced. But then again, since I don't know where that bug stems from, better be safe.

Speaking of not being able to create the notification and since the two of us spoke about the notification creation failing you have seen on AppSignal. It could also be that the failures are caused the bug this PR also tries to fix. Because the background job would also fail if `data_id` and `data_type` have been NULL in the first place (and not because of a race condition).

2023-03-07 13:16 UTC, cbliard commented
> Speaking of not being able to create the notification and since the two of us spoke about the notification creation failing you have seen on AppSignal. It could also be that the failures are caused the bug this PR also tries to fix. Because the background job would also fail if `data_id` and `data_type` have been NULL in the first place (and not because of a race condition).

Aha! Very true! Better explanation than the race condition, even if the race condition also occurs.

2023-03-07 13:19 UTC, cbliard approved these changes
Nice way to handle the cascade :+1:

2023-03-07 13:19 UTC, merged