[#46439] Bahn Plugin für OpenProject 12.5.x anpassen
opf/openproject pull request #12234
Opened 2023-03-08 15:42 UTC by ba1ash

https://community.openproject.org/work_packages/46439

2023-03-13 12:15 UTC, Kharonus requested changes
I'd like to reduce a bit the code used in here.

2023-03-13 12:15 UTC, Kharonus commented on frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.component.ts
> +
I'd probably remove this extra getter and instead just use in the template:

```html
[href]="attachment._links.originOpen?.href || attachment._links.staticDownloadLocation.href"
```

2023-03-13 12:15 UTC, Kharonus commented on frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.component.html
> +      *ngIf="!!this.attachment._links.delete"
you do not need to `this.` in the template

2023-03-13 15:30 UTC, ba1ash commented on frontend/src/app/shared/components/attachments/attachment-list/attachment-list-item.component.ts
> +
Cool!

2023-03-14 10:47 UTC, Kharonus approved these changes
LGTM

2023-03-15 14:13 UTC, merged