Replace Enumerations::TableCell by ViewComponent
opf/openproject pull request #12306
Opened 2023-03-20 16:17 UTC by cbliard

https://community.openproject.org/wp/47009

This is part of a larger effort to replace Cells by ViewComponents.

2023-03-23 16:32 UTC, ulferts requested changes
Just tiny remarks

2023-03-23 16:32 UTC, ulferts commented on app/components/enumerations/row_component.rb
> +      link_to h(enumeration.name), edit_enumeration_path(enumeration)
I believe the `h` is unnecessary as the link_to will already escape everything by now.

2023-03-23 16:32 UTC, ulferts commented on app/components/table_component.rb
> +  # end
leftovers?

2023-03-24 16:14 UTC, cbliard commented on app/components/enumerations/row_component.rb
> +      link_to h(enumeration.name), edit_enumeration_path(enumeration)
You're right
```
[1] pry(main)> include ActionView::Helpers
=> Object
[2] pry(main)> link_to('Hello, <b>World</>!', 'https://example.com')
=> "<a href=\"https://example.com\">Hello, &lt;b&gt;World&lt;/&gt;!</a>"
```
I'll fix it.

2023-03-24 16:16 UTC, cbliard commented on app/components/table_component.rb
> +  # end
Yep. I'll remove them.

2023-03-28 07:43 UTC, merged