[#47071] Remove budget activity items from the activity list
opf/openproject pull request #12321
Opened 2023-03-22 14:59 UTC by mrmir

https://community.openproject.org/work_packages/47071

2023-03-24 08:36 UTC, ulferts requested changes
Hey @mrmir, please see my feedback inline.

2023-03-24 08:36 UTC, ulferts commented on app/models/activities/fetcher.rb
> +      .excluding('budgets')
The cleaner way is to remove `Activities::BudgetActivityProvider` and the registration of it in the budget's engine.

I thought about also removing the journals while we are at it on account of them not carrying a lot of valuable information but that might be too hasty.

2023-03-27 12:41 UTC, mrmir commented
Hey @ulferts, I have pushed the changes to remove `Activities::BudgetActivityProvider` and its registration in the budget engine. 

Is it okay now?

2023-03-27 12:41 UTC, mrmir commented
Hey @ulferts, I have pushed the changes to remove `Activities::BudgetActivityProvider` and its registration in the budget engine. 

Is it okay now?

2023-03-28 07:57 UTC, ulferts requested changes
Almost there @mrmir

2023-03-28 07:57 UTC, ulferts commented on spec/models/activities/fetcher_integration_spec.rb
> +  shared_let(:permissions) { %i[view_work_packages view_time_entries view_changesets view_wiki_edits view_budgets] }
With the `BudgetActivityProvider` removed, I don't think the changes in this file are necessary any more. `budgets` can no longer be part of the activities to fetch. 

With such a change it sometimes makes sense to test for the removed functionality to no longer have an effect if a user by some means triggers the functionality (e.g by having a URL stored as a bookmark). 

With that in mind, I'd test that `Activities::Fetcher.new(some_user).event_types` does no longer include `'budgets'`.

2023-03-29 16:40 UTC, mrmir commented on spec/models/activities/fetcher_integration_spec.rb
> +  shared_let(:permissions) { %i[view_work_packages view_time_entries view_changesets view_wiki_edits view_budgets] }
@ulferts I have removed all the extra tests and added what I believe you are asking for. Not sure if the` view_budgets` permission needs to also be removed, however.

2023-03-30 08:13 UTC, ulferts commented on spec/models/activities/fetcher_integration_spec.rb
> +  shared_let(:permissions) { %i[view_work_packages view_time_entries view_changesets view_wiki_edits view_budgets] }
Hi @mrmir simple way to test that: If you now revert the removal of the `BudgetActivityProvider` and run the test, will it become red? And is it still red if the `view_budgets` permission is removed?

2023-03-30 08:57 UTC, mrmir commented on spec/models/activities/fetcher_integration_spec.rb
> +  shared_let(:permissions) { %i[view_work_packages view_time_entries view_changesets view_wiki_edits view_budgets] }
Aah thanks @ulferts. As the test stayed red without the permission as well, I have removed it.

2023-03-30 14:58 UTC, ulferts approved these changes
👍

2023-03-30 14:58 UTC, merged