Add stories and argstable for basic datepickers
opf/openproject pull request #12376
Opened 2023-04-06 10:09 UTC by b12f

Closes https://community.openproject.org/work_packages/46645/activity

2023-04-13 12:21 UTC, Kharonus requested changes
I think, the stories look quite fine. I'd just challenge the current form of the service stubs.

2023-04-13 12:21 UTC, Kharonus commented on frontend/src/app/core/days/weekday.service.shim.ts
I somehow have the feeling, that the shims are more stubs then shims. :D In addition, I see no benefit to add them right next to the service class they are replacing. Why not putting them to the stories directory? maybe in a subfolder there called `stubs` or `service-stubs`.

2023-04-13 12:23 UTC, b12f commented on frontend/src/app/core/days/weekday.service.shim.ts
I put them there because they might also be interesting for usage in TypeScript specs. I agree with the naming, I'll change that.

2023-04-13 15:24 UTC, wielinde commented
Hey @b12f I just checked this branch out. For whatever reason the days of the weeks do not get rendered for any of the three stories:
![image](https://user-images.githubusercontent.com/327272/231807949-00d4a7e1-fa99-4f02-a4ce-843c21ff779b.png)

2023-04-13 15:35 UTC, b12f commented
> Hey @b12f I just checked this branch out. For whatever reason the days of the weeks do not get rendered for any of the three stories.

Ah! I think this is because I'm faking the translation files instead of loading them all: https://github.com/opf/openproject/pull/12376/files#diff-5c8447512de6ab867c557a8426da0992dfb66c183d6b3ec8d05428b3d90964beR4

I'll add those translations.

2023-04-13 16:21 UTC, psatyal commented
Removed the other stories and extended the Basic Date Picker story to include relevant bits from the (now removed) _Common elements_ page.

2023-04-14 12:30 UTC, psatyal commented
@b12f, just checked out the pullpreview and I think the date picker docs do indeed make more sense like this. A few thoughts:

- For the building blocks, we could perhaps try embedding Figma frames directly for the examples?
- The Mini day section has a lot of specifications around colour. Do we think that this level of detail is appropriate for the DS docs?

Cheers
Parimal

cc @wielinde just to keep you posted.

2023-04-20 14:07 UTC, Kharonus approved these changes
LGTM from code perspective

2023-04-20 14:20 UTC, merged