[#47991] Include the status code and explanation into the journals and projects table
opf/openproject pull request #12552
Opened 2023-05-03 21:17 UTC by aaron-contreras

https://community.openproject.org/work_packages/47991

2023-05-11 13:22 UTC, cbliard reviewed
I only reviewed the changes to the seed data and translations. That's correct! Thanks.

There is only a `timeline:` that you reintroduced, probably due to the git conflict you solved.

2023-05-11 13:22 UTC, cbliard commented on modules/bim/app/seeders/bim.yml
> +      name: Timeline
This can be removed. It was dead code that I removed in another PR.

2023-05-12 06:15 UTC, ulferts requested changes
Good first PR, @aaron-contreras :+1:

I only have tiny remarks so this should be good to be merged very soon. Well done.

2023-05-12 06:15 UTC, ulferts commented on app/models/queries/projects/filters/project_status_filter.rb
> +          :status_code
I am aware that I might have caused the renaming but i would refrain from this change as it changes the API in the sense that a client filtering for 

```
http://localhost:3000/api/v3/projects?filters=[{"project_status_code": { "operator": "=", "values": ["5"] }}]
```

will receive  a 400 after the change as the filter is now named 'status_code'.

2023-05-12 06:15 UTC, ulferts commented on app/services/users/replace_mentions_service.rb
> +                            self.class.replacements.select { |r| r == replacement }
I believe the intend of this change is to be able to simplify the `rewrite` method below. But a different caller caller would now have to know the internal object structure, e.g. `{ class: MeetingContent, column: :text }`, and can only provide a single one per service instance where before the caller could simply provide a list of classes to have the mentions replaced. To me, that is way more cumbersome than before.

2023-05-12 14:11 UTC, aaron-contreras commented on app/services/users/replace_mentions_service.rb
> +                            self.class.replacements.select { |r| r == replacement }
The intent was actually to not cause a stack overflow on the `rewrite` method since there were two replacements with `Project` as class, the condition where there was only once replacement in `self.replacements` would never become true.

I could (no pun intended) rewrite this service to handle multiple columns while still keeping the constructor using simply class names.

2023-05-12 15:06 UTC, aaron-contreras commented on app/models/queries/projects/filters/project_status_filter.rb
> +          :status_code
Addressed in https://github.com/opf/openproject/pull/12552/commits/1748b51b2cf68f0c7d16e49a682661d354f4158d

2023-05-12 15:06 UTC, aaron-contreras commented on app/services/users/replace_mentions_service.rb
> +                            self.class.replacements.select { |r| r == replacement }
Addressed in https://github.com/opf/openproject/pull/12552/commits/c004b65288a93a31a38a248fe37e83807ee91d96

2023-05-15 18:12 UTC, oliverguenther approved these changes

2023-05-15 18:12 UTC, merged