[#48250# implement global index page for boards
opf/openproject pull request #12674
Opened 2023-05-22 09:52 UTC by klaustopher

Implements the global index page for boards.

See https://community.openproject.org/projects/openproject/work_packages/48250

2023-05-22 09:55 UTC, klaustopher commented on modules/boards/app/views/boards/boards/overview.html.erb
> +<% end %>
The modal for creating a new board currently does not include any selection of the project. Should we add a WP (like we have for global meetings create) to implement a new modal view that will include a product selection?

//cc @oliverguenther

2023-05-22 13:32 UTC, klaustopher commented on modules/boards/app/views/boards/boards/overview.html.erb
> +<% end %>
Never mind, I saw that https://community.openproject.org/projects/openproject/work_packages/47989/activity exists

2023-05-23 11:25 UTC, oliverguenther requested changes
Only a small thing I noticed: The global page is missing a heading. Apart from that, LGTM :+1:

2023-05-23 11:31 UTC, klaustopher commented
Nice catch. Title added

2023-05-23 11:52 UTC, oliverguenther approved these changes

2023-05-23 11:53 UTC, merged