[#45745] Allow setting all available timezones
opf/openproject pull request #12704
Opened 2023-05-25 07:44 UTC by klaustopher

2023-05-25 07:59 UTC, oliverguenther commented
Please rebase this against `release/12.5` to target the next patch release

2023-05-25 08:00 UTC, klaustopher commented
Will do. Still playing around and looking at the history why this was introduced :)

2023-05-25 19:33 UTC, oliverguenther requested changes
The selected option appears to be wrong for existing values:

My user has this time_zone pref:

```ruby
=> #<UserPreference:0x00000001186bf148
 id: 6,
 user_id: 6,
 settings:
  {"time_zone"=>"Asia/Yangon", ... }
```
But with that time zone (canonically mapped from Asia/Rangoon +6:30, the is now shown as unselected (value '')
<img width="1016" alt="Bildschirm­foto 2023-05-25 um 21 31 22" src="https://github.com/opf/openproject/assets/459462/b8cce716-aa49-46de-9355-9d4b6e2935f3">

2023-05-26 14:05 UTC, klaustopher commented
Will check on tuesday. Interesting: The timezone Asia/Yangon was introduced by [renaming `Asia/Rangoon` in 2016](https://mm.icann.org/pipermail/tz-announce/2016-September/000041.html)

It also exists when querying for it:

```ruby
>> ActiveSupport::TimeZone['Asia/Yangon']
=>
#<ActiveSupport::TimeZone:0x000000010857ff90
 @name="Asia/Yangon",
 @tzinfo=#<TZInfo::DataTimezone: Asia/Yangon>,
 @utc_offset=nil>
```

but in `AS::TimeZone.all` it is not included:

```ruby
>> ActiveSupport::TimeZone.all.select { |tz| tz.tzinfo.identifier == 'Asia/Yangon' }
=> []

>> ActiveSupport::TimeZone.all.select { |tz| tz.tzinfo.identifier == 'Asia/Rangoon' }
=>
[#<ActiveSupport::TimeZone:0x0000000108a74640
  @name="Rangoon",
  @tzinfo=#<TZInfo::DataTimezone: Asia/Rangoon>,
  @utc_offset=nil>]
```

That seems very strange ... Will take a look

2023-05-26 14:18 UTC, klaustopher commented
In the TZInfo DB it is correctly implemented that Rangoon is an alias for Yangon: https://github.com/tzinfo/tzinfo-data/blob/master/lib/tzinfo/data/definitions/Asia/Rangoon.rb
```ruby
>> TZInfo::Timezone.all.select { |tz| tz.name == "Asia/Yangon" }
=> [#<TZInfo::TimezoneProxy: Asia/Yangon>]
>> TZInfo::Timezone.all.select { |tz| tz.name == "Asia/Rangoon" }
=> [#<TZInfo::TimezoneProxy: Asia/Rangoon>]
```

Maybe it makes sense, we take `TZInfo::Timezone` as the source of truth.

All entries in TZInfo can be thrown into `AS::TimeZone` and they produce the right data:

```ruby
>> TZInfo::Timezone.all.select { |tzinfo| ActiveSupport::TimeZone[tzinfo.name].nil? }
=> []
```

I'll probably file a bug with Rails. There are **many** timezones missing in `AS::TimeZone.all`:

```ruby
TZInfo::Timezone.all.map { |x| x.send(:real_timezone) } - ActiveSupport::TimeZone.all.map(&:tzinfo)
```

returns 462 items

2023-05-30 06:57 UTC, klaustopher commented
Seems like rails has intentionally only added 134 out of the ~600 timezone identifiers into `AS::TimeZone` (see comment in https://github.com/rails/rails/blob/main/activesupport/lib/active_support/values/time_zone.rb). That's why `Rangoon` is still in there and and `Yangon` is not.

I think we have 2 options forward:

1. Use `TZInfo::Timezone.all` to list all timezones that are available.
   That would result in a very long list of options and might be confusing for the users. The [TZInfo database itself suggest](https://github.com/tzinfo/tzinfo#time-zone-selection) to not do that, but instead let the user choose a country and then based on that country selection select the timezone. I like that approach as it removes a lot of the complexity (including the long select list). But IMHO this is too much of a refactoring for this bug fix here.
2. Implement a bit more grouping logic, so that the options that link to the same canonical zone get aggregated in the list. This way we would have an option like `UTC+1:00 Berlin, Copenhagen, Brussels, ...`

I'm sort of tending towards the second option.

2023-05-30 08:05 UTC, klaustopher commented
Implemented this way now: Options are grouped together when they use the same identifier.

![Bildschirmfoto 2023-05-30 um 09 22 14](https://github.com/opf/openproject/assets/522537/84a8cf68-bfbb-42ce-94a7-bbe03a3f057f)

2023-05-30 11:28 UTC, oliverguenther approved these changes

2023-05-30 11:28 UTC, merged