[#48641] Automatic time tracking for work packages (start/stop buttons)
opf/openproject pull request #12936
Opened 2023-06-22 19:37 UTC by oliverguenther

https://community.openproject.org/work_packages/48641

2023-07-03 14:13 UTC, dombesz requested changes
I have two remarks, the first is just a nit: some files are missing the license comment.

The second perhaps is not intended to be part of this PR and probably we should do as a follow up PR. The start/stop timer synchronisation between tabs does not seem to work. Let's consider the following scenario:

1. Start the timer on a work package.
2. Open the same work package in a new tab. Now we have two tabs running the same active timer.
3. Stop the timer in the first tab and save the time entry.
4. Stop the timer in the second tab and save the time entry.

The second timer will overwrite the first timer, which is a bit unexpected. When trying to save the timer the second time, I would rather raise an error with the message: "The timer has been already stopped by another session.".

If we want to make it "smarter" in the future, we can implement a polling mechanism for active timer as we do for notifications. (Not ideal thought.)

If we do the same double tab scenario when starting the timer, the timer on the second tab is being silently ignored and a `ActiveRecord::RecordNotUnique` is raised. Fetching for the active timer in this scenario and updating the UI could be a more graceful handling of this edge case. We can also display an error message instead: "An active timer is already running for this work package".

2023-07-03 14:13 UTC, dombesz commented on frontend/src/app/features/invite-user-modal/principal/principal.component.ts
> +  @Input() showTimer = false;
I can't find any use of this variable, I assume it was added accidentally.

2023-07-03 14:13 UTC, dombesz commented on frontend/src/app/features/work-packages/components/wp-timer-button/wp-timer-button.component.ts
> +  @HostBinding('class.op-wp-timer-button') className = true;
The `className` property does not seem to be changed anywhere, is this some convention to define it, even if it's not used?

2023-07-03 14:13 UTC, dombesz commented on frontend/src/app/shared/components/time_entries/edit/edit.service.ts
> +    readonly timeEntry:TimeEntryTimerService,
Naming seems to be a bit inconsistent, I would suggest `readonly timeEntryService:TimeEntryTimerService,`

2023-07-03 14:13 UTC, dombesz commented on frontend/src/app/features/work-packages/routing/wp-full-view/wp-full-view.component.ts
> +    readonly timerService:TimeEntryTimerService,
Naming seems to be a bit inconsistent, I would suggest `readonly timeEntryService:TimeEntryTimerService,`

2023-07-03 14:13 UTC, dombesz commented on frontend/src/stimulus/controllers/dynamic/my/timers.controller.ts
> +    }, 1000);
This can be simplified by using the moment formatter, the format `"HH:mm:ss"` will also zero pad the string and we don't need the `pad` function either.
```suggestion
    setInterval(() => {
      this.elapsedTimeTarget.textContent = moment.utc(now.diff(start, 'seconds')).format("HH:mm:ss")
    }, 1000);
```

2023-07-03 14:13 UTC, dombesz commented on modules/costs/app/views/my/timer/show.html.erb
> +<%= turbo_frame_tag "my_timers" do %>
Is this file currently being used? (There is also a related rails and stimulus controller plus the route definition that does not seem to be used.)

2023-07-03 14:13 UTC, dombesz commented on modules/costs/app/helpers/timer_helper.rb
> +    "#{pad(parts[:hours])}:#{pad(parts[:minutes])}:#{pad(parts[:seconds])}"
We can achieve the same formatting without a custom padding method.
```suggestion
    "%02d:%02d:%02d" % [parts.fetch(:hours, 0), parts.fetch(:minutes, 0), parts.fetch(:seconds, 0)]
```
This will also output  `#=> "01:00:00"` without using the pad method.

2023-07-03 14:13 UTC, dombesz commented on modules/costs/spec/contracts/time_entries/shared_contract_examples.rb
> +    it_behaves_like 'is valid'
Should we still validate the presence of the `activity_id` but only when the time entry is not `"ongoing"`?

2023-07-03 14:13 UTC, dombesz commented on modules/costs/spec/features/timer_spec.rb
> +
The specs are passing successfully, however when I run the specs in chrome, I'll get the following error message toast right after the success toast:

<img width="1279" alt="image" src="https://github.com/opf/openproject/assets/83396/d11b1730-cd75-4591-8244-544b638c8c7c">

2023-07-04 13:38 UTC, oliverguenther commented on modules/costs/spec/contracts/time_entries/shared_contract_examples.rb
> +    it_behaves_like 'is valid'
I discussed this with Jens and Wieland and we all wanted to make the activity optional, so to allow a time entry without any item. If administrators want to set a default, they can do so through the admin UI already

2023-07-04 13:54 UTC, dombesz commented on modules/costs/app/helpers/timer_helper.rb
> +
```suggestion
```

2023-07-04 14:21 UTC, dombesz commented on frontend/src/app/features/work-packages/components/wp-timer-button/wp-timer-button.component.ts
> +}
```suggestion

```

2023-07-04 14:21 UTC, dombesz commented on frontend/src/stimulus/controllers/dynamic/my/timers.controller.ts
> +  }
```suggestion
```

2023-07-04 14:22 UTC, dombesz commented on frontend/src/app/features/work-packages/components/wp-timer-button/wp-timer-button.component.ts
> +
```suggestion
```

2023-07-05 08:16 UTC, dombesz approved these changes
Apart from [this comment](https://github.com/opf/openproject/pull/12936#discussion_r1250945921) everything seems to work as expected.
Nice job @bsatarnejad and @oliverguenther !👏

2023-07-06 18:14 UTC, merged