[#48862] Add PDF Export of work plans to our documentation  https://c…
opf/openproject pull request #13040
Opened 2023-07-05 11:38 UTC by MayaBerd

…ommunity.openproject.org/work_packages/48862

2023-07-05 13:25 UTC, as-op approved these changes

2023-07-11 06:57 UTC, birthe requested changes

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
>  # Exporting work packages
I would suggest we write **Export work packages** (just like create, edit or copy). Also in the title of the document -> Navigation.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
> +To export a work package table or card view to another format, visit the *Work packages* module or select a saved view, opening a work package table that you want to export. Click on the settings ico
To export a work package table, visit the *Work packages* module and select the list of work packages which you want to export. You can either export a saved view or filter the work packages based on your needs. Click on the settings icon in the top right corner. Trigger the **Export** dialog from the dropdown menu.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
> +This will open a dialog where you can select the desired format. Below, we will detail how to adjust which data should be exported as well as what the various formats contain.
Click on one of the possible formats to start the export.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
[save the work package view] --> all as a link?

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
Some spaces and line breaks can be removed.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
with the selected columns for the work package table.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
> +- **PDF Table** exports the work package table displaying work packages as single rows.
Remove the h3 PDF export and list both PDF options (PDF Table and PDF Report and PDF Report with images) as h3.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
Add a small introduction, e.g. : With PDF Reports you can export detailed up to date work plans for your project in a nice format. ...It includes ...

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
(listing all of the work packages of the selected work package table view)

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
> +   > **Note**: Images attached to the work package or in activity comments are not included into exported report.
are not included into the exported report.

2023-07-11 06:57 UTC, birthe commented on docs/user-guide/work-packages/exporting/README.md
> +### Excel (XLS) export
Can you please move all Excel format options below also to h3.

2023-07-11 19:43 UTC, merged