[#49076] Add technical documentation for file storage integration
opf/openproject pull request #13108
Opened 2023-07-12 08:23 UTC by Kharonus

- https://community.openproject.org/work_packages/49076
- added check list for new file storage integration candidates

2023-07-12 08:24 UTC, Kharonus commented
@wielinde please definitely check, if the location of the checklist is okay, or if we should merge it into any existing docs.

2023-07-12 14:19 UTC, wielinde commented on docs/development/file-storage-integration/README.md
> +# File storage integration
```suggestion
# Integrating more external file storage providers
```

2023-07-12 14:21 UTC, wielinde commented on docs/development/file-storage-integration/README.md
> +External file storages can be used from within OpenProject with the file storage module. This adds certain use cases,
```suggestion
External file storages can be integrated OpenProject via the _File storages_ module. This adds certain use cases,
```

2023-07-12 14:22 UTC, wielinde commented on docs/development/file-storage-integration/README.md
> +e.g. in the files tab of a work package, to interact with files located on the storage and link them to entities in
```suggestion
e.g. in the _Files_ tab of a work package, to interact with files located on the storage and link them to work packages in
```

2023-07-12 14:25 UTC, wielinde requested changes
@Kharonus Looks good to me so far. Maybe we could add some differentiation to attachments and their direct uploads, explaining that this is not about that? Also please check my inline comments/suggestions.

I don't really understand what will be the title of the menu item in the docs for this page.

2023-07-13 07:45 UTC, Kharonus commented
The title for the menu is something, I don't know yet. This is also a reason, why I asked, if we should integrate it somewhere else. Will first add your changes.

2023-07-13 07:50 UTC, Kharonus commented on docs/development/file-storage-integration/README.md
> +# File storage integration
added

2023-07-13 07:50 UTC, Kharonus commented on docs/development/file-storage-integration/README.md
> +External file storages can be used from within OpenProject with the file storage module. This adds certain use cases,
added

2023-07-13 07:50 UTC, Kharonus commented on docs/development/file-storage-integration/README.md
> +e.g. in the files tab of a work package, to interact with files located on the storage and link them to entities in
added

2023-08-21 11:36 UTC, Kharonus commented
@wielinde Can we finish that list up? Open question is currently, where to put that list.

2023-08-21 12:26 UTC, wielinde approved these changes

2023-08-21 12:26 UTC, wielinde commented
@Kharonus I added a couple of changes. If you are fine with them, please go ahead and merge.

2023-08-21 14:14 UTC, merged