[#48604] Add "I am member" filter for projects
opf/openproject pull request #13117
Opened 2023-07-12 17:58 UTC by aaron-contreras

**NOTE FOR REVIEWER**: This PR builds on the work done in https://github.com/opf/openproject/pull/13073. Therefore, only the [last commit](bb6a148fb22c051d004aa6e6ecad8a3273682d57) is part of this PR (at least until https://github.com/opf/openproject/pull/13073 is merged into dev)

See Work Package: https://community.openproject.org/work_packages/48604

2023-07-12 19:19 UTC, aaron-contreras commented
First time creating a filter. Looking for comments/suggestions dropped here on both the filter's implementation/spec 🙏

2023-07-13 11:41 UTC, ulferts requested changes
Only a tiny thing @aaron-contreras. Merge at will after addressing it.

2023-07-13 11:41 UTC, ulferts commented on app/models/project.rb
> +  scope :without_member, ->(user = User.current) { where.not(id: user.memberships.pluck(:project_id)) }
Using `pluck` in this context leads to an unnecessary extra request as the `pluck` has to be resolved first with the results of that then being passed into the next query. Using `select` avoids that.

2023-07-14 12:09 UTC, ulferts approved these changes
👍

2023-07-14 12:09 UTC, merged