[#48649] Filter attributes table in the pdf export
opf/openproject pull request #13250
Opened 2023-07-26 07:49 UTC by as-op

https://community.openproject.org/work_packages/48649

2023-07-26 23:49 UTC, aaron-contreras commented on app/models/work_package/pdf_export/work_package_detail.rb
> +           end
It seems these don't need `work_package` as an argument at all. Perhaps

```suggestion
    list = if respond_to?(:column_objects)
             attributes_list_by_columns
           else
             attributes_list_by_wp
           end
```

2023-07-26 23:49 UTC, aaron-contreras commented on app/models/work_package/pdf_export/work_package_detail.rb
> +  def attributes_list_by_columns(_work_package)
```suggestion
  def attributes_list_by_columns
```

2023-07-26 23:49 UTC, aaron-contreras commented on app/models/work_package/pdf_export/work_package_detail.rb
> +  def attributes_list_by_wp(_work_package)
```suggestion
  def attributes_list_by_wp
```

2023-07-26 23:51 UTC, aaron-contreras requested changes
Very nice refactor. Only itch would be the unused parameter for both `#attributes_list_by_columns` and `#attributes_list_by_wp`.

2023-07-27 07:29 UTC, as-op commented
🙏 Thank you @aaron-contreras!

2023-07-27 07:29 UTC, merged