[#49144] Fix missing link to Meeting location on index pages
opf/openproject pull request #13440
Opened 2023-08-10 19:11 UTC by aaron-contreras

## Bug description
There just wasn't a link being rendered from the get-go, instead it was `html_escaped` plaintext.

## Demo screenshot
![image](https://github.com/opf/openproject/assets/61627014/6bd5d4da-d764-4a96-b9fa-05ccc7204da6)

## Notes
See Bug Work Package: https://community.openproject.org/work_packages/49144

2023-08-11 14:15 UTC, cbliard requested changes
It works, but I'm not sure that's correct. A location can be a url, but it can also be a place description, a city, a room name, etc. So it should be converted to a link only if it's a valid URL.

2023-08-11 17:16 UTC, aaron-contreras commented
@cbliard Thanks for the catch 👍. Didn't really think of using the Location field as something other than a URL. I've addressed the comment in https://github.com/opf/openproject/pull/13440/commits/7df7ec97a196d56c5a1b794e9814dc8809999736 and https://github.com/opf/openproject/pull/13440/commits/8ac6616f1afdd354252de48690e81d3ed622b27b

2023-08-14 05:35 UTC, oliverguenther commented on modules/meeting/app/components/meetings/row_component.rb
> +      if valid_meeting_location_link?
We already use riku for automatically linking to URLs. I think we could just reuse this here? https://github.com/opf/openproject/blob/dev/lib/open_project/text_formatting/filters/autolink_filter.rb#L46

`

2023-08-14 14:38 UTC, aaron-contreras commented on modules/meeting/app/components/meetings/row_component.rb
> +      if valid_meeting_location_link?
Thank you! Determining valid URLs turned out to be more daunting than expected. Addressed here: https://github.com/opf/openproject/pull/13440/commits/bb126714ddbb457401a0e6e2e30cb076339185e7 and a precautionary spec here https://github.com/opf/openproject/pull/13440/commits/6463d44f39bef97125a8dc1bda6dd77b958ff0ce

2023-08-14 17:29 UTC, oliverguenther approved these changes
Thanks for deep diving into the autolinking 🙇

2023-08-14 18:10 UTC, merged