Epic/37297 automatic meeting agendas and minutes linked to work packages
opf/openproject pull request #13527
Opened 2023-08-21 10:45 UTC by jjabari-op

https://community.openproject.org/projects/openproject/work_packages/37297

2023-09-14 12:23 UTC, ulferts requested changes
I haven't yet taken a look into the code but only tried out the changes from a user perspective. Sorry for the barrage of topics. I generally like the change.

- [ ] **Unclear purpose of the user selection**

Upon creation of an agenda item/work package item the user gets to select a user. That field is prefilled with the current user. The purpose of that field however is not immediately clear:
<img width="996" alt="image" src="https://github.com/opf/openproject/assets/617519/bc9aa8c4-4ba6-4ca9-a2a1-0239d83a0a14">

Is it the user that added the item? Or the one that will speak about it or somebody that is the target audience? 

I believe this to be the consequence of not having [labels on those form fields](https://primer.style/design/ui-patterns/forms/overview#label-required)

- [x] **Possible to create an agenda item without user** (by design)

It is possible to have agenda items without a responsible users:

<img width="1014" alt="image" src="https://github.com/opf/openproject/assets/617519/eaa60d98-ff1f-421d-8c4a-a3e8105c0163">

This is because the responsible value can be deleted. Attempting to edit such an item will result in an error.

- [x] **Removing the last invitee from the meeting leads to 500**

Attempting to create a meeting without any invitee or removing all invitees from the meeting will lead to an error

- [ ] **Discrepancy between invitees and responsible selection**

Users not selected as invitees can still be selected as being responsible for an agenda item.

<img width="585" alt="image" src="https://github.com/opf/openproject/assets/617519/39217c44-ace8-4404-88f5-f55a8cacfae4">

Even members without permissions to see the meeting can be selected. Those users are correctly removed from the list possible participants.

- [ ] **Typing in the responsible selection field leads to form resizing**

When typing in the responsible selection autocompleter the field changes its size due to the loading animation leading to the whole form being resized.

- [x] **Focus misplaced when adding work package items**

After pressing the "Add" button and selecting to want to add a "Work package", the focus is in the responsible autocompleter instead of in the title field.

<img width="1009" alt="image" src="https://github.com/opf/openproject/assets/617519/67752403-d2f8-4edd-b531-8050590efd4e">

- [x] **Adding a large value for the duration crashes the application**

A large value for the duration field crashes the application:

<img width="1018" alt="image" src="https://github.com/opf/openproject/assets/617519/16c7d980-508a-484a-98b5-84ed28304c4e">

Adding a validation for the upper boundary (and possibly also limiting the field visually) would help.

- [ ] **Opinion/Feedback: Always show the description field**

Having to click on the '+ Description' button to display an input is cumbersome. Clicking on the button will only display a single field (and I cannot hide it again). Given what it currently is, I'd always display the field. If the assumption is that people will only rarely insert a description  this might not be necessary but I believe, that they will insert it more often especially if they want to take notes of the result. And in that case, they have to click two buttons while being in a meeting to take minutes per item.

- [ ] **Opinion/Feedback: Naming of the date field**

The field when editing the meeting's attributes is named "Start date" suggesting that there would also be a finish date

<img width="465" alt="image" src="https://github.com/opf/openproject/assets/617519/4f3a36d8-f921-4481-be2a-b4a5aaf02158">

Admittedly, it is called the same in the create form but there the date is combined with the time which to me makes it a little better.

- [ ] **Two ways of configuring the participants in close proximity**

Clicking on the gear icon as well as clicking on 'Add participants' triggers the same modal and the two options are in close proximity to each other.

- [ ] **Opinon/Feedback: Change default of meeting type**

Instead of having the old style of meeting selected by default I'd chose the new one:

<img width="1031" alt="image" src="https://github.com/opf/openproject/assets/617519/d5edf449-a8fa-42e1-865f-2723c298f8c4">

- [ ] **Drag & Drop while editing/creating an agenda item looses user input**

When draging&dropping and dropping while having an agenda item open to be created/edited will lead to completely rerendering the agenda section potentially loosing text the user has created. It might be an option to disable drag&drop while editing.   

- [x] **Deleting a structured meeting leads to a white page**

<img width="800" alt="image" src="https://github.com/opf/openproject/assets/617519/b3fbdf95-f1d4-4527-b8ec-5ae3d1e3b48a">

- [x] **Opinion/Feedback: Added content is not scrolled into view**

When having a longer meeting agenda and adding another one, that new item is not scrolled completely into view making editing awkward:

<img width="1270" alt="image" src="https://github.com/opf/openproject/assets/617519/8cb2d318-d452-4086-af32-991ab5fcf52d">

- [ ] Height and width of autocompleter components change / are not consistent

![Bildschirmfoto 2023-09-18 um 08 53 40](https://github.com/opf/openproject/assets/459462/e8349e86-6640-4ecf-b1a6-54eba6aa7e7d)

2023-09-14 13:55 UTC, cbliard commented on modules/meeting/app/forms/meeting_agenda_item/duration.rb
> +      max: 86400,
That's 60 days. Is it intended? Did you mean `24*60` instead? (`24.hours.in_minutes.to_i`)

2023-09-14 14:13 UTC, oliverguenther commented
I think I've caught all the bugs you mentioned, we'll discuss the feedback next week

> Possible to create an agenda item without user

This is by design and should not break (fixed)

> Removing the last invitee from the meeting leads to 500

Couldn't reproduce this @ulferts , does it happen on the head of the branch to you?

> Adding a large value for the duration crashes the application

Fixed (arbitrary max value of 1440)

> Focus misplaced when adding work package items

Should be fixed already in the meantime

> Drag & Drop while editing/creating an agenda item looses user input

this was mentioned by Jonas already as a know caveat, we'll discuss this with product

> Deleting a structured meeting leads to a white page

Fixed, caused by turbo taking over as not explicitly disabled

2023-09-14 15:04 UTC, ulferts requested changes
I did not manage to go through the whole PR yet and plan to continue tomorrow. Please find most of my remarks next to the code.

There are also a couple of general issues

- [x] **Members autocompleter broken**

(OG: Cannot reproduce, are you sure?)


The members autocompleter has become non functional. The fact that the specs did not catch it is unnerving.

<img width="741" alt="image" src="https://github.com/opf/openproject/assets/617519/78e6fe2f-cbba-407e-ae88-658d3fbac0d5">


- [ ] Avatars on members page no longer have a padding

![Bildschirmfoto 2023-09-18 um 09 09 29](https://github.com/opf/openproject/assets/459462/ac54faa2-e72a-438e-9682-d7cec517f763)



- [ ] **Non working days in primer date selector**

The date selector of primer naturally does not display the non working days:

<img width="236" alt="image" src="https://github.com/opf/openproject/assets/617519/98e46f6b-31fe-4ce1-b9ea-7c6a6165d5e5">

Is there any chance we can get them to be adhered to?

2023-09-14 15:04 UTC, ulferts commented on app/forms/op_primer/forms/autocompleter.rb
> +module OpPrimer
Why is this situated in `app/forms` when the rest of the custom components are in `app/components`? It does now have `forms` in its path twice.

2023-09-14 15:04 UTC, ulferts commented on app/views/homescreen/index.html.erb
> +
Those changes are unnecessary

2023-09-14 15:04 UTC, ulferts commented on frontend/src/global_styles/openproject/_primer-adjustments.sass
> +// disabled for now in order to see the conflicts
So this file is responsible for reasserting the styles already defined in Primer by a higher specificity? It does not override the primer styles? If so, the comment could be a bit clearer on that.

2023-09-14 15:04 UTC, ulferts commented on frontend/src/stimulus/controllers/dynamic/meeting-agenda-item-form.controller.ts
> +  }
I think this isn't actually used (any more?).

2023-09-14 15:04 UTC, ulferts commented on modules/meeting/app/components/flash_message_component.rb
> +class FlashMessageComponent < ApplicationComponent
Since the intend of this is to be used throughout the application, it should be moved to OpPrimer::FlashMessageComponent or Primer::OpenProject::FlashMessageComponent.

2023-09-14 15:04 UTC, ulferts commented on modules/meeting/app/components/meeting_agenda_items/item_component/show_component.rb
> +      @meeting.open? && User.current.allowed_to?(:create_meeting_agendas, @meeting.project)
The mapping of the already existing permissions to the new paradigm doesn't work very well. The agenda items are edited also during the meeting as part of the minutes. 

We could introduce new permissions that better reflect the altered paradigms and have the old permissions faded out. Or we simply use the `:edit_meetings` permission for all of those checks.

2023-09-14 15:04 UTC, ulferts commented on modules/meeting/app/components/meeting_agenda_items/list_component.rb
> +        # component.with_primary_action(href: "#").with_content(t("label_meeting_empty_action"))
Leftover?

2023-09-14 15:04 UTC, ulferts commented on modules/meeting/app/components/meetings/sidebar/details_component.rb
> +      end
This part should be extracted into a component for rendering durations. We are doing it on the meetings page two times already (the other usage is in the `MeetingAgendaItems::ItemComponent::ShowComponent`) and I'd expect we do it again.

Interestingly enough I couldn't find good information on how durations are internationalized but having the format moved to our yml files sound good to me.

2023-09-14 15:12 UTC, ulferts commented
>  
> > Removing the last invitee from the meeting leads to 500
> 
> Couldn't reproduce this @ulferts , does it happen on the head of the branch to you?
> 

It's now working without problem @oliverguenther

2023-09-14 15:15 UTC, ulferts commented
Another feedback @oliverguenther. I believe that the participant modal can become unwieldy if there are a larger number of members (e.g. 100) in the group. Admittedly, a problem inherited from the existing participant selection.

2023-09-15 07:10 UTC, cbliard commented on app/forms/op_primer/forms/autocompleter.rb
> +module OpPrimer
[Current recommendation](https://primer.style/view-components/lookbook/pages/forms/getting_started) is to put form objects in `app/forms` and mimic the same directory structure as `app/controllers`.

These files are not forms, but rather extensions of the forms dsl. They have been moved to `lib/` in 0a4dbe97a.

2023-09-15 07:21 UTC, cbliard commented on frontend/src/global_styles/openproject/_primer-adjustments.sass
> +// disabled for now in order to see the conflicts
There are editor configs to do it automatically:

* VSCode: `files.trimFinalNewlines: true`
* Atom: `whitespace.ensureSingleTrailingNewline: true`
* RubyMine: under Settings > Editor > General
  * check "Remove traling blank lines at the end of saved files"
  * check "Ensure every saved file ends with a line break"

2023-09-15 07:21 UTC, cbliard commented on app/views/homescreen/index.html.erb
> +
There are editor configs to do it automatically:

* VSCode: `files.trimFinalNewlines: true`
* Atom: `whitespace.ensureSingleTrailingNewline: true`
* RubyMine: under Settings > Editor > General
  * check "Remove traling blank lines at the end of saved files"
  * check "Ensure every saved file ends with a line break"

2023-09-15 07:50 UTC, ulferts commented on app/forms/op_primer/forms/autocompleter.rb
> +module OpPrimer
Understood, @cbliard. Now, those auxiliary form files are in lib/primer/open_project and the actual forms used in pages will be in `app/forms`. I can understand that distinction. Thanks for clarifying.  

I like that the auxiliary classes now are also in `Primer::OpenProject` same as the components by which we extend `Primer`.

2023-09-15 12:29 UTC, ulferts requested changes
I still did not manage to work through all of the PR and plan to continue to do so on Monday. Most of the remarks up until now are at the code but some is also more general:

### CSS included multiple times:

The css seems to be included multiple times:

<img width="514" alt="image" src="https://github.com/opf/openproject/assets/617519/eddb7c36-f516-471e-92de-9feb5fdfd88d">

I did not check whether that is a problem originating in this PR.

### Empty page on canceling the editing of the meeting title

Clicking on 'Cancel' when editing the meeting title leads to an empty page:

<img width="620" alt="image" src="https://github.com/opf/openproject/assets/617519/5e83b5e2-44b1-43a9-9ba4-0b4a64a005fb">
 
### Opinion/Feedback: Closing (the agenda) and editing other values

It feels weird that I can close/lock the agenda and then still edit the meetings attributes and participants:

<img width="191" alt="image" src="https://github.com/opf/openproject/assets/617519/0dca4a23-9e97-4b65-9b99-88ef00a83a19">

Especially while we have no built in support for the minutes which will probably result in people writing that information inside the "Description" field, closing (the agenda) will, if at all , be done at the end of the meeting. And then, the other attribute should be locked as well.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meeting_agenda_items/item_component/show_component.rb
> +             ))
I am rather sure that a `DragHandlerComponent` will be used again and again, so I'd rather extract it now.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meeting_agenda_items/item_component/show_component.rb
> +      end
This part could also be extracted into a component.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meeting_agenda_items/item_component/show_component.rb
> +    end
Unless this is planned to be used, please remove the method and those affected by it, e.g. `time_slot_partial`

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meeting_agenda_items/new_component.rb
> +      @meeting_agenda_item = meeting_agenda_item || MeetingAgendaItem.new(meeting:, author: User.current)
The initialization of a new item should rather be done in the controller (where we formerly relied on the SetAttributesService to do so) than in the view.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meetings/header_component.rb
> +  class HeaderComponent < ApplicationComponent
We do have the `Primer::OpenProject::PageHeader` component in by now and this looks to be a good case where it should be applied - at least for the show state.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meetings/row_component.rb
> +        I18n.t('meeting.types.classic')
A key other then classic would be more descriptive

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/meetings/sidebar_component.rb
> +  end
It appears that we are rebuilding GitHub's sidebar here which is not part of Primer. 

When looking at the CSS classes we seem to be doing it a way different from the way GitHub does it even though the result looks the same. 

We should move the component to a more general place so that it can be reused, ideally into the `primer_view_components` repo. To me, it would also make sense to mimic the styles used by GitHub in the implementation.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/components/users/avatar_component.rb
> +    end
This component isn't meeting specific and should be moved to `/app/components`

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/contracts/meeting_agenda_items/delete_contract.rb
> +  end
This contract does not check permissions. Is this intended as the permissions are checked elsewhere?

If permissions are to be checked. Inheriting from `DeleteContract` would make that easier.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/contracts/meeting_agenda_items/create_contract.rb
> +      end
No permission check is applied here. Is this intended and is the permission checked elsewhere?

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/contracts/meeting_agenda_items/update_contract.rb
> +    end
Again, no permission checked. And the contents is basically the same as in the other contracts so using a module could reduce duplication.

2023-09-15 12:29 UTC, ulferts commented on modules/meeting/app/controllers/concerns/agenda_component_streams.rb
> +module AgendaComponentStreams
Namespacing this so that in reads `Meetings::AgendaComponentStreams` would make the references in the code clearer.

2023-09-15 12:29 UTC, ulferts commented on app/controllers/concerns/op_turbo/component_stream.rb
> +    end
the before action and explicit initialization of the `@turbo_streams` variable is not really needed if a method like this is introduced

```
def turbo_streams
  @turbo_streams ||= []
end
```

and only the method is called.

2023-09-18 05:40 UTC, oliverguenther commented on modules/meeting/app/components/meetings/header_component.rb
> +  class HeaderComponent < ApplicationComponent
We will replace the header component with the PageHeader as soon as it becomes editable

2023-09-18 05:51 UTC, oliverguenther commented
> CSS included multiple times:

Not introduced in this PR: https://github.com/opf/openproject/pull/13720

2023-09-18 06:49 UTC, oliverguenther commented
- [ ] When creating a new agenda item, selecting a user and leaving the title blank, then saving the agenda item "resets" the user selection hidden input. When you fill out a title and hit save, a different user is saved.

2023-09-18 09:57 UTC, oliverguenther commented
- [ ] Escape on title input should cancel create and editing of an meeting agenda item (no confirmation)

2023-09-19 11:52 UTC, oliverguenther commented on modules/meeting/app/components/meeting_agenda_items/new_component.rb
> +      @meeting_agenda_item = meeting_agenda_item || MeetingAgendaItem.new(meeting:, author: User.current)
The problem here is that this is called from multiple places, so you'd need to duplicate the initialization logic. I suggest we discuss a convention for this separately

2023-09-19 14:45 UTC, oliverguenther commented
Squashed into https://github.com/opf/openproject/pull/13725

2023-09-19 14:45 UTC, closed without merging