[#39455] Allow filtering of "empty" date fields (start/finish/custom)
opf/openproject pull request #13667
Opened 2023-09-08 09:37 UTC by mrmir

https://community.openproject.org/work_packages/39455

2023-09-19 22:02 UTC, aaron-contreras commented on spec/features/work_packages/is_empty_filter_spec.rb
> +#-- copyright
```suggestion
# frozen_string_literal: true

#-- copyright
```

2023-09-19 22:04 UTC, aaron-contreras commented on spec/features/work_packages/is_empty_filter_spec.rb
> +RSpec.describe 'Filter by date with "is empty"', js: true do
There's a new Rubocop well... - cop - that suggests the symbol style metadata. Also, using cuprite add a small performance boost to this spec out of the box :)

```suggestion
RSpec.describe 'Filter by date with "is empty"', :js, :with_cuprite do
```

2023-09-19 22:05 UTC, aaron-contreras commented on spec/features/work_packages/is_empty_filter_spec.rb
> +           searchable: true).tap do |custom_field|
Recently learned that FactoryBot yields the object to the factory if a block is provided; no need to `#tap` :)
```suggestion
           searchable: true) do |custom_field|
```

2023-09-19 22:08 UTC, aaron-contreras requested changes
Nice! 🖌️ Left some suggestions in the specs.

I feel the feature spec better fits under `spec/features/work_packages/table/queries/is_empty_filter_spec.rb`. All other filter feature specs are grouped there so it would make it easier to discover if it were grouped there as well

2023-09-22 11:18 UTC, mrmir commented on spec/features/work_packages/is_empty_filter_spec.rb
> +RSpec.describe 'Filter by date with "is empty"', js: true do
Hey @aaron-contreras, what does this mean?

> There's a new Rubocop well... - cop - that suggests the symbol style metadata.

2023-09-22 11:21 UTC, aaron-contreras commented on spec/features/work_packages/is_empty_filter_spec.rb
> +RSpec.describe 'Filter by date with "is empty"', js: true do
`js: true` can also be written as `:js`, as RSpec picks up the example group and infers you'd like to set it to true. The style that RSpec is enforcing now is the latter. It also reads a little more declaratively that way :)

2023-09-22 11:34 UTC, mrmir commented on spec/features/work_packages/is_empty_filter_spec.rb
> +RSpec.describe 'Filter by date with "is empty"', js: true do
Aah okay, thanks!

2023-09-22 11:39 UTC, mrmir commented
Thanks for those suggestions and for finding a better spot for the file @aaron-contreras, ready for you to review again :)

2023-09-22 11:44 UTC, aaron-contreras approved these changes

2023-09-22 12:16 UTC, merged