Correctly save and handle boolean settings in OIDC administration
opf/openproject pull request #13876
Opened 2023-10-09 14:30 UTC by oliverguenther

https://community.openproject.org/work_packages/50432
https://community.openproject.org/work_packages/50448

2023-10-11 10:11 UTC, machisuji requested changes
@oliverguenther Thanks, this does fix the "use_graph_api" setting for the providers. Unchecking it and saving it now results in "use_graph_api" being false as expected.

The limit self registration functionality isn't working as expected anymore, though. Could you please have a look (see my other comment)?

2023-10-11 10:11 UTC, machisuji commented on app/services/users/register_user_service.rb
> +      if limited_provider?(user) && Setting::SelfRegistration.disabled?
Thanks for adding the specific error message helping users to help themselves.

However, this only covers the case that the global self registration is disabled. As it stands right now your PR allows OIDC/SAML users to register and activate even when the global self registration is set to manual.

The expected behaviour is that the OIDC/SAML registration should follow the global setting when "Limit self registration" is checked. That is a user should be able to register but **not** be activated if the global setting says manual.

2023-10-11 10:16 UTC, machisuji commented on app/services/users/register_user_service.rb
> +      if limited_provider?(user) && Setting::SelfRegistration.disabled?
I'm not sure why the spec doesn't catch this but I can definitely activate straight away.

![image](https://github.com/opf/openproject/assets/158871/ed698e52-1c4c-4ec9-8fd1-1e242a01c482)

![image](https://github.com/opf/openproject/assets/158871/0f5c7e50-6880-4730-8aa0-4224bf2b47b8)

![image](https://github.com/opf/openproject/assets/158871/7e8ec584-4bc7-4272-adb4-149fdaf7c8e3)

![image](https://github.com/opf/openproject/assets/158871/c704076b-e9a3-45ed-9e04-95d0b7305c70)

2023-10-11 14:55 UTC, oliverguenther commented
The test did not fail as `activate` was being stubbed so the user never actually changes statuses. This was quite confusing to me, but I've now added explicit tests for all of the different cases. The important bit was this line was missing: https://github.com/opf/openproject/pull/13876/commits/f58c7cda5e7375b3837a451872c2bca54e1d0ce3#diff-a17b7585f4902955b36e61e3ddc85553af1855b7da91c59cce8dc3b8b5db4d1eR119

I've double checked with a keycloak OIDC and saml idP now

2023-10-12 11:13 UTC, machisuji commented
> The test did not fail as `activate` was being stubbed so the user never actually changes statuses. This was quite confusing to me, but I've now added explicit tests for all of the different cases. The important bit was this line was missing: [f58c7cd#diff-a17b7585f4902955b36e61e3ddc85553af1855b7da91c59cce8dc3b8b5db4d1eR119](https://github.com/opf/openproject/commit/f58c7cda5e7375b3837a451872c2bca54e1d0ce3#diff-a17b7585f4902955b36e61e3ddc85553af1855b7da91c59cce8dc3b8b5db4d1eR119)
> 
> I've double checked with a keycloak OIDC and saml idP now

Thanks for fixing and expanding the specs! There just one failure where an expected call is done one too many times. Could you please have a look? Once that is green this is good to merge! 👍

2023-10-12 12:27 UTC, machisuji approved these changes
👍

2023-10-12 12:27 UTC, merged