[#50236] Allow sharing with groups
opf/openproject pull request #13883
Opened 2023-10-10 17:45 UTC by aaron-contreras

## Description
**NOTE FOR REVIEWER**
This PR is based off https://github.com/opf/openproject/pull/13845. Some early commits are pulled from it. Real commit history for this branch should reflect when the aforementioned PR is merged.

### What is bundled in this PR?
#### Including Groups in share modal's auto-completer search results
![Kapture 2023-10-10 at 12 44 13](https://github.com/opf/openproject/assets/61627014/2b31a5b8-a8a6-4633-8fa9-d8bfcbb9f218)

## Notes
See: https://community.openproject.org/work_packages/50236

2023-10-13 08:21 UTC, ulferts requested changes
I like the PR. Reads straightforward and the added tests give a feeling of being solid.

When trying out the functionality a couple of scenarios fail. Since the code for fanning out and destroying group memberships wasn't touched, it might well be that the problem is caused by code that existed before and has had the same problem all the time.

Given: 
* User is part of the group
Steps:
* Add user with permission "View"
* Add group with permission "Edit"
* Edit user's share to have permission "Edit"
* Remove group's share
Expected
* Group's share is removed
* Users' share stays
Actual:
* Both shares are removed

Given: 
* User is part of the group
Steps:
* Add user with permission "View"
* Add group with permission "Edit"
* Edit user's share to have permission "Edit"
* Re-Add group to have permission "View"
Expected
* Group's share is updated
* Users' share stays the same
Actual:
* Group's share is updated
* User's share is removed

Given: 
* User is part of the group
Steps:
* Add group with permission "Edit"
* Add user with permission "Edit"
Expected
* Group's share is unchanged
* Users' share is added with "Edit" permission
Actual:
* Group's share is unchanged
* Users' share is is not added

Given: 
* User is part of the group
Steps:
* Add group with permission "Edit"
* Add user with permission "View"
* Update user's share to have permission "Edit"
* Close and reopen modal
Expected
* Group's share is showing "Edit"
* Users' share is showing "Edit"
Actual:
* Group's share is showing "Edit"
* Users' share vanished

2023-10-13 08:21 UTC, ulferts commented on app/components/work_packages/share/modal_body_component.html.erb
> +                               .first
Not caused by this PR but we need to find a better way of dealing with this. The way we are currently doing it will lead to n+1 queries. 

Not part of the PR so does not need to be fixed in it.

2023-10-13 08:21 UTC, ulferts commented on app/components/work_packages/share/permission_button_component.rb
> +        end
Same as above, we need to avoid n+1 loading this information. But as above, it can also happen outside of this PR.

2023-10-13 08:21 UTC, ulferts commented on app/components/work_packages/share/permission_button_component.rb
> +               .first
`share.roles` will already have `member_roles` joined as it is the join table between `members` and `roles`.

2023-10-13 08:21 UTC, ulferts commented on app/controllers/work_packages/shares_controller.rb
> +                                        .size
In this PR you are redoing the pattern `Member.joins(:member_roles).where(member_roles: { inherited_from: nil))`. Additionally I see  `Role.join(:member_roles).where(member_roles: { inherited_from: nil))`.  

You could have a `MemberRole.not_inherited` scope. And by that have:
`Member.joins(:member_roles).where(MemberRole.not_inherited))`
`Role.join(:member_roles).where(MemberRole.not_inherited)`

You'd still end up repeating the joins. That can also be placed into a scope if you deem it appropriate. All of this is not super important admittedly.

2023-10-13 08:21 UTC, ulferts commented on app/forms/work_packages/share/invitee.rb
>                      { name: 'id', operator: '!', values: [::Queries::Filters::MeValue::KEY] }],
There is an edge case hidden in here:

If the user is part of a group, that user can now give permissions to the group they are member of and by that in effect manage their own sharing. 

I don't think it is super critical for now since share_work_packages requires edit_work_packages. But this might be subject to change. And even now, the user potentially gains the ability to:
* be assignee 
* log own time and see them
* manage relations
over what the edit_work_package permission allows.

The only thing we could do to avoid this would be to limit the groups to those the user is not a member in and that might also be weird as it is hard to communicate that to the user. 

Or we exclude the user from being added when adding their group.

But ideas sound bad and I don't have better ones. One could also argue that we have the same problem with members where having the manage members permission allows to set additional permission for oneself.

2023-10-13 08:21 UTC, ulferts commented on app/models/principal.rb
> +           foreign_key: 'user_id'
We now have:
```
has_many :members, dependent: :destroy
has_many :memberships, dependent: :nullify
has_many :work_package_shares, dependent: :delete_all
```

Which all reference the same entries in the database. I don't know which one wins.

An inherited problem but I would like to know what actually happens.

2023-10-13 08:21 UTC, ulferts commented on app/workers/mails/work_package_shared_job.rb
> +          .select('members.id')
Minor thing and not awfully relevant here but typically you want to use `COUNT(*)` over `COUNT(column)`. The only reason for using `COUNT(column)` is if you want to exclude NULL values which that statement filters out. But it has to check that value for doing it which is why it is slower.

2023-10-13 08:21 UTC, ulferts commented on spec/features/work_packages/share_spec.rb
> +      click_button 'Share'
Why close the modal at this step?

2023-10-13 08:21 UTC, ulferts commented on spec/features/work_packages/share_spec.rb
> +        share_modal.expect_shared_count_of(7)
Kudos 🙇 for the love you showed on this feature spec.

2023-10-13 08:21 UTC, ulferts commented on spec/support/components/work_packages/share_modal.rb
>          modal_element.send_keys(:escape)
By now there is a close button on the share modal so we can just press that one. So good if the usability is right. 😄

2023-10-13 21:57 UTC, aaron-contreras commented
Hi @ulferts , thanks for catching those edge cases❗️ As discussed in our quick-chat this morning, the pattern indeed re-occurs when both the Group and User are granted the same Role and I have tracked down what's going on. I've detailed my findings with a walkthrough of what's happening and I've verified the current behavior of how Project memberships with Users and Groups are currently behaving and actually there is no bug coming from before, what was discovered in this PR is expected behavior (at least for Projects):

## Why is this happening?

The underlying issue lies in the `WorkPackageMembers::UpdateService` and specifically, in the `Members::Concerns::RoleAssignment` concern. Let's take the first mentioned scenario:

### Walkthrough

Given:
- User is part of the group

Steps:
 1. Add user with permission "View"
 2. Add group with permission "Edit"
 3. Edit user's share to have permission "Edit"
 4. Remove group's share
 
Expected:
- Group's share is removed
- User's share stays

Actual:
- Both shares are removed

**Step 1**

Sharing the work package with the user with the "View" role creates the following DB structure:

<img width="652" alt="image" src="https://github.com/opf/openproject/assets/61627014/db79ac56-eae2-449b-8392-b7f882c63128">

**Step 2**

Subsequently, sharing the work package with the group with the "Edit role" creates the following DB structure:

<img width="652" alt="image" src="https://github.com/opf/openproject/assets/61627014/ca00eaa9-2fb5-45e4-bc6e-0a16a6fc123d">


All is fine after this step. However, when executing...

**Step 3**

The PATCH request performed by the select dropdown is providing `Member1` (The `Member` record for Dinesh). What happens next in the `SetAttributesService` is the root cause of the problem. I've annotated the code snippets with a step by step walkthrough:
```ruby
module WorkPackageMembers
  class SetAttributesService < ::BaseServices::SetAttributes
    prepend Members::Concerns::RoleAssignment

    private

    def set_attributes(params)
      # The call to super invokes the `set_attributes` method in the prepended concern
      super

      model.change_by_system do
        model.project = model.entity&.project
      end
    end
  end
end
```

```ruby
module Members::Concerns::RoleAssignment
  private

  # Which invokes this method
  def set_attributes(params)
    assign_roles(params)

    super
  end

  def assign_roles(params)
    raise ArgumentError, 'Cannot handle changing `roles`. Use role_ids instead.' if model.persisted? && params.key?(:roles)

    return unless params[:role_ids]

    role_ids = params
                 .delete(:role_ids)
                 .select(&:present?)
                 .map(&:to_i)
    # role_ids is the id of "EditRole"
    
    existing_ids = model.member_roles.map(&:role_id)
    # Dinesh's roles via his member_roles are "EditRole" and "ViewRole"

    # ["EditRole", "ViewRole"] - ["EditRole"] => ["ViewRole"]
    # Which means Dinesh's MemberRole1 (the non-inherited one) gets
    # marked for destruction.
    mark_roles_for_destruction(existing_ids - role_ids)

    # ["EditRole"] - ["EditRole", "ViewRole"] => []
    # Which means that Dinesh is not getting a new "MemberRole4"
    # with the "EditRole" that is not inherited.
    # Here lies the bug!
    build_roles(role_ids - existing_ids)
  end

  def mark_roles_for_destruction(role_ids)
    role_ids.each do |role_id|
      model
        .member_roles
        .detect { |mr| mr.inherited_from.nil? && mr.role_id == role_id }
        &.mark_for_destruction
    end
  end

  def build_roles(role_ids)
    role_ids.each do |role_id|
      model.member_roles.build(role_id:)
    end
  end
end
```

And here it is. After performing **Step 3**, Dinesh ends up solely with the `MemberRole3` which he inherited from his Group

<img width="651" alt="image" src="https://github.com/opf/openproject/assets/61627014/dab1a681-6388-4e24-b860-ae804dbc49b1">


So then when performing **Step 4**, the cleanup job is doing its job properly and deleting `Member2` along with `MemberRole2` (Cool Group's `Member` record along with its `MemberRole` record), **AND** `Member1` along with its only left `MemberRole3` (which was inherited). That is why all shares for the work package are gone and this is correct behavior on the cleanup job's end.

The 3rd described scenario in the failing cases demonstrates exactly what's happening in the `SetAttributesService`:

**Scenario 3**

Given:
* User is part of the group

Steps:
* Add group with permission "Edit"
* Add user with permission "Edit"

Expected:
* Group's share is unchanged
* Users' share is added with "Edit" permission

Actual:
* Group's share is unchanged
* Users' share is is not added


The reason why this is behaving in this manner can be digested in the following two bullet points providing a digest of how Project memberships for Users and Groups have worked thus far:

Given "Role A" exists
Given you're a member of "Cool Group", "Cooler Group", and _n_ other number of groups.

* "Role A" can only ever be granted to you via _n_ groups you're a member of (each creating a separate `member_role` record in your Project membership with its inherited_from column`inherited_from: <group_member_role_id>`) **OR** as a direct membership in a project. Meaning if you were granted "Role A" independently and then any group you belong to is granted "Role A", you would only keep the inherited `member_role` with "Role A" just granted to you via the group. This sort of makes sense because why would you have the same role assigned from two different sources on the same resource. At least, I believe that was the train of thought back in time.
* Following up with the previous bullet point, you can be granted "Role A" multiple times **as long as it is granted via a different group**. Meaning if you are part of "Cool Group" and "Cooler Group" and both groups were granted "Role A", you would have two distinct `member_roles` each with a different `inherited_from` id (respectively, "Cool Group"'s `member_role` and "Cooler Group"'s `member_role`). That's how the `CleanupInheritedRolesService` is able to work its magic when you're removed from a group or when a group's membership is revoked, given that there are two separate `member_role`s granted to you by both groups.

Following all of the above, this raises the following questions:
1. Do we want to be able to grant the same Role to a User independently **AND** via any _n_ number of groups?
2. If so, which benefits does this yield?

I would find reasonable if this works exactly as described in the Project membership mechanics, but I would also find it somewhat reasonable to be able to grant the same Role both independently and via _n_ number of groups: on the one hand, it'd be nice that if I had specifically granted Dinesh "Role A", and I granted a group he belonged to "Role A", that upon modifying the Role that the group is shared the work package with that Dinesh's role is intact given I specifically granted him "Role A". However, it seems to me like the former is exactly what a sharer might **NOT** desire.

I see two options:
1. Allowing the described behavior in entity memberships.
2. Modifying the share modal behavior:
   * Hide/disable the roles in the dropdowns in both the row and invite form that have been granted to a User via a group.
   * Given "Role A", "Role B", "Role C", and "Dinesh" is a member in "Cool Group"
   * If "Cool Group" was invited with "Role A", when attempting to invite "Dinesh" individually, only "Role B" and "Role C" should be available roles. 
   * If "Dinesh" was invited with "Role A", and subsequently "Cool Group" is invited with "Role A", then "Dinesh"'s share row should be removed from the dropdown modal (this could be surprising, some indication of what happened should be made visible)

2023-10-16 13:27 UTC, aaron-contreras commented
Discussed this today with @klaustopher and we DO want to be able to grant the same role to a user independently and via a group. Converting back to a draft to account for this

2023-10-16 19:28 UTC, aaron-contreras commented on spec/features/work_packages/share_spec.rb
> +      click_button 'Share'
No reason. It's a left-over

2023-10-16 19:34 UTC, aaron-contreras commented on spec/features/work_packages/share_spec.rb
> +        share_modal.expect_shared_count_of(7)
Thank you :)

2023-10-16 19:39 UTC, aaron-contreras commented on app/components/work_packages/share/modal_body_component.html.erb
> +                               .first
https://community.openproject.org/work_packages/50544/activity

2023-10-16 19:39 UTC, aaron-contreras commented on app/components/work_packages/share/permission_button_component.rb
> +        end
https://community.openproject.org/work_packages/50544/activity

2023-10-18 15:00 UTC, klaustopher reviewed
PR looks good from my side. I'll leave the final review for @ulferts as he has brought up some valid concern and I cannot 100% assess if they are fulfilled.

2023-10-20 12:02 UTC, ulferts commented on app/forms/work_packages/share/invitee.rb
>                      { name: 'id', operator: '!', values: [::Queries::Filters::MeValue::KEY] }],
I copied that question to the Share-Epic on OpenProject community.

2023-10-20 12:03 UTC, ulferts approved these changes
Thanks for the detective work, @aaron-contreras. Feels good now and I did not run into any more weird cases.

2023-10-20 12:03 UTC, merged