Enable the Nextcloud Sync Service to mark a storage as unhealthy
opf/openproject pull request #14130
Opened 2023-11-09 18:30 UTC by mereghost

##### Related Work Package: [OP#50914](https://community.openproject.org/projects/openproject/work_packages/50914) 

## What?

The sync jobs run on the background, frequently failing without knowledge of the admins. This PR aims to lay the groundwork for the SyncService/CronJob pair to mark the storage as unhealthy.

## How?

I added a new `jsonb` field to the storage, containing the attributes that we would need to notify an admin that something is wrong with their integration.

The names right now are... dumb, I'm all ears for better suggestions.

Moreover I've made changes so that the entire SyncService works with service results, which will make it easier to return the necessary info.

2023-11-10 12:27 UTC, Kharonus requested changes

2023-11-10 12:27 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/add_user_to_group_command.rb
> +      error_data = Storages::StorageErrorData.new(source: self.class, payload: response)
🟢 Nice, thanks!

2023-11-10 12:27 UTC, Kharonus commented on modules/storages/app/models/storages/nextcloud_storage.rb
> -    def self.sync_all_group_folders
❓  can you shortly elaborate, why this class method is no longer needed? I fail to see the connection to the scope of the PR, yet.

2023-11-10 12:27 UTC, Kharonus commented on modules/storages/app/services/storages/group_folder_properties_sync_service.rb
> -      prepare_remote_folders and apply_permissions_to_folders
🟡 why can't we bind both calls together? so that a failure in `prepare_remote_folder` would already return failure service result? We did this with the `>>` operator, didn't we?

The new lines contain the same error handling twice.

2023-11-10 12:27 UTC, Kharonus commented on modules/storages/app/services/storages/group_folder_properties_sync_service.rb
> +        # ServiceResult.failure(errors: error)
🔴 commented line

2023-11-10 12:27 UTC, Kharonus commented on modules/storages/app/models/storages/nextcloud_storage.rb
> -    def self.sync_all_group_folders
Ah, is it, that you basically moved the code into the cron job?

2023-11-10 12:27 UTC, Kharonus commented on modules/storages/app/workers/storages/manage_nextcloud_integration_cron_job.rb
> +            storage.mark_as_unhealthy(reason: error.code)
🟡 a bit confused: how does a storage will get healthy again? I see no branch where it is marked as healthy.

2023-11-10 12:35 UTC, mereghost commented on modules/storages/app/models/storages/nextcloud_storage.rb
> -    def self.sync_all_group_folders
Yep. This was moved to bring it closer to what triggers the behaviour.

2023-11-10 13:11 UTC, mereghost commented on modules/storages/app/services/storages/group_folder_properties_sync_service.rb
> -      prepare_remote_folders and apply_permissions_to_folders
`bind` is sure an option. I've changed it a bit to a syntax that may look clearer to the casual rubyist.

2023-11-10 14:25 UTC, ba1ash commented on modules/storages/app/services/storages/group_folder_properties_sync_service.rb
> +        # This hides the folder, but it will be in the logs
I cannot understand the comment here.
The return of failure directly will not hide the folder, right. I suggest  to be more explicit here:
1. clarify which folder: `the root group folder`
2. have a reference how returning a failure result leads to hiding.

2023-11-10 17:12 UTC, mereghost commented on modules/storages/app/services/storages/group_folder_properties_sync_service.rb
> +        # This hides the folder, but it will be in the logs
The comment is wrong XD It should say, "don't hide the folder" 🤦🏼

2023-11-20 13:22 UTC, apfohl requested changes
Please create a default value for the health status as described in my comments.

2023-11-20 13:22 UTC, apfohl commented on modules/storages/app/models/storages/storage.rb
> +
I Suggest adding a default value to the health status in the database and simplify the logic here to side effect free methods.

2023-11-20 13:22 UTC, apfohl commented on modules/storages/app/models/storages/storage.rb
> +
I suggest `unhealthy` as the default and setting it to `health` upon completion of the setup.

2023-11-20 13:22 UTC, apfohl commented on modules/storages/spec/models/storages/nextcloud_storage_spec.rb
> +    end
With the changes above in the storage model these specs need to be reworked.

2023-11-22 14:50 UTC, Kharonus approved these changes
I have nothing to add to this change anymore. So I agree for a merge. If we find anything not fitting, we can still adapt the code. from maintenance perspective code looks good! 👍🏽

2023-11-22 15:45 UTC, merged