[#50255] Add User Details to the Share Modal List
opf/openproject pull request #14170
Opened 2023-11-17 14:19 UTC by aaron-contreras

This PR adds "user details" indicating the current membership state of each user within their row in the share modal. This can comprise their status ("locked", "invited"), their belonging to a group, project memberships, invitation status, and work package role.

I've written some thorough component specs for it to serve as documentation for the expected rendering based on each scenario. I hope this makes the reviewer's experience a bit smoother and can help us discuss any specific scenarios that might need textual changes.

## Notes
See: https://community.openproject.org/work_packages/50255

2023-11-20 10:01 UTC, HDinger requested changes
Nice job, it looks already quite solid 👍 

I have found one case in which the wrong text is shown:
- [ ] I have user X who is not member of the project, but part of a group (which is also not member of the project). I share WP A with the group, and I share WP B with the user X. I would have expectd to read "not project member", but instead it was shown "Part of a shared group. Not project member"

Further, there is an edge case which we probably have to tackle separatly:
- [ ] I have user X who is a project member and part of a group. I share any WP with the user, and read "Project member: roleXY" (which is correct). Afterwards, I share the same WP with the group. The text of the user X is not affected by that. Only when I close and reopen the modal I see the updated text below the user "Part of a shared group. Project member: roleXY" 

Last but not least, I'd like to question the whole wording, as it is really hard to understand what this text should tell me. Especially when there are two information combined due to a group, it gets really difficult. Taking this example: "Part of a shared group. Project member: Member": I assumed that the two sentences belong to each other or build upon each other. I thought, "project member: member" is the role of the group not of the user.
I honestly think that we sometimes confuse more than we deliver value with this extra line /cc @psatyal

2023-11-20 10:01 UTC, HDinger commented on app/components/work_packages/share/user_details_component.rb
> +        user.locked? || user.invited?
We already have a method `active?` on the users. Couldn't we use that one instead?

2023-11-20 12:15 UTC, HDinger commented
> Last but not least, I'd like to question the whole wording, as it is really hard to understand what this text should tell me. Especially when there are two information combined due to a group, it gets really difficult. Taking this example: "Part of a shared group. Project member: Member": I assumed that the two sentences belong to each other or build upon each other. I thought, "project member: member" is the role of the group not of the user.
> I honestly think that we sometimes confuse more than we deliver value with this extra line

@aaron-contreras I talked with the product team about that and they will come up with an alternative proposition.

2023-11-20 12:16 UTC, aaron-contreras commented
Hi @HDinger , thanks for the review.

Regarding your first point, I understood this is actually what is expected when one if part of a shared group. You'd like to know that you're part of a shared group + your project membership status. This is my understanding based on the Figma designs but as you said, this is all quite confusing to begin with 😅

Would you like your second point addressed as critical in this PR or in a next round?

2023-11-20 12:28 UTC, HDinger commented
> Regarding your first point, I understood this is actually what is expected when one if part of a shared group. You'd like to know that you're part of a shared group + your project membership status. This is my understanding based on the Figma designs but as you said, this is all quite confusing to begin with 😅

mhh.. hard to say 😅 I thought, only groups that are shared with this specific WP are relevant 🤷‍♀️  Let's wait for the new texts. Maybe it isn't an issue any more after that 🤞 

> Would you like your second point addressed as critical in this PR or in a next round?

I wouldn't say it is critical. So I am fine with doing that in a second iteration. 👍

2023-11-22 12:32 UTC, HDinger commented on app/components/work_packages/share/user_details_component.rb
> +      end
Hi @aaron-contreras 

I am pretty sure that this can be written better, but I didn't know how 🙈 Could you please have a look at this? Thanks :)

2023-11-22 15:33 UTC, aaron-contreras commented on app/components/work_packages/share/user_details_component.rb
> +      end
Could try:
```ruby
Member.where(project: share.project, principal: user, entity: nil) # membership in the project
      .merge(MemberRole.only_inherited) # that was inherited
      .any?
```

2023-11-23 08:46 UTC, HDinger approved these changes
Good to merge from my side. Waiting for the final okay from @aaron-contreras

2023-11-23 12:08 UTC, aaron-contreras commented
@HDinger Thumbs up! 👍

2023-11-23 12:08 UTC, merged