[50749] Contrast issues
opf/openproject pull request #14185
Opened 2023-11-20 12:41 UTC by bsatarnejad

2023-11-24 09:09 UTC, HDinger requested changes
Hi @bsatarnejad 

Looks good overall. I found some place that still don't have enough contrast:

- [x] In the files tab (`To add a link, see or upload files...`) the text is too bright. (contrast 2,8:1)
<img width="200" alt="Bildschirmfoto 2023-11-24 um 09 26 48" src="https://github.com/opf/openproject/assets/7457313/b0c5b4b8-eb8c-4f9d-92b3-d9b823421512">


- [ ] There are multiple places where we reached a ratio of 5:1 which is not sufficient for wcag AAA. I am not sure at the moment whether we aim for AA or AAA. Please double check that. For AAA we would need a ratio of 7:1. Examples are the sidebar headlines, locked users in the administration, filtered out parents in the WP table, the placeholder in date modal or greyed out options in the configuration dropdown of the WP table.
<img width="200" alt="Bildschirmfoto 2023-11-24 um 09 25 46" src="https://github.com/opf/openproject/assets/7457313/1583c8cf-2ec0-4941-b6d4-6f100e8c0d89">
<img width="200" alt="Bildschirmfoto 2023-11-24 um 09 24 42" src="https://github.com/opf/openproject/assets/7457313/88937f7a-c75c-4897-a458-1043fe7c29fa">
<img width="200" alt="Bildschirmfoto 2023-11-24 um 09 35 54" src="https://github.com/opf/openproject/assets/7457313/4d0b4bfd-852d-4112-847c-0f33cf6c461c">

2023-11-24 09:09 UTC, HDinger commented on frontend/src/app/shared/components/colors/colors.service.ts
> +    return document.body.getAttribute('data-light-theme') ?? 'light';
Currently you are checking (at multiple places) directly for the string Primer sets on the body. So whenever Primer changes that string, all of these checks will fail. Please make that a bit more future-proof and set `colorMode` to some kind of constant provided by us and then ckeck against that constant. Thus we will only have to adapt one place if Primer changes the string.

e.g.
```
   export const colorModes = {
     lightHighContrast: 'lightHighContrast
   }

   ...

    return document.body.getAttribute('data-light-theme') === 'light_high_contrast' ? colorModes.lightHighContrast : 'light';
    
    ... 

    if colorMode === colorModes.lightHighContrast ...
```

2023-11-24 09:09 UTC, HDinger commented on frontend/src/global_styles/content/_project_status.sass
> +$project-status-deep-green: var(--fgColor-success, var(--color-success-fg))
Please rename these variables. The variables don't necessarily translate to the colors in the names any more. Further, `status-green` and `status-deep-green` now have the same color. I know, that it was specified like this, so I asked the product team in the ticket to double check.

2023-11-30 07:43 UTC, bsatarnejad commented
> Hi @bsatarnejad
> 
> Looks good overall. I found some place that still don't have enough contrast:
> 
> * [x]  In the files tab (`To add a link, see or upload files...`) the text is too bright. (contrast 2,8:1)
> 
> <img alt="Bildschirmfoto 2023-11-24 um 09 26 48" width="200" src="https://private-user-images.githubusercontent.com/7457313/285400759-b0c5b4b8-eb8c-4f9d-92b3-d9b823421512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzA0MTEsIm5iZiI6MTcwMTMzMDExMSwicGF0aCI6Ii83NDU3MzEzLzI4NTQwMDc1OS1iMGM1YjRiOC1lYjhjLTRmOWQtOTJiMy1kOWI4MjM0MjE1MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDc0MTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWUyMTc0MTIyNmMxYjBkNTNmNTkyMzk0YTFiMmExZmRkZGI5OGI1OTYwN2RhNzhjOTBlMmQ4NjlhZGYwNTQxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.drchIZ-C2t5TIMFtiffUKI2-R5vUuavTY1Nc2iPl5hc">
> * [ ]  There are multiple places where we reached a ratio of 5:1 which is not sufficient for wcag AAA. I am not sure at the moment whether we aim for AA or AAA. Please double check that. For AAA we would need a ratio of 7:1. Examples are the sidebar headlines, locked users in the administration, filtered out parents in the WP table, the placeholder in date modal or greyed out options in the configuration dropdown of the WP table.
> 
> <img alt="Bildschirmfoto 2023-11-24 um 09 25 46" width="200" src="https://private-user-images.githubusercontent.com/7457313/285401245-1583c8cf-2ec0-4941-b6d4-6f100e8c0d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzA0MTEsIm5iZiI6MTcwMTMzMDExMSwicGF0aCI6Ii83NDU3MzEzLzI4NTQwMTI0NS0xNTgzYzhjZi0yZWMwLTQ5NDEtYjZkNC02ZjEwMGU4YzBkODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDc0MTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRkNzQ1MDM3ZWU5ZTk4MzY1ZjRhMDIwYWY1MGFlYTgxZGE1NWJiOTE3YjY1OTQ4MmJlOTIzZTUxZjk4ZGUzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NEq2Fxv3cB5TfaPZW9BXdf-BJLUbF6FOIU2rr2vjtPE"> <img alt="Bildschirmfoto 2023-11-24 um 09 24 42" width="200" src="https://private-user-images.githubusercontent.com/7457313/285401259-88937f7a-c75c-4897-a458-1043fe7c29fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzA0MTEsIm5iZiI6MTcwMTMzMDExMSwicGF0aCI6Ii83NDU3MzEzLzI4NTQwMTI1OS04ODkzN2Y3YS1jNzVjLTQ4OTctYTQ1OC0xMDQzZmU3YzI5ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDc0MTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE3Y2UyMzc5NTc3MDc5OWVlNTcwMzY0OTVjODMyYjkzYjgyZDNkM2Y3YzMxYWZkOTY3ZDZmN2IwODE3Mzg5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QcRTvAq1Sy3DlBmdBvTm6L-CFhhsR8LxgMOY_1YB-ow"> <img alt="Bildschirmfoto 2023-11-24 um 09 35 54" width="200" src="https://private-user-images.githubusercontent.com/7457313/285402414-4d0b4bfd-852d-4112-847c-0f33cf6c461c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzA0MTEsIm5iZiI6MTcwMTMzMDExMSwicGF0aCI6Ii83NDU3MzEzLzI4NTQwMjQxNC00ZDBiNGJmZC04NTJkLTQxMTItODQ3Yy0wZjMzY2Y2YzQ2MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDc0MTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc4MzNlZTNmZDliMDllMWZiYzI2ZWYxNzJkMzE4ZWRjN2IyNjExMjdkOTNlZjQwZWFlNGI2MDI3NzcyOGQ1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SxLBrcok7ZspI9f2Du-_9XLcgwjX-84gjtl3KriXjWQ">

As we discussed, We need to pass AA level, so for now a ratio of 5:1 is sufficient.

2023-11-30 11:39 UTC, HDinger approved these changes

2023-11-30 11:39 UTC, merged