[51170] Gantt: shorten menu and add "Show relations" action
opf/openproject pull request #14287
Opened 2023-11-30 12:37 UTC by bsatarnejad

- [ ] Change menu actions on Gantt view
- [ ] Add a new action entry for showing relations of a WP
- [ ] Write a test for showing relations in Gantt view

https://community.openproject.org/work_packages/51170/activity

2023-12-20 13:40 UTC, HDinger requested changes
Hi @bsatarnejad 

I tried to write down what we just discussed.

* Taken from the ticket description, there are two menu entries missing on the Gantt `Copy link to clipboard` and `Indent hierarchy`

2023-12-20 13:40 UTC, HDinger commented on frontend/src/app/features/work-packages/components/wp-table/context-menu-helper/wp-context-menu-helper.service.ts
> +    if (!!workPackage.addRelation && this.wpViewTimeline.isVisible) {
This checks for permissions to add relations, but we wan't this special menu always when the timeline is visible. I'd also vote for renaming the variable to something more gantt specific.

2023-12-20 13:40 UTC, HDinger commented on frontend/src/app/features/work-packages/components/wp-table/context-menu-helper/wp-context-menu-helper.service.ts
> +      });
Same as above, this should not only be visible when the user has the permission to add relations, but always when the Gantt is visible.

2024-01-09 09:12 UTC, ulferts commented
@bsatarnejad , @HDinger , the failing spec should disappear when merging with dev

2024-01-09 10:42 UTC, HDinger reviewed
The changes look good to me 👍  When testing it, I noticed that "Log unit costs" is still shown in the menu. In the ticket it is not specified but I assume that it should be hidden as "log time" is also hidden. After that, it is good to merge 👍

2024-01-09 11:13 UTC, HDinger approved these changes

2024-01-09 11:19 UTC, merged