Add mod_rewrite to nextcloud troubleshooting
opf/openproject pull request #14313
Opened 2023-12-04 09:51 UTC by tiroessler

Add mod_rewrite to the Nextcloud troubleshooting section in the documentation.

2023-12-07 11:02 UTC, machisuji requested changes

2023-12-07 11:02 UTC, machisuji commented on docs/system-admin-guide/integrations/nextcloud/README.md
> +  This often happens because mod_rewrite is not activated on the Nextcloud server.
@tiroessler I would mention this before the pretty URLs in NextCloud and adjust the description of that block to say to try this if the previous step with just enabling mod_rewrite didn't work.

2023-12-08 12:30 UTC, tiroessler commented on docs/system-admin-guide/integrations/nextcloud/README.md
> +  This often happens because mod_rewrite is not activated on the Nextcloud server.
@machisuji I added the requested changes

2023-12-19 08:56 UTC, oliverguenther approved these changes

2023-12-19 08:56 UTC, merged