[#49527] Allow Shared with users to become assignees
opf/openproject pull request #14472
Opened 2023-12-26 21:40 UTC by aaron-contreras

See: https://community.openproject.org/work_packages/49527

2024-01-05 14:35 UTC, aaron-contreras commented on spec/support/api/v3/shared_available_principals_examples.rb
> +                      I18n.t('api_v3.errors.not_found.work_package')
Default behavior for work-package-scoped endpoints is not to reveal the presence of restricted work packages

2024-01-08 15:03 UTC, ulferts requested changes
The change is looking good @aaron-contreras with the exception of a permission check which I think can be tightened.

2024-01-08 15:03 UTC, ulferts commented on lib/api/v3/work_packages/available_assignees_api.rb
> +            authorize_in_work_package(:view_work_packages, work_package: @work_package)
Why is the permission asked for here `:view_work_packages`? I realise that it is the same permission queried for by the `Projects::AvailableAssigneesAPI` as well. But a user being allowed to see the work packages does not need to see every assignable user. Only users having the `:edit_work_packages` permission need to see it here. For the `Projects::AvailableAssigneesAPI` endpoint, the permission should be `:add_work_packages` by now I think as that endpoint will only be used when creating a new work package now.

2024-01-08 15:03 UTC, ulferts commented on docs/api/apiv3/paths/work_package_available_assignees.yml
> +                message: The specified work package does not exist.
The message actually seems to be ` The work package you are looking for cannot be found or has been deleted.`.

2024-01-08 15:03 UTC, ulferts commented on docs/api/apiv3/paths/work_package_available_assignees.yml
> +      headers: {}
With the way the API is currently structured, this case cannot happen. If the user lacks the `view work packages` permission, they will not see the work package (`/api/v3/work_packages/:id`) which is the precondition to reaching its assignees (`/api/v3/work_packages/:id/available_assignees`).

This might change if the permission is changed to `edit_work_packages`

2024-01-08 15:15 UTC, aaron-contreras commented on lib/api/v3/work_packages/available_assignees_api.rb
> +            authorize_in_work_package(:view_work_packages, work_package: @work_package)
You're right. Nice catch!

2024-01-08 16:07 UTC, aaron-contreras commented
Feedback addressed. The specs should read a bit better now as well :) @ulferts

2024-01-09 08:03 UTC, klaustopher approved these changes
lgtm

2024-01-09 13:25 UTC, merged