add save option to project list menu
opf/openproject pull request #14487
Opened 2024-01-04 13:02 UTC by ulferts

Adds the option to save project queries (lists) for the user themselves. 

* [ ] Add "Save" item to menu
* [ ] Add query controller that saves
* [ ] Add Project Query Create service
* [ ] Add Project Query Create contract
* [ ] Display created Project queries in sidebar
* [ ] Persist filters (serialize/deserialize as JSON)

----

https://community.openproject.org/wp/51666

2024-01-29 08:24 UTC, ulferts commented on app/helpers/sort_helper.rb
> -    link_to_content_update(h(caption), safe_query_params(%w{filters page per_page expand}).merge(sort_options), html_options)
We explicitly want to loose the `page` here. Whenever the sorting changes, the first page should be displayed. The user just changed the sort order so staying on e.g. the 3rd page does not make sense.

2024-01-30 12:14 UTC, oliverguenther commented
- [ ] Adding a filter (at least Name and Identifier, project status) and clicking apply results in an error
<img width="1617" alt="Bildschirmfoto 2024-01-30 um 13 12 49" src="https://github.com/opf/openproject/assets/459462/5efa39f5-39d5-474c-8f57-00b87995323e">

2024-01-30 14:24 UTC, oliverguenther requested changes
- [ ] The export dialog always exports the default query, not the current saved one. This is not the case in current production (but may be broken in dev already)

2024-01-31 16:30 UTC, ulferts commented
@oliverguenther , the export feature broke in this PR. It was broken for persisted queries only but now will work also for them.

2024-01-31 18:16 UTC, oliverguenther approved these changes

2024-01-31 18:16 UTC, merged