[#52065] 13.2 Documentation: Enable manual project folders for OneDri…
opf/openproject pull request #14528
Opened 2024-01-10 14:13 UTC by MayaBerd

…ve/SharePoint storages  https://community.openproject.org/work_packages/52065

[#52065] 13.2 Documentation: Enable manual project folders for OneDrive/SharePoint storages

https://community.openproject.org/work_packages/52065

2024-01-10 15:01 UTC, Kharonus requested changes
WDYT about those change requests?

2024-01-10 15:01 UTC, Kharonus commented on docs/user-guide/projects/project-settings/file-storages/README.md
> +1. **No specific folder**: By default, each user will start at their own home folder when they upload a file.
in OneDrive/SharePoint there is no such thing as "user home folder", like in nextcloud. If `no specific folder` is selected, the user will start in the drive root when uploading files or selecting files for linking.

2024-01-10 15:01 UTC, Kharonus commented on docs/user-guide/projects/project-settings/file-storages/README.md
> +2. **Existing folder with manually managed permissions**: Once you selected this option, you can designate an existing folder as the project folder for this project using the button **Select folder**
"The permissions are however not automatically managed**, instead the folder and its content inherits the permissions as configured in the SharePoint site or drive**.

I'd add this, as Microsoft cloud uses a quite elaborate inheritance system for managing access. This should serve as a reminder for any admin.

2024-01-11 08:31 UTC, MayaBerd commented
> WDYT about those change requests?

@Kharonus very helpful, thank you! I've made the changes.

2024-01-11 08:59 UTC, merged