Unset moment.js locale in timezone service
opf/openproject pull request #14674
Opened 2024-01-29 17:35 UTC by dombesz

https://community.openproject.org/wp/48834

2024-01-30 09:20 UTC, oliverguenther requested changes
@dombesz Can you elaborate on why this would fix the issue? Removing these lines would prevent localized output of dates in e.g, the work package cards

2024-01-30 11:07 UTC, dombesz commented
The error is related to the localization mechanism in moment.js. In some languages, such as Arabic, Bengali, Burmese, Cambodian, Hindi etc, the numbers are also translated from traditional arabic `2024-01-30` to the language's native characters `៣០/០១/២០២៤`, `٣٠/‏١/‏٢٠٢٤` etc. I just removed the localization to see how many tests would be affected by that.

Imo the final solution would be to respect the user's language format from the settings `admin/settings/date_format` in the datepicker and translate it back to machine readable date formats, before sending it to the server.

2024-01-31 07:04 UTC, oliverguenther commented
Both your suggested changes would require a big change in the frontend (not saying I'm rejecting either, but would lean towards the second - using the Intl. APIs to access dates instead of moment).

You mentioned we could try to disable the locale setting just for parsing the ISO8601 dates (or use another mechanism to parse these).

2024-02-08 13:49 UTC, dombesz commented on frontend/src/app/core/datetime/timezone.service.ts
> -  public setupLocale():void {
This is no more required, because we set the locale in the `init-locale.ts` below.

2024-02-12 09:12 UTC, oliverguenther approved these changes

2024-02-12 09:12 UTC, merged