[52127] Project list: Truncate long text fields and disable expand action
opf/openproject pull request #14777
Opened 2024-02-13 08:01 UTC by bsatarnejad

https://community.openproject.org/projects/openproject/work_packages/52127/activity

2024-02-16 17:01 UTC, ulferts requested changes
Hi @bsatarnejad ,

it is good to see , that we can remove a bunch of code by this change. However, there are a couple of issues with this PR:

------

* [x] The text of the status description, descriptionText not displayed in only a single line.
<img width="1220" alt="image" src="https://github.com/opf/openproject/assets/617519/99110660-e1e5-4753-baa5-bd1aeb8c3b48">

With tables and images possible being part of the text, this might become quite hard to achieve. I believe there are two options: 
* Remove all tags from the output/render the text without tags
* Limit the height to a single line
Of the two options, I would go with the first because it promises to be simpler to implement and does not run into edge cases like having only an image or a table in the text which might lead to the whole text being removed in case the first option is taken.

------

* [x] The "Expand" is not on the same height as the shortened text:
<img width="392" alt="image" src="https://github.com/opf/openproject/assets/617519/796c7abe-4d45-42df-bcf7-cf760dda77d8">

------

* [x] The "Expand" is not always displayed:
<img width="498" alt="image" src="https://github.com/opf/openproject/assets/617519/6fd5bd2f-3a07-4097-af08-6c8bfb5d9b59">

For this, the height would also have to be taken into account when calculating whether to add the "Expand" element. This problem is of course strongly coupled to the first mentioned problem and might be affected by the solution to it.

------

* [x] Formatting (newlines) not applied in modal:
<img width="337" alt="image" src="https://github.com/opf/openproject/assets/617519/f5cc3c6b-0e4e-4876-9100-ca127ae01030">

When clicking on "Expand" becomes:

<img width="536" alt="image" src="https://github.com/opf/openproject/assets/617519/6f1c97f9-72a4-4df4-8c62-52a929434edc">

Additionally, the modal does not have a header. The need for a header on the modal is not specified but I would think that the user would have an easier time understanding the behaviour if the modal would have a header consisting of the project name and the attribute. But ultimately, that is for product to decide, so better check with @psatyal.

2024-02-16 17:01 UTC, ulferts commented on app/components/projects/row_component.rb
> +        content_tag :div, helpers.format_text(project.description), class: 'wiki'
I think the `class: 'wiki'` part should be removed. The fact that the other methods in this class also use it is a relic of the past we should fix.

2024-02-16 17:01 UTC, ulferts commented on frontend/src/global_styles/content/_table.sass
> +  display: flex
This breaks the layout in some cases where multi line custom fields are now displayed in one line with each of them shortened:
<img width="323" alt="image" src="https://github.com/opf/openproject/assets/617519/a384bab7-f207-4eba-b7a6-8a92684e38fb">

2024-02-22 14:56 UTC, bsatarnejad commented
I'm closing this PR because this feature is implemented in another PR.

2024-02-22 14:56 UTC, closed without merging