Allow attachments on meetings for agenda items
opf/openproject pull request #14862
Opened 2024-02-26 14:40 UTC by oliverguenther

- [x] Introduces a meetings API so it can be plugged into the attachable mixin for uploading files, as agenda items are not journalized itself, but only in the meeting container
- [x] Extend the primer rich text input so that it can receive a resource

https://community.openproject.org/work_packages/26819

2024-02-27 20:26 UTC, dombesz requested changes
LGTM, just a few minor comments. I tried to check the documentation at the `/api/docs` and the newly added api information do not show up, probably we need to add them to the [dev/docs/api/apiv3/openapi-spec.yml](https://github.com/opf/openproject/blob/dev/docs/api/apiv3/openapi-spec.yml).

2024-02-27 20:26 UTC, dombesz commented on modules/meeting/app/forms/meeting_agenda_item/notes.rb
> +    return unless object&.meeting
Just out of curiosity, in what case would we not have the meeting set?

2024-02-27 20:26 UTC, dombesz commented on modules/meeting/spec/lib/api/v3/meetings/meeting_representer_spec.rb
> +      expect(subject).to be_json_eql(meeting.location.to_json).at_path('location')
Just a minor note, `created_at` and `updated_at` fields are not tested.

2024-02-27 20:26 UTC, dombesz commented on modules/meeting/lib/api/v3/meetings/meeting_representer.rb
> +        date_time_property :start_time
Would it be useful to expose the `:end_time` attribute too? Probably as a readonly attribute.

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/components/schemas/meeting_model.yml
> +      addAttachment:
Shall we enumerate the other properties like `attachments`, `project`, `author`, `self`?

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                        title: wiki
```suggestion
                        title: meeting
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                        href: "/api/v3/wiki_pages/72"
```suggestion
                        href: "/api/v3/meetings/72"
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +  - description: ID of the wiki page whose attachments will be listed
```suggestion
  - description: ID of the meeting whose attachments will be listed
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +# /api/v3/wiki_pages/{id}/attachments
```suggestion
# /api/v3/meetings/{id}/attachments
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                    href: "/api/v3/wiki_pages/72/attachments"
```suggestion
                    href: "/api/v3/meetings/72/attachments"
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +        Returned if the wiki page does not exist or the client does not have sufficient permissions
```suggestion
        Returned if the meeting does not exist or the client does not have sufficient permissions
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +        **Required permission:** view wiki pages
```suggestion
        **Required permission:** view meetings
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +        *Note: A client without sufficient permissions shall not be able to test for the existence of a work package.
```suggestion
        *Note: A client without sufficient permissions shall not be able to test for the existence of a meeting.
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +  - description: ID of the wiki page to receive the attachment
```suggestion
  operationId: List_attachments_by_meeting
  summary: List attachments by meeting
post:
  parameters:
  - description: ID of the meeting to receive the attachment
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                    href: "/api/v3/wiki_pages/72"
```suggestion
                        href: "/api/v3/meeting/72/attachments"
                        method: post
                      attachments:
                        href: "/api/v3/meeting/72/attachments"
                      project:
                        href: "/api/v3/projects/12"
                        title: Demo project
                      self:
                        href: "/api/v3/meeting/72"
                    _type: Meeting
                    id: 72
                    title: meeting
                _links:
                  author:
                    href: "/api/v3/users/1"
                    title: OpenProject Admin
                  container:
                    href: "/api/v3/meeting/72"
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +        *Note that you will only receive this error, if you are at least allowed to see the wiki page*
```suggestion
        **Required permission:** edit meetings

        *Note that you will only receive this error, if you are at least allowed to see the meeting*
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +        *Note: A client without sufficient permissions shall not be able to test for the existence of a wiki page
```suggestion
        Returned if the meeting does not exist or the client does not have sufficient permissions
        to see it.

        **Required permission:** view meetings

        *Note: A client without sufficient permissions shall not be able to test for the existence of a meeting
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +  summary: Add attachment to wiki page
```suggestion
    Adds an attachment with the meeting as it's container.

  operationId: Add_attachment_to_meeting
  summary: Add attachment to meeting
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                        href: "/api/v3/wiki_pages/72"
```suggestion
                        href: "/api/v3/meetings/72/attachments"
                        method: post
                      attachments:
                        href: "/api/v3/meetings/72/attachments"
                      project:
                        href: "/api/v3/projects/12"
                        title: Demo project
                      self:
                        href: "/api/v3/meetings/72"
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                    title: wiki
```suggestion
                    _type: Meeting
                    id: 72
                    title: meeting
```

2024-02-27 20:26 UTC, dombesz commented on docs/api/apiv3/paths/meeting_attachments.yml
> +                    title: wiki
```suggestion
                    title: meeting
```

2024-03-05 07:45 UTC, oliverguenther commented on modules/meeting/app/forms/meeting_agenda_item/notes.rb
> +    return unless object&.meeting
If you link a work package to a meeting, you get a new unpersisted agenda item without the meeting being set (as you can see the editor without the meeting being present).

This also means currently it's not possible to add attachments in that modal. I think that's fine for the first iteration though.

2024-03-05 07:47 UTC, oliverguenther commented on modules/meeting/lib/api/v3/meetings/meeting_representer.rb
> +        date_time_property :start_time
Yes good idea! 👍

2024-03-05 07:49 UTC, oliverguenther commented on docs/api/apiv3/components/schemas/meeting_model.yml
> +      addAttachment:
Yes I missed this, thanks for spotting 👍

2024-03-05 08:29 UTC, merged