Implementation/50915 send an email with the information and how to fix it
opf/openproject pull request #14879
Opened 2024-02-28 12:24 UTC by apfohl

2024-03-04 13:38 UTC, ba1ash requested changes
- `/letter_opener` page needs inline scripts execution to be allowed by CSP.
![letter_opener_content_security](https://github.com/opf/openproject/assets/11717656/2ed54fe5-449b-431a-b164-30bbe5c01805)

2024-03-04 13:38 UTC, ba1ash commented on config/environments/development.rb
>    config.action_mailer.delivery_method = :letter_opener
This line seems to be obsolete in favor of the next one.
```suggestion
```

2024-03-04 13:38 UTC, ba1ash commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = File.exist?('/.dockerenv') ? :letter_opener_web : :letter_opener
Why not to set it to `letter_opener_web` for docker based dev env and not docker based? Then it would be simpler and dev experience will be same.

2024-03-04 13:38 UTC, ba1ash commented on modules/storages/app/services/storages/health/health_service.rb
> +  module Health
I suggest removing this namespace and have just 'Storages::HealthService`

2024-03-04 13:38 UTC, ba1ash commented on modules/storages/app/workers/storages/health_status_mailer_job.rb
> +        Storages::StoragesMailer.notify_unhealthy(admin, storage).deliver_now
Probably, should be `deliver_later`. What happens to other deliveries if one `deliver_now` fails with Timeout, for instance?

2024-03-04 13:38 UTC, ba1ash commented on modules/storages/app/workers/storages/health_status_mailer_job.rb
> +    def perform(admins:, storage:)
I assume it is not correct to pass predefined set of admins as a parameter to the job, because job scheduling can happen on one day and execution on the next one, but during this time a set of admins can easily change(user has been promoted to admin, admin has been removed from the system etc.). Due to that I suggest query admins at the job runtime.

2024-03-04 13:38 UTC, ba1ash commented on modules/storages/app/workers/storages/health_status_mailer_job.rb
> +      if storage.health_healthy?
It should be check that storage is actually present in the database here. Because it can be removed after the job has been scheduled.

2024-03-04 13:38 UTC, ba1ash commented on modules/storages/app/services/storages/health/health_service.rb
> +        if @storage.health_reason != last_reason
It seems like we have similar logic for checking whether health_reason is same or not inside `Storages::Storage` model. Therefore it seems like a duplication. Should we try to do it in one place?

2024-03-04 13:38 UTC, ba1ash commented on modules/storages/app/services/storages/health/health_service.rb
> +          ::Storages::StoragesMailer.notify_healthy(admin, @storage, reason).deliver_later if was_unhealthy
We have a check inside `Storages::Storage#mark_as_healthy` if it was healthy before. For me it seems like a duplication. Does not it?

2024-03-05 09:35 UTC, apfohl commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = File.exist?('/.dockerenv') ? :letter_opener_web : :letter_opener
I don't exactly get what you want. Right now it's `:letter_opener_web` for Docker and the normal `letter_opener` for normal dev setup.

2024-03-05 09:36 UTC, apfohl commented on modules/storages/app/services/storages/health/health_service.rb
> +  module Health
Then I would have to move this file one level up... I don't like this.

2024-03-05 09:39 UTC, apfohl commented on modules/storages/app/workers/storages/health_status_mailer_job.rb
> +        Storages::StoragesMailer.notify_unhealthy(admin, storage).deliver_now
good point

2024-03-06 07:19 UTC, HDinger approved these changes
LGTM 👍

2024-03-06 12:21 UTC, apfohl commented on modules/storages/app/workers/storages/health_status_mailer_job.rb
> +      if storage.health_healthy?
I also added a reload for the object, to see if it actually still has an error.

2024-03-06 12:27 UTC, apfohl commented on modules/storages/app/services/storages/health/health_service.rb
> +          ::Storages::StoragesMailer.notify_healthy(admin, @storage, reason).deliver_later if was_unhealthy
The `HealthService` itself is now in charge of setting the state on the storage. I know that `mark_as_healthy` is doing a check, but it is too transparent from the outside to see, if it was unhealthy before. I need this to determine if I need to send mails or not. 

We could think about something like a `finalize` method to call a block if it has changed or something like that. But for now I think this would just make it more complicated.

My favorite thing would be, to extract this logic from the model completely, because it's not the right this to handle this invariant inside a data class, which main purpose should be writing consistent data to the database an obtaining it again.

2024-03-06 12:29 UTC, apfohl commented on modules/storages/app/services/storages/health/health_service.rb
> +        if @storage.health_reason != last_reason
Yep, but it's private. I don't see a need to change the API for the `Storage` model here. It already has too much logic in it.

2024-03-06 13:02 UTC, ba1ash commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = File.exist?('/.dockerenv') ? :letter_opener_web : :letter_opener
My point is to have only one thing `:letter_opener_web` and do not bother differentiating development environments.

2024-03-06 13:06 UTC, apfohl commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = File.exist?('/.dockerenv') ? :letter_opener_web : :letter_opener
Shall I make it the only default? Someone will find this unexpected....

2024-03-06 13:27 UTC, ba1ash commented on config/environments/development.rb
> +  config.action_mailer.delivery_method = File.exist?('/.dockerenv') ? :letter_opener_web : :letter_opener
True. I do not think it is a big problem. I am under the impression that emails are rarely touched. So, I would just change it and announce then it has been changed. But let's have it like that for now. Could we have a ticket to get rid of `letter_opener` later then?

2024-03-06 13:44 UTC, ba1ash commented on modules/storages/app/workers/storages/health_status_mailer_job.rb
> +      return unless Storages::Storage.exists?(storage.id)
While testing I see the following error:

![image](https://github.com/opf/openproject/assets/11717656/3fadc6a9-ceea-4e4f-8bba-908d77e601f5)

I scheduled the job, then removed storage, then started worker. 

So to prevent error properly we should pass `storage_id` and find storage at the beginning of `perform`.
The second option would be get back to previous implementation and accept raising of `ActiveJob::DeserializationError` which then removes job from the que and no emails are sent.

2024-03-22 09:21 UTC, apfohl commented on modules/storages/app/services/storages/health/health_service.rb
> +        if @storage.health_reason != last_reason
Health logic moved to `HelthService`.

2024-03-22 13:30 UTC, ba1ash commented on Gemfile.lock
> +    commonmarker (1.0.4-x86_64-linux)
I think we should not have linux specific version of the gem here. Let's just keep 1.0.4.

2024-03-22 13:30 UTC, ba1ash commented on Gemfile.lock
> +    nokogiri (1.16.3-x86_64-linux)
same here.

2024-03-22 13:30 UTC, ba1ash commented on Gemfile.lock
> +  x86_64-linux
Let's get back to ruby.

2024-03-22 13:30 UTC, ba1ash commented on modules/storages/app/services/storages/health_service.rb
> +    def schedule_mail_job(storage)
I do not see where this method is called. Then it is not clear how `::Storages::HealthStatusMailerJob` gets its way to the queue.

2024-03-22 13:30 UTC, ba1ash commented on modules/storages/app/services/storages/health_service.rb
> +    def mail_job_exists?
This method seems to be obsolete due to GoodJob being merged to dev branch. It seems to be unused as well.

2024-03-22 13:31 UTC, apfohl commented on Gemfile.lock
> +  x86_64-linux
Oh, when did that happen....

2024-03-22 13:32 UTC, apfohl commented on modules/storages/app/services/storages/health_service.rb
> +    def mail_job_exists?
Oh damn, something went wrong. Some code is missing.... need to check.

2024-03-22 13:57 UTC, apfohl commented on modules/storages/app/services/storages/health_service.rb
> +    def mail_job_exists?
@ba1ash Can you tell me how I should act here.

2024-03-27 07:45 UTC, mereghost commented on modules/storages/app/services/storages/health_service.rb
> +    def mail_job_exists?
You can probably rely on GoodJob concurrency settings. Take a look at `ManageNextcloudIntegrationJob.good_job_control_concurrency_with` to handle that.

2024-03-27 10:38 UTC, merged