[#53368] add authentication for storage interaction
opf/openproject pull request #14954
Opened 2024-03-08 11:03 UTC by Kharonus

[#53368](https://community.openproject.org/wp/53368)

### WAT?

- Added the authentication class to storage interaction namespace
- added unit test that shows the usage and test the auth behaviour of all storage providers

2024-03-08 11:04 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication.rb
> +        def self.authorization_state(storage:, user:)
ignore this method, I simply didn't want to cut this out into a separate commit. It is needed later, when authorization state is extracted from the connection manager

2024-03-08 16:35 UTC, mereghost requested changes
From what I see you have the usage be somewhat like so:

```ruby
CreateTemplateFolderCommand.call(auth: Strategy.new(:oauth_client_credentials), storage: ....)

# or on the inside of an object
class RmRfCommand
  def call(strategy: :basic_auth, storage:, location:)
     Authentication[strategy].call do |authed_http_session|
       do_awesome_requests
     end
  end
end
```

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/oauth_configurations/nextcloud_configuration.rb
> +        Util = ::Storages::Peripherals::StorageInteraction::Nextcloud::Util
🟢 The reference here could probably omit the `::Storages::Periphereals` part.

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/error.rb
> +        class Error
🟡 Since this is basically a factory for `ServiceResult`s we could make it into a simple lambda:

```ruby
module X...
  FailureBuilder = ->(code:, log_message:, data:) { same_implementation } 
end
```

and use `FailureBuilder.call(...)` on the code. `create` seems so tied to `ActiveRecord` that I thought you were persisting the data XD

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_client_credentials.rb
> +            end
🟡 WDYT we make it into a guard clause?

```ruby
return build_error(bunch:, of:, data:) unless config.complete?
```

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_client_credentials.rb
> +          end
🟡 Any reason we have the yield outside of the block?

You will return in case the first part raises, so the `begin...end` and just yield after building the httpx session. The rescue then can move to the outer scope.

It might catch other non-caught HTTPX errors, but that can be great if the messaging is improved (likely by using the exception error message). OR it can be refined into just rescuing 401/403s.

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_configuration.rb
> +            [@client_id, @client_secret, @issuer].all?(&:present?)
🟡 WDYT of leveraging [`ActiveModel::Validations`](https://api.rubyonrails.org/classes/ActiveModel/Validations.html) to check this and call `valid?` on the code, making it more... seamless and idiomatic.

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +            super()
🔴 Unnecessary call to super()

2024-03-08 16:35 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +              data = ::Storages::StorageErrorData.new(source: self)
🟡 All uses of data are the same, we could just initialize it directly at the instance level `@data = Storage::ErrorData.new(source: self)`.

Also Is your intention of adding the whole object to the `ErrorData` or just a reference to the class name? On a log this would look like `<StorageErrorData#12313 @source: <SomeClass#1234551>>`

2024-03-08 16:35 UTC, mereghost commented on modules/storages/spec/common/storages/peripherals/storage_interaction/network_error_spec.rb
> +      httpx_double = class_double(HTTPX, get: HTTPX::ErrorResponse.new(request, 'Timeout happens', {}))
🔴 You can actually mock a timeout with `WebMock`

```ruby
stub_request(:get, 'https://timeout-as-a-service.com/').to_timeout

2024-03-12 08:36 UTC, Kharonus commented on modules/storages/spec/common/storages/peripherals/storage_interaction/network_error_spec.rb
> +      httpx_double = class_double(HTTPX, get: HTTPX::ErrorResponse.new(request, 'Timeout happens', {}))
True, that spec was part of the query tests before, hence webmock was no option (interfering with vcr). 

I can change that now.

2024-03-12 10:05 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +            super()
Same question as in the configuration classes? linter wants super calls, should we disable linter locally or call super? Or should we disable linter globally?

2024-03-12 10:07 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/oauth_configurations/nextcloud_configuration.rb
> +        Util = ::Storages::Peripherals::StorageInteraction::Nextcloud::Util
removed

2024-03-12 10:08 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/error.rb
> +        class Error
Sure, I have no dips on this as a class. will change it to a lambda.

2024-03-12 10:16 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +              data = ::Storages::StorageErrorData.new(source: self)
Yeah, we need to make this discussion:

there are some advantages and disadvantages for both, IMHO.

- putting an object makes a written error log less readable
- putting an object makes debugging simpler, as the object contains state, as the internal values

wdyt?

2024-03-12 10:18 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_configuration.rb
> +            [@client_id, @client_secret, @issuer].all?(&:present?)
What would be part of leveraging the configuration objects to an active model? Pros and cons?

2024-03-12 10:21 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_client_credentials.rb
> +          end
point for the rescue here is actually to raise on every status. e.g. GRAPH API fails under certain circumstances with a 400, not a 401, when refreshing tokens (misconfigured or corrupted data).

My understanding was, that when moving the yield inside the rescue, that we will catch exceptions also from within our queries, and we might not want that. Instead we probably want the queries to make there own error handling. Or do you think different?

2024-03-12 10:22 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_client_credentials.rb
> +            end
done

2024-03-20 08:55 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +            super()
You know what is weird? The fact that the Rubymine complains but lefthook doesn't. >.< Maybe it is ignoring something.

2024-03-20 09:04 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_configuration.rb
> +            [@client_id, @client_secret, @issuer].all?(&:present?)
the validations module just add the validation macros to an object. I'm usually more on the `Dry::Validation` side of having a validation contract et al, but for now adding the ActiveModel can help with clarity and error messaging.

```ruby
class OAuthConfiguration
  include ActiveModel::Validations

  validate :presence, of: :client_id, :client_secret, :issuer
end
```

Does basically the same using RoR idioms of `validity.

2024-03-20 09:24 UTC, mereghost commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +              data = ::Storages::StorageErrorData.new(source: self)
Discussed on Element and reached an agreement. I'd add a link to it... if Element would cooperate. :yells-at-element:

2024-03-20 09:37 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_client_credentials.rb
> +          end
discussed: we will leave it outside the block for now, due to the mentioned reasons.

2024-03-20 09:40 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +            super()
discussed: prefer disabling linter rule over writing unnecessary super

2024-03-20 09:41 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_user_token.rb
> +              data = ::Storages::StorageErrorData.new(source: self)
discussed: use `self.class` as we value logging > debugging.

2024-03-20 09:42 UTC, Kharonus commented on modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/o_auth_configuration.rb
> +            [@client_id, @client_secret, @issuer].all?(&:present?)
great one, will use it.

2024-03-20 12:30 UTC, Kharonus commented on modules/storages/spec/common/storages/peripherals/storage_interaction/network_error_spec.rb
> +      httpx_double = class_double(HTTPX, get: HTTPX::ErrorResponse.new(request, 'Timeout happens', {}))
Update: I will refactor that test with the first query that is moved to new auth strategies. Right now, I don't see a good sense in this whole test :/

I wanted to cover the behaviour of httpx to return network errors in a different object. But the handling of it happens inside the queries. So, I would suggest to add a network unit test with webmock, that runs on top of an example query, which is considered a placeholder for all other queries, too.

2024-03-20 12:46 UTC, mereghost approved these changes

2024-03-20 12:54 UTC, merged