Don't subscribe to subsequent updates of the work_package model auth
opf/openproject pull request #15024
Opened 2024-03-18 15:48 UTC by oliverguenther

https://community.openproject.org/work_packages/49136

2024-03-20 10:11 UTC, dombesz requested changes

2024-03-20 10:11 UTC, dombesz commented on frontend/src/app/features/work-packages/components/wp-buttons/wp-create-button/wp-create-button.component.ts
> +        filter((links) => !!links.work_package),
The fix seems to work correctly but it breaks some permission related specs. Adding the following change, will keep the fix and also not break the other specs.

```suggestion
        filter((links) => !!links.work_package || !links.work_package),
```

2024-04-18 11:25 UTC, oliverguenther commented
@dombesz I rewrote the check using the capabilities API instead of relying on model links, which might change when creating children.

2024-04-18 16:02 UTC, dombesz approved these changes
Looks good 👍

2024-04-18 16:02 UTC, merged