Rename docker image registry from openproject/community to openproject/openproject
opf/openproject pull request #15269
Opened 2024-04-16 09:33 UTC by oliverguenther

https://community.openproject.org/projects/devops/work_packages/50623/activity

2024-04-16 12:21 UTC, oliverguenther commented
Failing spec is unrelated

2024-04-17 11:46 UTC, machisuji commented on .github/workflows/docker.yml
> -
Is the removal of this intended @oliverguenther ?

2024-04-17 12:04 UTC, machisuji requested changes
Looks good overall, but I have some minor comments.

2024-04-17 12:04 UTC, machisuji commented on test.sh
> +#!/bin/sh
accidental commit?

2024-04-17 12:04 UTC, machisuji commented on docs/installation-and-operations/misc/migration-to-postgresql13/README.md
> +openproject/openproject:14
the two spaces in the beginning should be kept!

2024-04-17 13:09 UTC, merged