Add truly async primer dialogs using custom turbo_stream action
opf/openproject pull request #15297
Opened 2024-04-17 11:50 UTC by oliverguenther

2024-04-18 09:24 UTC, HDinger requested changes
Great job, @oliverguenther ! 🥳 I really like the new approach, it reads so much easier and should also be much more intuitive to use 👍 I only have a small remark on the project attribute dialog. Otherwise, this is good to go from my side.

2024-04-18 09:24 UTC, HDinger commented on modules/overviews/app/components/project_custom_fields/sections/edit_component.html.erb
> +        collection.with_component(Primer::Alpha::Dialog::Body.new(my: 3, classes: "Overlay-body_autocomplete_height")) do
We do not need the `Dialog::Body` here any more, as it is now correctly set by the Dialog. Currently, this results in additional outer spacing:

<img width="400" alt="Bildschirmfoto 2024-04-18 um 11 20 09" src="https://github.com/opf/openproject/assets/7457313/8be55a4f-c0cf-41df-a81d-c834fa1e62e6">

2024-04-18 09:24 UTC, HDinger commented on modules/overviews/app/components/project_custom_fields/sections/edit_component.html.erb
> +        collection.with_component(Primer::Alpha::Dialog::Footer.new) do
Same as above. If we can use the footer correctly, we'll also benefit from the correct scrolling behavior on longer modals. Currently, we still have to scroll the whole content to see the "Save" and "Cancel" buttons.

2024-04-19 06:06 UTC, HDinger approved these changes
Good to merge once the ci is green 👍

2024-04-23 06:25 UTC, oliverguenther commented
Remaining spec is the calendar widget spec flickering

2024-04-23 06:25 UTC, merged