add logos feature for support Ukraine
opf/openproject pull request #15360
Opened 2024-04-23 16:56 UTC by daggett-doofus

![image (2)](https://github.com/opf/openproject/assets/110599815/cf6beb6d-05b8-4805-972a-99e947b03580)

Supporting Ukraine with Symbolic Unity

In light of recent events, we propose a meaningful initiative to express solidarity and support for Ukraine within our digital community. Our project aims to implement a subtle yet powerful gesture—a display of the Ukrainian flag alongside logos when users select the Russian language option. This small but significant change serves as a reminder of our unwavering support for Ukraine and its people during these challenging times.

By integrating the Ukrainian flag into our platform when Russian language preference is selected, we hope to promote awareness and solidarity among our users. This initiative is not only about showcasing a flag; it's about standing together in unity, amplifying the message of support, and fostering a sense of togetherness across borders.

Through this feature, we aspire to encourage empathy, understanding, and a shared sense of humanity. Our intention is clear: to use our platform to express compassion and solidarity with Ukraine and its people.

Join us in this meaningful endeavor to show that even in the digital world, symbols can carry profound messages of unity and support. Together, let's make a difference and demonstrate that solidarity knows no boundaries.

2024-04-25 09:16 UTC, ba1ash requested changes
Thanks for your contribution @daggett-doofus :ukraine: !
There are some things that should be improved in my opinion. Kindly take a look.
After swapping logo names it looks nice and works as expected:
![2024-04-25_10-23_1](https://github.com/opf/openproject/assets/11717656/7f5c5a2d-be26-4142-95b3-bd4afa80b7e4)
![2024-04-25_10-23](https://github.com/opf/openproject/assets/11717656/df287fdc-2f44-4b51-8f5e-caef48d1f0cd)

2024-04-25 09:16 UTC, ba1ash commented on app/views/custom_styles/_inline_css_logo.erb
> +  isRu = current_user.language == 'ru'
I think it would be better to check for locale like this:
```suggestion
  isRu = I18n.locale == :ru
```
For example, in this case correct logo will be rendered for not logged in users with Russian browser language as well.

2024-04-25 09:16 UTC, ba1ash commented on app/assets/images/logo-black-bg-ua.png
I assume the file should be renamed to `logo-white-bg-ua.png`.

2024-04-25 09:16 UTC, ba1ash commented on app/assets/images/logo-white-bg-ua.png
And this one should be renamed to `logo-black-bg-ua.png`.

2024-05-09 11:59 UTC, daggett-doofus commented on app/views/custom_styles/_inline_css_logo.erb
> +  isRu = current_user.language == 'ru'
Thank you for your comment. Accepted changes.

2024-05-13 14:45 UTC, ba1ash approved these changes
Looks good to me :+1: 
Thanks @daggett-doofus

2024-05-30 16:33 UTC, lindenthal commented
Hi @ba1ash, Do you have an idea why pp fails?

2024-06-03 12:06 UTC, ba1ash commented
> Hi @ba1ash, Do you have an idea why pp fails?

Hi @lindenthal 
Pull previews do not work for PRs created from forks.

2024-06-04 21:15 UTC, lindenthal commented
Freedom and democracy are under attack. Russia represents a clear and present danger to all democracies and peace-loving countries in the world. Only by standing together to defend Ukraine we can safeguard our future. 
<img width="1000" alt="logo-resistance-mockup" src="https://github.com/opf/openproject/assets/1019287/494aa125-790c-4e8b-a086-97ea3ef3df08">

Putin, stop this war against Ukraine! Stop the killing of innocent people!

2024-06-04 21:15 UTC, merged