Update Nextcloud docs screenshots after NC 2.6.2 release
opf/openproject pull request #15425
Opened 2024-04-30 08:24 UTC by MayaBerd

Update Nextcloud docs screenshots after NC 2.6.2 release

2024-05-12 23:14 UTC, dominic-braeunlein requested changes
I think something went wrong with 2 of the 3 screenshots

2024-05-12 23:14 UTC, dominic-braeunlein commented on docs/user-guide/file-management/nextcloud-integration/NC_1_00-FileWPRelation.png
Hi Maya, I think you accidentally uploaded the same screenshot again.

2024-05-12 23:14 UTC, dominic-braeunlein commented on docs/user-guide/file-management/nextcloud-integration/NC_1_01-FileWPActions.png
This one too

2024-05-13 09:39 UTC, MayaBerd commented on docs/user-guide/file-management/nextcloud-integration/NC_1_00-FileWPRelation.png
I've adjusted the screenshot, but saved it under same name. The change on screen was minimal (avatar alignment more the left), so it looks almost the same.

2024-05-13 09:39 UTC, MayaBerd commented on docs/user-guide/file-management/nextcloud-integration/NC_1_01-FileWPActions.png
same with this screenshot

2024-05-13 11:53 UTC, dominic-braeunlein approved these changes
LGTM 👍

2024-05-13 12:01 UTC, merged