Timeout open project storage modal after 120 secs.
opf/openproject pull request #15537
Opened 2024-05-13 13:23 UTC by ba1ash

https://github.com/opf/openproject/assets/11717656/4bca4eea-46d8-48eb-9e75-38f2531cbd9f

@wielinde have a look at the behavior, please. 
Topic to be cleared;
1. Texts to be put after timeout is hit.
2. Number of seconds for timeout. Currently is set to 120 seconds.
3. Icon to replace waiting spinner if we would like to do it.

2024-05-28 09:12 UTC, dominic-braeunlein requested changes
LGTM 👍
The one URL changed in the meanwhile

2024-05-28 09:12 UTC, dominic-braeunlein commented on config/locales/js-en.yml
> +          If that problem persists please contact you OpenProject administrator to check the <a href="https://www.openproject.org/docs/system-admin-guide/file-storages/file-storage-troubleshooting/">
Hi @ba1ash, the link changed to https://www.openproject.org/docs/system-admin-guide/files/external-file-storages/file-storage-troubleshooting/

2024-05-28 13:30 UTC, dominic-braeunlein commented
Looks good 👍

2024-05-28 13:30 UTC, dominic-braeunlein approved these changes
👍

2024-05-28 13:30 UTC, merged

2024-06-13 08:26 UTC, mMuck commented
Don't know if this is the right place but there is a typo in line https://github.com/opf/openproject/blob/d231bbbe11e95045770ef1e704a1a7aab6706fe3/config/locales/js-en.yml#L1453

> please contact you_**r**_ OpenProject administrator

2024-06-13 11:48 UTC, ba1ash commented
> Don't know if this is the right place but there is a typo in line
> 
> https://github.com/opf/openproject/blob/d231bbbe11e95045770ef1e704a1a7aab6706fe3/config/locales/js-en.yml#L1453
> 
> > please contact you_**r**_ OpenProject administrator

Thanks for pointing it out @mMuck!
Yes, it is not the right place. The ideal place would be to report it in https://community.openproject.org/ as  a bug.