[#45896] Generate PDF document from a work package description
opf/openproject pull request #15850
Opened 2024-06-13 14:36 UTC by as-op

* [x] Refactor for better resue
* [x] Reuse logo handling from PDF export
* [x] Use md-to-pdf to generate the document from a work package description 
* [x] Trigger with entry in work package drop down menu
* [ ] Hide behind feature flag
* [ ] Specify handling of different yml styles files (static? editor and/or upload in administration?)
* [ ] Specify handling of fonts used in different styles (static? upload in administration?)

https://community.openproject.org/work_packages/45896

2024-11-12 20:13 UTC, lindenthal commented
Hi @as-op,
Is the disclaimer in the description not correct? Are there topics to be specified?
Best
Niels

2024-11-13 08:10 UTC, as-op commented
Hi @lindenthal! No, that was a deprecated warning. I removed it.

2024-11-20 10:52 UTC, EinLama requested changes
Added a couple of questions and smaller notes.

I tried generating some PDFs and it works and looks great! Great job :) Couldn't see any performance issues due to creating it synchronously, but didn't try it with a giant work package.

2024-11-20 10:52 UTC, EinLama commented on app/components/work_packages/exports/generate/modal_dialog_component.rb
> +          [{ value: "", label: "Off", default: true }].concat(supported_languages)
I think this method would read better if we added an empty line between return value and the bulky hash definition above it. Makes it clear that they are separate instructions.

2024-11-20 10:52 UTC, EinLama commented on app/components/work_packages/exports/generate/modal_dialog_component.rb
> +          # The labels are the language names in the language itself (NOT to be put I18n)
Great comment! 👍🏻

2024-11-20 10:52 UTC, EinLama commented on app/models/work_package/pdf_export/common/attachments.rb
> +    work_package.attachments.detect { |a| api_url_helpers.attachment_content(a.id) == src }
Since the comment above already uses the verb "find", consider using the alias `find` instead of `detect`.

2024-11-20 10:52 UTC, EinLama commented on app/models/work_package/pdf_export/common/logo.rb
> +    image_file
This could be shortened to: 

```suggestion
    custom_logo_image_filename || Rails.root.join("app/assets/images/logo_openproject.png")
```

2024-11-20 10:52 UTC, EinLama commented on app/models/work_package/pdf_export/common/logo.rb
> +module WorkPackage::PDFExport::Common::Logo
Not commenting in every file, but most of these new files lack the copyright notice, while others got them. I think when in doubt, we should include these in every file.

2024-11-20 10:52 UTC, EinLama commented on app/models/work_package/pdf_export/common/logo.rb
> +module WorkPackage::PDFExport::Common::Logo
Additionally, `frozen_string_literal: true` is a good idea, unless you explicitly want unfrozen strings in these files.

2024-11-20 10:52 UTC, EinLama commented on config/routes.rb
> +    get "generate_pdf" => "work_packages#generate_pdf", on: :member
Why is this a GET call? Should creating a file not be POST? 🤔

2024-11-20 10:52 UTC, EinLama commented on app/models/work_package/pdf_export/generator/contracts.yml
> +  font: 'NotoSans'
This PR adds OpenSans as font, but NotoSans is used here instead (and SpaceMono further below). Is this an accident or a conscious decision?

2024-11-20 10:52 UTC, EinLama commented on spec/models/work_package/pdf_export/document_generator_spec.rb
> +      end
That's a nice spec! Very easy to read.

2024-11-20 10:52 UTC, EinLama commented on spec/models/work_package/pdf_export/document_generator_spec.rb
> +    # File.binwrite("WorkPackageDocumentGenerator-test-preview.pdf", content)
A debug leftover? Could be useful to keep, but a short explanation in another comment above might be helpful for future use.

2024-11-20 10:52 UTC, EinLama commented on app/models/work_package/pdf_export/common/common.rb
> +module WorkPackage::PDFExport::Common::Common
`Common::Common` 😄 That's a wonky name. Don't have anything better to offer though.

2024-11-20 11:19 UTC, as-op commented on app/components/work_packages/exports/generate/modal_dialog_component.rb
> +          [{ value: "", label: "Off", default: true }].concat(supported_languages)
True, I also pre-sorted the array, so sorting is not necessary at runtime

2024-11-20 11:20 UTC, as-op commented on app/models/work_package/pdf_export/common/attachments.rb
> +    work_package.attachments.detect { |a| api_url_helpers.attachment_content(a.id) == src }
Done.

2024-11-20 11:20 UTC, as-op commented on app/models/work_package/pdf_export/common/logo.rb
> +    image_file
Thanks! Much nicer.

2024-11-20 11:21 UTC, as-op commented on app/models/work_package/pdf_export/common/logo.rb
> +module WorkPackage::PDFExport::Common::Logo
Done, included copyright and string freezing to every export file

2024-11-20 11:22 UTC, as-op commented on app/models/work_package/pdf_export/generator/contracts.yml
> +  font: 'NotoSans'
Very good catch. For now only NotoSans is used, so I removed OpenSans that was only added for a spike.

2024-11-20 11:23 UTC, as-op commented on spec/models/work_package/pdf_export/document_generator_spec.rb
> +    # File.binwrite("WorkPackageDocumentGenerator-test-preview.pdf", content)
It is quite helpful for debugging to actually see the PDF, so I left that in there but added a comment.

2024-11-20 11:25 UTC, as-op commented on app/models/work_package/pdf_export/common/common.rb
> +module WorkPackage::PDFExport::Common::Common
Wonky indeed 😁

2024-11-20 11:42 UTC, as-op commented on config/routes.rb
> +    get "generate_pdf" => "work_packages#generate_pdf", on: :member
The other exports are GET, too and I wanted to have that consistent. 
So it’s enough to add .pdf to the end of your URL to start/download the export

e.g. https://community.openproject.org/work_packages/45896.pdf
or even on a query https://community.openproject.org/projects/openproject/work_packages.pdf?query_id=5307

Arguably it's less useful for `https://community.openproject.org/work_packages/45896/generate_pdf`, but I'm not aware of good reasons that a file download must be issued via a POST. But I don't have strong feelings about this, so I would be happy to hear your reasoning!

2024-11-20 12:19 UTC, EinLama commented on config/routes.rb
> +    get "generate_pdf" => "work_packages#generate_pdf", on: :member
I figured from a REST point of view, this route is creating an export, thus POST. The description of a work_package might change in-between exporting two PDFs, using POST prevents the browser from implicitly caching an old version of the file.

Both of these are rather weak arguments, though. And I was not aware that the other export already uses GET. I agree that consistency is a good reason to keep it that way.

2024-11-20 12:26 UTC, EinLama commented on app/components/work_packages/exports/generate/modal_dialog_component.rb
> +          [{ value: "", label: "Off", default: true }].concat(supported_languages)
nice, good catch

2024-11-20 12:32 UTC, as-op commented on config/routes.rb
> +    get "generate_pdf" => "work_packages#generate_pdf", on: :member
I have found a good argument against GET myself. 

For now passing the form values as query parameters is fine. In the future the form will probably contain file uploads, e.g. for a custom logo image. So this would need to be POST, so I will introduce this endpoint already as POST.

Feels more natural for a form endpoint anyhow. Fixed. Thanks 😀

2024-11-20 12:38 UTC, EinLama approved these changes
Nice work! 🎉

2024-11-20 14:44 UTC, merged