[#55961] Define the project lists query for activated storages
opf/openproject pull request #16038
Opened 2024-07-04 12:28 UTC by judithroth

https://community.openproject.org/work_packages/55961

This also defines a basic table in the view, so it can be tested. I've choosen not to go with a new query filter for projects belonging to a storage because it seemed to be more work than necessary and not provide any further benefits, since for the API there already is such a filter (which also seems to be tailored to the needs of the API. It would not have worked for the table because the table should include archived projects as well).

2024-07-04 12:56 UTC, judithroth commented on modules/storages/app/views/storages/admin/storages/project_mappings.html.erb
> +    params: params
@akabiru I assume this is a false positive and could be added to brakeman.ignore, but I am not sure about it. Do you have a suggestion on how to handle this?

2024-07-04 13:38 UTC, akabiru requested changes
Looking good Judith! ⭐ 

🟠 Could we add https://github.com/opf/openproject/pull/16018 first into `dev` first and rebase this PR so it fits into the new structure?

2024-07-04 13:46 UTC, akabiru commented on modules/storages/app/components/storages/project_storages/project_mapping/row_component.rb
> +module Storages::ProjectStorages::ProjectMapping
Given the new namespacing structure in https://github.com/opf/openproject/pull/16018 I think the following would be more fitting- as we essentially can drop the "project_mapping" naming across the board
```suggestion
module Storages::ProjectStorages
```

2024-07-04 13:46 UTC, akabiru commented on modules/storages/app/components/storages/project_storages/project_mapping/table_component.rb
> +module Storages::ProjectStorages::ProjectMapping
ditto:
```suggestion
module Storages::ProjectStorages
```

2024-07-04 14:04 UTC, judithroth commented
> Looking good Judith! ⭐
> 
> 🟠 Could we add #16018 first into `dev` first and rebase this PR so it fits into the new structure?

Sure! - I thought the same actually so I can adjust wording and some file names :slightly_smiling_face:

2024-07-04 14:04 UTC, akabiru commented on modules/storages/app/components/storages/project_storages/project_mapping/row_component.rb
> +module Storages::ProjectStorages::ProjectMapping
i.e. we'd have

1. `Storages::ProjectStorages::ProjectRowComponent` - for  projects
2. `Storages::ProjectStorages::StorageRowComponent` - for  storages _(in the future when the [current list is primerised](https://qa.openproject-edge.com/projects/demo-project/settings/project_storages/external_file_storages))_

2024-07-04 14:14 UTC, judithroth commented on modules/storages/app/components/storages/project_storages/project_mapping/row_component.rb
> +module Storages::ProjectStorages::ProjectMapping
I'd rather go with another namespace here. It's also nice if the files are grouped (not only by name but by a folder). What do you think about
`Storages::ProjectStorages::Project::RowComponent` (and `Storages::ProjectStorages::Project::TableComponent`) and keeping the other files as is?

2024-07-04 14:54 UTC, akabiru commented on modules/storages/app/components/storages/project_storages/project_mapping/row_component.rb
> +module Storages::ProjectStorages::ProjectMapping
That also works- +1 on folder naming, can be further reused 👍🏾

2024-07-05 08:45 UTC, akabiru reviewed
🟠 Almost there - two issues mentioned in the comments. 🛠️

2024-07-05 08:45 UTC, akabiru commented on modules/storages/app/components/storages/project_storages/projects/table_component.rb
> +    end
Oddly enough this doesn't seem to kick in:

- [ ] I still see the "sorting icon" - which should be disabled in this feature.
- [ ] The action list is filled in with the default properties, in this feature spec- the menu actions are (1) Edit Project Folder (2) Remove project - I suggest either leaving them empty or defining placeholders.

![Screenshot 2024-07-05 at 11 15 57 AM](https://github.com/opf/openproject/assets/17295175/9233c431-9daa-4b45-8b92-4f96df029e99)

2024-07-05 08:45 UTC, akabiru commented on modules/storages/app/components/storages/project_storages/projects/table_component.rb
> +    end
https://github.com/opf/openproject/assets/17295175/b2a0d89b-4261-4aaf-b8b5-2925c13161f4

2024-07-05 09:51 UTC, akabiru approved these changes
:shipit:

2024-07-05 09:51 UTC, akabiru commented
We agreed to address the issues separately 👍🏾

2024-07-05 15:19 UTC, merged