[53807] Update PageHeaders & SubHeaders in the My account pages
opf/openproject pull request #16141
Opened 2024-07-15 15:41 UTC by bsatarnejad

Use page header component in following pages:

- [ ] Profile
- [ ]  Settings
- [ ]  Change password
- [ ]  2fA
- [ ]  Access tokens
- [ ]  Session management
- [ ]  Notification settings
- [ ]  Email reminders
- [ ]  Avatar
- [ ]  Delete account
- [ ]  Additional: My Page

https://community.openproject.org/projects/openproject/work_packages/53807/activity

2024-07-26 11:48 UTC, HDinger requested changes
There were some pages forgotten:

* Notification settings
<img width="1000" alt="Bildschirmfoto 2024-07-26 um 13 41 01" src="https://github.com/user-attachments/assets/2d494780-c30b-4902-afcf-88d38cd198f9">

* All sub pages, e.g w
<img width="1000" alt="Bildschirmfoto 2024-07-26 um 13 48 59" src="https://github.com/user-attachments/assets/5d4bf474-3c3f-467c-9e32-4c83bb084734">
hen adding a new 2fa device

2024-07-26 11:48 UTC, HDinger commented on app/views/my/access_token.html.erb
>  <div class="access-token-page--container">
Please get rid of this additional container. I don't think that it is needed

2024-07-26 11:48 UTC, HDinger commented on app/views/my/reminders.html.erb
> +<%= angular_component_tag "opce-reminder-settings", inputs: { show_toolbar: false } %>
The `show_toolbar` flag was introduced, because the myPage still needed the toolbar whereas the administration settings already had the PageHeade in place. So we can now get rid of the flag and remove the toolbar altogether from the component

2024-07-26 11:48 UTC, HDinger commented on modules/two_factor_authentication/app/views/two_factor_authentication/my/two_factor_devices/index.html.erb
> +<%=
That looks a bit weird with the banner above. I'd rather move it below the SubHeader
<img width="1878" alt="Bildschirmfoto 2024-07-26 um 11 55 37" src="https://github.com/user-attachments/assets/0a8905d1-aa82-4aee-b801-de1367176a6b">

2024-07-26 11:48 UTC, HDinger commented on app/components/users/delete_account_page_header_component.rb
> +       { href: user_path(@user), text: @user.name },
I think this should rather be the edit path of the given user as this is usally they you get to the deletion page. Currently you get to the show page

2024-07-26 11:48 UTC, HDinger commented on app/components/users/delete_account_page_header_component.rb
> +class Users::DeleteAccountPageHeaderComponent < ApplicationComponent
If we follow the naming convention we implicitly introduced for the other components, this should be named `DeletePageHaderComponent` and the file `delete_page_header_component.rb`

2024-08-02 06:13 UTC, HDinger requested changes
Please add the PageHeader to this page. The parent my lead back to the login page. Currently, there is absolutely no way to get back or to cancel.

<img width="1592" alt="Bildschirmfoto 2024-08-02 um 08 07 34" src="https://github.com/user-attachments/assets/6555cd6d-226f-4e83-9b30-bca334d1afdd">

Further, there is one other page which was forgotten: Backup codes
<img width="1364" alt="Bildschirmfoto 2024-08-02 um 07 48 15" src="https://github.com/user-attachments/assets/e42f80e8-7a4a-49d5-acd5-b1e7054dcd82">

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/app/views/two_factor_authentication/my/two_factor_devices/index.html.erb
> +    render(Primer::Alpha::ActionMenu.new(test_selector: "two_factor_authentication_devices", anchor_align: :end)) do |menu|
Also you defined `anchor_align: :end` it looks a bit off too close to the screen:
<img width="349" alt="Bildschirmfoto 2024-08-02 um 07 48 30" src="https://github.com/user-attachments/assets/30781506-6061-45e6-8daf-65b4819cc451">

Could you please check why that happens?

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/app/views/two_factor_authentication/two_factor_devices/new.html.erb
> +                             "#{t('two_factor_authentication.devices.add_new')}: <b>#{t("two_factor_authentication.devices.#{@device_type}.title")}</b>".html_safe], selected_item_font_weight: :normal
This looks weird, as the bold element shoould be the one that matches the PageHeader title

<img width="543" alt="Bildschirmfoto 2024-08-02 um 07 48 53" src="https://github.com/user-attachments/assets/fd1e582a-a3e3-400e-a8cc-e5d7fdb08fa6">

I'd suggest, you change the order "WebAuthn: <b>Add new...</b>". 

Further, there is a an I18n key to cunstruct this string, so that you don't have to that yourself: 

```
I18n.t("menus.breadcrumb.nested_element", section_header: t("two_factor_authentication.devices.#{@device_type}.title"), title: h("wo_factor_authentication.devices.add_new")).html_safe
```

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/spec/features/my_two_factor_devices_spec.rb
> +    menu_button = find("[data-test-selector='two_factor_authentication_devices'] button")
Why don't you set a test_selector on the button directly?

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/spec/features/my_two_factor_devices_spec.rb
> +    expect(page).to have_css("[data-test-selector='two_factor_authentication_devices_sms']")
please use the `have_test_selector` method

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/spec/features/my_two_factor_devices_spec.rb
> +    sms_menu_item = find("[data-test-selector='two_factor_authentication_devices_sms']")
same here, please use `find_test_selector`

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/spec/features/my_two_factor_devices_spec.rb
> +    expect(page).to have_current_path new_my_2fa_device_path, ignore_query: true
See my comments above. Please use the test_selector helper methods instead of constructing the selector by yourself.

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/spec/features/my_two_factor_devices_spec.rb
> +    expect(page).to have_css("h1", text: I18n.t("two_factor_authentication.devices.add_new"))
I don't know if we really want to test the tag here. It would feel safer if you were testing for a test_selector with the given text

2024-08-02 06:13 UTC, HDinger commented on modules/two_factor_authentication/spec/features/password_change_spec.rb
> +    expect(page).to have_css("h1", text: I18n.t(:button_change_password))
Same here, please test for the existance of a test_selector not the tag

2024-08-06 10:22 UTC, bsatarnejad commented on modules/two_factor_authentication/app/views/two_factor_authentication/my/two_factor_devices/index.html.erb
> +    render(Primer::Alpha::ActionMenu.new(test_selector: "two_factor_authentication_devices", anchor_align: :end)) do |menu|
Hi @HDinger 
This issue is due to the long text for title or description of item. In this case, the description is too long and width is auto so it is stretched and too close to the screen. The solution would be to set a max-width for it.

2024-08-13 09:44 UTC, HDinger reviewed
Good job 🥳 🙇  I only have one minor remark left. After that, it is good to merge 👍

2024-08-13 09:44 UTC, HDinger commented on modules/two_factor_authentication/app/views/two_factor_authentication/my/backup_codes/show.html.erb
> +    header.with_title { "#{ t('two_factor_authentication.backup_codes.plural') } #{t('two_factor_authentication.backup_codes.your_codes', login: current_user.login, app_name: Setting.app_title)}" }
<img width="400" alt="Bildschirmfoto 2024-08-13 um 11 42 30" src="https://github.com/user-attachments/assets/2af35387-5fce-444f-b0a7-1ab557fba3a8">

That looks weird. I think "Backup codes" would be enough in the title and the breadcrumb. As you are in the MyAccount section, users know for which user they are generating codes.

2024-08-14 08:10 UTC, HDinger approved these changes
Lgtm 👍

2024-08-14 08:30 UTC, merged