Update Dockerfile
opf/openproject pull request #16176
Opened 2024-07-17 12:46 UTC by kale1d0code

remove as many RUN commands as possible to reduce the amount of layers in image and attempt to get its weight down (855.86 MB Compressed!)

2024-07-19 09:31 UTC, oliverguenther commented
Hi @kale1d0code , thanks for the contribution. @crohr / @machisuji could you take a look at this PR?

2024-07-19 11:24 UTC, machisuji commented on docker/prod/Dockerfile
> +RUN cp Gemfile.lock.bak Gemfile.lock && rm Gemfile.lock.bak \ &&
```suggestion
RUN cp Gemfile.lock.bak Gemfile.lock && rm Gemfile.lock.bak && \
```

2024-07-19 11:36 UTC, machisuji requested changes
Looks good overall, thanks! 👍 I have just suggested one fix that's necessary to fix the build.

2024-08-26 13:30 UTC, crohr commented
Did it bring meaningful improvements? In any case, this looks fine to me.

2024-08-26 13:31 UTC, merged

2024-08-26 13:31 UTC, oliverguenther commented
I'll merge it and we can observe the flavour builds for it.