[#55299] Project attributes: Fix phrasing of "required" and "visible" fields
opf/openproject pull request #16334
Opened 2024-08-05 13:10 UTC by dombesz

# What are you trying to accomplish?
Update custom field attribute names and descriptions for `required` and `visible`. Change the `visible` boolean field to `admin_only` and flip the logic around the flag.

# What approach did you choose and why?
  - Rename the text in the translation fiels
  - Create a migration that renames `visible` to `admin_only` and flip the boolean values also flipping the default value from true to false
  - Replace the `visible` occurences in the code with `admin_only`

# Ticket
https://community.openproject.org/wp/55299

# Merge checklist

- [X] Added/updated tests
- [ ] ~~Added/updated documentation in Lookbook (patterns, previews, etc)~~
- [X] ~~Tested major browsers (Chrome, Firefox, Edge, ...)~~

2024-08-06 09:19 UTC, cbliard reviewed
Is it ok if renaming also happens for other custom fields?

"Required for all projects" sounds a bit off: for instance for user custom fields and groups custom fields, the custom field is not related to any projects. Same for Time Spent custom fields.

<img width="936" alt="image" src="https://github.com/user-attachments/assets/1e56df60-a0e7-4d9a-b8ab-be3cce372d2d">

For work package custom fields, it's also strange to have "Required for all projects" and "For all projects" at the same time, as it's possible to have it required and being disabled for some projects.

Maybe the renaming should be limited to project attributes?

2024-08-06 09:20 UTC, cbliard commented
It also has an impact on the table view of work package custom fields

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/572f5d5b-90b0-47aa-961e-16854d9515ca">

2024-08-06 09:33 UTC, cbliard requested changes
The admin-only attribute can not be saved.

[admin-only attribute not kept.webm](https://github.com/user-attachments/assets/c03d0612-2f98-4a0e-90f2-dce6c473d707)

`:admin_only` is missing in permitted params in `app/models/permitted_params.rb:462`.

2024-08-06 09:42 UTC, cbliard reviewed
Thanks.

It seems to work well, except the field admin_only which can not be saved. Other than that it matches the spec.

The renaming seems confusing for custom fields that are not project custom fields. I'd like to have @psatyal point of view about it.

2024-08-06 09:42 UTC, cbliard commented on spec/migrations/rename_visible_to_admin_only_in_custom_fields_spec.rb
> +    end
I really like how this test is written. Good job 👍

2024-08-06 09:58 UTC, dombesz commented
> Thanks.
> 
> It seems to work well, except the field admin_only which can not be saved. Other than that it matches the spec.
> 
> The renaming seems confusing for custom fields that are not project custom fields. I'd like to have @psatyal point of view about it.

Thanks @cbliard , I agree the renaming seems to be tailored to the project attributes. One option could be to apply the renaming only on the project attributes, and not all the custom fields. cc @psatyal .

2024-08-06 12:29 UTC, cbliard approved these changes

2024-08-06 12:36 UTC, cbliard commented
> I agree the renaming seems to be tailored to the project attributes. One option could be to apply the renaming only on the project attributes, and not all the custom fields.

Yep, it looks like a good option. Parimal is back tomorrow.

2024-08-07 09:07 UTC, cbliard commented
> I agree the renaming seems to be tailored to the project attributes. One option could be to apply the renaming only on the project attributes, and not all the custom fields.

@dombesz I talked about it during today's frontend meeting. We agreed upon this:
* Apply renaming of "required" and "visible" attribute label and description only for project attributes (so it should be reverted back for all other custom fields)
* Apply renaming of "visible" attribute for all custom fields (which is user and project, so it's 👌 like it is right now). This will also address and fix https://community.openproject.org/projects/openproject/work_packages/56897/activity
* Target 14.5 instead of 14.4, because it's not a regression introduced in 14.4, and it would be too late for QA-ing for 14.4 before the release.

I'll update the work package description to reflect this.

2024-08-07 12:40 UTC, merged