MIME prefix constraint removed
opf/openproject pull request #16341
Opened 2024-08-05 18:09 UTC by salvadorleo

# What are you trying to accomplish?
The imposition of providing a MIME prefix on BCF snapshots could be a problem.
**snapshot_url_parts.length > 1**

Some of the BIM platforms that offer a BCF API, for example BIMcollab, have the opposite constraint: do not accept the MIME prefix.
In the case of a client application that adapts to this constraint, this will not work with OpenProject.

Ideally, OpenProject would also accept the case where the prefix is ​​not provided.

# What approach did you choose and why?
- Removing the imposition of a prefix
- Support for both cases (with or without prefix)

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-08-06 06:34 UTC, oliverguenther commented
Hi @salvadorleo , thanks for your request. I think the change is reasonable. @Kharonus could you take another look?

Best
Oliver

2024-08-06 09:28 UTC, Kharonus commented on modules/bim/app/services/bim/bcf/viewpoints/set_attributes_service.rb
> +        if snapshot_base64.include?('base64,')
```suggestion
        if snapshot_base64.include?("base64,")
```

2024-08-06 09:29 UTC, Kharonus commented on modules/bim/app/services/bim/bcf/viewpoints/set_attributes_service.rb
> +          Base64.decode64(snapshot_base64.split('base64,').last)
```suggestion
        if snapshot_base64.include?("base64,")
          Base64.decode64(snapshot_base64.split("base64,").last)
```

2024-08-06 09:30 UTC, Kharonus requested changes
Looks reasonable, thanks for the input.

just a minor suggestion.

2024-08-07 09:44 UTC, Kharonus approved these changes
LGTM, many thanks!

2024-08-07 09:44 UTC, merged