User interface for SAML configuration
opf/openproject pull request #16377
Opened 2024-08-08 19:21 UTC by oliverguenther

# Ticket
https://community.openproject.org/work_packages/40279

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-09-03 09:02 UTC, machisuji requested changes
Epic! Thanks for the great work. Seems to be working quite well. Although I have probably missed a couple of things.

I only have a few minor remarks. Could you please have a look?

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/app/contracts/saml/providers/base_contract.rb
> +      validates :idp_slo_service_url,
This validation seems to be not entirely correct because it complains about an invalid URL even when the value is empty (which it can be, because the field is optional in this case at least).

![image](https://github.com/user-attachments/assets/017e51fe-66b0-45be-9180-d4fc4a4dbc3d)

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/app/components/saml/providers/row_component.rb
> +        User.where("identity_url LIKE ?", "%#{provider.slug}%").count.to_s
I know it's unlikely that the slug occurs in the rest of the url, but I'd still prefer if we at least removed the leading `%` because we do know that the slug will be at the beginning of the identity_url like in `google:1923892412894`.

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/app/services/saml/providers/set_attributes_service.rb
> +          model.public_send(:"#{key}=", value)
🥴

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/app/services/saml/providers/set_attributes_service.rb
> +          model.public_send(:"#{key}=", value)
I know this is nit-picking, but perhaps curlies (or a method) would be better here if rubymine can't wrap its head around the indentation for do;end. This is not critical but you know, for the record.

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/config/locales/en.yml
> +        sp_entity_id: Service entity ID
Depending on the provider this may also be referred to as the following:

* SP Entity ID - SP being service provider, I claim that this might be the most common name for this even
* Audience 

I think it might be useful to mention these too some way because this will be tricky to identify for 'normal' users.

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/config/locales/en.yml
> +        assertion_consumer_service_url: Assertion consumer service URL
This is often simply referred to as ACS URL. For the likes of you and me it's obvious that these are the same. For inexperienced administrators it may not. So I would propose to include both. For instance, like this:

> ACS (Assertion consumer service) URL

That is either in parentheses after the acronym directly or as an info badge.

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/config/locales/en.yml
> +        metadata_form: "If your identity provider has a metadata endpoint or XML download, add it below to pre-fill configuration."
I would say it should be "the configuration" at the end, shouldn't it?

2024-09-03 09:02 UTC, machisuji commented on modules/auth_saml/config/locales/en.yml
> +        These attributes are added to the SAML request XML to communicate to the identity provider which attributes OpenProject requires.
This is almost exactly the same as a translation further up (request_attributes.legend). Perhaps it could be re-used?
Not critical though. My actual comment is the following.

I think it might be useful to point out to users that they may still configure their IdP explicitly to send these attributes even if we request them already in the response. I know this to be the case for at least some EntraID and Jumpcloud setups where I had to add the fields manually first on the IdP side to make things work.

So perhaps something like:

> You may still need to explicitly configure your IdP (identity provider) to send these attributes. Please refer to your IdP's documentation.

2024-09-03 09:02 UTC, machisuji commented on modules/storages/spec/requests/project_storages_open_spec.rb
> +                                                 ServiceResult.failure(result: code,
I'm not sure this is an improvement. But I blame RubyMine.

2024-09-03 09:02 UTC, machisuji commented on modules/storages/spec/requests/project_storages_open_spec.rb
> +                                                                    "http://#{Setting.host_name}/oauth_clients/#{storage.oauth_client.client_id}/ensure_connection?destination_url=http%3A%2F%2F#{CGI.e
same

2024-09-05 06:33 UTC, oliverguenther commented on modules/auth_saml/config/locales/en.yml
> +        assertion_consumer_service_url: Assertion consumer service URL
I've never seen this abbreviated as ACS, but it won't hurt to include

2024-09-05 09:49 UTC, machisuji commented on modules/auth_saml/config/locales/en.yml
> +        assertion_consumer_service_url: ACS (Assertion consumer service URL
@oliverguenther Missing closing parenthesis!

2024-09-26 09:39 UTC, machisuji approved these changes
👍

2024-09-26 11:19 UTC, merged