[#57592] 14.5 Documentation: Rename actions in work package dropdown …
opf/openproject pull request #16626
Opened 2024-09-04 11:54 UTC by MayaBerd

…menu  https://community.openproject.org/work_packages/57592

[#57592] 14.5 Documentation: Rename actions in work package dropdown menu

https://community.openproject.org/work_packages/57592

# Ticket

# What are you trying to accomplish?

## Screenshots

# What approach did you choose and why?

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-09-04 12:02 UTC, MayaBerd commented
@as-op could you please take a look at Links and URL changes triggered by the change in terms? Thank you!

2024-09-05 16:51 UTC, psatyal requested changes
Hi @MayaBerd, just one small change but looks good otherwise.

Cheers
Parimal

2024-09-05 16:51 UTC, psatyal commented on docs/user-guide/work-packages/duplicate-move-delete/README.md
> +If you right-click in a work package table, editing options will be displayed. Here, you can move a work package to another project, duplicate a work package, or copy its URL to the clipboard, delete
Here, I would rephrase the last bit: "... duplicate it in another project" (vs "to").

2024-09-06 06:57 UTC, MayaBerd commented on docs/user-guide/work-packages/duplicate-move-delete/README.md
> +If you right-click in a work package table, editing options will be displayed. Here, you can move a work package to another project, duplicate a work package, or copy its URL to the clipboard, delete
```suggestion
If you right-click in a work package table, editing options will be displayed. Here, you can move a work package to another project, duplicate a work package, or copy its URL to the clipboard, delete it or duplicate it in another project.
```

2024-09-09 06:49 UTC, merged