[#57037] Migrate UserPreference settings with the "default" theme to "light"
opf/openproject pull request #16676
Opened 2024-09-09 15:41 UTC by aaron-contreras

# Ticket
https://community.openproject.org/work_packages/57037

# What are you trying to accomplish?
A lot of areas were broken display-wise when upgrading from 9.x versions. This happened if users still had in their `UserPreference` theme settings the `default` option. I'm bringing these "default" values to "light" which is the current default setting for the theme setting.

## Screenshots
**Before**
<img width="467" alt="Screenshot showing the transparency issue" src="https://github.com/user-attachments/assets/b9a541af-811f-4556-bf2b-0c9ad3e81eed">

**After**
<img width="524" alt="Screenshot showcasing the fixed transparency" src="https://github.com/user-attachments/assets/ea32bd85-730a-4a85-b964-5db050adc089">

# What approach did you choose and why?
This was missed when upgrading OpenProject at some point so this should bring everything back in order for users that still have the "default" theme setting which is no longer supported, and keep the preferences for said users who have since moved to one of the valid options like "light" or "light_high_contrast".

A migration should suffice.

# Merge checklist

- [x] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [x] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-09-09 16:54 UTC, toy requested changes

2024-09-09 16:54 UTC, toy commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
As the class is nested, I think it is cleaner to name it `UserPreference` and not specify `table_name`

2024-09-09 16:54 UTC, toy commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
This will not find settings if anything but theme is set, which is probably the main case.
I assume either walking using `find_each` and filtering/updating in ruby, or updating in SQL, finding using `jsonb_extract_path` and updating using `jsonb_set` should be done. SQL way should be faster, so less chances of overwriting settings if user is changing them in parallel.

2024-09-09 16:54 UTC, toy commented on spec/migrations/migrate_legacy_default_theme_to_light_theme_spec.rb
> +  shared_let(:user_with_dark_theme) { create(:user, preferences: { settings: { theme: "dark" } }) }
Something besides theme should be set, `settings: { foo: "bar", theme: "default" }`

2024-09-09 17:24 UTC, aaron-contreras commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
I just followed the pattern in other migrations for naming

2024-09-09 17:25 UTC, aaron-contreras commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
Ah interesting, didn't think of this. Now looking at the SQL that's spit out, you're right. Thought it was a partial match and inferred that it's a jsonb column. Nice catch

2024-09-09 17:28 UTC, aaron-contreras commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
I actually can't replicate the above. I've ran this migration against a couple of different scenarios with different users and it does find and update the right columns. But I understand the plain SQL way is probably a bit faster.

2024-09-10 10:21 UTC, toy commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
Indeed a lot have prefix or suffix, but some don't. I can't come up with a big benefit of the prefix, maybe it is just a bit of cargo cult

2024-09-10 10:38 UTC, toy commented on db/migrate/20240909151818_migrate_legacy_default_theme_to_light_theme.rb
> +  end
I'm not sure I get your second comment.
`MigrationUserPreference.where(settings: { theme: "default" }).update_all(settings: { theme: "light" })` will run following SQL: `UPDATE "user_preferences" SET "settings" = $1 WHERE "user_preferences"."settings" = $2  [["settings", "{\"theme\":\"light\"}"], ["settings", "{\"theme\":\"default\"}"]]`, so it will only update rows with one key value pair.

2024-09-10 17:04 UTC, toy approved these changes

2024-09-10 22:02 UTC, merged