[#57671] Improve display of work package and agenda titles in meetings
opf/openproject pull request #16791
Opened 2024-09-24 12:18 UTC by mrmir

# Ticket
(https://community.openproject.org/work_packages/57671)

# What are you trying to accomplish?

## Screenshots

# What approach did you choose and why?

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-10-01 07:59 UTC, HDinger requested changes
Hi @mrmir 

I have some minor remarks

- [ ] In the visuals, the type and status are highlighted with their respective colours. 
- [ ] The position of the user avatar differs between WorkPackage agenda  items and normal agenda items:
<img width="250" alt="Bildschirmfoto 2024-10-01 um 09 27 02" src="https://github.com/user-attachments/assets/ad4f43bf-f5b2-4050-8c60-01e732ad57b0">

- [x] The three dots are not correctly aligned compared to the user name next to it
<img width="300" alt="Bildschirmfoto 2024-10-01 um 09 27 25" src="https://github.com/user-attachments/assets/efa219f7-eb34-4ad9-a3d5-958e1bd6975d">

2024-10-01 07:59 UTC, HDinger commented on modules/meeting/app/components/meeting_agenda_items/item_component/show_component.sass
> +    grid-template-columns: 20px auto 1fr 150px 50px
Why don't you use the variable you introduced?
```suggestion
    grid-template-columns: 20px auto 1fr $meeting-agenda-item--presenter-width--mobile 50px
```

2024-10-01 16:28 UTC, mrmir commented
Thanks @HDinger,

The spec has been updated, so please take another look

2024-10-02 08:39 UTC, HDinger approved these changes
Looks nice 👍 🌟

2024-10-02 08:39 UTC, merged