[56343] Move Colours page into a tab of Admin/Design page
opf/openproject pull request #16829
Opened 2024-09-27 06:12 UTC by bsatarnejad

# Ticket
https://community.openproject.org/projects/openproject/work_packages/56343/activity

# What are you trying to accomplish?
We want to remove admin/colors page and move its content to a separate tab in admin/design page.

## Screenshots

# What approach did you choose and why?

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2026-07-10 10:52 UTC, HDinger requested changes
Looks good overall. I think there is some more cleanup that can be done..

One other thing: I know that it was not explicitly named in the ticket, but it would be nice to also primerize the edit and create form for colors given that they are rather small.

2026-07-10 10:52 UTC, HDinger commented on app/components/colors/edit_page_header_component.rb
> +        { href: custom_style_path(tab: :default_colors), text: t(:label_custom_style) },
I think, the edit page should show the tab you are on. Currently it says "Administration / Desgin / **Orange**". My proposal would be "Administration / Desgin / Default colors: **Orange**"

2026-07-10 10:52 UTC, HDinger commented on app/views/colors/new.html.erb
> +       { href: custom_style_path(tab: :default_colors), text: t(:label_custom_style) },
Same as before.. I think it should match the actual structur: "Administration / Design / Default colors: **New color**"

2026-07-10 10:52 UTC, HDinger commented on app/views/custom_styles/_default_colors.html.erb
> +        <%= color.hexcode %>
I think this mighte be worth extracting it into it's own component

2026-07-10 10:52 UTC, HDinger commented on app/views/custom_styles/show.html.erb
> +  <% if theme_tab? %>
The name is not really well chosen.. I'd prefer a more self-explaining name like `show_theme_selector?`

2026-07-10 10:52 UTC, HDinger commented on frontend/src/global_styles/layout/_colors.sass
> +  width: 12px
Some of those can be primer variables

2026-07-10 10:52 UTC, HDinger commented on app/controllers/colors_controller.rb
>    end
I think we don't need this method anymore, do we?

2026-07-10 10:52 UTC, HDinger commented on app/views/colors/confirm_destroy.html.erb
I am nearly 100% sure that this file (and it's route and tests) are not used/needed any more

2026-07-10 10:52 UTC, HDinger commented on spec/controllers/colors_controller_spec.rb
> +
Can be removed once the index method is removed

2026-07-10 10:52 UTC, HDinger commented on spec/features/custom_styles/default_colors_administration_spec.rb
It probably makes sense to move that to the custom_styles folder

2026-07-13 09:40 UTC, bsatarnejad commented on app/controllers/colors_controller.rb
>    end
Removed

2026-07-14 06:15 UTC, HDinger requested changes

2026-07-14 06:15 UTC, HDinger commented on app/forms/admin/settings/color_form.rb
> +            validation_message: validation_message_for(:hexcode),
Why do you add the error message by hand here? If the error is attached to the model, it is shown automatically.

2026-07-14 06:15 UTC, HDinger commented on app/components/colors/default_color_swatch_component.rb
> +  class DefaultColorSwatchComponent < ApplicationComponent
I would like to see a preview for this

2026-07-14 06:15 UTC, HDinger commented on frontend/src/global_styles/layout/_colors.sass
> +  min-width: var(--base-size-12)
This belongs to the component and thus should be in a default_color_swatch.component.sass

2026-07-14 06:15 UTC, HDinger commented on app/components/colors/default_color_swatch_component.rb
> +  class DefaultColorSwatchComponent < ApplicationComponent
Imho, the name is a bit off.. The component is generic and can be used outside the "default colors" tab. So including the name `default` in here feels confusing.. I'd suggest to just name it `Colors::SwatchComponent`

2026-07-14 06:15 UTC, HDinger commented on app/components/colors/default_color_swatch_component.rb
> +      @color = color
The only thing you need from this color is the hexcode, so maybe it is easier to pass that directly.

2026-07-14 06:15 UTC, HDinger commented on app/components/colors/swatch_component.rb
> +      @system_arguments = system_arguments
What do you think about adding an option like `show_value` which shows the hexcode as text next to the swatch when being set to `true`. I guess, this is a use case that will appear quite often for this componentn.

2026-07-14 06:15 UTC, HDinger commented on frontend/src/global_styles/layout/_colors.sass
> +  margin-bottom: 10px
It took me a while to realize that those styles actually belong together. Part of the reason is that the names are again not self explaining. Further, it would have helped if the rules were nested. Since this is specific for that form, I'd also vote to move it to a color_form.sass

```suggestion
.color-form--hexcode-row
  align-items: flex-end
  width: fit-content
  
  // Needed for proper alignment of the swatch next to the input. Due to the label being part of the input, we need to do that manually. 
  .color-form--hexcode-row-swatch
    margin-bottom: 10px
```

2026-07-14 07:49 UTC, bsatarnejad commented on app/forms/admin/settings/color_form.rb
> +            validation_message: validation_message_for(:hexcode),
Removed 👍🏼

2026-07-14 09:10 UTC, HDinger requested changes

2026-07-14 09:10 UTC, HDinger commented on lookbook/previews/colors/swatch_component_preview.rb
> +  # @logical_path Colors
```suggestion
  # @logical_path OpenProject
```

For it to appear under the OpenProject folder. Otherwise it would look left alone

<img width="296" height="199" alt="Image" src="https://github.com/user-attachments/assets/89635b59-06f5-46e5-92d1-4b6253d16a00" />

2026-07-14 09:10 UTC, HDinger commented on app/components/colors/swatch_component.rb
> +    end
This looks way too complicated

```rb
def initialize
   @system_arguments[:classes] = class_names(
        @system_arguments[:classes],
        "op-color-swatch"
      )
end

def call
  flex_layout(**system_arguements) do |flex|
    flex.with_colum do
      render(Primer::Box.new(**swatch_arguments))
      end
    if show_value?
      flex.with_colum do
        render(Primer::Beta::Text.new(tag: :span)) { hexcode }
      end
    end
  end
end

def swatch_arguements
  {  
     tag: span,
     aria: @system_arguments.fetch(:aria, {}).merge(hidden: true),
    style: "background-color: #{hexcode}"
  }
end
```

```sass
.op-color-swatch
  border: 1px solid var(--borderColor-default)
  border-radius: var(--borderRadius-small)
  display: inline-flex
  align-items: center
  gap: var(--base-size-8)
  min-height: var(--base-size-12)
  min-width: var(--base-size-12)
```

Then you can get rid of all the helper rendering methods which is somehow bad style anyway. Further, this clearly separates the system arguments from the swatch arguments, and shortens the CSS

2026-07-14 09:26 UTC, bsatarnejad commented on lookbook/previews/colors/swatch_component_preview.rb
> +  # @logical_path Colors
My bad :(

2026-07-14 10:59 UTC, HDinger requested changes

2026-07-14 10:59 UTC, HDinger commented on app/components/colors/swatch_component.rb
> +        end
Although, this is already better, it is not what I had in mind.. My idea was to always render the flex around and thus extract the swatch_arguments from the system_arguments. If needed, the swatch_arguments can be another named param but currently you are mixing that heavily. 

Let me try to explain in an example: 
* If I write `Color::SwatchComponent.new(hexcode: "#fff", show_value: false, mr: 2)`, the margin will be added at the end of the component (e.g. when I want to show something after it)
* f I write `Color::SwatchComponent.new(hexcode: "#fff", show_value: true, mr: 2)`, the margin will be added between the swatch and the text. I have no choice to add a margin right at the end of the component itself.

This is why, my [original proposal](https://github.com/opf/openproject/pull/16829#discussion_r3577521330) was to add a flex wrapper which contains the system_arguments (and is always rendered). The text column is the one that is rendered conditionally, which also makes more sense from a component design point of view. The swatch_arguments are independent of the system_arguments are always applied on the swatch as the name implies.

2026-07-14 12:07 UTC, bsatarnejad commented on app/components/colors/swatch_component.rb
> +        classes: "op-color-swatch--indicator",
I am not really sure about the class name, WDYT?

2026-07-14 13:21 UTC, HDinger commented on app/components/colors/swatch_component.rb
> +        classes: "op-color-swatch--indicator",
I don't have a better name either, so let's stick with that 👍

2026-07-14 13:22 UTC, HDinger approved these changes
Awesome, thanks a lot 👍 🙇 Please squash the commits when merging

2026-07-14 13:24 UTC, merged