Bug/57305 sorting by custom field has strong impact on performance for the project list
opf/openproject pull request #16841
Opened 2024-09-27 13:08 UTC by toy

# Ticket
[OP#57305](https://community.openproject.org/wp/57305)

# What are you trying to accomplish?

## Screenshots

# What approach did you choose and why?

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-10-10 18:13 UTC, toy commented on app/models/queries/work_packages/selects/custom_field_select.rb
>    end
Diff may make it confusing, this is extracted from `set_summable!`

2024-10-21 11:40 UTC, ulferts requested changes
The change looks good functionality and also performance wise, in the tests I have conducted. It is now possible to group by way more fields which when looking at community is nice. 

There are some issues with the added grouping options, though. Of those, the first is but a display issue. But the second one leads to entries being sorted into the wrong group.

#### Grouping by integer cf
<img width="925" alt="image" src="https://github.com/user-attachments/assets/c34cea0c-a8a1-4b3d-b579-79921ee359f2">

Here, the grouping happens with an integer cf. The groups however are presented as floats.

#### Grouping by link cf

<img width="967" alt="image" src="https://github.com/user-attachments/assets/ac5023bd-7ebb-4109-af5d-383f3fb09a6b">

The backend correctly returns just one item in the group. The frontend still places more entries into the group.

2024-10-21 11:40 UTC, ulferts commented on app/models/custom_field/order_statements.rb
> +  # For single value custom fields thejoin ensures single value for every
Typo 'thejoin' -> 'the join'

2024-10-30 19:23 UTC, toy commented
@ulferts I wasn't able to reproduce the problem with grouping, we should look at it together

2024-11-11 18:36 UTC, toy commented
Grouping by link is fixed by 804986d91121d149c2da2e97997d2ed3fe0597ad, the issue was already there, but it was not possible to group by link custom field. Similar problem exists for grouping by bool custom fields, as absence of value will lead to `nil` used for grouping/ordering, but default value (which can only be `true` or `false`) used for work package custom field value, so currently there will be odd groups or adding to wrong group, the issue exists on dev.

2024-11-13 16:54 UTC, toy commented
Last commit dc28e44b5e932542d9e97f5f4e0a899bb46dd2e2 is also extracted as #17201

2024-11-15 08:55 UTC, ulferts approved these changes
👍

2024-11-15 08:55 UTC, merged