[58454] Sidebar menu should be hidden when page width is reduced
opf/openproject pull request #17003
Opened 2024-10-21 10:55 UTC by bsatarnejad

# Ticket
https://community.openproject.org/wp/58454

# What are you trying to accomplish?
While resizing the window, if the window size is small, hide the menu like when we reload the page.

## Screenshots
Before:
https://github.com/user-attachments/assets/7fae43a9-0505-4f8d-9ef5-bff49760d4f3

After:
https://github.com/user-attachments/assets/7da06ace-4a34-4592-9364-195f07d2f184

# What approach did you choose and why?
Hide the side menu while resizing if the window size is smaller than 1012px.

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [X] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-10-29 13:26 UTC, dombesz commented
Hi @bsatarnejad 

I have one remark, the sidemenu is not showing up after the browser width was reduced and then increased.  I believe the sidemenu should show up according to the specification.

> When the browser page is reduced and the sidebar menu is hidden (after a reload for instance), it should be shown again when the browser page is widened (like when reloading, but without having to reload)

![sidebar not showing again](https://github.com/user-attachments/assets/356b8a16-26b7-4d73-91cf-d680c97b4a16)

2024-10-29 14:05 UTC, bsatarnejad commented
> Hi @bsatarnejad
> 
> I have one remark, the sidemenu is not showing up after the browser width was reduced and then increased. I believe the sidemenu should show up according to the specification.
> 
> > When the browser page is reduced and the sidebar menu is hidden (after a reload for instance), it should be shown again when the browser page is widened (like when reloading, but without having to reload)
> 
> ![sidebar not showing again](https://private-user-images.githubusercontent.com/83396/381140608-356b8a16-26b7-4d73-91cf-d680c97b4a16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTA5NjEsIm5iZiI6MTczMDIxMDY2MSwicGF0aCI6Ii84MzM5Ni8zODExNDA2MDgtMzU2YjhhMTYtMjZiNy00ZDczLTkxY2YtZDY4MGM5N2I0YTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE0MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzcyNmExNTczMjBjZDcyZTk1ZGEwMTg0OGFjYjJjZTI4ZGVhODBmYzYzMjljNWVhMjkwNzlkODYwMThmZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nD5qJ9Ez4BIn6pVoKqWCOZ1ASRQA__CtTnJPC9DulgU) [ ![sidebar not showing again](https://private-user-images.githubusercontent.com/83396/381140608-356b8a16-26b7-4d73-91cf-d680c97b4a16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTA5NjEsIm5iZiI6MTczMDIxMDY2MSwicGF0aCI6Ii84MzM5Ni8zODExNDA2MDgtMzU2YjhhMTYtMjZiNy00ZDczLTkxY2YtZDY4MGM5N2I0YTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE0MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzcyNmExNTczMjBjZDcyZTk1ZGEwMTg0OGFjYjJjZTI4ZGVhODBmYzYzMjljNWVhMjkwNzlkODYwMThmZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nD5qJ9Ez4BIn6pVoKqWCOZ1ASRQA__CtTnJPC9DulgU) ](https://private-user-images.githubusercontent.com/83396/381140608-356b8a16-26b7-4d73-91cf-d680c97b4a16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTA5NjEsIm5iZiI6MTczMDIxMDY2MSwicGF0aCI6Ii84MzM5Ni8zODExNDA2MDgtMzU2YjhhMTYtMjZiNy00ZDczLTkxY2YtZDY4MGM5N2I0YTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE0MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzcyNmExNTczMjBjZDcyZTk1ZGEwMTg0OGFjYjJjZTI4ZGVhODBmYzYzMjljNWVhMjkwNzlkODYwMThmZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nD5qJ9Ez4BIn6pVoKqWCOZ1ASRQA__CtTnJPC9DulgU) [ ](https://private-user-images.githubusercontent.com/83396/381140608-356b8a16-26b7-4d73-91cf-d680c97b4a16.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTA5NjEsIm5iZiI6MTczMDIxMDY2MSwicGF0aCI6Ii84MzM5Ni8zODExNDA2MDgtMzU2YjhhMTYtMjZiNy00ZDczLTkxY2YtZDY4MGM5N2I0YTE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE0MDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzcyNmExNTczMjBjZDcyZTk1ZGEwMTg0OGFjYjJjZTI4ZGVhODBmYzYzMjljNWVhMjkwNzlkODYwMThmZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nD5qJ9Ez4BIn6pVoKqWCOZ1ASRQA__CtTnJPC9DulgU)

Hi @dombesz thanks, It's good point to fix this issue too. 👍

2024-10-30 11:56 UTC, dombesz commented
Thanks @bsatarnejad , the resizing now works correctly. However, if the sidebar is hidden it will still reappear after a refresh of the page.
![hidden sidebar reappears](https://github.com/user-attachments/assets/df3b5fe8-eb07-4575-b639-12e81ce09b08)

2024-10-30 11:57 UTC, dombesz requested changes
Thanks @bsatarnejad , the resizing now works correctly. However, if the sidebar is hidden it will still reappear after a refresh of the page.
![hidden sidebar reappears](https://github.com/user-attachments/assets/df3b5fe8-eb07-4575-b639-12e81ce09b08)

2024-11-02 14:35 UTC, bsatarnejad commented
> Thanks @bsatarnejad , the resizing now works correctly. However, if the sidebar is hidden, it will still reappear after a refresh of the page. ![hidden sidebar reappears](https://private-user-images.githubusercontent.com/83396/381534046-df3b5fe8-eb07-4575-b639-12e81ce09b08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTc0ODYsIm5iZiI6MTczMDU1NzE4NiwicGF0aCI6Ii84MzM5Ni8zODE1MzQwNDYtZGYzYjVmZTgtZWIwNy00NTc1LWI2MzktMTJlODFjZTA5YjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE0MTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDExYzIxMjRmYWFjMzFjNzFhY2E5OTY0OTMwM2M0MzI5NThkNTA4NDRkYTI4NmIxOGQ5YzE3YTE3N2U3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vzzyfpy9C8lvzplrAQQdorboDA8SkN621jzbE5jXWm0) [ ![hidden sidebar reappears](https://private-user-images.githubusercontent.com/83396/381534046-df3b5fe8-eb07-4575-b639-12e81ce09b08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTc0ODYsIm5iZiI6MTczMDU1NzE4NiwicGF0aCI6Ii84MzM5Ni8zODE1MzQwNDYtZGYzYjVmZTgtZWIwNy00NTc1LWI2MzktMTJlODFjZTA5YjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE0MTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDExYzIxMjRmYWFjMzFjNzFhY2E5OTY0OTMwM2M0MzI5NThkNTA4NDRkYTI4NmIxOGQ5YzE3YTE3N2U3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vzzyfpy9C8lvzplrAQQdorboDA8SkN621jzbE5jXWm0) ](https://private-user-images.githubusercontent.com/83396/381534046-df3b5fe8-eb07-4575-b639-12e81ce09b08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTc0ODYsIm5iZiI6MTczMDU1NzE4NiwicGF0aCI6Ii84MzM5Ni8zODE1MzQwNDYtZGYzYjVmZTgtZWIwNy00NTc1LWI2MzktMTJlODFjZTA5YjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE0MTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDExYzIxMjRmYWFjMzFjNzFhY2E5OTY0OTMwM2M0MzI5NThkNTA4NDRkYTI4NmIxOGQ5YzE3YTE3N2U3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vzzyfpy9C8lvzplrAQQdorboDA8SkN621jzbE5jXWm0) [ ](https://private-user-images.githubusercontent.com/83396/381534046-df3b5fe8-eb07-4575-b639-12e81ce09b08.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTc0ODYsIm5iZiI6MTczMDU1NzE4NiwicGF0aCI6Ii84MzM5Ni8zODE1MzQwNDYtZGYzYjVmZTgtZWIwNy00NTc1LWI2MzktMTJlODFjZTA5YjA4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE0MTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDExYzIxMjRmYWFjMzFjNzFhY2E5OTY0OTMwM2M0MzI5NThkNTA4NDRkYTI4NmIxOGQ5YzE3YTE3N2U3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vzzyfpy9C8lvzplrAQQdorboDA8SkN621jzbE5jXWm0)

Thank you for sharing your feedback! The behavior you're seeing is actually the default for the sidebar menu, so this particular fix doesn't address the issue you've pointed out.

2024-12-06 19:24 UTC, dombesz approved these changes
Thanks @bsatarnejad , LGTM! 👍

2024-12-11 07:27 UTC, merged