[58783] Make it possible to make the split screen narrower
opf/openproject pull request #17104
Opened 2024-11-04 10:13 UTC by bsatarnejad

# Ticket
https://community.openproject.org/projects/openproject/work_packages/58783/activity

# What are you trying to accomplish?
Reduce min-width of right panel.

## Screenshots
Before:
![Screenshot 2024-11-04 at 11 12 50](https://github.com/user-attachments/assets/ba982224-f66a-44bf-bb05-10d6c4124571)

After:
![Screenshot 2024-11-04 at 11 12 03](https://github.com/user-attachments/assets/018e0b49-4b89-47a6-bcc2-655220b91f9c)

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2026-07-20 17:18 UTC, lindenthal commented
Hi @HDinger and @bsatarnejad,
Can we close this? Or will we continue this one time?

2026-07-21 08:24 UTC, bsatarnejad commented
> Hi @HDinger and @bsatarnejad, Can we close this? Or will we continue this one time?

Thanks @lindenthal 
We continue working on it.

2026-07-22 09:48 UTC, HDinger requested changes

2026-07-22 09:48 UTC, HDinger commented on app/components/work_packages/split_view_component.sass
> +  min-width: 430px
I'd prefer to use the variable here

2026-07-22 09:48 UTC, HDinger commented on frontend/src/global_styles/layout/work_packages/_full_view.sass
> +    min-width: 430px
Same here, please use the variable we already have

2026-07-22 09:48 UTC, HDinger commented on frontend/src/global_styles/layout/_base.sass
> +    grid-template-columns: minmax($left-side-min-width, 1fr) minmax(430px, var(--split-screen-width))
I am a little bit lost on what this is supposed to be doing 😅 I know that I wrote the original rule, but it looks weird because it basically translates to
`grid-template-columns: minmax($left-side-min-width, 1fr) minmax(430px, 430px)`

So we could probably write directly:

```suggestion
    grid-template-columns: minmax($left-side-min-width, 1fr) var(--split-screen-width)
```

2026-07-30 11:06 UTC, HDinger approved these changes

2026-07-30 11:31 UTC, merged