Feature/58159 fixed set of project stages and gates editable on project overview page
opf/openproject pull request #17119
Opened 2024-11-05 16:01 UTC by dombesz

# Ticket
https://community.openproject.org/wp/58159

# What are you trying to accomplish?

## Screenshots

# What approach did you choose and why?

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-11-14 16:46 UTC, ulferts commented
Idea discussed between @dombesz , @toy and @ulferts 

```
Project::LifeCycleStepDefinition { has_many :life_cycle_steps }
Project::GateDefinition < LifeCycleStepDefinition { has_many :gates }
Project::StageDefinition < LifeCycleStepDefinition { has_many :stages }
Project::LifeCycleStep { belongs_to :definition, class: '' }
Project::Gate < LifeCycleStep 
Project::Stage < LifeCycleStep

Project { has_many :life_cycle_steps }
```

2024-11-18 18:57 UTC, toy requested changes
Looks good, most my points are minor, also we agreed to change names of classes as in the comment from @ulferts

2024-11-18 18:57 UTC, toy commented on app/models/life_cycle.rb
> +  end
Will `self.abstract_class = true` work instead? As a downside I see only the need to set `table_name` explicitly as default will be to use separate per concrete class.

2024-11-18 18:57 UTC, toy commented on app/models/project.rb
> +  has_many :life_cycles, through: :project_life_cycles
We discussed that this relation may not really be needed

2024-11-18 18:57 UTC, toy commented on app/models/project/gate.rb
> +  validates :date, presence: true
Do you think it is better to have a separate column for `date` and not reuse `start_date` (probably aliasing it)?

2024-11-18 18:57 UTC, toy commented on app/models/project/life_cycle.rb
> +  has_many :work_packages, inverse_of: :project_life_cycle, dependent: :nullify
Was it clarified if work package can or can not belong to multiple stages/gates?

2024-11-18 18:57 UTC, toy commented on app/models/life_cycle.rb
> +  validates :type, inclusion: { in: %w[Stage Gate], message: :must_be_a_stage_or_gate }
I think this is already validated on framework level by inheritance

2024-11-18 18:57 UTC, toy commented on app/models/project/life_cycle.rb
> +  validates :type, inclusion: { in: %w[Project::Stage Project::Gate], message: :must_be_a_stage_or_gate }
Same point about validation on framework level

2024-11-18 18:57 UTC, toy commented on app/models/project/life_cycle.rb
> +  end
Same question about using `self.abstract_class = true `

2024-11-18 18:57 UTC, toy commented on config/initializers/new_framework_defaults_7_1.rb
> +Rails.application.config.active_record.raise_on_assign_to_attr_readonly = true
I think it should be removed from here as you already added it to application.rb

2024-11-18 18:57 UTC, toy commented on spec/support/shared/project_life_cycle_helpers.rb
> +    expect(described_class < Project::LifeCycle).to be true
```suggestion
    expect(described_class).to be < Project::LifeCycle
```

2024-11-18 18:57 UTC, toy commented on spec/support/shared/project_life_cycle_helpers.rb
> +    it { is_expected.to belong_to(:life_cycle).required(true) }
required argument is true by default, so can be:
```suggestion
    it { is_expected.to belong_to(:project).required }
    it { is_expected.to belong_to(:life_cycle).required }
```

2024-11-18 18:57 UTC, toy commented on spec/support/shared/life_cycle_helpers.rb
> +    expect(described_class < LifeCycle).to be true
```suggestion
    expect(described_class).to be < LifeCycle
```

2024-11-18 18:57 UTC, toy commented on spec/support/shared/life_cycle_helpers.rb
> +    it { is_expected.to belong_to(:color).required(true) }
```suggestion
    it { is_expected.to belong_to(:color).required }
```

2024-11-18 18:57 UTC, toy commented on spec/seeders/basic_data/life_cycle_seeder_spec.rb
> +          color_id: Color.find_by(name: "Orange (dark)").id
I think it reads better without inversion:
```suggestion
          color: have_attributes(name: "Orange (dark)")
```

2024-11-18 18:57 UTC, toy commented on spec/models/project/life_cycle_spec.rb
> +  end
Confusing nesting of context, but it can be probably all replaced with a `have_readonly_attribute` test

2024-11-18 18:57 UTC, toy commented on spec/models/project/life_cycle_spec.rb
> +  end
These two tests feel like testing rails itself

2024-11-18 18:57 UTC, toy commented on spec/models/life_cycle_spec.rb
> +  end
Same point about feeling like this tests the framework

2024-11-18 18:57 UTC, toy commented on db/migrate/20241114130242_add_active_flag_to_project_life_cycles.rb
> +    add_column :project_life_cycles, :active, :boolean, default: false, null: false
I think it is better to add the column during creation of the table

2024-11-18 18:57 UTC, toy commented on db/migrate/20241030154245_create_life_cycles.rb
> +end
As separate creation of tables is needed only during development, I think it is better to combine all migrations into one. As far as I understand PostgreSQL has transaction DDL, so inconsistency should not be a problem

2024-11-18 18:57 UTC, toy commented on db/migrate/20241105175000_add_life_cycle_to_work_packages.rb
> +                  foreign_key: { to_table: :project_life_cycles },
I think here rails can guess the table, so can be:
```suggestion
                  foreign_key: true,
```

2024-11-18 18:57 UTC, toy commented on db/migrate/20241030154245_create_life_cycles.rb
> +      t.belongs_to :color, type: :int
Could you clarify why type: :int is specified when colors.id is `bigint`?
Also why no foreign key, color is not optional and we probably don't want deletion of referenced color.
And I suggest using either only `belongs_to` or only `references` in migrations of one PR (seems code has both methods in existing migrations).

2024-11-18 18:57 UTC, toy commented on config/locales/en.yml
> +              date_not_allowed: "Cannot assign `date` to a Stage"
These are very development centric which feels odd, but it should not be possible to trigger them from UI, so not sure if something should be done about it.

2024-11-18 18:57 UTC, toy commented on app/seeders/common.yml
> +    hexcode: "#B1D13A"
I'm not sure about this, but maybe better to name according to stage or gate they are used for? Downside is that reusing them will make it confusing and renaming stage or gate will not change the color name

2024-11-18 18:57 UTC, toy commented on app/seeders/basic_data/color_seeder.rb
> +      model_class.transaction do
I don't think transaction here is needed, as it will be already called from another transaction

2024-11-18 18:57 UTC, toy commented on app/seeders/basic_data/life_cycle_seeder.rb
> +    end
I think it should be simpler to create another seeder for life cycle colors, like `ColorSchemeSeeder` that also seeds colors

2024-11-19 10:55 UTC, dombesz commented on app/models/life_cycle.rb
> +  end
Unfortunately the STI mechanism is not compatible with abstract classes.
Defining an abstract parent class will tell rails that there is no table associated with it, and it disables the STI. Even if you define `self.abstract_class = false` for the child classes, the STI mechanism will not be able to infer the common table name. Defining the `table_name` in each child won't work either, because STI mechanism won't kick in and the `type` field won't be correctly utilised for inferring child classes.

2024-11-19 11:33 UTC, toy commented on app/models/life_cycle.rb
> +  end
Yes, you are correct.
Then it should be enough to validate presence of type, currently validation of inclusion is doing it, but as rails will already check that type is a name of a subclass, I think we don't need to repeat it.

2024-11-19 14:02 UTC, dombesz commented on app/seeders/common.yml
> +    hexcode: "#B1D13A"
I didn't use the stage gate names for the downside you mention.

2024-11-19 16:02 UTC, toy commented on app/seeders/common.yml
> +    hexcode: "#B1D13A"
What do you think about adding some prefix, like `PM2` or `Life Cycle` to all color names? `PM2 Orange`, `Life Cycle Orange` or `Life Cycle: Orange` look odd, but it separates them from other colors

2024-11-20 08:46 UTC, dombesz commented on app/models/project/life_cycle.rb
> +  has_many :work_packages, inverse_of: :project_life_cycle, dependent: :nullify
Yes we have specified that a work package can be optionally assigned to one life cycle.
It is specified [in another epic that is out of scope](https://community.openproject.org/wp/59177) for the current development.

> A stage/gate can be an attribute of a work package (similar to versions).
> A work package can be optionally assigned to stages and gates (no multi-select).

I wouldn't remove it, because it is already done, but it won't get much use until we develop the other epic anyway.

2024-11-20 11:15 UTC, toy commented on app/models/project/life_cycle.rb
> +  has_many :work_packages, inverse_of: :project_life_cycle, dependent: :nullify
I asked as I remember that there was a question in one of the tickets about allowing work package to be connected to multiple stages/gates, but I failed to find it while reviewing, so was wondering if you know if there was a decision

2024-11-20 11:18 UTC, dombesz commented on app/models/life_cycle.rb
> +  validates :type, inclusion: { in: %w[Stage Gate], message: :must_be_a_stage_or_gate }
I agree, the reason behind adding this validation is that the `type` will be a user supplied value and in case it is incorrect, the page will fail with an 500 error. Having this validation will gracefully handle the eventual type mismatch coming from the UI and will display the error message.
Perhaps an improvement would be to add the error to the `:base` and not on the `:type`, as we won't display the type as a separate input field on the LifeCycle creation form.

2024-11-20 11:22 UTC, dombesz commented on app/models/project/life_cycle.rb
> +  validates :type, inclusion: { in: %w[Project::Stage Project::Gate], message: :must_be_a_stage_or_gate }
Same reason as [here](https://github.com/opf/openproject/pull/17119/files#r1850134591).
perhaps I would add another validation that if the associated `life_cycle` is a `Gate` then allow `Project::Gate` as a type, so we won't end up with a type mismatch between a `LifeCycle` and a `Project::LifeCycle`.

2024-11-20 11:55 UTC, dombesz commented on config/initializers/new_framework_defaults_7_1.rb
> +Rails.application.config.active_record.raise_on_assign_to_attr_readonly = true
Normally I would like to have the configuration defined here, but unfortunately this file it is not being loaded correctly in production and the test environment, hence the definition is also done in the application.rb .

I would rather leave this here, and add a comment in the application.rb to remove that definition, once the issue is cleared.

2024-11-20 12:20 UTC, dombesz commented on db/migrate/20241030154245_create_life_cycles.rb
> +      t.belongs_to :color, type: :int
Good point! Not sure, this is how it was defined for the other relations in the migrations and I just followed this pattern:
https://github.com/opf/openproject/blob/0ae0349d9bd3f305bcabe2892937c4b3f4417dd4/db/migrate/20180504144320_add_color_to_statuses_and_enumerations.rb#L31-L37
https://github.com/opf/openproject/blob/0ae0349d9bd3f305bcabe2892937c4b3f4417dd4/db/migrate/tables/types.rb#L40

They are old and I'm not sure if there was a specific reason to do this.
Looking through the structure sql, we have a few more examples of `*_id` columns defined as `integer` when their corresponding primary key columns are bigint.
This could cause a problem at some point I guess, I logged a [code maintenance work package](https://community.openproject.org/wp/59476) to solve the other examples.

2024-11-20 13:09 UTC, dombesz commented on db/migrate/20241030154245_create_life_cycles.rb
> +end
I would rather keep one table creation per migration, in case we have to roll back a migration it is going to be simpler.

2024-11-20 13:21 UTC, dombesz commented on app/models/project/life_cycle.rb
> +  has_many :work_packages, inverse_of: :project_life_cycle, dependent: :nullify
Unfortunately I'm not aware of that discussion. Since this is out of scope for the epic, I would suggest leaving it as is. We can revisit it at a latter point if the specification changes.

2024-11-21 08:00 UTC, dombesz commented
@toy I believe I addressed your comments. I will do the discussed renaming in another PR.

2024-11-21 19:00 UTC, toy approved these changes
LGTM, only deciding on migrations being in one file or not, and merging renaming into this should be done before merging the PR

2024-11-21 19:00 UTC, toy commented on app/models/project/gate.rb
> +  end
Just a note that this could have been replaced by `validates :end_date, absence: true`, but it would not be possible to add the error on base

2024-11-21 19:00 UTC, toy commented on app/models/life_cycle.rb
> +  validates :type, inclusion: { in: %w[Stage Gate], message: :must_be_a_stage_or_gate }
I at first tried `LifeCycle.new(type: "Color")` and saw it raising an exception, found that this is checked in a call to [`find_sti_class`](https://github.com/rails/rails/blob/5f14ba8d647d241c1705513d718436853faf8464/activerecord/lib/active_record/inheritance.rb#L311C13-L311C27) from [overridden `new` method](https://github.com/rails/rails/blob/5f14ba8d647d241c1705513d718436853faf8464/activerecord/lib/active_record/inheritance.rb#L56), but then realised that the problem is that type will be assigned not during initialisation, but afterwards which is not checked by framework, so `Gate.new.update(type: "Color", name: "Name", color: Color.last)` without this validation inserts an invalid row after which simple `LifeCycle.all.to_a` raises because of the exception from `find_sti_class`.

2024-11-21 19:00 UTC, toy commented on app/models/life_cycle.rb
> +  end
Not a merge stopper, but I still think that given validation of type to be in know list, customising initialiser is not needed

2024-11-21 19:00 UTC, toy commented on app/models/project/life_cycle.rb
> +  end
See comment for initializer of `::LifeCycle`

2024-11-21 19:00 UTC, toy commented on spec/models/project/life_cycle_spec.rb
> +  end
I meant that this whole describe can be replaced by a check to have_readonly_attribute, see [shoulda matcher docs](https://github.com/thoughtbot/shoulda-matchers/blob/6f4de5ad6d0d09486c2c713fb1a0bf38169d399e/lib/shoulda/matchers/active_record/have_readonly_attribute_matcher.rb)

2024-11-21 19:00 UTC, toy commented on db/migrate/20241030154245_create_life_cycles.rb
> +end
Migrations are connected, so it is not possible to roll back them not from the end, and I assume rolling back only one of the migrations can be helpful for this PR, but probably not really needed afterwards. From my perspective benefit is just in grouping related changes to database, so there is no need to search for commit or even the PR that introduced the change, but it is all in one file.

2024-11-22 11:02 UTC, dombesz commented on app/models/project/gate.rb
> +  end
Good point, I didn't knew about `absence: true`, unfortunately in this case wouldn't work as you said.

2024-11-22 11:24 UTC, dombesz commented on app/models/life_cycle.rb
> +  end
I believe it is required, because otherwise the validations of the child classes can be circumvented. Let's consider the following scenario:
 1. Instantiate a `Project::LifeCycleStep.new`
 2. Assign attributes outside of the initialisation also including the `type: "Project::Stage"`
 3. The class of the already initialised object won't change to `Project::Stage` after the assignment, and the validations declared in the `Project::Stage` class won't be applied.
 4. An invalid object will be saved to the database.

```ruby
[1] pry(main)> lc = Project::LifeCycleStep.new
=> #<Project::LifeCycleStep:0x00000003144794d0
 id: nil,
 type: nil,
 start_date: nil,
 end_date: nil,
 active: false,
 position: nil,
 project_id: nil,
 definition_id: nil,
 created_at: nil,
 updated_at: nil>
[2] pry(main)> lc.assign_attributes(type: "Project::Stage", definition: Project::LifeCycleStepDefinition.first, project: Project.first)
  Project::LifeCycleStepDefinition Load (1.8ms)  SELECT "project_life_cycle_step_definitions".* FROM "project_life_cycle_step_definitions" ORDER BY "project_life_cycle_step_definitions"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Project Load (0.5ms)  SELECT "projects".* FROM "projects" ORDER BY "projects"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> nil
[3] pry(main)> lc.valid?
=> true
[4] pry(main)> lc
=> #<Project::LifeCycleStep:0x00000003144794d0
 id: nil,
 type: "Project::Stage",
 start_date: nil,
 end_date: nil,
 active: false,
 position: nil,
 project_id: 1,
 definition_id: 1,
 created_at: nil,
 updated_at: nil>
[5] pry(main)> lc.save
  TRANSACTION (11.8ms)  BEGIN
  Project::LifeCycleStep Load (18.0ms)  SELECT "project_life_cycle_steps".* FROM "project_life_cycle_steps" WHERE (1 = 1) AND ("project_life_cycle_steps"."position" IS NOT NULL) ORDER BY "project_life_cycle_steps"."position" DESC LIMIT $1  [["LIMIT", 1]]
  Project::LifeCycleStep Create (3.9ms)  INSERT INTO "project_life_cycle_steps" ("type", "position", "project_id", "definition_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["type", "Project::Stage"], ["position", 1], ["project_id", 1], ["definition_id", 1], ["created_at", "2024-11-22 11:21:33.569747"], ["updated_at", "2024-11-22 11:21:33.569747"]]
  TRANSACTION (2.7ms)  COMMIT
=> true
[6] pry(main)> Project::LifeCycleStep.find(lc.id).valid? 
  Project::LifeCycleStep Load (12.4ms)  SELECT "project_life_cycle_steps".* FROM "project_life_cycle_steps" WHERE "project_life_cycle_steps"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Project Load (0.4ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Project::LifeCycleStepDefinition Load (0.2ms)  SELECT "project_life_cycle_step_definitions".* FROM "project_life_cycle_step_definitions" WHERE "project_life_cycle_step_definitions"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
=> false

```

2024-11-22 11:24 UTC, dombesz commented on app/models/project/life_cycle.rb
> +  end
See above https://github.com/opf/openproject/pull/17119#discussion_r1853763577 .

2024-11-22 11:57 UTC, dombesz commented on spec/models/project/life_cycle_spec.rb
> +  end
I still have to keep the context, because the subject should be instantiable for the test to work.

2024-11-22 12:47 UTC, dombesz commented on db/migrate/20241030154245_create_life_cycles.rb
> +end
I added it to the [renaming PR](https://github.com/opf/openproject/pull/17248) to avoid merge conflicts.

2024-11-22 14:25 UTC, toy commented on app/models/life_cycle.rb
> +  end
It is still possible to create an invalid Stage if Gate is initialised and then switched dynamically - create a gate with only `start_date`/`date` and change type to Stage. So it is a problem of STI, if you really want to ensure no invalid instances, all validation should move from sub classes to base class and apply depending on the value of `type` attribute
```rb
gate = Project::Gate.new
gate.attributes = {start_date: Date.today, type: 'Project::Stage', definition: Project::LifeCycleStepDefinition.first, project: Project.first}
gate.valid? # => true
gate.save
Project::LifeCycleStep.find(gate.id).valid? # => false
Project::LifeCycleStep.find(gate.id).tap(&:validate).errors # => #<ActiveModel::Errors [#<ActiveModel::Error attribute=end_date, type=blank, options={}>]>
```

2024-11-22 15:11 UTC, dombesz commented on app/models/life_cycle.rb
> +  end
I don't like the idea of moving class related validations into the parent model, it defeats the purpose of the whole structure.
I would rather add a validation the following validation to ensure no invalid objects can be created:

```ruby
class Project::Stage < Project::LifeCycleStep
  validates :type, inclusion: { in: %w[Project::Stage], message: :must_be_a_stage }
end

class Project::Gate < Project::LifeCycleStep
  validates :type, inclusion: { in: %w[Project::Gate], message: :must_be_a_gate }
end
```

2024-11-22 19:18 UTC, toy approved these changes
LGTM

2024-11-25 08:31 UTC, merged