Start implementing mobile behavior for border-box table
opf/openproject pull request #17216
Opened 2024-11-18 06:47 UTC by oliverguenther

# Ticket
https://community.openproject.org/work_packages/59248

# What are you trying to accomplish?
Trying to have all but the last column in the BorderBoxTableComponent stack on mobile

2024-11-18 13:56 UTC, HDinger requested changes
Looks nice 👍 While clicking through, I found some issues:

- [x] According to figma: On the meetings page, the project should not display a label in front on mobile
- [ ] On the meetings page, there are different vertical spacings between the elements. That happens on all places where an action button is displayed because the first row takes the height of that button. Thus is it is larger and the space appears bigger. 

<img width="400" alt="Bildschirmfoto 2024-11-18 um 14 18 59" src="https://github.com/user-attachments/assets/28e16805-531a-43c1-9a56-4a659cb81a63">

And one minor optional comment:

- [x] Currently, I can enter empty values for the mobile_label and the mobile_columns which does not make much sense I guess. So maybe we should prevent that?

2024-11-18 13:56 UTC, HDinger commented on app/components/op_primer/border_box_table_component.sass
> +      justify-content: flex-end
This can be removed as it is already written above.

2024-11-18 13:56 UTC, HDinger commented on app/components/op_primer/border_box_table_component.html.erb
> +        concat render(Primer::BaseComponent.new(classes: "op-border-box-grid--heading",
`op-border-box-grid--heading` should probably be a variable as it is reused in `header_classes`.

2024-11-18 13:56 UTC, HDinger commented on lookbook/docs/patterns/12-tables.md.erb
> +### Mobile headers
There is a `#` missing

2024-11-18 13:56 UTC, HDinger commented on lookbook/docs/patterns/12-tables.md.erb
> +mobile_labels users: :label_user_plural
Do we really want to allow a custom label here? In the specification it was written `a flag to show the column header as label`

2024-11-18 15:29 UTC, oliverguenther commented
>  On the meetings page, there are different vertical spacings between the elements. That happens on all places where an action button is displayed because the first row takes the height of that button. Thus is it is larger and the space appears bigger.

Do you have a suggestion on how to fix this?

2024-11-18 15:38 UTC, oliverguenther commented on lookbook/docs/patterns/12-tables.md.erb
> +mobile_labels users: :label_user_plural
Indeed we could probably get rid of it

2024-11-18 16:15 UTC, oliverguenther commented
>  Currently, I can enter empty values for the mobile_label and the mobile_columns which does not make much sense I guess. So maybe we should prevent that?

If you enter empty mobile_columns, it falls back to showing all columns - which I think is a good default

2024-11-19 09:54 UTC, HDinger commented
> > On the meetings page, there are different vertical spacings between the elements. That happens on all places where an action button is displayed because the first row takes the height of that button. Thus is it is larger and the space appears bigger.
> 
> Do you have a suggestion on how to fix this?

I just pushed a change. The space between the lines is now 4px larger than what is specified in Figma, but imho that is acceptable.

<img width="436" alt="Bildschirmfoto 2024-11-19 um 10 52 44" src="https://github.com/user-attachments/assets/586d5d05-6637-4839-8f2a-643fb773e91a">

2024-11-19 10:00 UTC, HDinger approved these changes

2024-11-19 10:33 UTC, oliverguenther commented
Thanks for looking into it. It's definitely better than before 👍

2024-11-19 10:33 UTC, merged