Hierarchy filters
opf/openproject pull request #17247
Opened 2024-11-21 15:02 UTC by brunopagno

# Ticket
https://community.openproject.org/wp/59069 & https://community.openproject.org/wp/59070

# What are you trying to accomplish?
Include filtering for hierarchy items

## Screenshots

https://github.com/user-attachments/assets/c5a51404-6313-465f-8624-f3696c0215fd

# What approach did you choose and why?

# Merge checklist

- [X] Added/updated tests
- [X] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-11-21 15:04 UTC, brunopagno commented
@apfohl I opened a PR in the current branch. We can for sure create a separate branch and reapply the changes here if you prefer. But alternatively we could keep it simple and just do a `Squash and Merge` to keep the tree clean whenever we decide to merge this one.

2024-11-22 07:48 UTC, apfohl commented
It's good. Let's just squash it.

2024-11-22 11:02 UTC, ulferts reviewed
This was a quick fly-over glance and not a proper review, i.e. I haven't tried out the functionality and didn't spent a long time to think this through. Especially the actual SQL used for filtering would be important to look at in this case. 

To that end it would be helpful to know the expected filter behaviour. E.g. is filtering on a category (encompassing multiple items below) intended to be possible and if so, what is the intended outcome.

An integration spec on the filter would serve to guarantee the quality of the changes as well as explain the expected filter results. https://github.com/opf/openproject/blob/dev/spec/models/query/results_custom_field_filter_integration_spec.rb could be a good place for this. And of course a feature spec to safeguard the whole functionality.

But the structure of the change seems to be going into the right direction.

2024-11-22 11:02 UTC, ulferts commented on app/models/queries/filters/shared/custom_fields/hierarchy.rb
> +        end
❓ What is the purpose of this class here?

2024-11-22 11:33 UTC, brunopagno commented on app/models/queries/filters/shared/custom_fields/hierarchy.rb
> +        end
@ulferts it's because of the expected values on the [query_filter_instance_representer.rb](https://github.com/opf/openproject/blob/dev/lib/api/v3/queries/filters/query_filter_instance_representer.rb#L76-L100). It seems to be designed to operate on a type of object and we needed the adapter so that it would render correctly.

Same for the path we added to the `path_helper.rb`

2024-11-22 15:03 UTC, Kharonus requested changes
Pretty cool, that in the end it is indeed relatively small code changes. great code discovery to find all the needed locations.

2024-11-22 15:03 UTC, Kharonus commented on app/models/queries/filters/shared/custom_fields/hierarchy.rb
> +        end
Specifically we are talking about the filter representer being very specific about needing a `.name` method on entities. the hierarchy items do not have a name. To not pollute either the record or the representer, an adapter was created, wrapping the hierarchy item into a readable model for the filter representer.

2024-11-22 15:03 UTC, Kharonus commented on spec/features/work_packages/table/queries/hierarchy_cf_filter_spec.rb
> +RSpec.describe "Work package filtering by user custom field", :js do
🔴 spec description not correct, copy paste intrusion 😝

2024-11-22 15:03 UTC, Kharonus commented on spec/features/work_packages/table/queries/hierarchy_cf_filter_spec.rb
> +        filters.add_filter_by(hierarchy_cf.name, "is", [luke.label], hierarchy_cf.attribute_name(:camel_case))
❓ ooc: how much effort is it to have a clone of the `is` filter operator which is called `is any`, being more precise in what it is doing?

question opts for maybe suggesting within our current epic scope a renaming (in code) from `is` to `is any`, to easily distinguish between `is any` and `is all` in future.

2024-11-22 15:08 UTC, Kharonus commented
@brunopagno you already added a UI test as Jens suggested. For the correct wire up of schemas, representers and all the stuff, this is a nice and valuable thing. But it is not proper (IMHO) for a full functionality test of the filter. For the current operators (is any and is not) this is no big deal, but my take would be, that we write requests specs (API integration) once we have the `is any (with descendants)` for the work package collection, to really cover which work packages are filtered and which not.

requests specs are much faster then UI tests, and hence can be used to cover all relevant functionality of filtering the wp collection.

2024-11-22 15:37 UTC, brunopagno commented on spec/features/work_packages/table/queries/hierarchy_cf_filter_spec.rb
> +        filters.add_filter_by(hierarchy_cf.name, "is", [luke.label], hierarchy_cf.attribute_name(:camel_case))
We initially had implemented a custom operator for hierarchies, but after some investigation it turned out the behaviour would be exactly the same as the [Equals operator](https://github.com/opf/openproject/blob/dev/app/models/queries/operators/equals.rb).

And after looking into other operators, I found that there is already a [EqualsAll operator](https://github.com/opf/openproject/blob/dev/app/models/queries/operators/equals_all.rb).

Which leads me to think that using the default operators here is better because it is more aligned with the rest of the application. Meaning I don't think it is better to use explicit `is any` and `is all`.

2024-11-22 15:40 UTC, brunopagno commented
> requests specs are much faster then UI tests

@Kharonus that's a very valid point. I think I caught a glimpse of previous discussions around the topic in the past. To be honest at this point I don't have strong opinions, so I would be fine if we want to ditch these feature specs for API tests.

2024-11-26 13:55 UTC, apfohl approved these changes

2024-11-26 13:55 UTC, merged

2024-11-26 16:12 UTC, ulferts reviewed
The code change is still fine so nothing changed from my initial, brief glance-over. 

I personally wouldn't have written the detailed specs on the various filters including their operators in a feature spec. Rather, I would have written one feature spec to safeguard the end to end functionality and then have integrational, still somewhat unit specs on the level of checking that the expected results are returned for every operator.

What is amis on the user level is I think the filter value selection which currently is a flat list. 

<img width="549" alt="image" src="https://github.com/user-attachments/assets/c25a8a7b-dcd7-4c6a-89f1-fb78dda0f5a4">

Something that I stumbled over is that the filter results are not as expected (by me). In case I have two work packages and only one is of a type that has the cf enabled. The other doesn't have the cf configured at all. And that one work package with the matching type has a value set. If the filtering then happens with the "is not" operator, the work package that does not have the matching value is not returned. 

The above behaviour however is true for all custom field filters I checked. It still constitutes a bug I think as it goes against the user's expectations.

What is also surprising is the SQL that is generated:

```SQL
SELECT
	"work_packages"."id"
FROM
	"work_packages"
	LEFT OUTER JOIN "projects" ON "projects"."id" = "work_packages"."project_id"
WHERE
	(
		(
			WORK_PACKAGES.ID IN (
				SELECT
					WORK_PACKAGES.ID
				FROM
					WORK_PACKAGES
					LEFT OUTER JOIN CUSTOM_VALUES ON CUSTOM_VALUES.CUSTOMIZED_TYPE = 'WorkPackage'
					AND CUSTOM_VALUES.CUSTOMIZED_ID = WORK_PACKAGES.ID
					AND CUSTOM_VALUES.CUSTOM_FIELD_ID = 541
					JOIN CUSTOM_FIELDS_TYPES ON CUSTOM_FIELDS_TYPES.TYPE_ID = WORK_PACKAGES.TYPE_ID
					AND CUSTOM_FIELDS_TYPES.CUSTOM_FIELD_ID = 541
					JOIN CUSTOM_FIELDS_PROJECTS ON CUSTOM_FIELDS_PROJECTS.PROJECT_ID = WORK_PACKAGES.PROJECT_ID
					AND CUSTOM_FIELDS_PROJECTS.CUSTOM_FIELD_ID = 541
				WHERE
					(
						CUSTOM_VALUES.VALUE IS NULL
						OR CUSTOM_VALUES.VALUE NOT IN ('14')
					)
			)
		)
		AND (PROJECTS.ID IN (6))
	)
	AND (
		WORK_PACKAGES.ID IN (
			SELECT
				WORK_PACKAGES.ID
			FROM
				WORK_PACKAGES
				LEFT OUTER JOIN CUSTOM_VALUES ON CUSTOM_VALUES.CUSTOMIZED_TYPE = 'WorkPackage'
				AND CUSTOM_VALUES.CUSTOMIZED_ID = WORK_PACKAGES.ID
				AND CUSTOM_VALUES.CUSTOM_FIELD_ID = 541
				JOIN CUSTOM_FIELDS_TYPES ON CUSTOM_FIELDS_TYPES.TYPE_ID = WORK_PACKAGES.TYPE_ID
				AND CUSTOM_FIELDS_TYPES.CUSTOM_FIELD_ID = 541
				JOIN CUSTOM_FIELDS_PROJECTS ON CUSTOM_FIELDS_PROJECTS.PROJECT_ID = WORK_PACKAGES.PROJECT_ID
				AND CUSTOM_FIELDS_PROJECTS.CUSTOM_FIELD_ID = 541
			WHERE
				(
					CUSTOM_VALUES.VALUE IS NULL
					OR CUSTOM_VALUES.VALUE NOT IN ('14')
				)
		)
	)
	AND "work_packages"."id" IN (
		SELECT
			"work_packages"."id"
		FROM
			"work_packages"
			INNER JOIN "projects" ON "projects"."id" = "work_packages"."project_id"
			INNER JOIN "enabled_modules" ON "projects"."id" = "enabled_modules"."project_id"
			AND "enabled_modules"."name" IN ('work_package_tracking')
			AND "projects"."active" = TRUE
		WHERE
			"projects"."active" = TRUE
	)
ORDER BY
	WORK_PACKAGES.ID
``` 

So with the exception of the WHERE statement on the project, the subselect for the custom field values is repeated. This looks like potential for optimizations.

2024-11-26 16:23 UTC, brunopagno commented
That's briliant feedback, thanks for making the time @ulferts 

> I would have written one feature spec to safeguard the end to end functionality and then have integrational, still somewhat unit specs on the level of checking that the expected results are returned for every operator.

Fair enough. I am not sure I follow what you're thinking but I assume this aligns more with what @Kharonus was pointing out. Improvements can still be done. I might take some time to look into it this week, then.

> What is amis on the user level is I think the filter value selection which currently is a flat list.

This is happening on https://github.com/opf/openproject/pull/17281

> So with the exception of the WHERE statement on the project, the subselect for the custom field values is repeated. This looks like potential for optimizations.

Interesting. I had not noticed this behaviour when initially implementing the feature, but probably because we were still only trying to handle a single item filter. This feels like something that we could dive really deep into. I am not sure how to tackle yet, but I'll take upon myself to follow up after synchronising with the team