Implementation/59721 add setedit reminder buttondialog to workpackage page
opf/openproject pull request #17341
Opened 2024-12-03 16:06 UTC by jjabari-op

[Ticket](https://community.openproject.org/projects/communicator-stream/work_packages/59721/activity)

2024-12-06 11:19 UTC, akabiru requested changes
Quite the feat, nicely done! 👏🏾 I've noted a few general issues

- [x] Missing unit test coverage for model, contract and API changes - annotated in the code
- [x] Missing API specification & tests
- [x] Several eslint and rubocop issues

UI Wise
- [x] Missing modal cancel button as per [the design](https://www.figma.com/design/hC75Mf34GcQ2LFdm2pQu0l/Reminders?node-id=2-15928&node-type=frame&t=OWW2AAJ77CgnLgo4-0)
   - [x] Separately, it would be good to check with UX/Product if we can adopt "Remove reminder" instead of "Delete reminder" and "Schedule" instead of "Save" - from previous mention [people seemed in favour of the idea](https://matrix.to/#/!lesfhfcbTsKJRLPltu:openproject.org/$GL5v5x_-FTH12i5iqxho5myfRFKnu9TOZ0-jFRYQcbU?via=openproject.org)
 - [x] On hover of the "Set reminder icon" no label is displayed
 - [x] The reminders clock icon is off-centered to the left
 
![Kapture 2024-12-06 at 14 24 41](https://github.com/user-attachments/assets/18d63ec8-c195-42e1-8932-e4b494edb8cd)

 - [x] Content loader skeleton does not match the reminders UI
 - [x] Duplicate form error messages
<img width="644" alt="Screenshot 2024-12-06 at 11 03 09 AM" src="https://github.com/user-attachments/assets/79ba8e79-239b-402f-8f5f-f8c9440e4165">

- [x] Unhandled 404 when reminder edit modal is open, and the reminder notification is created whilst it's still open (you can test this by creating a reminder in the next minute, open the edit modal and wait for the reminder notification to be created then attempt to edit it)

<img width="2003" alt="Screenshot 2024-12-06 at 11 00 29 AM" src="https://github.com/user-attachments/assets/941338b3-7d11-44ab-83ba-367dde736c13">

- [x] icon is smaller than counter

<img width="851" alt="Screenshot 2024-12-09 at 2 02 10 PM" src="https://github.com/user-attachments/assets/348c5aa1-abc9-46bd-b895-b506b6c31400">

2024-12-06 11:19 UTC, akabiru commented on app/contracts/reminders/base_contract.rb
> +    def validate_remind_at_present
🟢  worth dropping in a unit test https://github.com/opf/openproject/blob/dev/spec/contracts/reminders/base_contract_spec.rb

2024-12-06 11:19 UTC, akabiru commented on app/controllers/work_packages/reminders_controller.rb
> +  end
🟠 I think this method and related calls would do well as an extracted simple PORO that can be unit tested- also reduce the perceived complexity on the controller

2024-12-06 11:19 UTC, akabiru commented on app/models/reminder.rb
> +
Nice one covering these- 🟠  it would be worth add the corresponding model unit specs in https://github.com/opf/openproject/blob/dev/spec/models/reminder_spec.rb

2024-12-06 11:19 UTC, akabiru commented on frontend/src/app/features/work-packages/components/wp-reminder-modal/wp-reminder.modal.html
> +        <svg:rect height="25%" rx="2" ry="2" width="180" x="0" y="16"/>
🟠 I noticed this content loader skeleton comes from the shares modal- could we ask design for one that matches the reminders modal?

2024-12-06 11:19 UTC, akabiru commented on frontend/src/app/features/work-packages/components/wp-buttons/wp-reminder-button/wp-reminder-button.component.ts
> +}
🧹 Several eslint issues that need fixing

2024-12-06 11:19 UTC, akabiru commented on frontend/src/app/features/work-packages/components/wp-reminder-modal/wp-reminder.modal.ts
> +}
🧹 Several eslint issues that need fixing

2024-12-06 11:19 UTC, akabiru commented on lib/api/v3/reminders/reminder_representer.rb
> +        date_time_property :remind_at
🔴 Since we're adding the reminder API either way, shall we take the chance to represent it fully? by adding the note and creator association

2024-12-06 11:19 UTC, akabiru commented on lib/api/v3/reminders/reminder_representer.rb
> +        date_time_property :remind_at
🔴 It would also be good to see either a representer unit spec or an API spec for this

2024-12-06 11:19 UTC, akabiru commented on app/models/reminder.rb
> +
🟠  Once the tests are added. I think the method to exclude reminders that have associated reminder notifications can be simplified via [where.missing](https://github.com/rails/rails/pull/34727)

Performance seems ~about the same~ faster - as the later results in no sub-queries and reads easier IMO

```suggestion
  # Currently, reminders are personal, meaning
  # they are only visible to the user who created them.
  def self.visible(user)
    where(creator: user)
  end

  def self.upcoming_and_visible_to(user)
    visible(user)
      .where(completed_at: nil)
      .where.missing(:reminder_notifications)
  end
```

2024-12-06 11:19 UTC, akabiru commented on frontend/src/app/features/work-packages/components/wp-buttons/wp-reminder-button/wp-reminder-button.component.ts
> +    );
Q: Why do we need to reference unread notifications? 🤔

2024-12-06 11:19 UTC, akabiru commented on frontend/src/app/features/work-packages/components/wp-reminder-modal/wp-reminder.modal.html
> +      #frameElement
Nice one 👍🏾

2024-12-06 11:19 UTC, akabiru commented on lib/api/v3/reminders/reminders_api.rb
> +end
🔴 ditto: would be good to see a basic API spec. I think we also need to to update the swagger open-api yml as well. cc tagging @Kharonus - who oversees the API at OP

2024-12-06 11:19 UTC, akabiru commented on spec/features/work_packages/reminders_spec.rb
> +        two_am = "02:00".to_time
<img width="1222" alt="Screenshot 2024-12-06 at 2 09 25 PM" src="https://github.com/user-attachments/assets/9a6d7b12-3e1c-4007-a819-835cd41c026a">

2024-12-06 11:19 UTC, akabiru commented on spec/features/work_packages/reminders_spec.rb
> +end
Nice work on the feature specs! 👍🏾

2024-12-09 11:10 UTC, Kharonus commented on lib/api/v3/reminders/reminders_api.rb
> +end
Yes, please, an inserting of this new endpoint into the OpenAPI specification would be great.

Also, looking at the representer, this is also not a big step. Seems to be like a very small endpoint.

2024-12-09 11:11 UTC, Kharonus commented on lib/api/v3/reminders/reminders_api.rb
> +end
You can though extract that into a separate PR, or even include me in the work (as in pairing on it), to avoid too many loops.

2024-12-09 15:25 UTC, jjabari-op commented
Thank you @akabiru for the comprehensive and detailed review! I'm on it! :)

2024-12-10 18:21 UTC, akabiru commented
@jjabari-op updating against dev as there were several recent CI stabalisation fixes that would be nice to have in

2024-12-12 09:55 UTC, akabiru approved these changes
🥇

2024-12-12 09:55 UTC, akabiru commented on app/controllers/work_packages/reminders_controller.rb
> +  end
https://community.openproject.org/wp/60127

2024-12-12 09:55 UTC, akabiru commented on lib/api/v3/reminders/reminders_api.rb
> +end
👍🏾 
<img width="1692" alt="Screenshot 2024-12-12 at 12 53 17 PM" src="https://github.com/user-attachments/assets/81329b6a-1a31-4fc2-9ea5-f2ecc8336f34" />

2024-12-12 09:57 UTC, merged