WIP storages new folder API endpoint
opf/openproject pull request #17375
Opened 2024-12-05 14:47 UTC by brunopagno

# Ticket
https://community.openproject.org/wp/59900

# What are you trying to accomplish?
...

# What approach did you choose and why?
...

# Merge checklist

- [ ] Added/updated tests

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/components/schemas/storage_folder_write_model.yml
> +  - path
🔴 rename to `parentId`

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/components/schemas/storage_folder_write_model.yml
> +    type: integer
🔴 type must be string

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/components/schemas/storage_folder_write_model.yml
> +    description: Folder name
🟡 Being more specific woudl be nice, like "The name of the folder to be created" and for parent id something like "The unique identifier of the parent folder the new folder is created in"

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/paths/storage_folders.yml
> +  operationId: storage_new_folder
🟡  opoeration id pattern is: `create_storage_folder`

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/paths/storage_folders.yml
> +  description: Creates a new folder on the given path
🟡 description is still written for "path", should be mentioning a specific parent folder.

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/paths/storage_folders.yml
> +            $ref: '../components/schemas/storage_file_model.yml'
🔴 error cases are missing. I'd assume 400, 404, 403.

2024-12-06 09:36 UTC, Kharonus commented on docs/api/apiv3/paths/storage_folders.yml
> +          $ref: '../components/schemas/storage_folder_write_model.yml'
🟡 add a small, simple, named example as a separate file and $ref it here. Same for response

2024-12-09 16:37 UTC, brunopagno commented on modules/storages/lib/api/v3/storage_files/storage_folders_api.rb
> +                  path = URI.decode_uri_component(folder_info.location)
Not sure if I am missing something here, but I needed to decode URI characters for the fetched information from the provider

2024-12-09 16:37 UTC, brunopagno commented on modules/storages/lib/api/v3/storage_files/storage_folders_api.rb
> +            requires :name, type: String, desc: "Folder name"
self reminder to double check parameters

2024-12-10 09:20 UTC, mereghost requested changes
Looks good overall. It might need some more tests using OneDrive as the base storage.

2024-12-10 09:20 UTC, mereghost commented on modules/storages/app/services/storages/create_folder_service.rb
> +      ::Storages::Peripherals::Registry
Since you are already on the `Storages` module you can call just `Peripherals::Registry`.

2024-12-10 09:20 UTC, mereghost commented on modules/storages/lib/api/v3/storage_files/storage_folders_api.rb
> +                  path = URI.decode_uri_component(folder_info.location)
Also on OneDrive, `FileInfo#location` isn't what you would send up to `CreateFolder`, it should be `id`

Annoying? Yes. Terribly so.

2024-12-10 09:20 UTC, mereghost commented on modules/storages/lib/api/v3/storage_files/storage_folders_api.rb
> +                  path = URI.decode_uri_component(folder_info.location)
WDYT of moving this method to the create folder service under another name like `CreateFolderService.with_parent_id(folder_name, parent_id)`, so that the resource ends up with no special business logic?

2024-12-10 09:20 UTC, mereghost commented on modules/storages/spec/requests/api/v3/storages/storage_folders_api_spec.rb
> +      )
An alternative to just replacing it with a lambda, now that we have validating mocks in place, would be to stub the command/query itself.

It is a bit more verbose, but can help with detecting bad argument passing.

```ruby
file_info = class_double(Storages::Peripherals::StorageInteraction::Nextcloud::FileInfoQuery)
allow(file_info).to receive(:call).with(valid: :arguments).and_return(ServiceResult.success)

Storages::Peripherals::Registry.stub('nextcloud.queries.file_info', file_info)
```

2024-12-10 09:24 UTC, brunopagno commented on modules/storages/spec/requests/api/v3/storages/storage_folders_api_spec.rb
> +      )
Oh, I like this :clap: 
Will give it a try

2024-12-10 17:12 UTC, brunopagno commented on modules/storages/lib/api/v3/storage_files/storage_folders_api.rb
> +                  path = URI.decode_uri_component(folder_info.location)
Moved the logic to the service!

2024-12-10 17:13 UTC, brunopagno commented on modules/storages/spec/requests/api/v3/storages/storage_folders_api_spec.rb
> +      )
I adjusted the specs here. It actually instantly caught a small issue with my setup. Looking better I think :)

2024-12-11 09:03 UTC, mereghost approved these changes
Nice work!

2024-12-11 09:03 UTC, merged