Discover access token audiences
opf/openproject pull request #17469
Opened 2024-12-16 09:30 UTC by NobodysNightmare

# Ticket

https://community.openproject.org/projects/cross-application-user-integration-stream/work_packages/60162

# What are you trying to accomplish?
This PR is an extension of previous work in https://github.com/opf/openproject/pull/16940. We want to be able to use tokens stored in the corresponding database model for access to third party services, such as Nextcloud.

There are different ways that we can use these existing tokens for that. The case handled in this PR is that the token might already be immediately usable for use in certain services, which we can discover from the token's audience.

# What approach did you choose and why?

We are expecting the access token to be a JWT that we can parse and verify using the metadata we have configured for the corresponding OIDC provider. While there is no guarantee that access tokens can be parsed as JWTs, it's very common to find when dealing with an OIDC IDP, since those are required to provide their ID tokens as JWTs, so the "infrastructure" for signing JWTs exists anyways.

To perform the parsing I extracted previously existing code from the `JwtOidc` warden strategy into a new parser service _and adapted it_ to the common needs of the warden strategy and our new code.

# Merge checklist

- Added/updated tests
    -  [x] For JWT parsing
    - [x] For audience discovery
- [x] ~~Added/updated documentation in Lookbook (patterns, previews, etc)~~
- [x] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-12-16 13:44 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
I am starting to become unhappy about names.

I called the `UserToken` like that, because it's a token that grants access in the name of the user.

I called the `ProviderTokenParser` like that, because it only allows proper parsing of JWTs that were issued by a configured provider (they are not parseable without knowing the provider).

But now looking at both names next to each other, it doesn't seem to make sense, because there are no tokens to do stuff in the name of a provider. It seems counter intuitive, that the `ProviderTokenParser` would parse a `UserToken` and yet that's what it does...

2025-01-10 15:28 UTC, mereghost requested changes
Overall seems solid just one point that'd like to check viability.

2025-01-10 15:28 UTC, mereghost commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
Names are hard as hell. This could easily become just `OIDC::JWTParser` and the `UserToken` could just be `OIDC::Token`.

I suck at naming. XD

2025-01-10 15:28 UTC, mereghost commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      raise Error, "The access token issuer is unknown" if provider.blank?
🟡 My guess here from the code, is that this exception is being used as flow control to represent an invalid but not exceptional state.

That's were we usually would rely on a `ServiceResult`, `Dry::Monad::Result` or similar object to represent a failed state without all the costs of raising an exception.

2025-01-10 15:28 UTC, mereghost commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      OpenIDConnect::Provider.where(available: true).find { |p| p.issuer == issuer }
🔴 This will load all the providers in memory then run `Array#find`, can't the block become part of the `where` clause?

2025-01-10 15:28 UTC, mereghost commented on modules/openid_connect/spec/services/openid_connect/associate_user_token_spec.rb
> +    expect(parser).to have_received(:parse).with(access_token)
🟢 isn't this testing the internals of the service, checking if a forcebly injected spy actually is being called with the correct params? 

Can't we use dependency injection here so that we don't need to stub the `.new` method? Is there a easy way to not have to mock/spy at all? Wouldn't be tested on the other examples below?

2025-01-10 15:31 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
It's definitely not a `JWTParser`, because the token being a **JSON Web** Token is optional. Though I'll give `TokenParser` and `Token` a second thought.

2025-01-10 15:33 UTC, mereghost commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
You could have multiple parsers being chosen at runtime for each type of token.

2025-01-10 15:33 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      raise Error, "The access token issuer is unknown" if provider.blank?
That's a fair comment. My excuse is that all of this started from refactoring previously existing code and extracting it into a common class.

But that excuse is bad. I'll look into getting friends with `Dry::Monad::Result` once more ;-)

2025-01-10 15:36 UTC, mereghost commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      raise Error, "The access token issuer is unknown" if provider.blank?
Feel free to enlist me if you get stuck at using it. =)

2025-01-10 15:39 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      OpenIDConnect::Provider.where(available: true).find { |p| p.issuer == issuer }
`issuer` is part of the options. I'll have to check, but assuming that `options` is a `JSONB` this should still be possible.

Now that I see this code, I also want to double check whether the new code circumvents a cache that the previous code may have been using (via `OpenProject::OpenIDConnect.providers`).

2025-01-10 15:50 UTC, NobodysNightmare commented on modules/openid_connect/spec/services/openid_connect/associate_user_token_spec.rb
> +    expect(parser).to have_received(:parse).with(access_token)
One way avoid the mocking is to pass a real JWT that has certain properties. We do this in `spec/requests/api/v3/authentication_spec.rb` where I think this approach is feasible, because it's an integrative spec.

Here I wanted to stay encapsulated, while still checking whether the tested unit properly behaves at its boundaries (e.g. whether it correctly sets-up token parsing). E.g. the token parser should not raise an error when the received token is for a foreign audience, but still it should ensure that an audience claim is part of the token.

Let me try to follow along with your suggestion: Your idea would be to hand in the token parser into the `AssociateUserToken` service. This would allow us to replace it with a mock during testing more easily (no need to overwrite new).

However, I'd still ask myself where we'd test that the "production parser" is configured correctly. The correct configuration is very much related to the use case of the service under test.

2025-01-10 15:52 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
I was even mixing things up. The token parser completely expects a JWT. Just other parts of the code (`AssociateUserToken`) treat JWT as optional. Thanks for the input :)

2025-01-10 15:54 UTC, mereghost commented on modules/openid_connect/spec/services/openid_connect/associate_user_token_spec.rb
> +    expect(parser).to have_received(:parse).with(access_token)
> However, I'd still ask myself where we'd test that the "production parser" is configured correctly. The correct configuration is very much related to the use case of the service under test.

This could be done by the request specs you mentioned. I'm okay with how it is now, but every time I see a stub of `.new`, I think of it as a code smell.

2025-01-13 07:50 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
Renamed to `OpenIDConnect::JWTParser`.

2025-01-13 08:20 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      OpenIDConnect::Provider.where(available: true).find { |p| p.issuer == issuer }
Fixed. Now using:

```
OpenIDConnect::Provider.where(available: true).where("options->>'issuer' = ?", issuer).first
```

This is still completely uncached, so every request with a JWT will cause us to fetch the provider once. However, I expect this to be a generally cheap operation and not much more expensive than making the same request to a network cache (a file-based cache would have lower latency).

2025-01-13 14:48 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +  class ProviderTokenParser
My latest commit modanizes the `JwtParser` and does so in a way that I think is a net win in readability :)

Let me know what you think.

2025-01-13 14:48 UTC, NobodysNightmare commented on modules/openid_connect/spec/services/openid_connect/associate_user_token_spec.rb
> +    expect(parser).to have_received(:parse).with(access_token)
Dependency injecting the parser now.

2025-01-14 07:28 UTC, NobodysNightmare commented on modules/openid_connect/app/services/openid_connect/provider_token_parser.rb
> +      raise Error, "The access token issuer is unknown" if provider.blank?
My latest commit monadizes the `JwtParser` and does so in a way that I think is a net win in readability :)

Let me know what you think.

2025-01-14 14:27 UTC, mereghost approved these changes

2025-01-14 14:33 UTC, merged