WIP pattern autocompleter input
opf/openproject pull request #17472
Opened 2024-12-16 15:37 UTC by brunopagno

# Ticket

https://community.openproject.org/projects/document-workflows-stream/work_packages/59999

# What are you trying to accomplish?

[Fancy input](https://www.figma.com/design/I2IVNb97j1fNNCs32H6p2m/Automatic-generated-subjects)

## Screenshots

Not yet

# What approach did you choose and why?

Haven't decided anything yet

# Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [ ] Tested major browsers (Chrome, Firefox, Edge, ...)

2025-01-14 10:24 UTC, NobodysNightmare requested changes
I've done some testing mostly from the UI side (i.e. not looking at the code first, but checking behaviour first) and left some comments.

Feel free to give me feedback on whether you agree or disagree to the findings, but also whenever you think that addressing a finding takes too much effort and should rather be extracted to a separate PR.

2025-01-14 10:24 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    // show suggestions for the current word
While using the component, I realized that suggestions do not change when I navigate with the mouse or the arrow keys. E.g. when I start typing `Aut`, a suggestion for `Author` pops up.

Now when I either click somewhere else or use arrow keys to move the cursor away, I'd expect the auto-completion to disappear or possibly update for the next selected word. Instead the auto completion proposal stays expanded.

2025-01-14 10:24 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +  input_blur() {
I think blur is also a good moment to close the auto-completion. I noticed that I automatically (i.e. through muscle memory) clicked next to the input when I wanted the dropdown to close and then I was surprised that it remained open.

2025-01-14 10:24 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    if (event.key === 'ArrowUp') {
What I see is that we implement the behaviour of a select box manually here. This is tricky. For example I noticed that when using a screen reader, the current implementation does not read out my selection when I change it using the arrow keys. A normal select box (e.g. the color selection in the settings tab) does this.

That's an accessibility concern as far as I can tell. **However**, I realize that the same problem can be observed for two other places in our UI: The project selection in the top left and our emoji autocompleter. So maybe we never solved this so far. (for comparison, the GitHub emoji autocompleter behaves fine)

Sadly I am by no means an expert in _implementing_ accessible custom components. As far as I can tell, the usually best practice is to start with a standard component that is already accessible, e.g. using a real select box in the background.

2025-01-14 10:36 UTC, brunopagno commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    // show suggestions for the current word
I had trouble deciding when to close or not the autocomplete. But this sounds correct. I might have stayed a bit too long staring at that same screen.

2025-01-14 10:37 UTC, brunopagno commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +  input_blur() {
This was the case at some point. I don't remember why I removed it, but I'll add again.

2025-01-14 10:38 UTC, brunopagno commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    if (event.key === 'ArrowUp') {
I am not sure how to handle this, though. I will reach out to other people on the dev team to see if it helps.

But I was *more afraid* of attempting to change focus/force navigate with something that is supposed to be a shortcut.

Maybe there's an obvious solution.

2025-01-14 13:03 UTC, brunopagno commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    // show suggestions for the current word
Adjusted the hiding autocomplete behaviour

2025-01-14 13:05 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    if (event.key === 'Escape' || event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
(Very optional)

Small suggestion after realizing that using `Esc` we can close the auto-completer: What do you think about adding `Ctrl+Space` as a combo to open the list again?

After the latest change this can also be useful for cases where the menu accidentially closed during keyboard navigation.

2025-01-14 13:05 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    // show suggestions for the current word
Yeah, I also realize that my actual user expectation is not easy.

First things first: **I like the current behaviour** (closing on any arrow L/R input) more than the previous behaviour of never closing.

However, if I wanted to iterate on this (and we can legitimately do that outside the scope of this PR), I'd probably check whether the currently selected word changes as a consequence of the cursor navigation, and only close the input if the selected word changes.

Main reason for writing this down is to provoke denying or approving reactions, i.e. checking whether others would agree.

2025-01-14 13:39 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +  private ensureSpacesAround():void {
I remember that we talked about this in person and pointed out that it is a hack/workaround. That's perfectly fine!

However, since this code is not self-explanatory, we should make sure the intention is clearly documented. What do you think about adding a comment that briefly explains why these spaces are necessary? Something along the lines of:

> If there is no editable text before or after an uneditable node, it's impossible to move the cursor there. As a workaround to ensure that the user can always move the cursor anywhere, we ensure that there is at least a whitespace character at the beginning and end of our text box.

2025-01-14 13:57 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +      while (pos > -1 && targetNode.textContent?.charAt(pos) !== ' ') { pos-=1; }
Mh, so maybe it's because I spent the past 10 minutes staring at the [Wikipedia page about whitespace](https://en.wikipedia.org/wiki/Whitespace_character), but seeing this code I am now wondering, whether we should not match for the space character and instead match for any kind of unicode whitespace.

I.e.

```suggestion
      while (pos > -1 && !isWhitespace(targetNode.textContent?.charAt(pos))) { pos-=1; }
```

where I leave the implementation of `isWhitespace` to the imagination of the reader.

2025-01-14 14:08 UTC, brunopagno commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +      while (pos > -1 && targetNode.textContent?.charAt(pos) !== ' ') { pos-=1; }
I found two implementations interesting :sweat_smile: 

```javascript
/\s/.test(ch)
// or
str.trim() === ''
```

This is fun~

2025-01-14 14:17 UTC, NobodysNightmare commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    if (htmlValue.endsWith('>')) { htmlValue = `${htmlValue} `; }
These two lines seem to be duplicated with `ensureSpacesAround`. Can we make sure to only implement this once?

E.g. the caller of `toHtml(...)` could then call `ensureSpacesAround()` afterwards. I.e. what I'd try to achieve is to "localize" the workaround, making sure that it's not too far spread out.

2025-01-14 14:25 UTC, NobodysNightmare commented
Because the PR template always reminds me about it: Should we add our new component also to the Lookbook?

I am not quite sure how this works, but I guess we need to add a file like `lookbook/previews/open_project/common/pattern_autocomplete_preview.rb`.

2025-01-14 14:56 UTC, brunopagno commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    if (htmlValue.endsWith('>')) { htmlValue = `${htmlValue} `; }
Yeah, this is fair. Things that I started doing in different times and did not clean up properly. Thanks for spotting.

2025-01-15 07:00 UTC, NobodysNightmare commented on app/components/work_packages/types/pattern_autocompleter.rb
> +          action: "click->pattern-autocompleter#suggestions_select",
I just spotted this one and noticed that I didn't try using the mouse to select an autocomplete entry. For me it doesn't work to click on an autoselect entry. The pop-up closes, but nothing gets selected.

2025-01-15 07:49 UTC, HDinger requested changes
Hi @brunopagno 

I don't know which detail of review you want at that point. I will just write down the issues I found, feel free to ignore when you already aware of that.

- [ ] When loading the page, the field is shortly shown. Sometimes, it there so long that I even could start typing before it vanished
<img width="500" alt="Bildschirmfoto 2025-01-15 um 07 54 54" src="https://github.com/user-attachments/assets/13844629-a56e-44eb-b388-be97f59c3472" />

- [ ] The search results are only selectable via keyboard, not via mouse click

- [ ] The label text and closing "x" are not alligned
<img width="200" alt="Bildschirmfoto 2025-01-15 um 07 56 45" src="https://github.com/user-attachments/assets/c3e0730d-ca8c-4cd9-91c0-9d80127daf00" />

- [ ] The labels can overflow the input
<img width="300" alt="Bildschirmfoto 2025-01-15 um 08 00 57" src="https://github.com/user-attachments/assets/f0c360c7-d45b-4f48-9db3-dcc167142455" />

- [x] When there are no search results, the headlines are still shown, which feels weird
<img width="215" alt="Bildschirmfoto 2025-01-15 um 07 56 22" src="https://github.com/user-attachments/assets/510e84ca-05f9-45cc-82e2-27d395655a5c" />

- [ ] I can't reliably reproduce it, but sometimes there are issues with the cursor position which is jumping around. For example when you select a label as the first element, it jumps to the right after pressing space.
![Jan-15-2025 08-09-38](https://github.com/user-attachments/assets/f460b3a8-a0c2-4471-a4e1-869b711f4fa2)

In general it works nicely. Looking at the code, it still feels however as if we should have solved that differently from the UX side from the beginning. We are implementing a lot of custom stuff here and misusing components for that. I know that it is too late now, but we should keep that in mind for later similar cases.

2025-01-15 07:49 UTC, HDinger commented on app/components/work_packages/types/pattern_autocompleter.html.erb
> +      <%= content_tag(:span, style: "cursor: default;", "data-role": "token-text") { "__VALUE__" } %>
Please do  not use inline styles. Either use system_arguments or if the style is not supported, add a class and write the styles in the CSS file.

2025-01-15 07:49 UTC, HDinger commented on app/components/work_packages/types/pattern_autocompleter.html.erb
> +            icon: :x, size: :xsmall, style: "cursor: pointer;margin: 0.2em;",
Same, please do not use inline styles. Further, 0.2 is somehow a magic number, that does not even align the cross to the center:
<img width="200" alt="Bildschirmfoto 2025-01-15 um 07 56 45" src="https://github.com/user-attachments/assets/18b72eed-b28b-41bc-9d06-de946125309e" />

Please try to resolve that with CSS alignment mechanism (e.g. `vertica-align` or a `flex`)

2025-01-15 07:49 UTC, HDinger commented on app/components/work_packages/types/pattern_autocompleter.html.erb
> +  <%= content_tag(:div, style: "position: relative;") do %>
```suggestion
  <%= render(Primer::BaseComponent.new(tag: :div, position: :relative)) do %>
```

2025-01-15 07:49 UTC, HDinger commented on app/components/work_packages/types/pattern_autocompleter.html.erb
> +            style: "cursor: pointer;position: absolute;right: 1em;top: 0.5em;",
Position absolute has some drawbacks in this case. You are enforcing it to lay at that specific place no matter what the content of the input is. Thus the content and the arrow can overlap:

<img width="485" alt="Bildschirmfoto 2025-01-15 um 08 18 12" src="https://github.com/user-attachments/assets/0af2227a-01a3-46c6-9337-ec330deb9f70" />

2025-01-15 07:49 UTC, HDinger commented on app/components/work_packages/types/pattern_autocompleter.sass
> +    color: var(--list-item-hover--color)
Looking at the ActionList component, they use `--fgColor-default` for hovered elements. As we try to mimic that style, I'd suggest that we use the same here.

2025-01-15 07:49 UTC, HDinger commented on frontend/src/stimulus/controllers/pattern-autocompleter.controller.ts
> +    if (event.key === 'ArrowUp') {
The idea with using Primer was to fully spport accessibility again, as the Primer components are claimed to be accessible. However, the ActionList in Primer is not meant to be used standalone afaik, so we are more or less misusing it here. Looking at other [components](https://primer-lookbook.github.com/view-components/lookbook/inspect/primer/alpha/action_menu/single_select) where the actionList is used, it is possible to navigate via arrows. Primer has an internal helper called `focus-group` for that, see:

* https://github.com/primer/view_components/blob/main/app/components/primer/focus_group.ts
* https://github.com/primer/view_components/blob/main/app/components/primer/alpha/action_menu.html.erb#L2

Maybe, we simply have to add that around our ActionList as well and we can get rid of the custom selection logic. But that is just an educated guess, I don't know what that really works.

2025-01-15 08:15 UTC, NobodysNightmare commented on app/components/work_packages/types/pattern_autocompleter.html.erb
> +            style: "cursor: pointer;position: absolute;right: 1em;top: 0.5em;",
I didn't see that arrow down at all until now :see_no_evil:

Devils advocate: Do we need this arrow at all? It makes the component look like a select, when it is mostly like a text input. E.g. we'd also not show an arrow down in a text input that allows autocompleting emojis (which I think is a good analogy for what we are doing here).

2025-01-15 08:16 UTC, NobodysNightmare commented on app/components/work_packages/types/pattern_autocompleter.rb
> +          action: "click->pattern-autocompleter#suggestions_select",
New learning: Selecting with the mouse works after opening the suggestion list via the arrow down button, but not when using the mouse after starting autocompletion via typing.

2025-01-15 08:19 UTC, brunopagno commented on app/components/work_packages/types/pattern_autocompleter.rb
> +          action: "click->pattern-autocompleter#suggestions_select",
I shall investigate. Maybe the focus group solution suggested above fixes all things and I can move on with life :eyes:

2025-01-15 08:21 UTC, brunopagno commented on app/components/work_packages/types/pattern_autocompleter.html.erb
> +            style: "cursor: pointer;position: absolute;right: 1em;top: 0.5em;",
The arrow allows for a mouse only interaction of adding tokens so I think it might be necessary. :thinking:

2025-01-15 08:24 UTC, HDinger commented
Some other things:

- [ ] When I selected and item from the list via Enter, and the press Enter again, the element is added again to the input
![Jan-15-2025 09-24-18](https://github.com/user-attachments/assets/ce0455ad-d369-461b-9379-ea030941bb9a)


- [ ] In Safari, after I added an item, the cursor jumps to the beginning of the input
![Jan-15-2025 09-24-10](https://github.com/user-attachments/assets/ca3e8189-5521-4442-8135-b7707ab33c40)


- [ ] Currently it is not possible to delete a label via keyboard, only with a mouse. That is also an accessibility issue.

2025-01-22 09:25 UTC, brunopagno commented
Closing this PR in favour of https://github.com/opf/openproject/pull/17634

More information at https://community.openproject.org/projects/document-workflows-stream/work_packages/60625/activity

2025-01-22 09:25 UTC, closed without merging