[#60291] Apply view permissions on the Project List page
opf/openproject pull request #17496
Opened 2024-12-18 15:27 UTC by dombesz

# Ticket
https://community.openproject.org/work_packages/60291

# What are you trying to accomplish?
Apply stages and gates view permissions on the project list page.

# Merge checklist

- [X] Added/updated tests
- [ ] Added/updated documentation in Lookbook (patterns, previews, etc)
- [X] Tested major browsers (Chrome, Firefox, Edge, ...)

2024-12-18 15:40 UTC, ulferts requested changes
@dombesz I fear it is a bit more complicated. It might be that the user has the permission to see the dates in one project but doesn't have it in the next. So if the user lists projects, the dates set for the former should be visible but at the same time, they should be invisible on the later.

2024-12-18 15:42 UTC, dombesz commented
Thanks @ulferts , I'll add the permissions verification on the row level.

2024-12-19 07:28 UTC, dombesz commented
Hi @ulferts I addressed your CR comments.

2024-12-20 10:25 UTC, oliverguenther approved these changes

2024-12-20 10:25 UTC, merged