specified users API adding endpoints for creation and listing
opf/openproject pull request #4894
Opened 2016-09-23 16:35 UTC by machisuji

WP [#23955](https://community.openproject.com/work_packages/23955/activity)

2016-09-26 08:16 UTC, ulferts requested changes
Apart from what I have written so far specifically at the various lines of code, I have three major concerns.

_Privacy_
This is a long pending change and thus I am willing to accept it as out of scope unless we find a viable solution. 
Currently it is specified to have the `/api/v3/users` end point only accessible for admins which is consistent with what we have in the user interface. This severely limits the usability of the api and when it comes to privacy, I only see that as being of limited effectiveness. The user id's are easily guessable and as soon as we add an available_users endpoint to provide a mechanism to add users as project members, we need to reduce the restrictions on accessing a list of users.
In oder to be able to do that I propose to:
- introduce a guid type id for the user so that the resource url is no longer guessable
- limit the visibility of attributes to the minimum of what the calling user needs to see. While an admin needs to know the login of a user, another user will probably not. 

_Forms_

To allow true discoverability but also because of the dynamic attributes and their allowed values, we introduced forms and schemas when we created the API for work packages. I see the same challenges for users and would thus choose the same pattern to cope with them. 
Therefore we need additional end points:
- `/api/v3/users/form`
- `/api/v3/users/schema`
- `/api/v3/users/:id/form`

_Groups_

The current implementation does not handle groups well. The proposed change to the api does not mention the group resources.
It is desirable to me to finally have a place in the system where the notion of `principal` and the differences of it to `user` and group`is considered.

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +| email       | User's E-Mail address                                     | String   | 60 max length                                        | READ / WRITE         | E-Mail address not hidden
needs to be unique as well

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +| language    | User's language                                           | String   | ISO 639-1                                            | READ / WRITE         | **Permission**: Administrator unle
the language is also constrained to be one of the languages activated in the system.

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +    + sortBy (optional, string, `"status:asc"`) ... Comma separated list of columsn to sort by. May be combined with direction through colon.
This creates a filtering interface different from what is [specified for the work packages](https://github.com/opf/openproject/blob/dev/doc/apiv3-documentation.apib#L3943). While I do not believe the interface specified for the work packages to be necessarily better than what is specified here, we should nevertheless strive for uniformity. And as the interface for work packages already exists, we should roll with that as a template. 

That would mean allowing a `filters` parameter which can include `status`, `group` and `name`.

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +    [User][]
I'd go with a 200 here so that the created user is returned. I'd do that for two reasons:
- we did it in other places
- because not all attributes have to be set (e.g. the language, admin, custom values), it makes sense to me to return the object. On top of that, returning the user resource will return the resource's url and by that enable processing the resource further.

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +## Users [/api/v3/users{?notify,offset,pageSize,status,group,name,sortBy}]
This should be added to [api/v3 root](https://github.com/opf/openproject/blob/dev/doc/apiv3-documentation.apib#L571)

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +                "message": "You are not allowed to see work packages."
The error message is targeted at work packages when it should be targeted at users.

2016-09-26 08:16 UTC, ulferts commented on doc/apiv3-documentation.apib
> +| showUser            | Link to the OpenProject user page (HTML)                             |                                                                  |
can we change that to only be `show`? It strikes me as being inconsistent with `update` and `delete`. As a general rule up thumb, I'd not add the resource name to the actions of the resource itself. Only when an associated resource is concerned should we add the resource's name.

2016-09-26 08:37 UTC, ulferts commented on doc/apiv3-documentation.apib
> +    [User][]
sorry, mixed up 201 and 204. Forget my comment.

2016-10-12 09:10 UTC, ulferts commented
I altered the documentation to take heed of what I have written at the various code points and also with regards to forms and schemas.

However, due to lack of time I have excluded:
* the guid discussion
* introducing groups (while I might be able to specify it, I will not have the time to implement it)

2016-10-12 09:10 UTC, ulferts approved these changes

2016-10-12 12:31 UTC, machisuji commented
👍

2016-10-12 12:31 UTC, merged