[24174] Allow users to filter work packages by an exact date
opf/openproject pull request #5071
Opened 2016-11-18 21:13 UTC by silkentrance

This PR allows users to filter the work package list by an exact date.

This applies to non custom fields such as created_at, updated_at, started_at and so on.

https://community.openproject.com/work_packages/24174

2016-11-18 21:19 UTC, silkentrance commented
Please note that required tests are still missing.

2016-11-18 21:37 UTC, silkentrance commented
Still working on custom fields and switching between operators.

2016-11-20 12:53 UTC, silkentrance commented
After some trial and error with angular handling date/time w/ timezone and the server always operating in UTC I finally managed to get things running. However, this requires all user input to be in UTC. Since all dates are displayed using the server's timezone this should not be a problem, but I think that the overall behavior should be changed and that date and time needs to be converted from server TZ to user TZ and vice versa.

2016-11-21 22:43 UTC, silkentrance commented
Right now I am reusing the op-date-picker directive instead of implementing a new one from scratch. It also turned out that simply using the 'date' input type did not suffice on all platforms / user agents. I had to make some adjustments to the directive in order for it to become reuseable in a context other than editing work packages. Some additions to the TimezoneService have also been made, namely getting various representations of the current timezone offset, based on the user's settings, and, failing that, based on the user agent's current timezone.

What is currently missing is the part where the user input gets augmented so that the server will only see UTC based calendarials such as date/datetime/time and where the user sees these calendarials in his or her configured timezone, be it either the one from the user preferences or the default one from the user agent.

2016-11-24 17:33 UTC, silkentrance commented
Further work. Now, the user input date will be adjusted to UTC prior to submitting to the server and will be adjusted back to the user's configured timezone once that the filter gets reloaded from the server.

Caveats: somehow, having a model value different from the actual view value will trigger a kind of rollback, effectfully leaving the date that is submitted to the server the same to the user's input. Still trying to figure out why this happens. It might be the case that the input element below the op-datepicker directive does not rule out on-blur/on-change in standard accessibility mode. Which requires additional changes.

2016-11-27 21:34 UTC, silkentrance commented
While I needed to dive deep into the inner workings of the application, I think I figured it out now.

However, this required some changes to the intrinsics of opDatePicker, which is now no longer bound to a model. I have removed all model bindings from that directive as it rendered it non reusable in situations where you do not want to special case accessibility mode operation. I think that with the current changes, existing special casing of accessibility mode operations in wp-edit can also be removed.

Since I did not experience any 'datepicker instance' exceptions since I have removed that part of the code, I think that it quite safe for overall reuse.

The timezone service has been extended to provide for filters, especially date specific filters.

Test cases need to be addressed as soon as I get some input from you. TIA!

2016-11-30 15:19 UTC, ulferts requested changes
Again :+1: for noticing the necessity to handle time zones. I would probably have missed that if you hadn't thought about it.

But now that you have brought it up I notice a severe problem with the approach taken in this PR. 

Because of the time zones, it will IMO not be possible for the client to only pass date as a filter.

Currently, both Date (start_date, end_date, date custom fields) as well as DateTime (created_at, updated_at) benefit from the new filter. AFAIK, by definition, only DateTime does take time zones into account. 

If we limit the applicability of the filter to Date fields, our problem space reduces and thus our solution can be simpler as well. If only Date fields are filtered, the front end does not need to handle time zones and we needn't concern us with them. Then, a lot of the code in here can be removed, both in the front end as well as in the back end, and it should work fine.

Currently the requirement states as an example:
"Show me all bugs reported in January 2016."
Which would mean to filter on the created_at column which in turn means filtering with time zones. And I double checked that requirement, so it is relevant to filter on DateTime columns.

I see three options for filters on DateTime columns and they all boil down to having a time interval which take time zones into account.
1) Transmit a DateTime filter value to the backend (in UTC) and let the back end know that when that specific operator is employed, it has to add or remove 24 hours to get the span in which to search.  
2) Do transmit a Date filter value and let the back end figure out the rest: Take the user time zone into account and do some magic to deduce the time interval in utc.
3) Change the filter (in the back end and api) to be able to take two values (interval start and the end date time in UTC). The front end can work independently from that. So we might still show a date picker but the front end would know to split that up into two values.
I personally would opt for option 3 as it is the most flexible solution. It would e.g. allow us to later also add an “show me all where the value is between those two filter values”. 

Sadly, that still poses the question of how to handle both Date and DateTime columns. Currently I think, that those two are not compatible. The only option for using them uniformly would be to make the front end smart enough to know if a Date column is filtered and to not perform any time zone adjustments in that case. That would complicate the front end quite a lot.

Therefore we will probably need two separate filter implementations:
1) Date - use Date objects in front end, no time zone adjustments, transmit only date filter values
2) DateTime - use DateTime objects in front end, Time zone adjustments, transmit date time values  

Currently, the PR only uses dates which falls short because 
* Time zone calculations is done when it shouldn’t be because we only have Date objects
* Date values are transmitted for DateTime columns

On top of that there are a couple of minor bugs:
* Reload causes an error as the url is not updated correctly.
* Saving a query with the new filter will save the time zone adjusted value.
* The filter is executed before a value has been selected.

Sorry, again a lot of text to read but you seem to pick the non trivial stuff.

2016-11-30 15:19 UTC, ulferts commented on Gemfile.lock
> +  openproject-wiki_boxes!
Those should not be checked in as they are unique to your op installation

2016-11-30 15:19 UTC, ulferts commented on app/models/queries/sql_for_field.rb
> +  end
This is more or less the same method as `#relative_date_range_clause` with the only difference being the time values, so this can be refactored into a shared method.

2016-11-30 15:19 UTC, ulferts commented on app/models/queries/sql_for_field.rb
> +      s << ("#{table}.#{field} <= '%s'" % [connection.quoted_date(to.to_time(form = :utc).end_of_day)])
The variable assignment `form = :utc` is unnecessary and confusing.

2016-11-30 15:19 UTC, ulferts commented on config/locales/js-en.yml
> +    label_exact_date: "Exact date"
The label does not fit into the flow of the filter:

![image](https://cloud.githubusercontent.com/assets/617519/20751074/3b9162c8-b6fa-11e6-82fa-b946508f65ef.png)

I suggest reusing `:label_equals`.

2016-11-30 15:19 UTC, ulferts commented on config/locales/js-en.yml
> +        exact: "date"
I don't think that the postfix is necessary for that filter at least in the en l10n, but that might be personal preference.
It might be beneficial to have the postfix for other locales, though, so we might just leave the i18n in place while providing an empty l10n for en.

2016-11-30 15:19 UTC, ulferts commented on frontend/app/components/filters/filter-model/filter-model.service.ts
> +          }
I honestly feel dumb when trying to read this because I fail most of the time.

2016-11-30 15:19 UTC, ulferts commented on frontend/app/components/wp-edit/op-date-picker/op-date-picker.directive.ts
> -    require: 'ngModel',
I don't care for the ngModel as long as the date picker is tied to the input field to have the two way synchronization between input and date picker in place which seems to be the case.

And if it removes that weird indirection, I am fine with the change.

2016-11-30 15:19 UTC, ulferts commented on app/models/queries/sql_for_field.rb
>        s << ("#{table}.#{field} > '%s'" % [connection.quoted_date((Date.yesterday + from).to_time.end_of_day)])
:+1: for spotting the necessity for time zone mgmt for the new filter. When reading the PR I noticed that it will be needed here as well.

2016-11-30 15:19 UTC, ulferts commented on app/models/queries/sql_for_field.rb
> +  # until the end of today + to.
The reason for using `(Date.yesterday + from).to_time.end_of_day)` is that it is compatible with both Date and DateTime when using the `>` operator. And as long as that operator is used, the result should be fine. If it is to be changed to `(Date.today + from).to_time.beginning_of_day)` the `>=` operator would have to be used, but that worked in my test as well.

(Only checked on PostgreSQL)

2016-11-30 18:50 UTC, silkentrance commented on Gemfile.lock
> +  openproject-wiki_boxes!
Thank you for seeing this. I relied on rubymine's smart checkout feature. I also removed the dependency towards openproject-emoji.

2016-11-30 18:54 UTC, silkentrance commented on config/locales/js-en.yml
> +        exact: "date"
Personally, I do not see any need for these labels in the UI as the filter operator itself is already stating that these are either weeks or days, or in this case, a date. And, it also complicates things in the UI template. I will remove the label from that filter.

2016-11-30 18:58 UTC, silkentrance commented on frontend/app/components/filters/filter-model/filter-model.service.ts
> +          }
The problem is that the type information is encoded into the operator, while the filter itself, based on the model attribute simply states ``date`` or ``date_past``, both of which do not convey any type information but merely a behavioral distinction of what filter operators become available when selecting for example created_at / start_date as the attribute to filter.

I fear that in order to get rid of the above, the type information needs to be a part of the operator, e.g. ```'=d`' would become ``{type:'date', op: '='}`` and which would also be the information that is then send to the server along with the values.

2016-11-30 18:59 UTC, silkentrance commented on frontend/app/components/wp-edit/op-date-picker/op-date-picker.directive.ts
> -    require: 'ngModel',
I will remove the require then.

2016-11-30 19:15 UTC, silkentrance commented on config/locales/js-en.yml
> +    label_exact_date: "Exact date"
Will do.

2016-11-30 19:19 UTC, silkentrance commented
@ulferts 

> Because of the time zones, it will IMO not be possible for the client to only pass date as a filter.
> Currently, both Date (start_date, end_date, date custom fields) as well as DateTime (created_at, updated_at) benefit from the new filter. AFAIK, by definition, only DateTime does take time zones into account.

The problem with timezones is that all datetimes are stored in the back end's local time which by default seems to be UTC. Now, the service will send these UTC dates back to the front end, without adapting them to the local timezone of the front end, which is correct.

> If we limit the applicability of the filter to Date fields, our problem space reduces and thus our solution 
> can be simpler as well.
> If only Date fields are filtered, the front end does not need to handle time zones and we needn't 
> concern us with them. Then, a lot of the code in here can be removed, both in the front end as well 
> as in the back end, and it should work fine.

Sadly, this is not the case. In the UI the user will be shown a created_at datetime that for example says ``2016-11-22 08:43``. Now, for my tests I am using a timezone in the client with an offset of ``+14:00``. If the user now enters a filter based on that date, he will see ``2016-11-22`` and select that in the date picker.

Now we must transform that date to UTC, which is handled by ``TimezoneService.parseDateToUTC``. The date the user filters on must be stored on the back end in UTC so that it can be equally shared with other users or even reused by the same user, now having a different timezone setting in her client. Since it is a simple date that we store on the back end it comes with no time zone information. (it is assumed that it is in UTC and that all time components are reset to either 0 or to 23:59:59, depending on the operator in use.)

> Currently the requirement states as an example: "Show me all bugs reported in January 2016."
> Which would mean to filter on the created_at column which in turn means filtering with time zones. 
> And I double checked that requirement, so it is relevant to filter on DateTime columns.

Yes, for that the system already supports a date range in the back end. In the front end's UI it still uses the ``dateValue`` attribute for single dates. I am going to implement a date range as well to support such queries as in January 2016.

I think that using date ranges here is more universal than having an input field for just a year and a month, don't you think?

I see three options for filters on DateTime columns and they all boil down to having a time interval which take time zones into account.

> Transmit a DateTime filter value to the backend (in UTC) and let the back end know that when that 
> specific operator is employed, it has to add or remove 24 hours to get the span in which to search.
> Do transmit a Date filter value and let the back end figure out the rest: Take the user time zone into 
> account and do some magic to deduce the time interval in utc.

The problem here is that the user's timezone might be unknown to the back end, which is the case if the user did not configure the timezone in his account settings. And, given the current version of ``moment`` in use, the ``moment.tc.guess()`` API call is not yet available.

I will reply to the rest of your points as soon as I get my head around it.

2016-11-30 19:20 UTC, silkentrance commented on app/models/queries/sql_for_field.rb
> +  # until the end of today + to.
Now I understand. Thanks for clearing this up, makes it easier when merging the two methods.

2016-11-30 19:22 UTC, silkentrance commented on app/models/queries/sql_for_field.rb
> +      s << ("#{table}.#{field} <= '%s'" % [connection.quoted_date(to.to_time(form = :utc).end_of_day)])
And might also be utterly wrong in case that the local timezone of the server is not UTC at all. Will remove that.

2016-11-30 19:41 UTC, silkentrance commented
@ulferts 

I see three options for filters on DateTime columns and they all boil down to having a time interval which take time zones into account.

> 3. Change the filter (in the back end and api) to be able to take two values (interval start and the end date time in UTC). The front end can work independently from that.
> So we might still show a date picker but the front end would know to split that up into two values.

> I personally would opt for option 3 as it is the most flexible solution. It would e.g. allow us to later also add an “show me all where the value is between those two filter values”.
> Sadly, that still poses the question of how to handle both Date and DateTime columns. Currently I think, that those two are not compatible. The only option for using them uniformly would be to make the front end > smart enough to know if a Date column is filtered and to not perform any time zone adjustments in that case. That would complicate the front end quite a lot.

The current solution already implements 3 as its default. The server will always be given a value array for all of the filters/operators. And I am already going into that direction. The current focus was however to get the "easier stuff" right before doing the more complex parts of the solution.


> Therefore we will probably need two separate filter implementations:

> 1. Date - use Date objects in front end, no time zone adjustments, transmit only date filter values
> 1. Time zone calculations is done when it shouldn’t be because we only have Date objects


Example: Server uses UTC, User resides in GMT+14:00. An UTC datetime (created_at) of ``2016-11-21 18:00:00`` will be shown to the user as ``2016-11-22 08:00:00``.
Now the user does not know about the timezone conversion stuff and will happily select ``2016-11-22``. If we do now adjust that date to the server's local time, the query result will display the wrong information as the server will now try to filter everything from ``2016-11-22 00:00:00`` to ``2016-11-22 23:59:59``. And, since the server is agnostic of the user's timezone settings, especially for those who did not edit their account settings, the results are not predictable, even if we'd try to guess the user's timezone on the server.

> 2. DateTime - use DateTime objects in front end, Time zone adjustments, transmit date time values

For use cases where the user also enters a time this is absolutely true.

> 2. Date values are transmitted for DateTime columns

Here, the user is currently able to select a date and not also a time. In fact, the information can be restored on the server by assuming that values.first is the beginning of the interval and that values.last 
represents the end of the interval. The first value will be assumed to have a time component that represents the beginning of the day ``00:00:00`` and the last value is assumed to have a time component that depicts the end of the day ``23:59:59``.


> On top of that there are a couple of minor bugs:
> 1. Reload causes an error as the url is not updated correctly.
> 2. Saving a query with the new filter will save the time zone adjusted value.
> 3. The filter is executed before a value has been selected.

Will be addressed as soon as the rest is working.

Thank you for your valuable input.

I will see what I can do about harmonizing the two use cases (date values/datetime values), but I think that the current approach already captures it quite well.

2016-11-30 19:58 UTC, silkentrance commented on app/models/queries/sql_for_field.rb
> +  end
Yes, it basically is the same, *but*, relative_date_range_clause operates on integers (from/to) and date_range_clause operates on date objects. I may be able to agument the from/to values passed to relative_date_range and then delegate to date_range_clause, what about that?

2016-11-30 20:11 UTC, silkentrance commented
@ulferts most of the changes implemented as requested

2016-11-30 20:56 UTC, silkentrance commented
@ulferts error on reload was fixed.

I get a warning from moment

```
openproject-global.self.js?body=1:66110 Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
```

This results from the fact that a moment instance is created from a simple date string and not an ISO date string, e.g. ``2016-11-28``, which in turn is related to the fact that everything is considered to be a simple date string instead of a datetime object with also time components. I will address this as soon as possible.

2016-11-30 20:58 UTC, silkentrance commented
@ulferts any plans yet to make query objects and filter objects part of the HAL resource mechanism?

2016-12-01 12:21 UTC, lindenthal commented
@silkentrance and @ulferts 

Not sure if I did understand the discussion about time zones correctly. Let's have a look at the following example:

The project manager from Berlin creates the following filter and saves a shared query for:

- All  work packages that are due today.

Let's assume a project member from Hawai accesses this filter. What is the expected behavior?
Should they (1) see exactly the same filter results? Or (2) might it bee that they get different filter results due to the different time zones?

Wouldn't it be easier if the project team defines the team's time zone?

Best
Niels

2016-12-03 19:23 UTC, silkentrance commented
@ulferts We still need to use ``to_time(:utc)`` as otherwise local time will be assumed by ``connection.quoted_date`` which will also ignore time zone settings from ``config/application.rb#config.time_zone``. In my case, this is set to ``UTC``, yet ``connection.quoted_date`` will use ``GMT+1:00``, which is the system's local time timezone.

And while ``ActiveRecord`` uses the timezone associated with the AR derived class, which I presume is always ``UTC``, the connection or at least the ``quoted_date`` method does not adhere to such standards.

``Houston, we have a problem``.

2016-12-03 19:37 UTC, silkentrance commented
@lindenthal Thank you for your input. In this case it is about the date/time representation on the backend, and by that in the database. Where we would assume that all datetime is stored using the UTC time normal regardless of any timezone offsets that for example a team or an individual user specifies.

And, yes, I would like to have the person from Hawaii see the exact same filter results, otherwise it would be near impossible to synchronize work between different timezone offsets.

2016-12-03 21:55 UTC, silkentrance commented
As for the auto update of the work packages list on selecting the '=d' operator, I had to remove all existing and by that semi working / side effects using pre-conditions from 
``scope.$watch('filter', function (filter, oldFilter) {``

in ``query-filter.directive.ts``.

The removed preconditions are

``
        var isEmptyText = filter.type === 'text' && filter.textValue === undefined;
        var isEmptySelect = filter.type === 'list_status' && filter.values && filter.values[0] === 'undefined';

        if (filter !== oldFilter && !isEmptySelect) {
``

These turned out to be either relying on unwanted side effects (``type=='text'``) or are just redundant.

I have tested this (manually) extensively, so I think that this should work with all of the given use cases.

2016-12-05 23:23 UTC, silkentrance commented
@ulferts while this works, it leaves a lot to be desired on behalf of the code. Not to mention the UI. I am currently working on a part refactoring of the filter architecture and partly also its logic. But this will take a while.

2016-12-06 07:18 UTC, oliverguenther commented
Hi Carsten,

could you rebase this on dev (or merge origin/dev into your branch, if you prefer that) ? It includes a fix for the preview docker build pipeline we use for previewing branches.

Also, Jens is at sick leave at the moment so please excuse missing replies from him.

2016-12-07 16:15 UTC, silkentrance commented
@oliverguenther I have rebased the branch as requested. I am currently working on a few issues and also try to figure out how to adjust the CSS so that the two input elements will show in the same line instead of below each other. Then I will check accessibility and see whether this still works as expected.
Finally, I need to implement the tests for the current approach and then comes the refactoring...

2016-12-07 20:08 UTC, silkentrance commented
@oliverguenther I have to refactor the whole shebang, namely TimezoneService and its various methods and all that depends upon that. May take some time.

2016-12-08 05:41 UTC, oliverguenther commented
Okay good. Let me know if you need help testing the karma tests. They can be a little fickle depending on which modules are changed.

2016-12-09 08:41 UTC, ulferts commented
> So my question is, are all datetimes represented as UTC internally? If not, well, then we really have a problem.

ActiveRecord will as of rails 3 (?) store all values as UTF values by default. If the [config](https://github.com/opf/openproject/pull/5071/files#diff-b1fe55db50c712fef0673345e5b9c0d9R123) specifies something differently, than of course, it would store it in a different time zone. As we didn't have that value set, it was UTC implicitly and with your change it will be UTC explicitly.

But that is only true if ActiveRecord is used. So for hand written SQL with DateTime objects, we have to ensure it ourself.

2016-12-09 08:46 UTC, ulferts commented
@silkentrance 

> any plans yet to make query objects and filter objects part of the HAL resource mechanism?

Yes, there are plans to replace the experimental API altogether by adding a `api/v3/queries` resource. But that will be one of the hardest ones to write so it might still be some time till we have it.

But of course the benefits will be huge with regards to:
* code quality
* performance
* API desirability
* reduced maintenance costs

Maybe with the timelines feature currently in development, there will be more reasons to build the resource than to add the required backend capabilities to the deprecated experimental API. That discussion is ongoing.

2016-12-09 13:04 UTC, ulferts commented
@silkentrance I haven't looked into the code but rather used the filters and took a look at the client server communication. Kudos for implementing all of the filters.

The client-server communication and your responses to my thoughts lead me to believe that we are not on par when it comes to how date and datetime filtering should be handled. Maybe it is just the complicit domain which lets me doubt everything I am thinking. In the following, I will therefore try to formulate a couple of theses I believe to be facts and it would help me a lot if you could let me know if you share my views on them. I hope they will then guide us to coming up with the correct solution.

### General
1) We have two different types of data in the database: Date and DateTime
2) "Start date", "Due date" and custom values of type "date" store values in the Date format.
3) "Created_at/on", "Updated_at/on" store values in the DateTime format.
4) DateTime objects have a timezone. The DateTime value "2016-12-09 08:00" describes a different thing depending on the time zone a user is in. But with time zone information, e.g. UTC "2016-12-09 08:00 UTC", the value will be 100% precise. 
5) Date objects do not have a timezone because they have no time. The date "2016-12-09" describes the same thing regardless of the time zone a user is in. (As such, defining "2016-12-09" to be the due date is imprecise, @lindenthal, regardless of whether talking to somebody in your time zone or to somebody in a different time zone. At the same time, the granularity of a date it is probably sufficient and the team will have to decide what it means. Forcing a time value as well would be to complicated)
6) Because Date and DateTime are different from one another, they can not be treated the same anywhere in the application. (The only exception to that is the presentation where both could use a DatePicker).
7) Because they are treated differently, we need to filter via a Date on "Start date", "Due date" and custom values of type "date" whereas we filter via DateTime on "Created_at/on" and "Updated_at/on".

### Date
8) Because Date values do not have a time and timezone, filtering with a time and timezone does not make sense. 
9) Because Date values have no time and timezone, the ruby application should not try to alter the value to take the user's local time into account.
10) Because Date values have no time and timezone, the JS application should not try to alter the value to take the user's local time into account.
11) Because the client application provides a Date which we use to filter by a Date against a Date value stored in the DB, the application will always return the same results regardless of a user's timezone. 
12) Because we have a Date value for "Start date", "Due date" and custom fields of format "date", we can simply use a date picker to select the value (or two for a span).
13) Because Date does not have a timezone and thus no transformations are performed on the value, the filter value will be displayed as the same for all users regardless of their timezone.

### DateTime
14) Because DateTime does have a time component and the timezone is important, filtering must take time differences between various users into account. 
15) The Ruby application should only deal with DateTime objects in the UTC timezone.
16) DateTime values are stored in UTC in the database.
17) Rails will take the local time unless specified differently (via `:utc` parameter) when using hand written sql.
18) The JS application should transform DateTime from the user's local time to UTC before talking to the API and backwards before presenting the API response to the user (via the UI).
19) Because of the transformation to UTC in the client application and because filtering is conducted with UTC values against values stored in UTC in the DB, the filter results will be the same for all users regardless of their respective time zones.
20) We can use a datepicker to select the filter value. 
21) Even if we use a datepicker, the value transmitted to the API will have to be a DateTime object so that we can filter by a DateTime object and take the time component into account.
22) Because of the transformation from UTC to the users local time, the Date which is interpolated for the datepicker from the DateTime provided by the API might be different for users of different time zones.

2016-12-13 12:12 UTC, silkentrance commented
@ulferts @oliverguenther 

Yes, you are correct in your assumption that the old, more experimental commit made no distinction between date values and datetime values. The latest commit, which also removes all of the experimental code, concentrates on the bare necessities and implements the requested feature as per your specification.

There is still a need to refactor the filters in general since the required changes, as you can see, add to the overall complexity of the code and make it more unreadable.

For the refactoring, I already begun working on that when it came to me that you might already have plans to move this into the HAL resource direction, so I stopped working on that for now. In addition, what is now a joint effort on behalf of both the client and the server in terms of responsibility for the actual filter data model (most of which is hard coded into the frontend) and where the backend is only responsible for custom field filters, should be made a single responsibility of the backend.

And, the date picker also needs some attention and should be implemented so that it becomes more reusable in terms of actual UI components. And, there is also the moment vs. JQuery UI picker format specifications, which are incompatible, missing calendar formats in the user settings, multiple date formats being used on the client (ISO vs. default) and so on.

2016-12-15 14:47 UTC, crohr commented
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/284115b1da6324a8970d11363576e3eee1cbd88e) (deployed commit: 5df0545d4d401d99cf53b54590a877d22c94aade).

2016-12-15 15:21 UTC, silkentrance commented
@crohr thanks for deploying this. however, i am not able to access the preview after having authorized PP to access parts of my GH account information.

2016-12-15 17:01 UTC, crohr commented
@silkentrance it's due to the fact that you're not (yet?) a member of the `opf` organization.
/cc @lindenthal

2016-12-15 17:56 UTC, crohr commented
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/4ebd7da4deb0eefb7362efbc709d0ac4a5b835c4) (deployed commit: 5df0545d4d401d99cf53b54590a877d22c94aade).

2016-12-17 18:04 UTC, silkentrance commented
@crohr okay, no problem, i can test this locally.

2016-12-19 13:39 UTC, crohr commented
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/991f01789eb4c2d69f027762732f7ba792458730) (deployed commit: 5df0545d4d401d99cf53b54590a877d22c94aade).

2016-12-21 09:57 UTC, closed without merging

2016-12-21 10:00 UTC, silkentrance commented
Opening up a new PR for this (renamed branch to feature-filter-by-date).