New settings: email_login, registration_footer
opf/openproject pull request #5095
Opened 2016-12-01 13:34 UTC by machisuji

Work in progress

<img width="1282" alt="email_login_and_registration_footer" src="https://cloud.githubusercontent.com/assets/158871/20795770/cedfde30-b7ca-11e6-8b5c-c86c2ba53e85.png">

2016-12-09 15:08 UTC, HDinger commented
There is a separate PR for the styling and the modal functionality which depends on this PR:
https://github.com/opf/openproject/pull/5105

2016-12-13 14:00 UTC, ulferts requested changes
Almost mergeable. Please see my tiny remarks.

2016-12-13 14:00 UTC, ulferts commented on spec/views/account/register.html.erb_spec.rb
> +      Setting.email_login = 0
Setting the values explicitly can have side effects with other tests.

It is therefore advisable to mock the value instead.

2016-12-13 14:00 UTC, ulferts commented on spec/views/account/register.html.erb_spec.rb
> +    it 'should render the emai footer' do
typo

2016-12-13 14:00 UTC, ulferts commented on spec/views/account/register.html.erb_spec.rb
> +      Setting.registration_footer = { "en" => footer }
Again, please mock `Setting.registration_footer`

2016-12-13 14:00 UTC, ulferts commented on app/helpers/accounts_helper.rb
> +    RedCloth3.new(footer).to_html if footer
`OpenProject::TextFormatting.format_text` is the OP spiced wrapper around RedCloth3 and should be used throughout the application.

2016-12-14 12:38 UTC, ulferts approved these changes

2016-12-14 12:39 UTC, merged