[24174] Allow users to filter work packages by date or range of date
opf/openproject pull request #5128
Opened 2016-12-21 13:30 UTC by silkentrance

Filter by date and date range.

https://community.openproject.com/work_packages/24174

See also previous PR under #5071

2016-12-21 13:33 UTC, silkentrance commented
@ulferts This includes the required tests, additional fixes and a little bit of refactoring.

@HDinger I managed to get the styles working as requested, however, in order to get this right, the whole grid layout of the filters needs to be redone. I am currently looking into foundation/grid model and see what I can come up with so that the filters become usable on phones and whatnot.

2016-12-21 18:31 UTC, silkentrance commented
Cleaning up, fixing newly introduced codeclimate issues.

2016-12-23 18:24 UTC, silkentrance commented
Rebased to current dev

2016-12-23 18:56 UTC, silkentrance commented
fixing specs

2016-12-23 20:57 UTC, silkentrance commented
hell, there a lot of redundant travisci test runs...

2016-12-27 18:38 UTC, silkentrance commented
@ulferts @lindenthal This now includes filtering by datetime / datetime ranges in the second commit. The tests for this are still missing, but you might want to have a look at it first and tell me your findings. I have used the RandomDataSeeder to create approx. 300 work packages with hourly advanced created_at dates and the filter seems to be working just fine across timezone boundaries.

In the UI, the displayed date will be adjusted to the user's (configured) local timezone while on the server it will make sure that all users see exactly the same results.

2016-12-29 14:31 UTC, silkentrance commented
@ulferts most code climate issues have been dealt with, the rest will require a more thorough refactoring and is beyond the scope of this PR.

2017-01-10 20:50 UTC, silkentrance commented
@ulferts all tests are failing due to

```
/home/travis/build/opf/openproject/app/models/queries/relations.rb:32:in `<module:Relations>': uninitialized constant Queries::Queries::Register
```

Has this been fixed?

2017-01-14 22:41 UTC, silkentrance commented
The following api endpoints have been removed

```
/api/experimental/projects/demo-project/work_packages?page=1&per_page=10
/api/experimental/projects/demo-project/queries/grouped
/api/experimental/projects/demo-project/queries/available_columns
```

This is the main reason that the tests are failing. I believe it is due to the overhaul of the query schema, so I will be patient :grinning:

2017-01-14 23:56 UTC, silkentrance commented
@ulferts some unrelated tests still fail (relations) but the rest seems to be working just fine. perhaps you will try and have a go with internal testing for this branch?

2017-01-16 13:57 UTC, ulferts requested changes
@silkentrance I still propose splitting up filtering by date and filtering by datetime.

The PR does currently consist of three parts:
* Filtering by date
* Filtering by datetime
* styling fixes 

From what I have seen, filtering by date is working fine and we should be able to merge it soon. There are some minor things, e.g. there is no concatenating word like "and" between the two dates when filtering in an interval, but all those could also be addressed after the initial merge.

Filtering by datetime is IMO still not working where the source of error is still to be found on the conceptual level as Datetime fields are still filtered by a Date value, which leads to the strange behaviour of a user not being able to use the filter at all when he is located somewhere with noticeable time difference e.g. the USA, Brazil, China as filter results are split seemingly arbitrarily (because the user will not understand that he would have to change his time zone setting to UTC in order to have the filters and their results aligned.)
Below is a screenshot of such a situation:
![image](https://cloud.githubusercontent.com/assets/617519/21985420/d988b330-dbfa-11e6-93b1-d268a7b3d2b0.png)
I have stopped testing the feature but on top of the problem I see with the approach taken, reloading the page would lead to loosing the filter.

In order to concentrate on the Datetime problem, we should split up the PR and get the date feature along with the styling fixes into dev first. Then, the code study at each time for the Datetime feature would be way less. Because of this, I have not yet taken a deeper look into the code again.

2017-01-16 17:36 UTC, silkentrance commented
@ulferts yes, the problem is communicating to the user that even though he enters a date, say, 2016-01-12 it is handled internally as a datetime object with timezone information, e.g. 2016-01-12T00:00:00-11:00. Similar for the range, however, here it will be two datetime objects, e.g. 2016-01-12T00:00:00-11:00 and 2016-01-12T23:59:59-11:00.

Now, what needs to be communicated to the user is that this will be converted to the server's local time zone and from these datetime object then the data will be filtered.

This also ensures that all users around the globe will get exactly the same result set.

For presentational purposes, datetime objects need to be displayed in the user's local timezone, then all datetime will be rendered correctly and you would no longer have the result from different dates problem.

As it is now, the implied UTC use case in the frontend, which I believe is a bad thing, will cause different dates to be shown.

If, on the other hand, the user configures a time zone in his or her settings, then the correct datetime will be shown.

So it is rather a question of why hold onto that implied UTC requirement when it clearly does not meet  real world requirements?

2017-01-17 07:44 UTC, ulferts commented
> @silkentrance I still propose splitting up filtering by date and filtering by datetime.

Can we please do that and then talk about the Datetime implementation?

2017-01-17 15:26 UTC, silkentrance commented
@ulferts This I can do, sure. However, I'd first like to see what I can do about the datetime impl, though. I think that I am determining the now() datetime object using just moment() instead of moment.utc(), which might lead to the observed problem. Let try to change that first, before going through the hustle of dissecting the individual changes.

2017-01-17 15:58 UTC, silkentrance commented
@ulferts the changes regarding datetime (range) filtering have been removed.

2017-01-17 16:00 UTC, silkentrance commented
@ulferts the changes for filtering datetime objects have been removed

2017-01-18 09:19 UTC, ulferts commented
@silkentrance ah, now I understand that this PR does now only contain the Date functionality. I was under the impression that this would be done by #5155. I'll take a look, then.

2017-01-18 09:41 UTC, ulferts requested changes
#### Unsupported operators for DateTime fields

The DateTime fields 'Updated on' and 'Created on' do still sport the 'on' and 'between' operators:

![image](https://cloud.githubusercontent.com/assets/617519/22058592/c845eb4a-dd69-11e6-9c6b-c468e9804301.png)

They should be removed for now until we are sure of how to support DateTime filtering correctly.

#### Console error

When selecting the 'on' or the 'between' operator, the following js error is logged:

![image](https://cloud.githubusercontent.com/assets/617519/22058740/57a5a21c-dd6a-11e6-82c3-e92f03b6450f.png)

There is probably required code in the removed commit.

2017-01-18 09:41 UTC, ulferts commented on frontend/app/components/filters/query-filters/query-filters.directive.html
> +      </div>
Didn't check the whole html tree but this `</div>` seems to be one to many.

2017-01-18 09:41 UTC, ulferts commented on app/models/queries/sql_for_field.rb
>    def date_range_clause(table, field, from, to)
We should cover this by tests

2017-01-18 23:04 UTC, silkentrance commented
Ups, nice find. These changes have been undone. As for the tests, I will implement these ASAP, but not this night :grin:

2017-01-18 23:06 UTC, silkentrance commented
@ulferts it seems that the existing tests do not cover such issues like for example missing operators and the frontend handling these missing operators, at all.

2017-01-19 13:34 UTC, ulferts approved these changes

2017-01-19 13:34 UTC, ulferts commented
👍

2017-01-19 13:34 UTC, merged