Fix #24417 force login for new WP in public project
opf/openproject pull request #5264
Opened 2017-03-20 15:58 UTC by wielinde

Quick and not very holistic solution.

It uses a direct redirect to the sign in page.

It might be better to already check the authorization within Rails and before rendering the WP index page.

However, given the low risk of that feature and the relatively small value I opted for a quick solution

2017-03-20 18:50 UTC, wielinde commented
Added a feature spec. However an old feature spec is failing (`as a user with no permissions`). I wonder what to do with it.

2017-03-21 12:46 UTC, crohr commented
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/571adc5748bdd4ac1f6b74187ab0f21805090ebc) (deployed commit: aeffd023d43102bbfccd94d3155b02db57e2f9de).

2017-03-22 11:43 UTC, ulferts requested changes

2017-03-22 11:43 UTC, ulferts commented on frontend/app/components/wp-create/wp-create.controller.ts
> +          window.location.href = loginUrl;
I believe you should double check to make sure that the user is actually not logged in and not only lacking permissions despite being logged in. If it is the later, redirecting to the login page will cause confusion. 

I think that this scenario is causing the spec failure you reported.

To double check, you'd have to fetch the root resource (/api/v3) which will have a user link if the user is logged in.

2017-03-22 12:48 UTC, wielinde commented
Absolutely right! Thanks for the hint.

On Wed, Mar 22, 2017, 12:43 ulferts <notifications@github.com> wrote:

> *@ulferts* requested changes on this pull request.
> ------------------------------
>
> In frontend/app/components/wp-create/wp-create.controller.ts
> <https://github.com/opf/openproject/pull/5264#discussion_r107392529>:
>
> > @@ -97,7 +99,15 @@ export class WorkPackageCreateController {
>              });
>          }
>        })
> -      .catch(error => this.wpNotificationsService.handleErrorResponse(error));
> +      .catch(error => {
> +        if (error.errorIdentifier == "urn:openproject-org:api:v3:errors:MissingPermission") {
> +          let url: string = $location.absUrl();
> +          $location.path('/login').search({back_url: url});
> +          let loginUrl: string = $location.absUrl();
> +          window.location.href = loginUrl;
>
> I believe you should double check to make sure that the user is actually
> not logged in and not only lacking permissions despite being logged in. If
> it is the later, redirecting to the login page will cause confusion.
>
> I think that this scenario is causing the spec failure you reported.
>
> To double check, you'd have to fetch the root resource (/api/v3) which
> will have a user link if the user is logged in.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opf/openproject/pull/5264#pullrequestreview-28359499>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAT-aNLa1hBeLB9Jh1wtuBjTgWEU4ubWks5roQlqgaJpZM4Miojy>
> .
>

2017-04-03 06:35 UTC, ulferts commented on frontend/app/components/wp-create/wp-create.controller.ts
> +          this.halRequest.get(this.v3Path.root()).then((root:HalResource) => {
After merging #5219 you can now simply use the [root resource dm](https://github.com/opf/openproject/blob/dev/frontend/app/components/api/api-v3/hal-resource-dms/root-dm.service.ts#L38) like this (after importing):

```
this.RootDm.load().then((root:RootResource) => {
...
```

2017-04-03 06:35 UTC, ulferts commented on frontend/app/components/api/api-paths/api-paths.config.ts
> +    root
This is no longer necessary as #5219 added those lines already.

2017-04-07 15:06 UTC, ulferts commented
👍

2017-04-07 15:07 UTC, merged