Provide configuration option for basic auth API access
opf/openproject pull request #5278
Opened 2017-03-24 12:31 UTC by oliverguenther

This adds:

1. A configuration option `apiv3_enable_basic_auth` to determine whether v3 may use the basic auth strategies
2. Extensions to the warden strategies to disable them unless configured

2017-04-06 08:41 UTC, machisuji requested changes
I suggest enabling it by default.

2017-04-06 08:41 UTC, machisuji commented on lib/open_project/configuration.rb
> +      'apiv3_enable_basic_auth' => false,
Why would we want to disable it by default?

2017-04-06 12:52 UTC, oliverguenther commented
@machisuji Okay, I've enabled it by default now.

2017-04-07 11:15 UTC, machisuji commented
👍

2017-04-07 11:15 UTC, merged