[24907] Internal error on member page in access. mode (when pressing "Enter")
opf/openproject pull request #5285
Opened 2017-03-28 07:50 UTC by HDinger

This avoids a from submit when pressing enter within the member autocompleter.

https://community.openproject.com/projects/openproject/work_packages/24907/activity

2017-03-28 13:54 UTC, oliverguenther requested changes

2017-03-28 13:54 UTC, oliverguenther commented on frontend/app/components/common/remote/remote-field-updater.directive.ts
> +        let keyCodes = [9, 13, 16]
you can use the TypeScript helper `[keyCodes.TAB, keyCodes.ENTER, keyCodes.LEFT_ARROW]` here instead to make it clear which codes are being used.

2017-03-28 13:54 UTC, oliverguenther commented on app/views/members/_member_form_impaired.html.erb
> +                                      onkeypress: "return event.keyCode != 13;" %>
Why do you need the additional return here?

2017-03-28 14:03 UTC, HDinger commented on app/views/members/_member_form_impaired.html.erb
> +                                      onkeypress: "return event.keyCode != 13;" %>
Because keypress seems to be favored over keydown. Thus we need to over both cases. (http://stackoverflow.com/a/1977126)

2017-03-29 11:44 UTC, oliverguenther commented on app/views/members/_member_form_impaired.html.erb
> +                                      onkeypress: "return event.keyCode != 13;" %>
Weird, okay. Thanks for the clarification!

2017-03-29 11:44 UTC, oliverguenther approved these changes

2017-03-29 11:44 UTC, merged