[24575] Instrument timeline visibility state through query
opf/openproject pull request #5318
Opened 2017-04-04 12:46 UTC by oliverguenther

https://community.openproject.com/work_packages/24575

2017-04-05 07:04 UTC, oliverguenther commented on frontend/app/helpers/angular-rx-utils.ts
> +      s.next(scope);
/cc @romanroe This caused errors when moving between (UI router) states due to the `scopedDestroyed$` raising errors.

2017-04-05 07:08 UTC, oliverguenther commented on frontend/app/components/api/api-v3/hal-resource-dms/payload-dm.service.ts
> +      if (resource.hasOwnProperty(property)) {
/cc @ulferts This caused saving a query with any `false` value (e.g., `displaySums: false` or, in this case, timelineVisible) to ignore that value.

2017-04-05 13:12 UTC, ulferts requested changes
Added functionality looks good. No Bugs detected. 

What is missing in my opinion:
* The timeline state is not reflected in the url. Therefore, the user can not send the url and expect the receiver to see what he is seeing. It also means that upon reloading, the timeline will be closed.
* unit tests on the query model, query (payload/schema) representers

2017-04-05 13:12 UTC, ulferts commented on db/migrate/20170404110156_extend_query_model.rb
> +    add_column :queries, :timeline_visible, :boolean, default: false
Just a matter of taste but I'd prefer it to be called simply `timeline`

2017-04-05 13:12 UTC, ulferts commented on frontend/app/components/api/api-v3/hal-resource-dms/payload-dm.service.ts
> +      if (resource.hasOwnProperty(property)) {
Thanks

2017-04-06 06:55 UTC, oliverguenther commented on db/migrate/20170404110156_extend_query_model.rb
> +    add_column :queries, :timeline_visible, :boolean, default: false
We'll likely have more timeline related properties (zoom level and whatnot) soon so I don't think thats a good idea.

2017-04-06 08:59 UTC, oliverguenther commented
I've added more tests and the timeline attribute is now part of the query_props URL.

2017-04-06 11:01 UTC, crohr commented
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/b7a63280ab94431b6c70b600747d8703c0d6a794) (deployed commit: b6555be667177770bb645be8b97cad919aa39fc1).

2017-04-06 13:46 UTC, crohr commented
A new preview environment is ready! [Click to open](https://pullpreview.com/opf/openproject/sessions/143ce288cbd3228a7651fa7dea91c2662b8cc467) (deployed commit: 931ced89347c72caa891b044e0a57e3576ecb486).

2017-04-07 06:48 UTC, oliverguenther commented
I've extracted the unrelated failing spec into https://github.com/opf/openproject/pull/5327

2017-04-07 13:29 UTC, ulferts approved these changes

2017-04-07 13:29 UTC, merged