Feature #24911 Add "Configure form" link to "more" menu for admins
opf/openproject pull request #5326
Opened 2017-04-06 15:53 UTC by wielinde

https://community.openproject.com/projects/openproject/work_packages/24911

2017-04-07 11:30 UTC, oliverguenther requested changes

2017-04-07 11:30 UTC, oliverguenther commented on lib/api/v3/work_packages/work_package_representer.rb
> +            href: 'custom-fields',
I'd prefer If we pass the correct path here instead of putting it together in the frontend.

2017-04-07 11:30 UTC, oliverguenther commented on lib/api/v3/work_packages/work_package_representer.rb
> +            href: 'form-configuration',
same here

2017-04-07 11:30 UTC, oliverguenther commented on lib/api/v3/work_packages/work_package_representer.rb
> +        link :'configure-form' do
Please use `adminConfigureForm` instead.

2017-04-07 11:30 UTC, oliverguenther commented on lib/api/v3/work_packages/work_package_representer.rb
> +        link :'custom-fields' do
Please use `projectCustomFields` instead

2017-04-07 11:31 UTC, oliverguenther commented on lib/api/v3/work_packages/work_package_representer.rb
> +            title: "Custom fields"
If you use the translation as the title, you won't have to provide translations in the frontend.

2017-04-11 09:10 UTC, wielinde commented on lib/api/v3/work_packages/work_package_representer.rb
> +            title: "Custom fields"
@oliverguenther Are you sure? Wouldn't it have to show "Custom fields" just like that (without any I18n)? However, it shows an translation error.

2017-04-11 09:11 UTC, wielinde commented on lib/api/v3/work_packages/work_package_representer.rb
> +            href: 'custom-fields',
This is in order to comply with the CSS icon class.

2017-04-11 09:21 UTC, wielinde commented on lib/api/v3/work_packages/work_package_representer.rb
> +        link :'custom-fields' do
@oliverguenther This is in order to comply with the CSS icon class. Further, I appears to me, that is used to find the translation key, which actually seems to be applied on the frontend and not on the backend side. I could not get and backend side translation to work.

2017-04-11 13:24 UTC, oliverguenther approved these changes

2017-04-11 13:25 UTC, oliverguenther commented
I've pushed a change to display icons and also added the two links to the representer spec. Rest LGTM

2017-04-11 18:24 UTC, merged