[25706] Custom attribute help texts
opf/openproject pull request #5729
Opened 2017-07-04 08:02 UTC by oliverguenther

Allows users to define custom help text per scope (currently, work packages only).

**TODOS**

- [X] Implement backend CRUD view to create global help texts
- [ ] Implement global API to retrieve all texts, grouped by scope
- [ ] Create frontend directive to render help text, given scope and attribute.
- [ ] Render preview in backend with API

**Out of scope**

- Override global help texts locally (i.e., per work package type). This is blocked by [#25706](https://community.openproject.com/projects/openproject/work_packages/25706)

https://community.openproject.com/projects/openproject/work_packages/25706

2017-07-05 09:25 UTC, ulferts requested changes
### General
Pretty straight forward implementation. From a user perspective I was quite confused with some of the attributes that I could assign help texts to, but that did not have means to display those help texts (e.g. ID, subject)

### Usability
The dialog opened when clicking the help text icon can not be closed by the keyboard as pressing enter on the "Close" button will reopen the dialog right away. 

### Accessibility

![image](https://user-images.githubusercontent.com/617519/27857305-732a8b48-6171-11e7-9b33-b6c653f9efd2.png)

In the wp show view, the icon to trigger the help to be displayed is placed before the attribute and only reads "Show attribute help text entry". A user going through the page with a screen reader will not know which attribute is meant here. 

The modal opened is also not accessible. Although it does have the role `alterdialog` at least chromevox does not read out the content and the user has no possibility to focus on the text.

2017-07-05 09:25 UTC, ulferts commented on app/models/attribute_help_text.rb
> +  def self.used_attributes(scope)
Not a big deal but it strikes me weird to name the variable scope in a method that returns a scope. Especially since it is the type internally.

2017-07-05 12:49 UTC, oliverguenther commented
> The dialog opened when clicking the help text icon can not be closed by the keyboard as pressing enter on the "Close" button will reopen the dialog right away.

There's a really weird bubbling from the close event handler to the element that receives focus afterwards. I now override the close function to stop the KeyEvent from bubbling and that seems to help.

> In the wp show view, the icon to trigger the help to be displayed is placed before the attribute and only reads "Show attribute help text entry". A user going through the page with a screen reader will not know which attribute is meant here.

I've tested this with Jaws and VoiceOver and they both report `<Attribute> (required) Show attribute help text entry`. 

The modal body is now focussable and receives the focus from ngDialog. Jaws reads out the entire dialog due to `role=alertdialog`.

> . From a user perspective I was quite confused with some of the attributes that I could assign help texts to, but that did not have means to display those help texts (e.g. ID, subject)

I now restrict the available attributes to those the type returns plus the two special fields status and project. That corresponds with the current implementation that disallows columns to receive a help text, but we may want to extend this later on.

2017-07-07 07:32 UTC, ulferts commented
> I've tested this with Jaws and VoiceOver and they both report <Attribute> (required) Show attribute help text entry.

I've tested it with ChromeVox and it does not read out the `<Attribute> (required)` part there. But as Jaws is the Benchmark it should be fine.

2017-07-07 07:33 UTC, ulferts approved these changes

2017-07-07 07:33 UTC, merged