[25490] Add publicity settings for query saving modal
opf/openproject pull request #5737
Opened 2017-07-06 15:01 UTC by oliverguenther

When copying queries, the publicity for other members is copied, but not
the query `star` setting (whether it is shown in the project menu or not).

This is confusing to the user in two ways:

1. The user does not know whether a query is public or not when copying it

2. It is weird to copy one setting, but not the other

This PR suggests to extend the `save as` modal with the visibility settings. To this end, I extracted the visibility form into a separate directive to be re-used from the publish/sharing modal and the save as modal.

![bildschirmfoto 2017-07-06 um 16 57 23](https://user-images.githubusercontent.com/459462/27917576-a9cb3bce-626c-11e7-818f-03c1186c7aec.png)

As://community.openproject.com/projects/openproject/work_packages/25490

2017-07-11 08:53 UTC, ulferts requested changes
### General
I for one like the change. I never liked having the query added automatically, and even worse, copying over the visibility setting. There where too many queries I have seen copied by others that where not intended to be shared.

But opinions can differ here, so maybe @lindenthal and @RobinWagner  can provide their opinion as well. 

### Bug:
![image](https://user-images.githubusercontent.com/617519/28060217-d9d67f82-6626-11e7-8eac-5b387cb8d230.png)

When saving the query initially, I cannot select the "show page in menu" option

2017-07-11 08:53 UTC, ulferts commented on config/locales/js-en.yml
>          share: "Share ..."
This translation key can probably be removed then.

2017-07-11 15:36 UTC, oliverguenther commented
This idea originated from a discussion with @wielinde , so I can safely assume he's on the pro side for this change.

2017-07-11 15:45 UTC, wielinde commented
Love it!

2017-07-11 15:49 UTC, oliverguenther commented
Fixed the bug, it was caused by the default query not having star/unstar permissions. I now assume that if you're able to save the query, you can star it as well (which the permission currently reflects).

2017-07-12 08:03 UTC, ulferts approved these changes

2017-07-13 14:38 UTC, RobinWagner commented
I like the change. Makes a lot of sense.

2017-07-14 06:08 UTC, lindenthal commented
@oliverguenther your change makes it much easier to understand. I like it.

2017-07-14 06:20 UTC, merged