Show parent's validation errors when saving child fails
opf/openproject pull request #6327
Opened 2018-05-18 08:40 UTC by machisuji

2018-05-18 10:07 UTC, machisuji commented
@ulferts Still need to use i18n and add tests but the essential fix is there.

2018-05-18 11:23 UTC, ulferts requested changes
It's probably a good enough approach but there are a couple of limitations:

* This will merge all errors to a single work package when in fact multiple work packages can be affected (e.g. the parent). But this would require us to redesign the error response.
* Because of that limitation, it will be harder for clients (especially non user clients) to actually process the error when all errors are assigned to the field of one work package.
* The approach here is currently limited to the `patch` method when the `post` could be equally affected. As such it would make sense to extract the code into some form of shared code.

Only the last of my points needs to be addressed before merging.

2018-05-25 12:12 UTC, machisuji commented
@ulferts The errors in the creation case are handled too now.

2018-05-25 13:19 UTC, ulferts approved these changes

2018-05-25 13:20 UTC, merged