notify admins if user could not activate due to the user limit
opf/openproject pull request #6373
Opened 2018-06-20 12:44 UTC by machisuji

WP [#27887](https://community.openproject.com/projects/openproject/work_packages/27887/activity?query_id=1315)

2018-06-20 14:24 UTC, ulferts commented on app/controllers/account_controller.rb
> +      send_activation_limit_notifcation_about user
spelling: `send_activation_limit_notifi[i]cation_about`

2018-06-20 14:25 UTC, ulferts commented
:+1:

2018-06-21 08:48 UTC, ulferts requested changes
Functionality is looking good. 

Please see my remarks for details on code improvements.

2018-06-21 08:48 UTC, ulferts commented on app/views/user_mailer/activation_limit_reached.html.erb
> +    <% host_link = "<a href=\"#{host}\">#{Setting.host_name}</a>" %>
This should rather be `Setting.app_title`

2018-06-21 08:48 UTC, ulferts commented on app/views/user_mailer/activation_limit_reached.html.erb
> +            <a href="<%= OpenProject::Enterprise.upgrade_url %>">here</a>
missing I18n for `here` and while you are at it, it would probably make sense to include the anchor tag in the `steps.a` localization string so that the position of the link can be different in different languages

2018-06-21 08:48 UTC, ulferts commented on app/views/user_mailer/activation_limit_reached.html.erb
> +            <a href="<%= users_url %>">here</a>
See above

2018-06-21 08:48 UTC, ulferts commented on app/views/user_mailer/activation_limit_reached.text.erb
> +<%= t("mail_user_activation_limit_reached.message", email: @email, host: Setting.protocol + "://" + Setting.host_name) %>
Seeing you doing this for the second time `Setting.protocol + "://" + Setting.host_name` it would probably make sense to extract it into a helper or separate method on `Setting`.

2018-06-21 14:01 UTC, ulferts commented on app/views/user_mailer/activation_limit_reached.html.erb
> +            <% a = "<a href=\"<%= OpenProject::Enterprise.upgrade_url %>\">here</a>" %>
the `here` is still not i18ned

2018-06-22 07:46 UTC, machisuji commented
@ulferts now it is!

2018-06-22 10:51 UTC, ulferts approved these changes

2018-06-25 07:08 UTC, merged