[28349] Download recent version of pandoc if needed
opf/openproject pull request #6563
Opened 2018-08-22 07:01 UTC by oliverguenther

https://community.openproject.com/projects/openproject/work_packages/28349/activity

2018-08-22 08:04 UTC, machisuji requested changes
Looking good. I do have some remarks, though.

2018-08-22 08:04 UTC, machisuji commented on lib/open_project/text_formatting/formats/markdown/pandoc_downloader.rb
> +          'https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-linux.tar.gz'
It would be good, if one could override this URL via an ENV var as well.

2018-08-22 08:04 UTC, machisuji commented on lib/open_project/text_formatting/formats/markdown/pandoc_downloader.rb
> +          tempfile = response.file
This needs error handling. Ideally the user would be informed that the setup is about to download pandoc and from where (the configured URL). When it fails for what ever reason an error should be shown that the download failed. Maybe a pointer to OPENPROJECT_PANDOC_PATH to allow for manual installation would be good here too. And also one to the var allowing to change the download URL.

2018-08-22 08:04 UTC, machisuji commented on lib/open_project/text_formatting/formats/markdown/pandoc_downloader.rb
> +          return if ENV['OPENPROJECT_PANDOC_PATH'] || executable?
We should also check the version and require one `>= 2.0` since we know there are issues with 1.12 and 1.16 at least.

2018-08-22 11:28 UTC, oliverguenther commented
@machisuji I think I have addressed all remarks you have posted.

2018-08-24 12:16 UTC, machisuji requested changes
Thanks, yes you have addressed all my concerns. Just this one text fragment has to be fixed then we can merge it.

2018-08-24 12:16 UTC, machisuji commented on docs/user/textile-to-markdown-migration/README.md
> +If you want to force a specific version within your path
... then what? :P I think something' missing here.

2018-08-24 12:16 UTC, machisuji commented
@oliverguenther Also this has to be rebased, please.

2018-08-27 05:40 UTC, merged

2018-08-27 05:41 UTC, oliverguenther commented
Thanks @machisuji , I've just done that