[28712] Application not responsive for a particular screen size
opf/openproject pull request #6774
Opened 2018-10-23 13:31 UTC by ingamai

## Problem
There is an unresponsive behaviour of the application for a particular screen size right before the breakpoint of the mobile layout, which is causing a horizontal scroll bar. So this is especially for the tablet sizes a problem.

## To-Do's

- [ ] Remove min-width
   - [ ] Tests in Chrome, Firefox, Opera and MSEdge
- [ ] Include new breakpoint for toolbar

https://community.openproject.com/projects/openproject/work_packages/28712

2018-10-24 08:21 UTC, HDinger requested changes
Although the LoC are rather small this is a larger change as it affects all pages. There are different issues coming up:

* There are pages which are not completely responsive and behave strange in that gap. Before there was the min-width and a scrollbar which was not modern but worked. Right now some parts of the pages behave responsive, others don't. This results in a strange look, e.g at the calendar the filter section is responsive, the calendar not. Or at the WP page the behavior is the other way around: The filter is not responsive, but the table is.
<img width="429" alt="bildschirmfoto 2018-10-24 um 10 12 32" src="https://user-images.githubusercontent.com/7457313/47416155-5a3ea300-d775-11e8-9e81-33fe33f61018.png">
<img width="430" alt="bildschirmfoto 2018-10-24 um 09 51 01" src="https://user-images.githubusercontent.com/7457313/47416286-a984d380-d775-11e8-8d00-1c347dfcfb06.png">


* The toolbar causes multiple problems:
<img width="405" alt="bildschirmfoto 2018-10-24 um 09 50 39" src="https://user-images.githubusercontent.com/7457313/47416211-793d3500-d775-11e8-9de9-f076bc987c44.png">
<img width="420" alt="bildschirmfoto 2018-10-24 um 09 53 12" src="https://user-images.githubusercontent.com/7457313/47416419-f8cb0400-d775-11e8-9f3b-b299a4c01506.png">
<img width="457" alt="bildschirmfoto 2018-10-24 um 09 54 10" src="https://user-images.githubusercontent.com/7457313/47416429-fd8fb800-d775-11e8-902a-6cdbd049a9b0.png">

* And there are other parts
 
<img width="474" alt="bildschirmfoto 2018-10-24 um 09 55 18" src="https://user-images.githubusercontent.com/7457313/47416468-139d7880-d776-11e8-8c7b-ce4ede6cb90c.png">
<img width="341" alt="bildschirmfoto 2018-10-24 um 10 16 45" src="https://user-images.githubusercontent.com/7457313/47416492-1f893a80-d776-11e8-83ba-00f4f48b92f4.png">

I do not think that we can close this gap without introducing a new breakpoint for tablet size devices and add at least some styles for that specific screen size. We do that already for the WP page. If we want to do it right, we should do it for other pages, too.

2018-10-24 08:21 UTC, HDinger commented on frontend/src/app/components/wp-query-select/wp-query-selectable-title.sass
> +  overflow: hidden
You can use `@include text-shortener` for this block.

2018-10-24 08:21 UTC, HDinger commented on app/assets/stylesheets/layout/_toolbar.sass
> +  overflow: hidden
This leads to something like this:
<img width="424" alt="bildschirmfoto 2018-10-24 um 10 06 29" src="https://user-images.githubusercontent.com/7457313/47415746-7ee64b00-d774-11e8-8735-de798a578da8.png">

2018-11-02 09:15 UTC, HDinger reviewed
Hey @ingamai , looks pretty good by now 👍 But is it possible that you forget to remove the `min-width`? 😅 

I did a short tour through only the core in Chrome (with the removed min-width) and found some minor issues. I did not check the plugins and other browsers. 
### Missing scrollbars
*  in the filter section
<img width="486" alt="bildschirmfoto 2018-11-02 um 09 20 45" src="https://user-images.githubusercontent.com/7457313/47904578-96fd4f00-de85-11e8-93fd-e954a1a2d710.png">

* in the repository statistics
<img width="681" alt="bildschirmfoto 2018-11-02 um 09 31 51" src="https://user-images.githubusercontent.com/7457313/47904669-b4321d80-de85-11e8-8793-eba52da4f3bc.png">

* notifications (although I would recommend to let the notification shrink instead of a scrollbar)
<img width="681" alt="bildschirmfoto 2018-11-02 um 09 22 25" src="https://user-images.githubusercontent.com/7457313/47905030-5a7e2300-de86-11e8-9559-703149ff50d5.png">


### Breakpoints?
There are places where a breakpoint might be useful (?). Although I really like that you managed to do it without them by now. However for the modal we could think of using one (or just increasing the mobile one?). As the modal lays above the content it is independent and could orient itself towards the width. We can discuss this on Monday if you want to.
<img width="678" alt="bildschirmfoto 2018-11-02 um 09 21 04" src="https://user-images.githubusercontent.com/7457313/47904955-2acf1b00-de86-11e8-99ff-9023347c941f.png">

### Misalignments
* For many checkbox there is a unnecessary line break. It does not happen for all but for many causing an ugly layout.
<img width="479" alt="bildschirmfoto 2018-11-02 um 09 36 22" src="https://user-images.githubusercontent.com/7457313/47905096-8bf6ee80-de86-11e8-8fcd-c358f6b714d9.png">

* On the WP full view the current layout shows everything correctly but looks quite ugly. Maybe we could move the back button up to the toolbar and let the rest span the whole width. I am aware that this is not easy. However since this is quite an important page we should think of a better solution. 
<img width="678" alt="bildschirmfoto 2018-11-02 um 09 26 53" src="https://user-images.githubusercontent.com/7457313/47905411-63bbbf80-de87-11e8-9f16-41611b95e381.png">

### Further stuff
<img width="714" alt="bildschirmfoto 2018-11-02 um 09 28 07" src="https://user-images.githubusercontent.com/7457313/47905143-a6c96300-de86-11e8-88a9-0482927bebba.png">
-------------------------------------------------------
<img width="489" alt="bildschirmfoto 2018-11-02 um 09 30 34" src="https://user-images.githubusercontent.com/7457313/47905150-ab8e1700-de86-11e8-988a-36c9f9eb9b2a.png">
-------------------------------------------------------
<img width="687" alt="bildschirmfoto 2018-11-02 um 09 39 36" src="https://user-images.githubusercontent.com/7457313/47905356-38d16b80-de87-11e8-97c8-280eb4b2a81e.png">

-------------------------------------------------------
<img width="686" alt="bildschirmfoto 2018-11-02 um 09 41 15" src="https://user-images.githubusercontent.com/7457313/47905190-c5c7f500-de86-11e8-9e8f-de053b4c04e9.png">
-------------------------------------------------------
<img width="685" alt="bildschirmfoto 2018-11-02 um 09 42 00" src="https://user-images.githubusercontent.com/7457313/47905206-ccef0300-de86-11e8-9d74-20a93f5bb839.png">
-------------------------------------------------------
<img width="688" alt="bildschirmfoto 2018-11-02 um 09 44 28" src="https://user-images.githubusercontent.com/7457313/47905225-d7110180-de86-11e8-894c-a87855bcffae.png">


* When I tested in the browsers mobile functionality there was a strange gap at the bottom. This was not there when I just resized the window to the same size. Maybe this is an issue with Chromes mobile functionality. Could you please also check with a real mobile device?

I did not look through the code in detail but I really like that you made use of flex boxes and could avoid breakpoints until here 👍

2018-11-02 09:15 UTC, HDinger commented on app/assets/stylesheets/content/_modal.sass
> +  width: fit-content
I don't know whether this is supported by all browsers (especially Edge). Could you please check? Feel free to resolve this when it is supported.

2018-11-05 08:09 UTC, ingamai commented on app/assets/stylesheets/content/_modal.sass
> +  width: fit-content
Your are right, unfortunately this is not supported by Edge and IE. I will try to replace this.

https://caniuse.com/#search=fit-content

2018-11-15 07:10 UTC, HDinger approved these changes

2018-11-15 07:11 UTC, merged

2018-11-15 07:14 UTC, HDinger commented
Good job 👍 Looks much better now and we did not add that many new lines! :)