Upgrade to Rails 5.2
opf/openproject pull request #6814
Opened 2018-11-05 19:49 UTC by oliverguenther

2018-12-18 15:04 UTC, oliverguenther commented
The deprecations will still need to be handled, however I'm not yet sure how to best approach them since there is no best practice yet for delegating to Arel but retaining a AR scope for later user.

2019-01-08 10:31 UTC, ulferts requested changes
Looks almost mergeable to me (please see my code remarks for details).

I'm for merging this first and then fixing the deprecations.

2019-01-08 10:31 UTC, ulferts commented on Gemfile
> +  # gem 'rspec-legacy_formatters', '~> 1.0.1', require: false
remove, please

2019-01-08 10:31 UTC, ulferts commented on config/storage.yml
> +# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
Let's rather remove the commented out code before somebody gets any ideas.

2019-01-08 10:31 UTC, ulferts commented on config/initializers/new_framework_defaults_5_2.rb
> +Rails.application.config.active_support.use_sha1_digests = true
I'd rather have this in the application.rb with all the rest of the generic config stuff.

2019-01-08 10:31 UTC, ulferts commented on config/storage.yml
> +  root: <%= Rails.root.join("storage") %>
It used to be `files`, right? Will we run into any problems because of that change for existing instances (expected symlinks or the like)?

2019-01-08 10:31 UTC, ulferts commented on lib/generators/open_project/plugin/templates/%full_name%.gemspec.tt
> -  s.add_dependency "rails", "~> 5.0"
:+1:

2019-01-08 10:31 UTC, ulferts commented on config/initializers/30-redmine.rb
> -require 'chili_project'
👍 and now the redmine stuff as well.

2019-01-08 13:04 UTC, ulferts approved these changes

2019-01-08 13:21 UTC, merged