[29003] Add PATCH api/v3/time_entries/:id endpoint
opf/openproject pull request #6828
Opened 2018-11-14 20:30 UTC by oliverguenther

Adds updating time entries to APIv3.

https://community.openproject.com/wp/29003

2018-11-15 08:17 UTC, ulferts requested changes
Functionality is looking good 👍 

Please see my tiny remarks regarding the code.

Speaking of code, there are bonus points available for grab for moving the [validations from the model to the contract](https://github.com/opf/openproject/blob/dev/app/models/time_entry.rb#L113-L123)

2018-11-15 08:17 UTC, ulferts commented on app/services/time_entries/update_service.rb
> +      end
```suggestion
      time_entry.errors.empty? && time_entry.save
```

2018-11-15 08:17 UTC, ulferts commented on app/services/time_entries/update_service.rb
> +      time_entry.errors.add :work_package_id, :invalid
I don't get why this cannot be moved into the contract. There is a comment there trying to explain it but I still don't get it. Can you enlighten me @oliverguenther.

If it can be moved into the contract, one should also be able to get rid of the `validate_and_yield`

2018-11-15 08:17 UTC, ulferts commented on docs/api/apiv3/endpoints/time_entries.apib
> ++ Request Create time entry
'Create' is wrong here

2018-11-15 08:17 UTC, ulferts commented on docs/api/apiv3/endpoints/time_entries.apib
> +                "id": 123,
`id` should not be part of the request as it is not writeable

2018-11-19 07:35 UTC, oliverguenther commented on app/services/time_entries/update_service.rb
> +      time_entry.errors.add :work_package_id, :invalid
It's already part of the base contract, and is due to the errors from the contract are not available once you render the form for marking errors of fields and providing error details.

2018-11-19 11:48 UTC, ulferts approved these changes

2018-11-19 11:48 UTC, merged

2018-12-30 08:51 UTC, vgladiyenko commented
Thanks for implementing this feature, but would whoever is responsible mind updating the API documentation too? [PATCH section](http://docs.openproject.org/apiv3-doc/#time-entries-time-entries-patch) is kinda a copy paste from POST and I had to find this PR in order to find out how this endpoint works. Thanks again.