Feature/apiv3/time entries
opf/openproject pull request #6833
Opened 2018-11-16 16:55 UTC by fupduck

based upon https://github.com/opf/openproject/pull/6828
tries to reflect the requested changed by @ulferts 
I added a DELETE for time entries.

I did not find an `delete_time_entry` permission therefore used `edit_time_entry` - is this the correct way to go?

I hope this is somewhat complete and helps - I wrote ruby the last time 9 years ago…

Any comments appreciated!

Many thanks @oliverguenther for taking time for our request.

References issues:
https://community.openproject.com/projects/openproject/work_packages/29003/activity
https://community.openproject.com/projects/openproject/work_packages/29029/activity

2018-11-16 17:59 UTC, fupduck commented
sorry for all the commits - plz squash when merging 😅

2018-11-19 07:32 UTC, oliverguenther commented
Hi @fupduck , thanks for the effort. `edit_time_entries` is correct. You can see the mapping of permissions to controller actions in `config/initializers/permissions.rb`, which includes `destroy` for that permission.

2018-11-19 10:43 UTC, ulferts requested changes
First of all, @fupduck, thanks for building that end point, it is very much appreciated.

I skimmed over the PR and made notes where I see problems right away but didn't go into too many details as the PR you are building on by @oliverguenther has been rebased and I also issued another PR against Oliver's.

So once those base branches are consolidated, you should rebase on that. I'll post a message once that has happened.

2018-11-19 10:43 UTC, ulferts commented on app/policies/work_package_policy.rb
> +                      delete_allowed?(work_package)
As this is the work_package_policy, changing it in the scope of this PR looks quite fishy. I suspected this happened on a bulk search&replace.

2018-11-19 10:43 UTC, ulferts commented on .gitignore
> +/vendor/bundle
Why this?

2018-11-19 10:43 UTC, ulferts commented on app/services/time_entries/delete_service.rb
> +    time_entry.destroy
```suggestion
    validate_and_yield(time_entry, user) do
      time_entry.destroy
    end  
```

Without the `validate_and_yield` the contract is not actually used.

2018-11-19 10:43 UTC, ulferts commented on app/services/time_entries/update_service.rb
> -  end
This needs to stay

2018-11-19 11:15 UTC, fupduck commented
Thanks for the headsup.
Let me know when I can continue.

2018-11-19 11:50 UTC, ulferts commented
@fupduck #6828 is in the dev branch now.

2018-11-20 10:24 UTC, fupduck commented on app/policies/work_package_policy.rb
> +                      delete_allowed?(work_package)
thanks

2018-11-20 10:44 UTC, fupduck commented
Thanks for your support and your comments @ulferts and @oliverguenther 
Find the squashed and rebased MR here: !6843
I hope I have adressed all open issues.

2018-11-20 10:44 UTC, closed without merging