[29029] DELETE option for TimeEntries
opf/openproject pull request #6843
Opened 2018-11-20 10:44 UTC by fupduck

This is !6833 rebased upon the dev branch.

This adds a DELETE option for TimeEntries in ApiV3.

2018-11-20 11:56 UTC, fupduck commented
I greatly would appreciate help with the tests.

I guess I did not create the project correctly and I have some issues with a wrong content-type.
Sadly I was not able to execute the tests locally - "'development' database is not configured."

2018-11-20 16:17 UTC, ulferts requested changes
The functionality itself is looking fine 👍 I made comments in the code where I deemed it appropriate.

I didn't have the time to take a closer look at the tests to see what is wrong there.

How are you trying to start the tests? It shouldn't require the `development` database.

2018-11-20 16:17 UTC, ulferts commented on app/contracts/time_entries/delete_contract.rb
> +  class DeleteContract < BaseContract
Let's rather inherit from `::ModelContract`. That way, validations defined on the `BaseContract` (e.g. project is the same as the work package's project)  are not taken into account, which seems appropriate given that the time entry is to be deleted anyway.

2018-11-20 16:17 UTC, ulferts commented on docs/api/apiv3/endpoints/time_entries.apib
> +                "message": "The specified user does not exist."
While the documentation sometimes claims to return resource specific messages for 404 and 403, the implementation does not. So for 
* 403 => "You are not authorized to access this resource."
* 404 => "The requested resource could not be found."

2018-11-20 16:17 UTC, ulferts commented on app/services/time_entries/delete_service.rb
> +    end
Services are expected to return a `ServiceResult`. So you should change this to:

```
result, errors = validate_and_yield(time_entry, user) do
  time_entry.destroy
end

ServiceResult.new(success: result,
                  errors: errors,
                  result: result)
```

2018-11-20 16:17 UTC, ulferts commented on lib/api/v3/time_entries/time_entries_api.rb
> +            end
Once the service returns a service result (please see above), this should be changed to:

```
call = ::TimeEntries::DeleteService.new(time_entry: @time_entry, user: current_user).call

if call.success?
  status 202
else
  fail ::API::Errors::ErrorBase.create_and_merge_errors(call.errors)
end
```

That way, the api controller does not need to know why the service call failed, it just knows that it did, and will return an appropriate error based on the errors provided by the service.

2018-11-20 16:17 UTC, ulferts commented on spec/requests/api/v3/time_entry_resource_spec.rb
> +      delete path
use 

```
delete path, {}, 'CONTENT_TYPE' => 'application/json'
```

to signal the correct content type.

2018-11-20 16:17 UTC, ulferts commented on spec/requests/api/v3/time_entry_resource_spec.rb
> +
remove this line

2018-11-20 17:30 UTC, fupduck commented
Thanks a lot for the review.
Helped a lot to understand what is going on.

I tried running the tests by executing locally
```
$ bash script/ci/setup.sh units postgres
$ bash script/ci/runner.sh units 4 1
```

2018-11-21 09:25 UTC, ulferts commented
The ci scripts are not meant to be run locally by a developer.  But it explains the message regarding 'development'. 

You should rather:
* Setup a test environment -> add appropriate statements in config/database.yml
* run the tests. In your case that would mean issuing the following statements in a bash:
  * `rspec ./spec/requests/api/v3/time_entry_resource_spec.rb`
  *  `rspec ./spec/contracts/time_entries/delete_contract_spec.rb`

2018-11-21 09:32 UTC, ulferts requested changes
Almost there @fupduck. Keep up the work.

2018-11-21 09:32 UTC, ulferts commented on app/services/time_entries/delete_service.rb
> +    validate_and_yield(time_entry, user) do
```suggestion
    result, errors = validate_and_yield(time_entry, user) do
```

You need to assign the return values to variables for them to be available later on.

2018-11-21 09:32 UTC, ulferts commented on app/services/time_entries/delete_service.rb
> +    ServiceResult.new(success: result, errors: errors, result: result)
```suggestion
    ServiceResult.new(success: result, errors: errors, result: time_entry)
```

My bad, I asked you to provide the wrong variable for the result, sorry.

2018-11-22 12:51 UTC, ulferts commented
The tests are currently broken on the dev branch but we'll get it working soon. 

The PR itself is looking fine now, so we'll only need Travis' consent now.

2018-11-22 12:51 UTC, ulferts approved these changes

2018-11-22 12:54 UTC, fupduck commented
Hey @ulferts  thanks a lot for your help.
I finally (just now) got it running locally and hopefully wlil fix the errors soon.

2018-11-22 13:03 UTC, ulferts commented
Glad to hear that @fupduck. I really appreciate your work as OpenProject will benefit from every end point available. With your help, all the basic functionalities on time entries should be available now. The only thing missing now will be telling the client the available values (e.g. on activity) via a form/schema.

2018-11-22 13:06 UTC, ulferts commented
To get the test running again on Travis, you'll need to merge the current dev in. Or rebase onto it if that is more to your liking.

2018-11-26 12:19 UTC, fupduck commented
@ulferts Now the tests should be alright. Thanks for all the support.

2018-11-27 07:08 UTC, ulferts commented
Good job @fupduck :+1:

2018-11-27 07:09 UTC, merged