TimeEntries: activity, created_at and spent_on filter/sortby
opf/openproject pull request #6859
Opened 2018-11-23 13:50 UTC by oliverguenther

Implements the following filters and sortBy for TimeEntries:

- created_at
- spent_on
- activity(_id)

2018-11-23 15:28 UTC, ulferts requested changes
That activity filter needs some more elaborate behaviour because of that weird data structure.

2018-11-23 15:28 UTC, ulferts commented on app/models/queries/time_entries/filters/activity_filter.rb
> +  end
The time entry activity use some really spaced out way of implementing a join table. If a time entry activity is activated in a project, a child of the global activity is created. So time entries that are created receive the specific project time entry activity. The only exception to this is when time entries are configured to be global (active for all projects). 

This data structure has no benefit that I see compared to a simple join table but that is the way the data is currently modelled. 

By the way, for that reason the `TimeEntries::CreateService` has a [mapping code](https://github.com/opf/openproject/blob/dev/app/services/time_entries/create_service.rb#L67) which I noted the `TimeEntries::UpdateService` does not but should have.

2018-11-23 15:28 UTC, ulferts commented on docs/api/apiv3/endpoints/time_entries.apib
> +    + sortBy = ["spent_on", "asc"] (optional, string, `[["speont_on", "asc"]]`) ... JSON specifying sort criteria.
typo: "speont_on"

2018-11-23 15:28 UTC, ulferts commented on docs/api/apiv3/endpoints/time_entries.apib
> +
:+1: for adding this section

2018-11-26 06:17 UTC, oliverguenther commented
@ulferts feel free to implement the changes yourself since I won't be working on it until at least thursday.

2018-11-26 14:09 UTC, ulferts approved these changes

2018-11-27 09:39 UTC, oliverguenther commented
Thanks 👏

2018-11-27 09:39 UTC, merged