Create SearchFilter on work packages that searches on
opf/openproject pull request #6879
Opened 2018-12-03 17:11 UTC by wielinde

- subject
- description
- attachment file name
- attachment file content

https://community.openproject.com/wp/29116

2018-12-05 17:16 UTC, lindenthal commented
hi @wielinde,

why do you restrict the search on global custom fields?

Best
Niels

2018-12-12 12:53 UTC, wielinde commented
@lindenthal I didn't know it better back than. I removed the restriction. However, I deprioritized it to "Nice to have" as I don't have the impression that the feature was strongly desired. Please feel free to give it a priority boost.

2018-12-17 08:57 UTC, ulferts requested changes
Functionality looks good, please see my few remarks within the code.

2018-12-17 08:57 UTC, ulferts commented on app/models/queries/work_packages/filter/comment_filter.rb
> +    %i{project journals}
Why does `project` need to be included?

2018-12-17 08:57 UTC, ulferts commented on app/models/queries/work_packages/filter/search_filter.rb
> +      filter_class_list = [
The handling of what filters are eligible should be extracted into a separate method to shorten the `filters` method.

2018-12-17 08:57 UTC, ulferts commented on app/models/queries/work_packages/filter/search_filter.rb
> +                                   values: values)
```
@filters = filter_class_list.map do |filter_class, filter_name|
  filter_class.create!(name: filter_name,
                       context: context,
                       operator: CONTAINS_OPERATOR,
                       values: values)
```
is equivalent and easier to read

2018-12-17 08:57 UTC, ulferts commented on spec/factories/attachment_factory.rb
> +
remove, please

2018-12-17 10:37 UTC, wielinde commented
@ulferts Thank you for your review. I took it as an opportunity to extract an OrBaseFilter that can serve us as a base for an IdAndStatusFilter for the Autocompleter, too.

2018-12-17 11:33 UTC, ulferts requested changes
I like the idea of extracting the or functionality.

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/search_filter.rb
> +    list + EE_TSV_FILTERS if EnterpriseToken.allows_to?(:attachment_filters) && OpenProject::Database.allows_tsv?
`nil` will be returned from the method if the condition is not met which is not expected by the code

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +  end
I think this should be removed. Doing that will mean that the functionality will fall back to a sensible default defined in   `Queries::Filters::Base`. That way, you wouldn't have to define the method again in `Queries::WorkPackages::Filter::SearchFilter`

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +  end
```
def self.type
```
is already defined in the same way in Queries::Filters::Base

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +  end
Is this actually required? The base filter already defines the behaviour, so if a subclass wants to rely on that it should be able to.

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +  end
Again, defined in base class.

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +  end
This method is defined, but not used in e.g. https://github.com/opf/openproject/pull/6879/files#diff-34c9d42ca6cd72148d28262066292d1dR34

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +      operator_for_instance = configurations[index].third
You rely on the subclass knowing that it has to provide an array of arrays (with at least three elements each) in `filter_configurations` and to know the semantics of each index in the inner arrays. To increase stability, please introduce a class/struct or at least turn it into an array of hashes.

2018-12-17 11:33 UTC, ulferts commented on app/models/queries/work_packages/filter/or_base_filter.rb
> +class Queries::WorkPackages::Filter::OrBaseFilter < Queries::WorkPackages::Filter::WorkPackageFilter
From the looks of it, using a mixin instead of a class would fit the intention better.

2018-12-18 06:42 UTC, merged