Make ProjectsController#destroy use background worker + service
opf/openproject pull request #6936
Opened 2018-12-12 10:25 UTC by oliverguenther

Trying to delete large projects in OpenProject may result in timeout errors since currently, the deletion is performed in the context of the web request.

This PR introduces a `Projects::DeleteService` and contract and a delayed job to schedule the deletion. The services handles both delayed and non-delayed cases to ensure authorization can happen in one place.

It also refactors `UserMailer` to allow a separate `ProjectMailer` to be created to the size of UserMailer. The `BaseMailer` now inherits some OpenProject specifics regarding mail ID generation and whatnot.

https://community.openproject.com/wp/29214

2018-12-19 09:42 UTC, oliverguenther commented
legacy_spec failing are the unrelated often-failing `git_repository_spec`

2018-12-20 07:46 UTC, ulferts requested changes
Code looks good and I aside from a type, I liked all of it.

Is there any chance, we can get an integration spec for the functionality?

2018-12-20 07:46 UTC, ulferts commented on app/services/projects/delete_project_service.rb
> +    # @return True if the user deletion has been initiated, false otherwise.
`s/user/project`

2018-12-21 13:15 UTC, merged

2018-12-21 13:15 UTC, oliverguenther commented
Added, thanks!