[29738] Use CKEditor decoupled editor for sticky toolbar
opf/openproject pull request #7534
Opened 2019-08-14 13:40 UTC by oliverguenther

https://community.openproject.com/wp/29738

2019-08-15 08:23 UTC, HDinger commented on app/assets/stylesheets/content/editor/_ckeditor.sass
> +    top: 0
Please add `z-index: 1` here. Otherwise, tables and images will be placed above the toolbar.

2019-08-15 08:31 UTC, HDinger requested changes
It works fine on all browsers except Chrome. In the WP description (and other long text fields) the control buttons are misplaced after scrolling down. Either there are not visible at all, or they are somewhere they don't belong, e.g.
<img width="793" alt="Bildschirmfoto 2019-08-15 um 10 20 43" src="https://user-images.githubusercontent.com/7457313/63082932-c5957380-bf47-11e9-9d5f-058968860360.png">

2019-08-15 12:46 UTC, HDinger approved these changes

2019-08-15 13:17 UTC, merged

2019-08-23 11:15 UTC, xmeng1 commented
Hope this feature can release ASAP. Currently, I always use the other editor to write markdown and paste to OpenProject...

2019-08-23 12:49 UTC, oliverguenther commented
Hey @xmeng1 ,

this feature will be released as part of OpenProject 10.0. You can follow our release ticket to get notified of changes to the release date and the release itself: https://community.openproject.com/projects/openproject/work_packages/30753/activity?query_id=918

[Please also see our open issues list](https://community.openproject.com/projects/openproject/work_packages?query_id=1910) to see what we're working on while finishing the 10.0 release

2019-08-27 10:43 UTC, xmeng1 commented
ok, thanks @oliverguenther