Create BCF projects extension GET endpoint
opf/openproject pull request #7888
Opened 2019-11-19 14:26 UTC by oliverguenther

https://community.openproject.com/wp/31601

2019-11-20 10:18 UTC, ulferts requested changes
Please see my comments.

Other than those, I believe that either the `Definitions` class or the `Representer` (with a preference to the former) need unit tests.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +        allowed_service.call(permission, project).result
This could be written more easily as:

`
@user.allowed_to?(permission, project)
`

which under the hood already has an `AuthorizationService` instantiated. The service instantiated here then becomes superfluous and the application benefits from caching results that might already be available within the user's service.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +          %w[update updateRelatedTopics updateFiles createComment createViewpoint]
I'd rather we only add the topic_actions that we plan to implement for 10.3. AFAIK, `createComment` is not intended to be implemented right now.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/spec/requests/api/bcf/v2_1/project_extensions_api_spec.rb
> +    end
might be personal preference but I believe using the 
`'bcf api successful response'` shared example is more readable. For an example please see https://github.com/opf/openproject/blob/dev/modules/bcf/spec/requests/api/bcf/v2_1/current_user_api_spec.rb#L51-L57

It also has the benefit to:
* Be standardized if every we change the implementation
* Detect additional (and possible unwanted) properties in the response

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +        OpenProject::Cache.fetch(Status.all.cache_key) do
The cache keys here need to be scoped more explicitly to their usage within the definitions object e.g. by adding a prefix/postfix as done above. Otherwise we risk collisions with different cache values.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +      # TODO: This returns all statuses regardless of workflow
We could at least scope it down to all statuses included in workflows defined for the types and roles of the user within the project. But to a certain extend, this cannot be helped IMO given the format defined by the BCF API specification as those do not take the state of the objects into account.

But based on https://github.com/buildingSMART/BCF-API/blob/release_2_1/Schemas_draft-03/Collaboration/Topic/topic_GET.json#L87 I'd say that the current workflow can be communicated within each topic.

The part I currently do not understand in the specification however is: 'The most recent extensions state which values are valid at a given moment for newly created topics and comments.' (https://github.com/buildingSMART/BCF-API#414-get-project-extension-service)
The part I do understand is that clients are supposed to use the values in here when picking e.g. the status for newly created topics. However, I would not know which status within the list of status it would then have to be.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +    class Definitions
I believe that this should be split up into:
* The representer where the representation itself is considered (e.g. `...pluck(:name)`)
* The respective contracts where the available values themselves are concerned (e.g. `project.types`) 

That way way we avoid having to duplicate the available values checks that we are going to need for the update/create end points of the api.

But as the contracts do not exist yet, I think we should make that change once the contracts exist.

It might turn out that it is still beneficial to have this class as some kind of orchestration object between the multiple contracts but the class itself should have way less domain knowledge and representation logic.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +          project.users.pluck(:mail)
Only users with roles allowing to see work_packages (and possibly only those that allow having work packages assigned to them) should be listed here. But maybe I simply do not understand the semantic of the `user_id_type` as there is no description of the property within the api specification.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +      end
Again, I believe we will not have comments support in 10.3.

2019-11-20 10:18 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +          project.types.pluck(:name)
Out of scope for this PR but we might want to limit the types further as it does not really make sense to have a BCF of type 'Feature' or 'Milestone'.

2019-11-20 10:24 UTC, oliverguenther commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +        OpenProject::Cache.fetch(Status.all.cache_key) do
I wanted it to be generic since we might need other places where all status names are cached. I'll add a prefix to ensure its clear the names are being cached there

2019-11-20 10:38 UTC, oliverguenther commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +      # TODO: This returns all statuses regardless of workflow
I'll output all statuses for the project types for now

2019-11-20 10:40 UTC, oliverguenther commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +          project.users.pluck(:mail)
Let's use `project.possible_assignees` then for now

2019-11-20 12:15 UTC, oliverguenther commented on modules/bcf/spec/requests/api/bcf/v2_1/project_extensions_api_spec.rb
> +    end
The problem with this pattern is that you compare the entire body. In the case where two users are returned, their order is not defined so you may be getting incorrect spec failures. Also I have hopes that someday we will have tests are not dependent on globally isolated databases and can handle more than an isolated database.

I will add a shared example that includes partial tests on the body

2019-11-21 06:53 UTC, ulferts requested changes
Almost good now 👍

2019-11-21 06:53 UTC, ulferts commented on modules/bcf/app/representers/bcf/api/v2_1/project_extensions/definitions.rb
> +          .pluck(:name)
Based on our talk yesterday, I believe that only the default status should be listed here.

2019-11-21 09:13 UTC, merged