[21304] Add notification for removed watchers
opf/openproject pull request #7918
Opened 2019-12-06 13:54 UTC by vlad-timofeev

From [Issue 21304](https://community.openproject.com/projects/openproject/work_packages/21304):

> As a OpenProject user
I want OpenProject to automatically send emails to removed watchers
so that I can easily inform these users about new information.

This PR will implement email notifications to removed watchers by analogy with existing emails to added watchers.

2019-12-10 12:27 UTC, ulferts requested changes
Looks good functionality wise. The notification is sent as desired when the watcher is removed. 

I believe that some parts of the code need improvement before the PR can be merged. Please see my remarks within the code for the most part but I would want to point out two areas explicitly where improvement is needed:
* The added/altered functionality needs to be tested.
* Not relying on the watcher object leads to a couple of interface becoming bloated. The reason for that is to be found in the `RemoveWatcher` job where the watcher is not retrieved which then requires to pass all the parameters that could be passed within the one watcher object.

2019-12-10 12:27 UTC, ulferts commented on lib/services/remove_watcher.rb
>        @work_package.watcher_users.delete(@user)
If the watcher for the user where to be retrieved first, and then destroyed, that destroyed object could then be passed on through the notification without the need to bloat up the interface from three parameters `watcher_toggled`, `watcher`, `watcher_setter` to five. 
The same would then be true for the `WatcherNotificationMailer.handle_watcher_toggle` method.

2019-12-10 12:27 UTC, ulferts commented on app/mailers/user_mailer.rb
> +  end
👍 for refactoring this into a separate method

2019-12-10 12:27 UTC, ulferts commented on app/mailers/user_mailer.rb
> +  end
You could use `alias` here and for the remove method as well.

2019-12-10 12:27 UTC, ulferts commented on app/models/watcher_notification_mailer.rb
> +    def notify_about_watcher_added?(user, watcher_setter, watchable)
The method could be renamed now( and was misnamed before) as it does not check for whether the user wants to be informed about a watcher being added but, regardless of the action, about events on the watchable.

2019-12-10 12:27 UTC, ulferts commented on app/views/user_mailer/work_package_watcher_removed.html.erb
> +</p>
The only difference between the 'work_package_watcher_added' view and this one is the translation. Extracting the shared code into a partial with the translation key being a parameter would remove the duplication.

2019-12-10 12:27 UTC, ulferts commented on app/views/user_mailer/work_package_watcher_removed.text.erb
> +<%= t(:text_latest_note, note: last_issue_note(@issue)) %>
Same as above.

2019-12-12 14:37 UTC, vlad-timofeev commented
@ulferts thanks for your review, I will let you know when the improvements are made.

2019-12-14 12:52 UTC, vlad-timofeev commented
@ulferts please take another look at my PR. 

Several things I'd like to note explicitly in regards to it:
* The tests have been fixed and extended
* The `watcher` argument is back for `RemoveWatcher` and `CreateWatcher`, 
`WatcherNotificationMailer.handle_watcher_toggle`, and
`Notifications.subscribe('watcher_toggled')`, reducing the number of
arguments in those methods
* In `DeliverWatcherNotificationJob` it still makes sense to replace `watcher` with
  `watchable` because
* 1. `watcher.user.id` is passed as a 2nd argument anyway, so the interface
doesn't become more bloated
* 2. when the job is related to **removing** the watcher, the `watcher` object is
already deleted. One possible solution would be reconstructing it from the attributes just for
the sake of extracting `watchable` and `user` back, but it's arguably not a
perfect approach
* At first I created partials for the mail view, but then realized that the i18n key can be set inside `user_mailer.work_package_watcher_toggled`, removing the need for extra views or particles
* The number of arguments in several methods can be further reduced by eliminating `is_watching` argument, but there is a trade-off - it would lead to necessity to add more classes/files/views with similar looks

In its current form my PR contains a smaller number of changes in production code than the first version to achieve the same goal.

2020-07-28 19:16 UTC, lindenthal commented
closed due to inactivity. Please reopen if you want to continue on this PR.

2020-07-28 19:16 UTC, closed without merging