[ 31914] Feature: Update admin tabs layout
opf/openproject pull request #7963
Opened 2020-01-10 11:07 UTC by ingamai

### Description
Update old tabs layout on Administration pages (Custom fields, Settings) to search tabs design

2020-01-10 11:08 UTC, openprojectci commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/1467f171160f2792355d25648556241efec2e2c7/frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts#L2">frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts#L2</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-01-13 13:14 UTC, HDinger requested changes
Without having dealt with it in detail, the solution seems a little too complicated for me. Maybe it's because the name is misleading. I have the impression that perhaps we do not need the additional component. However, if we do, we should rename some of it. It might be clearer if the `admin-tabs` became `scrollable-tabs`. For example, the former `scrollable-tabs` would then become `tabs`. This would then be an abstract class that only functions as a superclass. 
But also within the component we should clean up a bit. Some of it is not needed. I think it is best if we sit down together and work out a plan.

2020-01-13 13:14 UTC, HDinger commented on config/locales/js-en.yml
> +    enumeration_activities: "Activities (time tracking)"
Some of these strings refer to the project settings. They are thus not needed any more since the merge of #7949

2020-01-13 13:14 UTC, HDinger commented on frontend/src/app/modules/admin/tabs/admin-tabs.component.ts
> +export class AdminTabsComponent extends ScrollableTabsComponent {
As discussed the name `AdminTabs..` is not good as it is not only used for admin tabs. 
In general I am wondering why we need a separate component at all. Can't we use  the scrollableTabsComponent?

2020-01-13 13:14 UTC, HDinger commented on app/assets/stylesheets/content/_tabs.lsg
> +<div #scrollContainer class="scrollable-tabs">
There is still some Angular specific things in here, like `#scrollContainer`. These can all be removed.

2020-01-13 13:14 UTC, HDinger commented on app/controllers/project_settings_controller.rb
> +  helper_method :gon
This can also be removed since the merge #7949

2020-01-13 13:14 UTC, HDinger commented on frontend/src/app/modules/admin/tabs/admin-tabs.component.ts
> +  public myTabs:Tab[] = [];
The name is not very intuitive. What are `this.myTabs` in comparison to `this.tabs`. Do we really need both?

2020-01-13 13:14 UTC, HDinger commented on frontend/src/app/modules/admin/tabs/admin-tabs.component.ts
> +    this.currentTab = jQuery.grep(this.myTabs, thisTab => thisTab.name === tab)[0];
This should be done by the super class. So `super.clickTab` should be sufficient.

2020-01-17 13:34 UTC, openprojectci commented on frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts
> +
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/opf/openproject/blob/b6de008196f192445ed7c73620340e71be5bbfaa/frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts#L8"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

2020-01-20 12:08 UTC, openprojectci commented on frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts
> +
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/opf/openproject/blob/32079589a06554b8e496863c812560c7d6677b0e/frontend/src/app/modules/common/tabs/scrollable-tabs.component.ts#L8"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

2020-01-20 12:08 UTC, openprojectci commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/32079589a06554b8e496863c812560c7d6677b0e/frontend/src/app/modules/global_search/tabs/global-search-tabs.component.ts#L36">frontend/src/app/modules/global_search/tabs/global-search-tabs.component.ts#L36</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-01-20 12:55 UTC, HDinger commented
[](url)

2020-01-20 13:27 UTC, ingamai reviewed
@HDinger I noticed that somehow the tab arrows are sometimes not shown properly. Maybe this is somehow related to the issue I commented below.

2020-01-20 13:27 UTC, ingamai commented on app/assets/stylesheets/content/_tabs.sass
> -    // Padding for hiding the scroll bar
@HDinger I guess this once was necessary, but when I tested it now without this style it also seemed to work fine. But we should have an eye on that...

2020-01-21 08:47 UTC, openprojectci commented on frontend/src/app/modules/global_search/tabs/global-search-tabs.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/opf/openproject/blob/565520ae6f2c58886c7e18d555597f7b982aed74/frontend/src/app/modules/global_search/tabs/global-search-tabs.component.ts#L36"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

2020-01-21 13:59 UTC, HDinger approved these changes

2020-01-21 15:13 UTC, merged