[31974] Simplify instance color theme changes
opf/openproject pull request #7966
Opened 2020-01-14 08:37 UTC by HDinger

This PR aims to simplify the change of colour schemes of an OpenProject instances with EE token. Therefore the view itself is made a bit more intuitive. Further predefined colour themes shall be provided.

### ToDo
- [x] Improve UX of design variable list 
  - [x] Change order of changeable design variables so that logical blocks are shown together
  - [x] Provide a natural language name for each variable
  - [x] Use all already available help texts for design variables
- [ ] Provide predefined color themes
  - [ ] Show a select field with themes and hide the design variable list under "Advanced settings"
  - [ ] Changing the color theme changes the variables when clicking on Save (Out of scope: Instead change when choosing a theme)
  - [ ] Recognise the used theme, to show the correct one in the list.

https://community.openproject.com/projects/openproject/work_packages/31974/activity

2020-01-14 08:37 UTC, HDinger commented
Ticket: 
https://community.openproject.com/projects/openproject/work_packages/31974/activity

2020-01-22 13:54 UTC, ulferts requested changes
A solid improvement @HDinger :+1: 

The only beef I have with the change is that when a custom theme is selected, the user will always have to first open the collapsed colors section to see/edit. How about we change this to be open by default if a custom theme is selected?

2020-01-22 13:54 UTC, ulferts commented on config/locales/en.yml
> +        alternative-color: "Strong accent color, typically used for most the important button on a screen."
typo: `most the important` -> `the most important`

2020-01-22 13:54 UTC, ulferts commented on app/views/custom_styles/show.html.erb
>            <span class="form--field-container">
Can we please use the chance to move the color representation right next to the input field? 

E.g. by adding
```
            <div class="form--field-affix">
              <%= icon_for_color(OpenStruct.new(variable: design_color.variable,
                                                hexcode: design_color.get_hexcode),
                                 data: { target: "#design_colors_" + design_color.variable }) %>
            </div>
```
as the first child of the `form--field-container` we get:

![image](https://user-images.githubusercontent.com/617519/72899623-af75b580-3d26-11ea-8876-7f5c56faff51.png)

2020-01-24 08:18 UTC, ulferts approved these changes
Looks good now @HDinger, good to merge once travis and codeclimate agree.

2020-01-24 09:03 UTC, merged