[31935] WIP: Enterprise activation frontend
opf/openproject pull request #7995
Opened 2020-01-31 11:04 UTC by ingamai

2020-02-27 11:00 UTC, machisuji commented on app/views/enterprises/_info.html.erb
> +<% content_for :header_tags do %>
@ingamai I found the problem. This doesn't work in partials (_info.html.erb). If you move this bit to show.html.erb t should work!

2020-02-28 14:52 UTC, HDinger commented
Ticket:
https://community.openproject.com/projects/saas/work_packages/32422/activity

2020-03-12 12:35 UTC, HDinger requested changes
Hi @ingamai , looks good :+1: don't worry, most of the remarks are rather small :) 

Please merge the current dev, as there are merge conflicts and the tests cannot run. Some additional hints:

* When I submit the form and close the modal after that, there is a message saying that my Session has timed out. I think this is not the correct message here.
<img width="382" alt="Bildschirmfoto 2020-03-12 um 13 23 09" src="https://user-images.githubusercontent.com/7457313/76521344-f3eb1b00-6464-11ea-937b-26e51a03d7fd.png">

* Also when I close the modal before confirming my mail address, the page never updates after I confirmed. 

* When I press: "Try another email address", the form in the background is immediately changed. As a user I assume, that I've lost all my previous content and that I now cannot start the trial with that email (which is true, as the page never checks for the old mail again).

* The page looks a bit unstructured because there are many headlines, some have the same depth, some not. Maybe you could see, if there is room for improvement. However this is low priority.
<img width="1442" alt="Bildschirmfoto 2020-03-12 um 13 29 43" src="https://user-images.githubusercontent.com/7457313/76526268-8e4f5c80-646d-11ea-8362-a9d790020fd8.png">

2020-03-12 12:35 UTC, HDinger commented on config/locales/js-en.yml
> +          mail_not_received: "You did not receive a mail? Resend mail or"
Please take care that you use `mail` and `email` consistently. In Englisch, we use `email`. Also please have a look at upper and lower case at the beginning of a string.

2020-03-12 12:35 UTC, HDinger commented on config/locales/js-en.yml
> +          status_confirmed: "confirmed ✓"
This is just a guess, but I can imagine that the checkmark could lead to issues when translating the string. Could you please check whether we could display this in any other way. Maybe with an icon?

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
> +      this.eeTrialService.errorMsg = 'Invalid e-mail address';
Please localise this.

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.html
> +      <h3 *ngIf="!eeTrialService.status"> {{ text.heading_test_ee }}</h3>
Instead of using three elements, just show one and change the text according to the status in the .ts file. 
`<h3 [textContent]="headerText()"> </h3>`

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.html
> +                    src="https://www.youtube.com/embed/zLMSydhFSkw?autoplay=1">
You can extract the URL into a constant so that is easier to find later when the URL should change.

2020-03-12 12:35 UTC, HDinger commented on app/assets/stylesheets/content/_info_boxes.lsg
> +# Info boxes
👍 Thanks for adding it to the LSG

2020-03-12 12:35 UTC, HDinger commented on app/assets/stylesheets/content/_info_boxes.sass
> +    max-width: 1140px
Why exactly this number (same for the base class)? And why is `-centered` wider than the base class?

2020-03-12 12:35 UTC, HDinger commented on app/assets/stylesheets/content/_enterprise.sass
> +  align-items: baseline
In many files the last (empty) line is missing. Pease add this for code climate reasons. 🙈

2020-03-12 12:35 UTC, HDinger commented on app/views/enterprises/_info.html.erb
> +  <a href="https://www.openproject.org/upgrade-enterprise-edition/" target="_blank">
Please extract these links as constants and collect them at one place. Thus it will be much easier to replace them in case the URL changes.

2020-03-12 12:35 UTC, HDinger commented on app/views/enterprises/_info.html.erb
> +      <%= image_tag "https://1t1rycb9er64f1pgy2iuseow-wpengine.netdna-ssl.com/wp-content/uploads/2017/06/icon-security-features.png",
Is there a reason to use the cryptical URL instead of adding the pictures to our image folder?

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-base.component.html
> +<div *ngIf="eeTrialService.status === 'mailSubmitted'">
The check for the status is used quite often. I think it makes sense to extract it to a method.

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.sass
> +  max-height: 65vh
Is this something relevant for all modals? And why exactly `65vh`?

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.sass
> +      border: 1px solid var(--content-form-danger-zone-bg-color)
We already have a rule for the border, called `-required-highlighting`. So pease use this one. I guess it is sufficient to highlight the border, so this file can then be replaced completely.

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.html
> +        <span>I want to receive the OpenProject
Please localise the file.

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.html
> +          <span>10</span>
Is this value fixed? If yes, please move to the .ts file anyway.

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-trial.service.ts
> +    this.savedUserData = window.OpenProject.guardedLocalStorage(this.localStorageKey);
As discussed, we should think about a different solution here.

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-base.component.html
> +    <enterprise-active-trial></enterprise-active-trial>
I assume that this should show the trial information within the modal? If yes, it doesn't work:
<img width="1097" alt="Bildschirmfoto 2020-03-12 um 13 21 23" src="https://user-images.githubusercontent.com/7457313/76521065-60b1e580-6464-11ea-84be-b46b17ad653e.png">

<img width="1088" alt="Bildschirmfoto 2020-03-12 um 13 19 53" src="https://user-images.githubusercontent.com/7457313/76521105-72938880-6464-11ea-8a13-eb93fdef00aa.png">

2020-03-12 12:35 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-trial.service.ts
> +  public status:string|undefined;
Please specify the types the `status` variable can be. So `public status:'startTrial'|'mailSubmitted'|undefined`.

2020-03-12 12:47 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.ts
> +    this.closeOnOutsideClick = _.defaultTo(this.options.closeByDocument, true);
Why do you set these variables so complicated? `locals.options` is not set when you call the modal, so all of this is somehow obsolete. You could also set `this.closeOnOutsideClick = true;`. The interface is then also not needed.

2020-03-26 07:51 UTC, ingamai commented
> Hi @ingamai , looks good 👍 don't worry, most of the remarks are rather small :)
> 
> Please merge the current dev, as there are merge conflicts and the tests cannot run. Some additional hints:
> 
> * When I submit the form and close the modal after that, there is a message saying that my Session has timed out. I think this is not the correct message here.
> 
> <img alt="Bildschirmfoto 2020-03-12 um 13 23 09" width="382" src="https://user-images.githubusercontent.com/7457313/76521344-f3eb1b00-6464-11ea-937b-26e51a03d7fd.png">
> 
> * Also when I close the modal before confirming my mail address, the page never updates after I confirmed.
> * When I press: "Try another email address", the form in the background is immediately changed. As a user I assume, that I've lost all my previous content and that I now cannot start the trial with that email (which is true, as the page never checks for the old mail again).
> * The page looks a bit unstructured because there are many headlines, some have the same depth, some not. Maybe you could see, if there is room for improvement. However this is low priority.
> 
> <img alt="Bildschirmfoto 2020-03-12 um 13 29 43" width="1442" src="https://user-images.githubusercontent.com/7457313/76526268-8e4f5c80-646d-11ea-8362-a9d790020fd8.png">

@HDinger I rebased and hope I could fix all of your additional hints.

2020-03-26 15:18 UTC, HDinger requested changes
Unfortunately there are still some things that are not quite yet complete. Here are the things I found. But please have a look at my comments from last time again. Some of them are still relevant.

* When I click through the modals to the onboarding video: The video reboots every few seconds because the polling is still running.
* In general, I had the impression several times that the polling was still running, even though it shouldn't. This also led to errors, but unfortunately I cannot reproduce them. But please make sure that you always stop polling correctly.
* As admin I can not delete the token created by another admin. This throws an error.
* If I have a ready token and enter it in the field at the bottom, the page will not change afterwards. The token will be saved correctly, but the page should also update. On the Rails console an error appears.
* When the time to confirm the mail has expired, a message appears that you should resend the mail. If I reload the page instead, I end up on the start page again and all my data is gone.
 
Rather unimportant:
* I don't think the name 'EnterpriseTrialToken' is well chosen. It implies that this is the real token, which it is not.
* If Admin1 and Admin2 request a token relatively simultaneously, the one who first confirmed the mail is accepted (in the example now Admin1). So far correct.  But if this is deleted, Admin2 suddenly sees the waiting screen again. I think both should see the start page again. The case is surely quite constructed, especially if you add the query that only tokens are loaded into gon that are not yet exposed.

2020-03-26 15:18 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.html
> +          <a href="https://www.openproject.com/terms-of-service/" target="_blank">{{ text.terms_of_service }}</a>
Please move these links to the component as constants, too.

2020-03-26 15:18 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.html
> +        <button *ngIf="eeTrialService.status === 'startTrial'"
As said before, please extract all calls of this structure `eeTrialService.status === 'XY'` into methods.

2020-03-26 15:18 UTC, HDinger commented on config/routes.rb
> +        post 'enterprise/create_trial_key' => 'enterprises#create_trial_key'
The name is misleading. The method is not really creating the trial key.

2020-03-26 15:18 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.ts
> +      }, 500);
Why this delay? It leads to a strange flickering effect, as you see the other form first, and then it is replaced.

2020-03-26 15:18 UTC, HDinger commented on frontend/src/app/components/enterprise/enterprise-trial.service.ts
> +  private getUserDataFromAugur(trialKey:string) {
I have a little stomachache with these two method private methods:
First of all, why are they part of the service when they are actually only needed by the ActiveTrial component. This results in many unpleasant consequences: First, most of the data is not needed by the service (actually only the key). You can tell this by the fact that you simply write it into the trialForm, an object that will not be visible anymore. On the other hand, you will have to manually pull the data out of the trialForm in the component again. This is pretty ugly all in all. I think it would be better to drag the whole loading from gon into the component that needs it. Then you don't have to execute unnecessary code every time. You can then simply set the key from the component in the service.

2020-03-26 15:18 UTC, HDinger commented on app/controllers/enterprises_controller.rb
> +    @trial_key = Token::EnterpriseTrialToken.find_by!(user_id: current_user.id)
Please remove the `!`, it throws an exception when no token is found. Thus a user without a token has no chance to get one, as the page already throws an exception. 

<img width="816" alt="Bildschirmfoto 2020-03-26 um 14 42 44" src="https://user-images.githubusercontent.com/7457313/77660712-f62b9a00-6f79-11ea-80cb-9613e688ea6c.png">

Also I think that we should only look for tokens that have not expired yet, so something like `expires_on < Date.today`.

2020-03-26 15:18 UTC, HDinger commented on app/views/enterprises/_current.html.erb
> +                         data-user-count="<%= @current_token.restrictions[:active_user_count] %>"
When I have an unlimited token, this causes the page to crash.
<img width="788" alt="Bildschirmfoto 2020-03-26 um 14 40 51" src="https://user-images.githubusercontent.com/7457313/77660944-44409d80-6f7a-11ea-8700-2bfa2eacd77c.png">

2020-03-27 13:52 UTC, ingamai commented
@HDinger Maybe this is interesting for you: The reloading of the onboarding video had nothing to do with the polling but it seems to be a newer issue with binding the method that uses the DomSanitizer directly to the src attribute without a pipe.
Have a look at: https://stackoverflow.com/questions/39429293/url-sanitization-is-causing-refresh-of-the-embedded-youtube-video/48154761

2020-03-30 13:05 UTC, ingamai commented on config/routes.rb
> +        post 'enterprise/create_trial_key' => 'enterprises#create_trial_key'
@HDinger I renamed it to "save_trial_key".

2020-03-30 13:06 UTC, ingamai commented on frontend/src/app/components/enterprise/enterprise-active-trial/ee-active-trial.component.ts
> +      }, 500);
@HDinger Moving the methods from the services into the component solved this issue as well :)

2020-03-30 13:31 UTC, ingamai commented on app/controllers/enterprises_controller.rb
> +    @trial_key = Token::EnterpriseTrialToken.find_by!(user_id: current_user.id)
@HDinger Sorry, copy and paste failure... I removed it!

2020-03-30 14:25 UTC, ingamai commented on app/views/enterprises/_info.html.erb
> +      <%= image_tag "https://1t1rycb9er64f1pgy2iuseow-wpengine.netdna-ssl.com/wp-content/uploads/2017/06/icon-security-features.png",
@HDinger I added the pictures to the images folder.

2020-03-30 15:33 UTC, ingamai commented on app/assets/stylesheets/content/_info_boxes.sass
> +    max-width: 1140px
@HDinger This is a very good question 😅 I will only give the base class a max-width (because I found it quite strange looking on a big screen if the elements span the whole width). I  used 1140px because this is the max-width of the content on openproject.org, on which I based the template for the info boxes. 
Should I change that to another value?

2020-03-30 16:39 UTC, ingamai commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial.modal.sass
> +  max-height: 65vh
@HDinger It was kind of a 'the biggest height that fits most screen sizes' decision. But I removed this style now.

2020-04-14 08:56 UTC, ingamai commented
@oliverguenther I started working on this one https://community.openproject.com/projects/openproject/work_packages/32912/activity
by showing the missing attributes in the waiting screen.
I did not extend the structure of the tokens yet because this may be out of scope. Do you think this is sufficient for now?

2020-04-14 13:51 UTC, RobinWagner commented
Hi @ingamai,
to keep the discussion in one place I'll add my comments here instead of on the work package.

Thank you for making the adjustment to the strings.
The 4 benefits (Installation support, professional support, premium features, security features) look good and match with the strings that Niels specified in the PPT.

Unfortunately, I cannot see the strings used by the default screen (upper section) since there seems to be an error.
When I go to the Enterprise Edition screen (on PullPreview) there seems to be a token set for which "Subscriber: undefined undefined" is shown. Also, the status indicates that an email has already been sent (which is not the case). I tried this in multiple different browsers - also in incognito mode but it always shows this state. I'm not able to remove this default token. Also, requesting a separate token does not seem possible.

Could you take a look at this?
![image](https://user-images.githubusercontent.com/4333337/79232013-3db19180-7e67-11ea-81b2-e93ee8488779.png)

When I click on the link "Or try with another email address." and enter an email address an internal error is shown and the subscriber (while briefly changing to the provided name) quickly changes back to the original "undefined undefined".

![image](https://user-images.githubusercontent.com/4333337/79232148-6f2a5d00-7e67-11ea-9fdd-10c85493f22c.png)

When this is properly displayed again, I'm happy to take a look at the other strings.

Thank you,
Robin

2020-04-15 09:19 UTC, RobinWagner commented
Hi @oliverguenther @ingamai,

Thank you for making the adjustment.
When I signed into PullPreview I still saw the default "undefined undefined" subscriber. But now it was possible to enter a different email address and receive the token. The internal error seems to be gone.

However, the displayed Enterprise Edition trial license seems to be off by 10 years. As a result, the trial license is immediately expired.
The end day is set to 2010 instead of 2020:
![image](https://user-images.githubusercontent.com/4333337/79319544-bf0d3080-7f08-11ea-9398-d01f8e4fdb12.png)

Inga and I already briefly spoke about this. @oliverguenther do you have an idea what could be causing this?

It would be great if we could make some small changes to the text. In some places some words seem to be missing. Also, there are two different spellings used for "Open Source". On our website we capitalized it and always wrote it as "Open Source". I would suggest we do this here as well:
![image](https://user-images.githubusercontent.com/4333337/79320022-64280900-7f09-11ea-8d3a-38506cc66348.png)

Maybe we should add a hint that we charge an extra (one-time) fee for the installation support. That may be more transparent. What do you think, @lindenthal?

When ordering the Enterprise Edition license, should it be activated automatically (like the trial license)?
When I tried to book / buy the Enterprise Edition I could fill out all the forms for the Enterprise Edition and go through the different steps (entering a test credit card number). However, after confirming nothing happened. The modal was hidden but the Enterprise Edition was not active. Instead, I received the Enterprise Edition by email.
Is that supposed to happen? Or should the Enterprise Edition license - similarly to the trial license be activated automatically?

Otherwise it looks good to me :)

Thank you,
Robin

2020-04-15 14:17 UTC, oliverguenther commented
Hi @RobinWagner , thanks for your latest remarks. I'm going to go ahead and merge this for now, we can create subsequent tickets for your two questions if we decide to implement them

2020-04-15 14:18 UTC, merged