[32156] Use backlogs sorting of versions date for work packages
opf/openproject pull request #8000
Opened 2020-02-04 12:17 UTC by oliverguenther

- Adds a null_handling option to the property columns to allow `NULLS FIRST/LAST` to be handled
- Adds a query specific SortCriteria that can work with null_handling 
- Fixes sorting of allowed_versions to reuse that sort order

https://community.openproject.com/wp/32156

2020-02-05 14:49 UTC, ulferts requested changes
I'd have expected the change to include all views, where versions are listed, but at least the following do not take the dates into account:
* Roadmap (both in the content area and in the versions list of the sidebar)
* Version settings in the project

Personally, but that is just personal preference, I would have expected the versions to be sorted by ASC date. But the DESC approach does have the advantage of having the more current values on top.

2020-02-05 14:49 UTC, ulferts commented on app/models/version.rb
> +  default_scope do
Do we really need the default_scope? They tend to cause problems.

2020-02-05 14:49 UTC, ulferts commented on spec/models/query/results_version_integration_spec.rb
> +describe ::Query::Results, 'Grouping and sorting for version', type: :model, with_mail: false do
:+1: good approach to start extracting into separate files.

2020-02-06 10:40 UTC, oliverguenther commented
@ulferts I implemented the version sorting in roadmap list/sidebar and settings.

2020-02-11 08:55 UTC, merged