Use text pattern for float number fields
opf/openproject pull request #8018
Opened 2020-02-06 09:31 UTC by oliverguenther

The number pattern doesnt correctly respect the lang field in all browsers it appears. Using text field with custom parsing/formatters with validations for the numbers, we can avoid the number field.

We however need to listen for keydown events to emulate a number field and disable inputting any other fields. This will probably break for some keys.

2020-02-06 09:37 UTC, openprojectci commented on frontend/src/app/modules/fields/edit/field-types/float-edit-field.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/opf/openproject/blob/cb362a4f9bde7e8b78dc5ea0b921de24830d93fc/frontend/src/app/modules/fields/edit/field-types/float-edit-field.component.ts#L31"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

2020-02-06 10:09 UTC, ulferts requested changes
There are some cases where it does not work, e.g.

* Floating point roundings: Insert 1 234 567 891 011 121 into the field and press 3, the value will change to 12 345 678 910 111 212 (with a 2 instead of a 3 at the end). Admittedly in `dev` the result is the same as while the user sees the correct value being put in, the wrong value is transmitted to the backend.
* Non number chars can be added (they are removed automatically once a number is inserted)
* Again floating point: lengthy fractions are cut off, e.g. 0,121212121212214322312312323123123 lead to 0,12121212121221432 being sent to the backend (not native to this PR it seems, also happens on `dev`)
* Adding numbers within an existing number (not at the end): The number is added at the intended position but then the cursor jumps to the end

2020-02-06 13:14 UTC, oliverguenther commented
- I can't reproduce the second one, for me regular chars are blocked from entering.
- We can't fix the floating point errors as long as we use JS floats. We could use a string that's converted to a decimal in ruby however, but not sure how this would be transmitted. Both are out of scope here IMHO

I can reproduce the cursor jumping, this is simply caused by angular updating the text value from my formatter function. We could remove it and leave the number as is again, but that would remove the feedback formatting.

2020-02-11 12:08 UTC, HDinger commented
For me, there are two issues:

* I cannot edit normal letters, but special chars like `"§$%&/`. I guess we should forbid that.
* To be honest, I find it a bit confusing when I enter long numbers and the number keeps changing and moving. Especially when the numbers are similar, I think it leads to confusion, because it is not clear whether the number is inserted at the end or the beginning.  I tried to capture this in the GIF. Although the number is correctly displayed, I was confused at the beginning.

![float_text_field](https://user-images.githubusercontent.com/7457313/74235420-389d5e00-4ccf-11ea-8479-101f48ac5839.gif)

In general, I wonder if this bug in Chrome is worth all the time we're spending on it. Maybe we should open a bug report in Chrome first and see how they react.

2020-02-12 07:32 UTC, closed without merging

2020-02-12 07:32 UTC, oliverguenther commented
The spec can be fixed  by switching to firefox in that example https://github.com/opf/openproject/pull/8034