Flexible width of edit field of widget title
opf/openproject pull request #8058
Opened 2020-02-17 11:30 UTC by nitinvupk

[Ticket](https://community.openproject.com/projects/openproject/work_packages/32176/activity?query_id=903)

2020-02-20 14:14 UTC, lindenthal commented
Hi @nitinvupk,
Thanks for your PR.
I just build your branch on [Pull Preview](http://openproject-pr-8058-flexible-width-of-dc291387.my.pullpreview.com/projects/your-scrum-project/):

- User: admin
- PW: admin

I noticed that there is visible line around a widget title which should only appear on hover. Also the field is wider than it needs to be.

Can you please have a look at it?
![image](https://user-images.githubusercontent.com/1019287/74941548-80209a00-53f3-11ea-9845-3d98c489c547.png)

Thanks
Niels





Thanks
Niels

2020-02-24 08:30 UTC, nitinvupk commented
@lindenthal I have updated changes. Please have a look and let me know if required any changes

2020-02-25 09:13 UTC, lindenthal commented
Hi @nitinvupk,
I wasn't able to build your PR on Pull Preview. Can you please rebase your PR to dev?
Can you also please have a look at the failing checks?
Best
Niels

2020-02-26 12:12 UTC, lindenthal commented
Hi @nitinvupk ,

it seems as if the formatting got lost:

![image](https://user-images.githubusercontent.com/1019287/75343869-a766e380-5899-11ea-8484-84769e8f1b2b.png)

Can you please check?

Best
Niels

2020-03-02 07:52 UTC, lindenthal commented
Hi @nitinvupk,

Thanks for fixing the formatting. I just found more things:


1. The text flickers and changes position during hovering (testet in FF).
2. Some text is cut off on the right.

![02-03-_2020_08-50-46](https://user-images.githubusercontent.com/1019287/75655910-23c74100-5c63-11ea-9c05-da0cf858f2bc.gif)


Can you please have another look?

Best
Niels

2020-03-12 17:21 UTC, lindenthal commented
Hi @nitinvupk,
your branch currently does not work on pullpreview:

http://openproject-pr-8058-flexible-width-of-e42adea1.my.pullpreview.com/

Can you please rebase and double check?

Thanks
Niels

2020-03-24 08:49 UTC, HDinger requested changes
Hi @nitinvupk 

thanks for your work. Unfortunately the PR still needs to be improved (see my comments below). Additionally I found an issue when I delete every character within the field, the width is too small to see the placeholder:
<img width="848" alt="Bildschirmfoto 2020-03-24 um 09 35 09" src="https://user-images.githubusercontent.com/7457313/77406229-a059c500-6db4-11ea-8659-d40d548fc3fb.png">
 
Please let me know, if anything is unclear or if you have questions.

2020-03-24 08:49 UTC, HDinger commented on app/assets/stylesheets/content/_tabs.sass
> +      color: tabs-font-color-disabled
Please revert this change. Without the `$`it is not recognised as a variable and simply ignored.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
> +  divToMeasureWidth:number;
This variable is never used, please remove it.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
> +  editableTitleInput:any;
Same here, the variable is not used so it can be removed.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.component.ts
> +  @ViewChild('hiddenDiv', { static: false }) hiddenDivElement:ElementRef;
Also not used.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
> +  id="inputTextID"
This ID is not very specific. An ID should short, but precisely describe the field. `inputTextID` could be any input field within the application. However, I think there is no ID needed at all, please see my comment below regarding the styles.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.sass
> +#inputTextID
I am strong for keeping the styles the way they were before. Unfortunately this was not clearly described in the ticket, it's on our head. I'm sorry about that. So I'm afraid we don't need any of the styles from this file.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
> +         class="editable-toolbar-title--input -border-on-hover-only toolbar--editable-toolbar-title ellipsis"
As the styles should be like before, the old class should be used, too.

2020-03-24 08:49 UTC, HDinger commented on frontend/src/app/modules/common/editable-toolbar-title/editable-toolbar-title.html
> +  [style.width.pt]="selectedTitle.length > 5 ? (selectedTitle.length + 2)*8 : (selectedTitle.length + 5)*5"
First of all, please extract the functionality into a method. Second, the switch after 5 characters leads to jump within the text:
![width_toggle](https://user-images.githubusercontent.com/7457313/77404645-566fdf80-6db2-11ea-8894-f72350e1bc66.gif)

And third, these are a lot of magic numbers. Why exactly `+ 2` when the title is long and why `+ 5` when the title is short? Why `* 8` and why `* 5`? Are these numbers necessary? Is the switch really necessary? If yes, where do these numbers come from? Are they the best effort or calculated? This is very hard to understand for anyone who has to read to code later on. So, if they are necessary, please extract them into variables and give them meaningful names to make it easier to understand.

2020-03-26 11:52 UTC, lindenthal commented
Hi @HDinger  and @nitinvupk,

since there is no progress in this PR for quite a while I am closing this PR for now.

Best
Niels

2020-03-30 07:49 UTC, lindenthal commented
I contacted @nitinvupk

2020-04-10 08:28 UTC, lindenthal commented
Closing this PR because of inactivity.

2020-04-10 08:28 UTC, closed without merging