Make boards a partitioned-page component and add split routes
opf/openproject pull request #8230
Opened 2020-03-30 12:42 UTC by oliverguenther

https://community.openproject.com/projects/openproject/work_packages/30918

:warning: Needs decision whether this can be moved into 10.5 or 10.6 (current scope):

2020-03-30 12:42 UTC, oliverguenther commented
![Screenshot from 2020-03-30 14-40-34](https://user-images.githubusercontent.com/459462/77913504-a9570480-7294-11ea-9169-ade08260da6d.png)

@HDinger there is a minor style issue with the back button, we could force it to `align-self: flex-start` but maybe you have a better idea?

2020-03-30 12:45 UTC, oliverguenther commented
Ticket: https://community.openproject.com/projects/openproject/work_packages/30918

2020-03-30 13:21 UTC, openprojectci commented on frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><del><span data-href="https://github.com/opf/openproject/blob/9fa518c8247ead78913e82abf903114474bb7670/frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts#L18"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</del></td>
    </tr>
  </tbody>
</table>

2020-03-30 13:21 UTC, openprojectci commented on frontend/src/app/modules/boards/boards-root/boards-root.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><del><span data-href="https://github.com/opf/openproject/blob/9fa518c8247ead78913e82abf903114474bb7670/frontend/src/app/modules/boards/boards-root/boards-root.component.ts#L7"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</del></td>
    </tr>
  </tbody>
</table>

2020-03-30 13:21 UTC, openprojectci commented
<!--
  0 Errors
  3 Warnings: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/9fa518c8247ead78913e82abf903114474bb7670/frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts#L44">frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts#L44</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/9fa518c8247ead78913e82abf903114474bb7670/frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts#L54">frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts#L54</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/9fa518c8247ead78913e82abf903114474bb7670/frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts#L41">frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts#L41</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-03-30 14:23 UTC, lindenthal commented
Hi @oliverguenther,
I just had a quick look at PP.

http://openproject-pr-8230-make-boards-a-3338efd8.my.pullpreview.com/projects/your-scrum-project/boards/3/details/28/overview

After activating the split view I can not switch to another work package. Can you please have a look. Am I using an outdated version?

2020-03-30 14:24 UTC, lindenthal commented
@oliverguenther: did you consider to add an info icon to the toolbar, similar to the work packages view?

2020-03-30 14:32 UTC, HDinger commented
> @oliverguenther: did you consider to add an info icon to the toolbar, similar to the work packages view?

When we add the info icon to the toolbar, we should briefly think about what this means for the selection. In the board, I can easily select multiple cards without any keyboard help (one card per list). The question I then ask myself is which card will appear when I press the info icon. The selected one of the first list? Or the one I selected last (which is currently not possible)?

2020-04-02 09:29 UTC, openprojectci commented on frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><del><span data-href="https://github.com/opf/openproject/blob/8d0ecb4b3ed813f91bb58c934f28a2845d090292/frontend/src/app/modules/boards/board/board-filter/board-filter.component.ts#L18"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</del></td>
    </tr>
  </tbody>
</table>

2020-04-02 09:29 UTC, openprojectci commented on frontend/src/app/modules/boards/boards-root/boards-root.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><del><span data-href="https://github.com/opf/openproject/blob/8d0ecb4b3ed813f91bb58c934f28a2845d090292/frontend/src/app/modules/boards/boards-root/boards-root.component.ts#L7"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</del></td>
    </tr>
  </tbody>
</table>

2020-04-02 09:29 UTC, openprojectci commented
<!--
  0 Errors
  3 Warnings: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/8d0ecb4b3ed813f91bb58c934f28a2845d090292/frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts#L44">frontend/src/app/modules/boards/board/add-list-modal/add-list-modal.component.ts#L44</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/8d0ecb4b3ed813f91bb58c934f28a2845d090292/frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts#L54">frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts#L54</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/8d0ecb4b3ed813f91bb58c934f28a2845d090292/frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts#L41">frontend/src/app/modules/boards/new-board-modal/new-board-modal.component.ts#L41</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-04-02 12:40 UTC, oliverguenther commented
@HDinger the failing PR state is due to PullPreview having failed to start. I stopped the auto-build but the status is still "failed" now.

2020-04-02 13:15 UTC, HDinger requested changes
I think there is one point we did not think about in the beginning: When I am on an action board (e.g. status) and I change the status in the split screen, the list should to be updated, right? 

Other than that. I also found a few other issues:

* When being on a free board, and I update the title, type or assignee in the split screen, the belonging card does not change.

* Sometimes opening the split screen, caused the save icon to appear. However I could not reliably reproduce this one.

* When I have the split screen open, a click on the info icon of another card only selects this card. I would expect it, to show the details in the split screen.

* The selection does not update when I click on a card with the split screen already opened. Also when I reload the page, there is no card selected when the split screen is open.

* When I have a lot of lists next to each other (e.g. 10), the split screen is not visible, although it is open and there are two scrollbars at the bottom.

* In a version board: When I press "Add new list" before all lists are loaded, the select shows no versions. When I close the modal, and press "Add" again, the select isn't loaded at all. There is also an error:
<img width="633" alt="Bildschirmfoto 2020-04-02 um 15 09 01" src="https://user-images.githubusercontent.com/7457313/78253381-98a4c980-74f4-11ea-8c2c-616a667fc4cc.png">



Some styling issues:

* I think we should switch the info and the close icon on the card. Close should always be the last one.

* There is no space between the filter section and the right screen border.

* There are some alignment issues: 
<img width="332" alt="Bildschirmfoto 2020-04-02 um 14 44 53" src="https://user-images.githubusercontent.com/7457313/78253475-bb36e280-74f4-11ea-87a7-d37d89476672.png">

2020-04-02 13:47 UTC, oliverguenther commented
> The selection does not update when I click on a card with the split screen already opened. Also when I reload the page, there is no card selected when the split screen is open.

Selections in the lists were deliberately disabled. We cannot have both the selection service from within the query space AND the focus service from outside. This will not work

2020-04-03 12:20 UTC, lindenthal commented
Hi @oliverguenther,

I just had a quick look at this change. Looks great!

I have one minor remark regarding the position of the info icon the card. Currently it is on the very right. I suggest to keep the remove icon on the very right. What do you think? ![grafik](https://user-images.githubusercontent.com/1019287/78359868-2694b900-75b6-11ea-973a-5a09d5da0b6a.png)

2020-04-03 12:23 UTC, lindenthal commented
Hi @oliverguenther,
I am not sure if I did understand you 100%. You said it is technically not possible to activate the split view from the toolbar similiar to the wp list view, right?

Best
Niels

2020-05-12 11:49 UTC, openprojectci commented on frontend/src/app/modules/boards/boards-root/boards-root.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><del><span data-href="https://github.com/opf/openproject/blob/9e5b6b49777d229a9eba6e0fdc8f169f6da51b80/frontend/src/app/modules/boards/boards-root/boards-root.component.ts#L8"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</del></td>
    </tr>
  </tbody>
</table>

2020-05-13 13:55 UTC, openprojectci commented on frontend/src/app/modules/fields/edit/edit-form/edit-form.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><del><span data-href="https://github.com/opf/openproject/blob/8d69993defa139b4de8d2475c6e45033c66c9883/frontend/src/app/modules/fields/edit/edit-form/edit-form.component.ts#L47"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</del></td>
    </tr>
  </tbody>
</table>

2020-05-15 07:43 UTC, HDinger approved these changes

2020-05-15 07:43 UTC, merged