upgrade to ruby 2.7.1
opf/openproject pull request #8327
Opened 2020-04-29 09:05 UTC by machisuji

2020-04-29 09:11 UTC, ulferts commented
Please also take a look at the documentation e.g. https://github.com/opf/openproject/blob/dev/docs/development/development-environment-ubuntu/README.md and https://github.com/opf/openproject/blob/dev/docs/installation-and-operations/installation/manual/README.md
We seem to tend to forget those places.

2020-04-29 13:39 UTC, ulferts requested changes
That ruby bump seems to be pretty straight forward. 

The failing feature specs fail because of some frozen string modification which shouldn't be to hard to fix. 

But even with those fixed, there is still the issue of the multitude of deprecation warnings, a lot of which do not stem from our code. We could of course disable them but if we do, we should at least have the deprecations in our code fixed to not be surprised later on.

2020-05-04 06:02 UTC, akasparas commented on docs/development/development-environment-osx/README.md
>  **Installing ruby-2.6**
Old version still slipped in the heading

2020-05-04 13:12 UTC, machisuji commented
The deprecation warnings immediately visible outside of our own code are:

- rubytree
- awesome_nested_set
- git
- activerecord
- railties

For the last two a RC is out which should fix the warnings. I don't expect any fixes any time soon for the first two gems, though, as they haven't been updated in a while. We could go ahead and fix the issues ourselves and propose them, I reckon.

The deprecation in git is fixed with an update to 1.7.0 which I included now.
We may want to wait until the activerecord update at least until doing the upgrade.

2020-05-13 08:34 UTC, machisuji commented
A rails update to 6.0.3 resolved some more warnings. But railties and activesupport still use some deprecated features (Passing the keyword argument as the last hash parameter) in some places.

2020-05-13 09:34 UTC, ulferts commented
Thanks for staying on the topic @machisuji. I'll see if I can find a solution for the `URI.escape is obsolete` warning which seems to be all over the place. 
We should probably cherry-pick the rails bump into dev to benefit from it right away as it might still take some time for us to get this PR merged.

2020-05-19 08:57 UTC, ulferts commented
I cherry-picked your commit https://github.com/opf/openproject/pull/8327/commits/54943f50736fa9f01ef271d0570a5ae3f1cfdc41 to a rails bump branch (#8381)

2020-09-02 06:50 UTC, ulferts approved these changes
Good to merge from my side now. There are still a whole lot of deprecations but those we can address separately.

2020-09-02 08:27 UTC, merged