[31973] Allow incoming email to log as Work Package comment
opf/openproject pull request #8494
Opened 2020-07-07 23:11 UTC by Givo29

ref: https://community.openproject.com/projects/openproject/work_packages/31973/activity

2021-01-13 14:06 UTC, b12f commented
Hi @Givo29 and please excuse us for the really long wait. I see tests are missing for sure, but before you put in extra work let me just check with the team if this would close the mentioned work package appropriately.

2021-01-13 22:01 UTC, cleary commented
@b12f thanks for the reply!

@Givo29 and I work together, I raised the original ticket in OpenProject and got Joel to do the work to meet the ticket requirements.

In so far as we are concerned, it meets the ticket requirements and can be closed.

2021-01-14 09:31 UTC, b12f commented
Hi @cleary and thanks for the info! I'll try to get this running on pullpreview and get some feedback from our team.

2021-01-14 10:22 UTC, ulferts requested changes
Hi @cleary, and @Givo29,

and once again apologies for getting back to you with this much delay.

I like the added functionality of being able to add to a work package from an e-mail client without having to have received a matching e-mail first (or modifying some headers by hand).

On the user level I have a couple of concerns/questions. Comments on the code level I have inlined:
* The change will lead to OpenProject parsing every mail address for `/+\d+/`. This runs the risk of false positives. If some other recipient were to have a matching pattern in her/his mail address and that one was ordered before the intended reference, the update would become derailed altogether. How about we only parse the mail address used by the OpenProject instance for receiving updates by e-mail. It will be in the list of cc/to anyway.
* The change will display the header attributes (Subject, Date, To, Cc) only for updates received with a +\d e-mail address. But updates received by responding to received updates (e.g. identified by the header) will not have those header attributes displayed. To me, either all or no updates received via e-mails should have this header. Other tools do not display such a header at all. We might thus want to add a setting to toggle this functionality. 

Additionally, tests are missing.

2021-01-14 10:22 UTC, ulferts commented on app/models/mail_handler.rb
> +    unless addresses.empty?
I know that it is better to be safe than sorry but I cannot see a way the `addresses` can be empty. How did the mail get to the code if it is?

2021-01-14 10:22 UTC, ulferts commented on app/models/mail_handler.rb
> +    addresses = [email.to, email.cc].flatten.compact.uniq.map { |a| a.strip.downcase }
This line of code is added 3 times within the PR and should thus be extracted into a method.

2021-01-14 10:22 UTC, ulferts commented on app/models/mail_handler.rb
> +        receive_work_package_reply(addressMatch.match(/\d+/).to_s)
The addresses are parsed two times here which makes the code harder to understand. The better approach would be to parse the addresses for the matching `/\+(\d+)/` segment (ideally only on the emission email address) and have that returned by a method.

2021-01-14 10:22 UTC, ulferts commented on app/models/mail_handler.rb
> +          #{cleaned_up_text_body}")
The header is not i18ned. A french person might want to have e.g. `Body` translated.

2021-01-14 10:22 UTC, ulferts commented on app/models/mail_handler.rb
> +          CC: #{cc_addresses}
`email.cc&.join(', ')` will suffice here.

2021-01-21 02:45 UTC, cleary commented
@ulferts thanks for the detailed review, we will spend some time on it over the next couple of weeks (in between the other competing work, hopefully)

2022-10-05 14:01 UTC, ulferts commented
Closing old PRs

2022-10-05 14:01 UTC, closed without merging