[31614] Prevent wp attribute fields from repositioning
opf/openproject pull request #8522
Opened 2020-07-23 14:13 UTC by ingamai

### Problem
Due to the CSS column-count calculation, fields will re-position when editing especially larger multi-select fields.

### Changes
Unfortunately, there is no thing like auto-spanning of rows in the CSS 'grid' layout yet, which could prevent larger gaps in the grid. So this PR proposes a solution, which calculates the row span and adapts the layout.

See ticket: https://community.openproject.com/projects/openproject/work_packages/31614

2020-07-23 14:17 UTC, ingamai commented
This still feels a bit 'hacky' but was the only option I could think of with an acceptable amount of effort for this issue. So this is more of a suggestion for a relatively easy and quick solution.

2020-08-04 08:06 UTC, ulferts requested changes
Hi @ingamai. The code alters the order the properties are distributed from being column based to row based. This has been proposed before and, as far as I remember was opposed by @lindenthal.

I also believe that it will not effectively prevent changes to the column distribution upon content changes, e.g. when multiple values are selected in a multi select custom field. 
I can imagine two solutions to this:
* Setting the value selection part of the editable field into `position: absolute` 
* Preventing reflows one the browser has done its work

I'd opt for the later although this can rightfully still be considered hacky. I found a [stackoverflow answer](https://stackoverflow.com/questions/41828769/prevent-css3-columns-from-reflowing-on-content-change) that might do what we need.

2020-08-13 11:21 UTC, openprojectci commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/ce4bc081bf0caa8f8a855472b72d180ee29b7312/frontend/src/app/components/wp-form-group/wp-attribute-group.component.ts#L34">frontend/src/app/components/wp-form-group/wp-attribute-group.component.ts#L34</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-08-13 11:32 UTC, ingamai commented
> I'd opt for the later although this can rightfully still be considered hacky. I found a [stackoverflow answer](https://stackoverflow.com/questions/41828769/prevent-css3-columns-from-reflowing-on-content-change) that might do what we need.

Hi @ulferts,
as discussed last week: After I unsuccessfully tried a few other ways like ‘grid-auto-flow’ or working with a flex layout, I decided that your last proposal was the best option.

So now we are again using the ‘columns-count’ to calculate our layout and after the view is loaded, we will fix the position of the columns with a bit JavaScript to prevent the columns from reflowing.

2020-08-17 12:33 UTC, ulferts approved these changes
From a first impression I'd say the solution is good enough. Let's see if it passes the test of time.

Thanks for being tenacious on this one, @ingamai.

2020-08-17 12:33 UTC, merged