[30007] Allow users to enable CORS on APIv3 resources
opf/openproject pull request #8582
Opened 2020-08-24 08:24 UTC by oliverguenther

Allows a setting and configuration option to allow access to APIV3.

Setting allows us to selectively enable this for cloud instances too.

https://community.openproject.com/wp/30007

2020-08-24 11:49 UTC, ulferts requested changes
Almost complete, but we should change the `origins` value as explained below.

2020-08-24 11:49 UTC, ulferts commented on config/initializers/rack-cors.rb
> +    origins '*'
I think it better to not set the wildcard origin here as this limits the ability to provide credentials (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials). E.g. we could alter the configuration/setting to take a value that is then passed to `origins`.

2020-08-24 13:53 UTC, oliverguenther commented
I made the entire thing accessible by API settings in the UI and let users configure the origins they want to open up to. @machisuji @ulferts please take another look at this if possible

2020-08-25 06:52 UTC, machisuji requested changes, later dismissed
Looking good and working. Thanks! Just one thing:

Right now the "API V3 Cross-Origin Resource Sharing (CORS) allowed origins" are required for it to work. Saving without any origins (which is possible) doesn't actually make CORS work.

So either we make the field required or do the reflective thing and simply allow as origin what ever is in `request.host` during the OPTIONS request.

2020-08-25 07:25 UTC, machisuji approved these changes
:+1:

2020-08-25 07:26 UTC, merged