[34167] Configurable project columns and gantt link
opf/openproject pull request #8610
Opened 2020-08-31 12:43 UTC by oliverguenther

https://community.openproject.com/wp/34167

2020-08-31 12:45 UTC, openprojectci commented on frontend/src/app/components/wp-table/external-configuration/external-query-configuration.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/opf/openproject/blob/9e0205465347a613a3b5b1319785373708e2af7f/frontend/src/app/components/wp-table/external-configuration/external-query-configuration.component.ts#L15"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

2020-08-31 12:45 UTC, openprojectci commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/9e0205465347a613a3b5b1319785373708e2af7f/frontend/src/app/modules/admin/types/type-form-configuration.component.ts#L34">frontend/src/app/modules/admin/types/type-form-configuration.component.ts#L34</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-01 12:55 UTC, ulferts requested changes
A couple of minor things:

* It is possible to configure the query that is applied when the user clicks on the "Open as Gantt view" button. In that configuration, I can select to have the "Project" filter set to some value. Regardless of what the user has selected for the filter,  is then overwritten with the projects currently filtered for. Ideally, we would prevent uselessly setting the value. Admittedly, this is an edge case.
* When all projects are filtered out, the button is still available. Clicking on it, will result in an erroneous query. I suggest to disable the button in such a case. 
* Only the projects of the current page serve as input values for the project filter behind the "Open as Gantt view" button. This is due to the `@projects` scope already being paginated.
* The matrix layout chosen for the selection of the project list was taken over from the work packages settings and suffer from the same shortcomings:
![image](https://user-images.githubusercontent.com/617519/91853211-292d3480-ec62-11ea-9501-7acd5b3b9043.png)
  * Displayed as a matrix when there is no need for it as it is basically a list of checkboxes with their labels. A styling like above would have served the same goal and would allow us to get rid of the matrix: 
![image](https://user-images.githubusercontent.com/617519/91853772-f9caf780-ec62-11ea-86c6-e5a31eed2523.png)
  * The header "Selected Columns" makes no sense
  * The labels are not connected with the checkbox.
  * As a personal preference, I would have listed the "Name" column together with the rest and prevented disabling it. That way, it becomes clearer that it will always be there. 
  * The list does not appear to be ordered.

2020-09-01 12:55 UTC, ulferts commented on spec/features/projects/projects_index_spec.rb
> +      Setting.enabled_projects_columns << "cf_#{invisible_custom_field.id}"
Doing this breaks test isolation as the settings are carried over to the next test.

2020-09-01 12:55 UTC, ulferts commented on spec/features/projects/projects_index_spec.rb
> +      Setting.enabled_projects_columns << "cf_#{integer_custom_field.id}"
Same as above.

2020-09-01 13:42 UTC, oliverguenther commented
I addressed all your remarks with the exception of the first one:

> It is possible to configure the query that is applied when the user clicks on the "Open as Gantt view" button. In that configuration, I can select to have the "Project" filter set to some value. Regardless of what the user has selected for the filter, is then overwritten with the projects currently filtered for. Ideally, we would prevent uselessly setting the value. Admittedly, this is an edge case.

I agree, but there's no easy way to restrict the set of allowed filters with the way we handle these external queries. As an easy fix I could disable the filter tab altogether but that would prevent other more useful filters.

2020-09-01 14:40 UTC, ulferts requested changes
Thanks for the fixes, @oliverguenther. 

I fear I spotted a new bug in there which is caused by archived projects being selected. Again, those will result in an invalid query. I propose to remove them from the projects scope.

2020-09-02 04:58 UTC, oliverguenther commented
> Thanks for the fixes, @oliverguenther. 
> 
> I fear I spotted a new bug in there which is caused by archived projects being selected. Again, those will result in an invalid query. I propose to remove them from the projects scope.

Good catch. I filter for active projects now.

2020-09-02 06:53 UTC, ulferts approved these changes
Good work :+1:

2020-09-02 06:53 UTC, merged