Restore dropped element's original styles when back-end error
opf/openproject pull request #8650
Opened 2020-09-09 08:35 UTC by aleixsuau

https://community.openproject.com/projects/openproject/work_packages/34332

This pull request:

- [x] Restores dropped element's original styles when a back-end error takes place so it is shown again on the table.

2020-09-09 11:29 UTC, ulferts requested changes
Better but not quite there yet as the element is not moved back to its original position so that the user might still think the work package to be replaced:

![image](https://user-images.githubusercontent.com/617519/92592730-543a0880-f2a0-11ea-8e74-37b969a47e37.png)

moving up 3046 above 3045:

![image](https://user-images.githubusercontent.com/617519/92592806-6ddb5000-f2a0-11ea-82b2-c1dbb48fa103.png)

Now 3046 looks as if it where the parent of 3045

2020-09-10 15:58 UTC, aleixsuau commented
Hi @ulferts ,

Thanks for your review. 

The last changes should fix it.

2020-09-11 09:29 UTC, ulferts commented
@aleixsuau The spec failing on travis is also failing locally on this branch. Could you please take a look?

2020-09-11 11:48 UTC, aleixsuau commented
I was too optimistic about tests @ulferts, sorry. Now it is passing.

2020-09-14 13:41 UTC, ulferts approved these changes
👍

2020-09-14 13:41 UTC, merged