Fix: Remove default values for BCF timestamps.
opf/openproject pull request #8674
Opened 2020-09-14 11:37 UTC by wielinde

The default values broke the ActiveRecord timestamp logic. AR did
not set the timestamp values with the real creation date time. Instead it left
the default values that were defined on DB level. The result was that all new BCF issues or viewpoints had identical timestamps.

This PR removes the default values from DB level.

2020-09-14 11:39 UTC, wielinde commented
@oliverguenther Could you please have a look at this tiny PR. It fixes a migration that you created. So it might be a good idea if you could check this PR if this is still aligned with your original intentions.

2020-09-14 12:29 UTC, oliverguenther requested changes
Hi @wielinde ,

Removing the database defaults is not a good solution I believe, since it will prevent bulk imports that do not set created_at/updated_at in Rails:


the error is as follows: the original migration did not use a proc:

```
# incorrect as statically evaluated time :-1: 
change_column_default :bcf_issues, default: DateTime.now

# correct: proc but evaluated in ruby :-1: 
change_column_default :bcf_issues, default: ->(*) { DateTime.now }

# Best: Postgres timestamp :+1: 
change_column_default :bcf_issues, :created_at, -> { 'CURRENT_TIMESTAMP' }
```

Could you change that to the third version?

Best
Oliver

2020-09-14 17:33 UTC, wielinde commented
@oliverguenther Probably I am missing some background here. When would such a bulk import happen? AFAIK we never set timestamp defaults for other models.

2020-09-14 19:14 UTC, oliverguenther commented
I set columns defaults for all newer migrations:

https://github.com/opf/openproject/blob/dev/modules/ldap_groups/db/migrate/20200427082928_ldap_groups_timestamps.rb
https://github.com/opf/openproject/blob/dev/db/migrate/20200708065116_fix_members_inconsistencies.rb
https://github.com/opf/openproject/blob/dev/modules/job_status/db/migrate/20200610124259_extend_job_status.rb

We do have a few cases were we use AR `insert_all` or `upsert_all`. Neither of these set the timestamps through Rails for performance reasons, which is why I believe we should set a default timestamp on the DB in all cases. Rails likes to assert that database constraints do not matter, but it always falls apart in these corner cases.

There is absolutely no reason not to set a column default in any case.

2020-09-15 07:57 UTC, wielinde commented
Thank you @oliverguenther . Makes sense.

2020-09-15 15:03 UTC, merged