[34355] EE: Trial creation modal changes size when error is shown
opf/openproject pull request #8741
Opened 2020-09-29 14:35 UTC by bsatarnejad

Modal size should ideally not be changed while there is an error shown.

2020-09-30 09:30 UTC, ulferts requested changes
This will change the width of the form--field-instructions on all of the pages, e.g. the change leads to this:

![image](https://user-images.githubusercontent.com/617519/94668255-1a44ab00-0310-11eb-9a2d-c6ab2f712f49.png)

being turned into this:

![image](https://user-images.githubusercontent.com/617519/94668360-39dbd380-0310-11eb-983c-3fbb87f3d4dd.png)

Is it possible to have the combination of `max-width` and `width` in the style so that it is not stretched to max-width all the time but cannot exceed the max-width?

2020-10-01 06:29 UTC, bsatarnejad commented
Hi @ulferts yes i tried both width and max-width, but the result is different in several places, for example in this image the width is set to min-content and max-width=500px or in other local tests width=110px and max-width=500px. There are not any identical results, i think it depends on its parent width. As we have this problem in this component, i prefer to add a sass file for its specific styles and fix this bug there. What's your opinion?

![Screenshot from 2020-10-01 08-27-28](https://user-images.githubusercontent.com/62008897/94775396-08badc00-03c0-11eb-82cc-023696ee5446.png)

![Screenshot from 2020-10-01 08-13-50](https://user-images.githubusercontent.com/62008897/94775236-be395f80-03bf-11eb-8241-01f94891b2e4.png)

2020-10-01 07:26 UTC, ulferts commented
Sounds good @bsatarnejad.

2020-10-01 07:59 UTC, openprojectci commented on frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/opf/openproject/blob/ee3402c46a0766828c603a1c6e252ae89c035fac/frontend/src/app/components/enterprise/enterprise-modal/enterprise-trial-form/ee-trial-form.component.ts#L37"></span>Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

2020-10-07 08:30 UTC, ulferts approved these changes
:+1:

2020-10-07 08:30 UTC, merged