Fix #35131:  Cleanup migration for BIM themes
opf/openproject pull request #8834
Opened 2020-11-09 12:27 UTC by wielinde

After the theme migrations elder BIM instances got "OpenProject" set instead of the "OpenProject BIM" theme. This is because "OpenProject" became the default for the `theme` column.

Fix:

BIM instances need to get the theme set in a new
CustomStyle entry AND its colors need to get
written to DB.

When digging around on Saas there were also BIM
instances that had a theme set in a CustomStyle
but did not have the colors written out to DB.

2020-11-11 09:21 UTC, ulferts requested changes
I have only read the code and did not try it. But I have added my code comments.

2020-11-11 09:21 UTC, ulferts commented on modules/bim/db/migrate/20201105154216_seed_custom_style_with_bim_theme.rb
> +    custom_style.theme_logo = theme[:logo].presence
This will always return the logo, right? If so, why not simply omit the `.presence`?

2020-11-11 09:21 UTC, ulferts commented on modules/bim/db/migrate/20201105154216_seed_custom_style_with_bim_theme.rb
> +    # There should not be any DesignColors be present. However, we want to make sure.
typo -> 'be ... be'

2020-11-11 09:21 UTC, ulferts commented on modules/bim/db/migrate/20201105154216_seed_custom_style_with_bim_theme.rb
> +      design_color.save
can be shortened to

`DesignColor.create variable: param_variable, hexcode: param_hexcode`

2020-11-11 09:21 UTC, ulferts commented on modules/bim/db/migrate/20201105154216_seed_custom_style_with_bim_theme.rb
> +    end
This seems a bit complicated. It boils down to two operations:
* Adding the `DesignColor`s
* Adding or updating the `CustomStyle`

Calls to two methods (`set_colors` and `set_style` or something like this) should be in this method then. The `custom_style.save!` really confused me, as it does not appear in the method before and I then have to figure out that the methods before have side effects on the custom_style (but not the `set_colors` method). 

The `set_style` method could be written like this:

```
custom_style = (CustomStyle.current || CustomStyle.new)
custom_style.attributes = { theme: theme[:theme], theme_logo: theme[:logo] }
custom_style.save!
```

2020-11-13 12:39 UTC, wielinde commented
Thank you @ulferts for the review. Good, valid points. The original code was basically a copy and paste plus some simplification. You found the points where my simplification did not go far enough. Thanks.

I manually tested the migration again. Looks good.

2020-11-16 08:28 UTC, merged