Fix/35144 milestones due dates not highlighted
opf/openproject pull request #8915
Opened 2021-01-08 17:33 UTC by aleixsuau

https://community.openproject.com/projects/openproject/work_packages/35144

This pull request:

- [x] Sets the DisplayField.name back to dueDate so it matches one of the query.highlightedAttributes and the date is highlighted when it is overdue or about to. The name is changed by its schema.mappedName, so the correct input type is displayed.

2021-01-08 17:35 UTC, openprojectci commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/op...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/opf/openproject/blob/9b71e6721c3b42a0d9f47f483737e36eb6aad28d/frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts#L11">frontend/src/app/components/wp-table/configuration-modal/tabs/highlighting-tab.component.ts#L11</a> - Please use <code>ChangeDetectionStrategy.OnPush</code> for this component</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-01-11 06:32 UTC, oliverguenther approved these changes

2021-01-11 06:33 UTC, oliverguenther requested changes
You're checking for `isMilestone` with a fixed type check. But in reality, there can be any number of milestones with varying IDs. This will not work.

You can check `this.resource.isMilestone`.

2021-01-11 09:47 UTC, oliverguenther approved these changes

2021-01-13 06:33 UTC, merged