Validate admin guard for all settings writers
opf/openproject pull request #9012
Opened 2021-02-15 19:59 UTC by oliverguenther

2021-02-16 08:04 UTC, ulferts requested changes
Good change overall. Just minor remarks within the code.

Additionally this need rebasing/merging to resolve conflicts with `dev`.

If we invest a bit into harmonizing of the template/menu names, we could remove basically all the code within the individual settings controllers in favour of inheriting it all from a base settings controller.

2021-02-16 08:04 UTC, ulferts commented on app/contracts/settings/base_contract.rb
> +    include RequiresAdminGuard
Do we need the `BaseContract` in this case? There is only the `UpdateContract` inheriting from it.

2021-02-16 08:04 UTC, ulferts commented on app/contracts/settings/update_contract.rb
> +  end
There are no specs for this contract.

2021-02-17 15:17 UTC, ulferts requested changes
The following menu items no longer work:

Emails -> Incoming Emails ---> triggers a redirect
Time and costs -----> Missing template error
Users & Permissions -> Avatars -----> Missing template error
Work packages ----> Clicking on it shows the right page but the submenu is not jumped into which is different from the other menu items with children
Work packages -> Settings ----> see above
System settings -> Repositories -----> Missing template error

2021-02-18 20:05 UTC, oliverguenther commented
Thanks for spotting, test coverage really is abysmal in that area. I've added another spec that traverse all menu items not only as anon/non-authorized, but also as admin and ensure the page renders something and a menu item is selected.

2021-02-22 09:35 UTC, ulferts commented
#### Label missing in avatar settings

![image](https://user-images.githubusercontent.com/617519/108689483-6d0a4380-74f9-11eb-86ab-6ab460ea2f3d.png)

#### Label missing in cost settings

![image](https://user-images.githubusercontent.com/617519/108689668-a80c7700-74f9-11eb-8d83-e9e23c74ea0a.png)

2021-02-22 10:19 UTC, oliverguenther commented
I now use the plugin's name to show the breadcrumb (i.e., "Avatar" and "Time and Costs" in your screenshots).

2021-02-22 14:26 UTC, ulferts approved these changes

2021-02-22 19:46 UTC, merged