Revert removal of groups XML responses
opf/openproject pull request #9024
Opened 2021-02-18 08:57 UTC by oliverguenther

Reverts the removal of XML responses in the groups controller as part of pull request https://github.com/opf/openproject/pull/8949 that we thought were unused anyway. Turns out they're not, thanks to the feedback of @maxemann96.

2021-02-18 10:00 UTC, ulferts requested changes

2021-02-18 10:00 UTC, ulferts commented on app/controllers/groups_controller.rb
> +      end
There are two blocks on `@group.save` which results in double rendering. Probably simply remove the second group.

2021-02-18 10:01 UTC, ulferts commented on app/controllers/groups_controller.rb
> +      end
same as above

2021-02-18 12:32 UTC, oliverguenther commented
Thanks @ulferts , I missed those two blocks. Should be fixed

2021-02-19 07:08 UTC, merged

2021-02-19 23:30 UTC, maxemann96 commented
Thanks for your understanding and time :)