[36296] Add PlaceholderUsers API
opf/openproject pull request #9033
Opened 2021-02-19 21:19 UTC by oliverguenther

https://community.openproject.com/work_packages/36296

2021-02-22 09:16 UTC, ulferts requested changes

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +| members     | Link to collection of all the user's memberships. The list will only include the memberships in projects in which the requesting user has the necessary permissions. | MemberCollection
That link is keyed `memberships` in the implementation which is more fitting anyway as far as I am concerned

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +    Returned if the user does not exist or if the API user does not have the necessary permissions to update it.
In this case it can only be due to the user not existing. 403 handles the other case.

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +                "message": "The specified user does not exist or you do not have permission to view them."
The returned error message is "The requested resource could not be found.". We unfortunately do not have a more specific error message even though our documentation in parts suggests it.

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +                "message": "The specified user does not exist."
See above

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +    Returned if the client does not have sufficient permissions or if deletion of users was disabled in the instance wide settings.
There is no such setting for placeholder_users

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +Permanently deletes the specified placeholder.
I think it would be good to write a sentence or two that this will be carried out asynchronously and might take a while depending on the size of the data.

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +                                "update": {
This should be `updateImmediately`

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +      + name: Filter placeholder users in whose first or last names, or email addresses the given string occurs.
the filters for `status` and `any_name_attribute` are not documented

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +    + filters (optional, string, `[{ "group": { "operator": "=", "values": ["1"] } }, { "name": { "operator": "=", "values": ["h.wurst@openproject.com"] } }]`) ... JSON specifying filter conditions.
The example is not that good here as the name will probably not include an email address in the case of a placeholder user.

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +    + sortBy (optional, string, `[["nmae", "asc"]]`) ... JSON specifying sort criteria.
typo `nmae` -> `name`

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +    Accepts the same format as returned by the [queries](#queries) endpoint.
The available sortBy are not listed

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +## Create Placeholder User [POST]
Please add a 
```
## Create placeholder user [/api/v3/placeholder_users]
```

Above this line as otherwise the filters/sortBy of the index endpoint will wrongfully be displayed for this endpoint as well (see https://docs.openproject.org/api/endpoints/projects/#projects-projects-post). This started when we no longer used aglio for rendering.

2021-02-22 09:16 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +            }
I have started to always list the endpoints in the following order:
View
Create
Update
Delete
List
Schema
Create form
Update form
Auxiliary endpoints

Can you please shift the order in this file accordingly?

2021-02-22 09:16 UTC, ulferts commented on lib/api/v3/placeholder_users/placeholder_user_collection_representer.rb
> +        include API::V3::Principals::NotBuiltinElements
In here, only placeholder users will be elements. So using 

```
element_decorator ::API::V3::PlaceholderUsers::PlaceholderUserRepresenter
```

would suffice

2021-02-22 09:16 UTC, ulferts commented on lib/api/v3/placeholder_users/placeholder_user_collection_representer.rb
> +        include API::V3::Principals::NotBuiltinElements
We might also want to improve the OffsetPaginatedCollection to use a representer of that schema as the default. It could be deduced from the name of the collection representer.

2021-02-22 09:16 UTC, ulferts commented on lib/api/v3/placeholder_users/placeholder_users_api.rb
> +            authorize_any %i[manage_placeholder_user], global: true
This will lead to only users having the `manage_placeholder_user` permission to be able to query the show endpoint for placeholder users which is not as intended. 

In this case, you should be able to simply remove that check as the contracts will catch an unauthorized access to patch/delete/post.

2021-02-22 09:16 UTC, ulferts commented on lib/api/v3/utilities/path_helper.rb
> +          end
Why that indirection, the show page is no v3 path after all. IMO you could just use the `placeholder_user_path` in the representer.

2021-02-22 12:55 UTC, oliverguenther commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +      + name: Filter placeholder users in whose first or last names, or email addresses the given string occurs.
`any_name` doesn't really make sense for placeholders. I added the status filter

2021-02-22 13:08 UTC, oliverguenther commented on lib/api/v3/placeholder_users/placeholder_user_collection_representer.rb
> +        include API::V3::Principals::NotBuiltinElements
done

2021-02-22 13:09 UTC, oliverguenther commented on lib/api/v3/placeholder_users/placeholder_users_api.rb
> +            authorize_any %i[manage_placeholder_user], global: true
If I remove the check, all users will be able to see all placeholder users. Do we need to update the query to have a base scope of `PlaceholderUser.visible` instead?

2021-02-22 14:15 UTC, ulferts commented on lib/api/v3/placeholder_users/placeholder_users_api.rb
> +            authorize_any %i[manage_placeholder_user], global: true
Good thinking. Initially I thought that it would not be necessary but it might make sense not rather disclose less information. So how about we implement the same as you did in https://github.com/opf/openproject/pull/9035 for placeholder users. On the other hand, we don't do the same for groups and also not on the UI (where we should be doing the same for users at the very least)
Let's focus on the placeholders for now where we add the scope and open up a ticket for the other parts.

2021-02-22 14:22 UTC, ulferts commented on lib/api/decorators/collection.rb
> +          .constantize
:+1: I like that. 

We might to eventually generate some of the boilerplate classes, e.g.:
* CollectionRepresenter
* PayloadRepresenter
* CreateService
* UpdateService
* DeleteService

automatically if they do not exist. That way, if they behave like the superclass, nothing needs to be done and one does not feel bad if no test is written for them. That would focus the work even more on where the knowledge is.

2021-02-22 14:25 UTC, ulferts commented on docs/api/apiv3/endpoints/placeholder_users.apib
> +      + name: Filter placeholder users in whose first or last names, or email addresses the given string occurs.
Ok, why does that filter exist anyway?

2021-02-23 10:17 UTC, ulferts commented on lib/api/v3/placeholder_users/placeholder_users_api.rb
> +            authorize_any %i[manage_placeholder_user], global: true
I'm merging the PR now and we can add the visible scope separately.

2021-02-23 10:18 UTC, merged