Documentation for features introduced with 11.2
opf/openproject pull request #9073
Opened 2021-03-08 19:11 UTC by ML-OpenP

2021-03-08 19:34 UTC, ML-OpenP commented on docs/system-admin-guide/users-permissions/users/README.md
> -* **Username** - this defaults to the email address for a new user (unless the user used the self registration). It can be changed on this page. Users cannot change their own user name.
here I mainly removed duplicate blanks

2021-03-09 10:01 UTC, RobinWagner requested changes
Hi @ML-OpenP,
Thank you for updating the documentation and not only including the new features for 11.2 but also updating the existing docs.
It looks really good. While reviewing, I just highlighted a couple of minor points which we could ideally address prior to merging this.
Thank you

2021-03-09 10:01 UTC, RobinWagner commented on docs/system-admin-guide/backlogs/README.md
> +1. Set the work package types which should be used as **story types**. Hold Ctrl. to choose several types. The story types will appear in the Backlogs view (product backlog, wish list, sprint) and ca
We could remove the dot after "Hold Ctrl**.**". While adjusting this, we could change it to "Hold Ctrl (or Cmd on Mac) [...]"

2021-03-09 10:01 UTC, RobinWagner commented on docs/system-admin-guide/users-permissions/roles-permissions/README.md
> +On the bottom of the roles list page there is a link to the **Permissions report**. This shows a grid of existing roles (horizontally) against permissions (vertically); the intersections are ticked i
Very good addition regarding the Permissions report.
The description of existing roles and permissions seems to be switched: The grid of existing roles is shown vertically, while the permissions are shown horizontally.

2021-03-09 10:01 UTC, RobinWagner commented on docs/system-admin-guide/users-permissions/roles-permissions/README.md
> +A "Check/uncheck all" tick box is shown on each role or permission to allow bulk change. **Be careful, this cannot be undone**. If you make a mistake do not save the report.
We should add a comma after "If you make a mistake": "If you make a mistake, do not save the report."

2021-03-09 10:01 UTC, RobinWagner commented on docs/system-admin-guide/users-permissions/roles-permissions/README.md
> +  Users with this role can see all users of your OpenProject instance and can add users and edit name, user-name email address and language of a user. They can't delete or lock users. They can only s
We should add a comma after "username" and add "the" in front of name: "[...] can add users and edit **the** name, username**,** email address, and language of a user."

2021-03-09 10:01 UTC, RobinWagner commented on docs/system-admin-guide/users-permissions/roles-permissions/README.md
> +  The user profile will look like this for them (user name and email address were redacted): ![create-and-edit-users-role](image-20210308180635158.png)
This is a detail but we could write "user name" consistently as "username" (in one word).

2021-03-09 10:01 UTC, RobinWagner commented on docs/system-admin-guide/users-permissions/users/README.md
> +5. **Preferences** - users can change these on their Profile page. Time zone defaults from chosen language. "Auto-hide success notifications" means that they will automatically be removed after some
It may be a bit clearer to write "Auto-hide success notifications" means that **notifications** will automatically be removed [...]" (instead of "they").

2021-03-09 10:01 UTC, RobinWagner commented on docs/user-guide/project-overview/README.md
> +The work package table widget includes a work package table to the project overview. The work package table can be filtered, grouped, sorted according to the [work package table configuration](../wor
Add "to": "e.g. **to** display only work packages with the priority "High"."

2021-03-09 10:01 UTC, RobinWagner commented on docs/user-guide/work-packages/exporting/README.md
> +The exported file will follow the columns that you activated for the work packages table. With it, you can control the columns that will be contained in various formats. Please make sure to [save](..
The sentence "The exported file will follow the columns that you activated for the work packages table." is probably more clear if we replace "follow" with "display"

2021-03-09 11:17 UTC, ML-OpenP commented
review comments are worked in, ready to merge

2021-03-09 11:19 UTC, merged