Add API users form and schema endpoints
opf/openproject pull request #9090
Opened 2021-03-15 13:37 UTC by oliverguenther

- [x] Create form POST /api/v3/users/form
- [x] Update form POST /api/v3/users/:id/form
- [x] Users schema /api/v3/users/schema
- [x] Extend custom fields to UserRepresenter

2021-03-17 08:38 UTC, ulferts requested changes
Apart from what I noted down in code, these are the things I noted when using the API 

* [x] The `name` property is not described in the schema
* [x] `firstName` and `lastName` are described as non writable
* [x] The `password` property is described although it does not exist on the user resource
* [ ] Attributes turn up in the form's payload although they are not writable (e.g. `name`):

![image](https://user-images.githubusercontent.com/617519/111435791-83bf4700-8701-11eb-8523-5c16d44d5c8d.png)

2021-03-17 08:38 UTC, ulferts commented on config/constants/ar_to_api_conversions.rb
> +      lastName: 'lastname',
I believe, and it is really only believe, that these two entries are not necessary as the entries above should handle the conversions in both directions.

2021-03-17 08:38 UTC, ulferts commented on app/contracts/users/base_contract.rb
> +    def assignable_custom_field_values(custom_field)
There is a concern for this: https://github.com/opf/openproject/blob/dev/app/contracts/concerns/assignable_custom_field_values.rb
Admittedly, it seems to only be suitable for list cfs in this case but it should still be good enough since it is used by the other contracts (project, time_entries, work_packages)

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +
There is a section above this line stating that custom fields are not supported yet: 
'Please note that custom fields are not yet supported by the api although the backend supports them.'

Typically, the custom field sporting endpoints note the possibility of having additional links/properties, e.g. https://github.com/opf/openproject/blob/dev/docs/api/apiv3/endpoints/time_entries.apib#L19

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +## Create User [POST]
This endpoint (and also the rest of them) are missing their headings:

![image](https://user-images.githubusercontent.com/617519/111431739-72277080-86fc-11eb-8382-ca362b383896.png)

vs e.g. 

![image](https://user-images.githubusercontent.com/617519/111431685-6176fa80-86fc-11eb-8c38-74465eb4df72.png)

This also leads to the urls being incorrect in parts (e.g. delete is /api/v3/users instead of /api/v3/users/:id). This could also have happened because of the change in indentation for the parameters

The side bar navigation on the website does not list the endpoints at all. :

![image](https://user-images.githubusercontent.com/617519/111432054-d21e1700-86fc-11eb-9262-fcf41e46dddc.png)

vs

![image](https://user-images.githubusercontent.com/617519/111432115-e5c97d80-86fc-11eb-8aa5-9c750150b975.png)

Because of the limitation we currently have on the website, we should not nest the sections. This flaw existed before but it would be a good opportunity to fix the problem. 

Lastly, 'User' is written with uppercase here while resources are (or at least should be) written in lowercase throughout the rest of the headings.

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +## View user schema [GET]
Same problems as above:

![image](https://user-images.githubusercontent.com/617519/111433175-3f7e7780-86fe-11eb-9ea3-bddabe471bbc.png)

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +            "options": {}
Sprinkling in one or two custom fields would help explaining their schema

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +            "firstname": "Matthew"
typo 'firstname' -> 'firstName'

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +            "firstname": "Matthew"
Again, a custom field value (especially a list cf in the `_links` section) would help avoid readers getting confused. I have already answered two or three inquiries about it.

2021-03-17 08:38 UTC, ulferts commented on docs/api/apiv3/endpoints/users.apib
> +        }
The 404 case is missing for the update form.

2021-03-17 13:37 UTC, oliverguenther commented
>  The password property is described although it does not exist on the user resource

The password property is a write-only property so it's not contained in the payload. It can still be set and written as per the schema

2021-03-17 13:46 UTC, oliverguenther commented on config/constants/ar_to_api_conversions.rb
> +      lastName: 'lastname',
Yes looks like it

2021-03-17 14:21 UTC, oliverguenther commented
@ulferts I believe addressed all remarks

2021-03-23 10:01 UTC, ulferts requested changes
* [ ] The property `email` has the key `mail` in the schema
* [ ] In the API description, the :id part is missing from the routes:
![image](https://user-images.githubusercontent.com/617519/112128671-f0858600-8bc6-11eb-834b-7ad420b37f3c.png)


* [ ] In the API description, the schema example seems to be malformed:

![image](https://user-images.githubusercontent.com/617519/112128769-08f5a080-8bc7-11eb-9681-92758fe28933.png)

2021-03-23 14:42 UTC, ulferts approved these changes
:+1:

Thanks for fixing the user API description along the way.

2021-03-23 14:42 UTC, merged