OAuth additions in docs (scope was missing)
opf/openproject pull request #9094
Opened 2021-03-15 17:28 UTC by ML-OpenP

https://community.openproject.org/work_packages/36589

2021-03-22 09:24 UTC, ML-OpenP commented
@wielinde may I ask you to add the technical info here (where the "...." are in the text)? Thank you in advance!

2021-03-26 12:38 UTC, wielinde requested changes
Hi @ML-OpenP, please find my review attached. I also filled in the one .... gap. I hope I didn't miss any other gap. 

One very important thing. Be careful with search and replace. Always review every replacement. Pay extra attention to file names and URIs.

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +![Sys-admin-authenticatoin-OAuth-applications](Sys-admin-authenticatoin-OAuth-applications.png)
Careful when rigorously search and replace "oauth" with "OAuth". The file path here is wrong now.

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +![add-new-oauth-application](image-20210315182306678.png)
That file path is not human readable. The file name does not say what that PNG is about. It is better practice to name files in a way that they are easy to understand.

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +* Auth URL: `https://example.com/OAuth/authorize`
don't replace it here. It's bad practice to use capital letters in URIs

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +* Access Token URL: `https://example.com/OAuth/token`
don't replace it here. It's bad practice to use capital letters in URIs

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +`https://example.com/OAuth/authorize?response_type=code&client_id=<Client ID>&redirect_uri=<Redirect URI>&scope=api_v3&prompt=consent`
don't replace it here. It's bad practice to use capital letters in URIs

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +  --url 'https://example.com/OAuth/token' \
don't replace it here. It's bad practice to use capital letters in URIs

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +Set redirect URLs to `urn:ietf:wg:OAuth:2.0:oob` in both, for your application (see step 2 above) and
oh oh, please don't replace it here.

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +![Sys-admin-authentication-add-OAuth-application](Sys-admin-authentication-OAuth-postman.png)
don't replace it here.

2021-03-26 12:38 UTC, wielinde commented on docs/system-admin-guide/authentication/oauth-applications/README.md
> +3. .................................
Here my 2 cents:

Set the **scope** that the OAuth application will have access to. Chose the API you want to grant access to. Multiple selections are possible. If no scope is checked, per default **api_v3** is assumed.

2021-03-26 15:26 UTC, merged