[35354] Harmonize work package autocompleters (replacing board inline adding wp)
opf/openproject pull request #9226
Opened 2021-05-05 14:03 UTC by bsatarnejad

Replacing the autocompleter in board inline adding wp with the new op-autocompleter component.

1. Remove the ng-select from the template
2. Add op-autocompleter to the template
3. Set the appropriate options for op-autocompleter

2021-05-06 11:12 UTC, aleixsuau requested changes
Hi @bsatarnejad ✋ 

Please take a look at my comments below.

Thanks!

2021-05-06 11:12 UTC, aleixsuau commented on frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
> +      const component = this.ngSelectComponent.ngSelectInstance as any;
The same commented in the other PR, I think we should handle focus, open and close operation inside the OpAutocompleterComponent to avoid polluting the app with setTimeouts that trigger unnecessary changeDetections.

2021-05-06 11:12 UTC, aleixsuau commented on frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.html
> +[defaulData]="false"
multiple, defaulData and closeOnSelect defaults to false, so it wouldn't be needed to pass them down.

2021-05-06 11:12 UTC, aleixsuau commented on frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.html
> +[ngClass]="'wp-inline-create--reference-autocompleter'"
String values can be passed without binding: `ngClass="wp-inline-create--reference-autocompleter"`

2021-05-06 11:12 UTC, aleixsuau commented on frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.html
> +(open)="opened()"
Here we have a method with a setTimeout only to repositioning the ngSelect. This should probably be handled inside the component on every open if it is a common need or provide a @Input repositionOnOpen.

2021-05-06 11:12 UTC, aleixsuau commented on frontend/src/app/modules/boards/board/inline-add/board-inline-add-autocompleter.component.ts
> +          this.ngSelectComponent.ngSelectInstance.close();
It is not the default behavior of the ng-select to close itself when an option is selected?

2021-05-26 09:07 UTC, oliverguenther approved these changes

2021-05-26 09:07 UTC, oliverguenther commented
Comments of Aleix have all been addressed. Rest LGTM

2021-05-26 09:07 UTC, merged