Bug process documentation
opf/openproject pull request #9414
Opened 2021-06-25 09:39 UTC by RobinWagner

Adding bug process documentation to docs

2021-06-25 09:41 UTC, RobinWagner commented
Hi @ulferts,
I added the bug process documentation that we wrote to our docs website.
May I ask you to review this when you have a moment?
Thank you,
Robin

2022-07-27 15:31 UTC, birthe commented
HI @HDinger und @RobinWagner, can we merge this to our docs? We can deploy it on Edge and then add more information to it or do more finetuning.

2022-07-27 17:25 UTC, HDinger requested changes
The part about how we fix the bugs is unfortunately outdate by now. So I'd say we cannot merge it like this. I can work it over, when I have time but it will only be after the release.

2022-07-27 17:25 UTC, HDinger commented on docs/development/bug-process/README.md
> +<u>Summary</u>:
That whole block has changed in the mean time. With our continuous bug fixing process they way we work on the prioritised bugs is different.

2022-07-27 17:26 UTC, HDinger commented
Shall this be published with version 12.2 or is it more something we would like to have internally? If the former, we'd need to change the base branch to `release/12.2`.

2022-08-12 09:03 UTC, cbliard commented
This doc helped me to understand the Bug process when I joined OpenProject. I was surprised to find it in pull requests (Jens pointed me to it). It was January 2022 back then.

I understand that the document is incomplete because it is missing the continuous bug fixing process, but for newcomers I think it still have value. Publishing this content somewhere would give it more visibility.

2024-03-05 13:49 UTC, oliverguenther commented
A different process is now followed and documented here: https://community.openproject.org/projects/development/wiki/query-based-bugfixing

2024-03-05 13:49 UTC, closed without merging