[#38028] Refresh button for Revit Add-in
opf/openproject pull request #9461
Opened 2021-07-15 10:43 UTC by wielinde

https://community.openproject.org/work_packages/38028

2021-07-15 13:42 UTC, oliverguenther commented on frontend/src/app/features/bim/ifc_models/pages/viewer/ifc-viewer-page.component.ts
> +      show: () => window.navigator.userAgent.search('Revit') > -1,
You should probably use the `ViewerBridgeService` which already has this logic defined to check whether the button is used.

2021-07-15 13:44 UTC, oliverguenther requested changes

2021-07-15 13:44 UTC, oliverguenther commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +export class RefreshButtonComponent extends UntilDestroyedMixin implements OnInit, OnDestroy {
UntilDestroyedMixin can be removed

2021-07-15 13:44 UTC, oliverguenther commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +    super();
super() call can be removed without `UntilDestroyedMixin`

2021-07-15 13:44 UTC, oliverguenther commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +    this.state.go('.', {}, { reload: true });
Didn't you change this to reload the work package instead? Is this the desired behavior?

2021-07-15 13:44 UTC, oliverguenther commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +  ngOnInit() {
ngOnInit can be removed

2021-07-15 13:44 UTC, oliverguenther commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +  selector: 'refresh-button',
Selector should be `op-refresh-button` to match our styleguide

2021-07-16 19:10 UTC, wielinde commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +export class RefreshButtonComponent extends UntilDestroyedMixin implements OnInit, OnDestroy {
I also remove `implements OnInit, OnDestroy` as we actually don't implement it.

2021-07-16 19:12 UTC, wielinde commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +    this.state.go('.', {}, { reload: true });
Yes, I found out that I also need to be able to refresh the WP list. This way it works for both scenarios and I don't need to check any contexts like "am I in the list?" or "am I in the WP?" or "both?". Probably that could be better but it does the job.

2021-07-16 19:12 UTC, wielinde commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +  selector: 'refresh-button',
You are right. Thank you.

2021-07-16 19:21 UTC, wielinde commented on frontend/src/app/features/bim/ifc_models/toolbar/import-export-bcf/refresh-button.component.ts
> +  ngOnInit() {
done

2021-08-05 09:34 UTC, oliverguenther approved these changes

2021-08-05 10:29 UTC, merged