[37775] Work package in inconsistent state when deleting value already set to work package
opf/openproject pull request #9488
Opened 2021-07-20 13:19 UTC by HDinger

- [x] Handle WPs before the budget is deleted
  - [x] Either reassign
  - [ ] Or delete the budget from the WP 
- [ ] Add tests
- [ ] Check conflicting modifications

https://community.openproject.org/projects/openproject/work_packages/37775/activity

2021-07-20 13:19 UTC, HDinger commented
Ticket: 
https://community.openproject.org/projects/openproject/work_packages/37775/activity

2021-07-21 10:58 UTC, oliverguenther commented on modules/budgets/app/controllers/budgets_controller.rb
> +      redirect_to destroy_info_budget_path(budget)
I'd suggest to do that in a `before_action` to make the signature of destroy smaller. Then you also don't need the `return` statement.

2021-07-21 10:59 UTC, oliverguenther commented on modules/budgets/app/controllers/budgets_controller.rb
> +   @possible_other_budgets = get_all_project_budgets - [@budget]
Here I'd prefer you use a query to exclude the current one: `@project.budgets.where.not(id: @budget.id)`

2021-07-21 11:00 UTC, oliverguenther requested changes
Thanks for the extra mile to create the spec helper pages. I only have a few remarks

2021-07-21 12:20 UTC, merged