Migrate UserPreference to JSON storage
opf/openproject pull request #9609
Opened 2021-08-25 20:24 UTC by oliverguenther

Removes existing columns of user preferences in favor of a `jsonb` backed settings column that behaves the same way for Rails-based usages, but allows performant queries and indexing (to be added).

**TODOS**

- [x] ~~Previously access through array notation was possible (such as user.pref[:comments_sorting]) but it is not the same as calling `user.pref.comments_sorting`. This has not been addressed yet, and will break compatibility. We could either remove array index or forward to the dynamic methods matcher instead.~~ Array access has been restored, but forwards to the accesor methods instead to correctly catch overridden handling.

2021-08-26 08:18 UTC, ulferts commented on db/migrate/20210825183540_make_user_preferences_json.rb
> +    add_column :user_preferences, :settings, :jsonb
Adding a `default: {}` should [remove the need for the initializer in the model](https://stackoverflow.com/a/38006327/3206935)

2021-08-26 08:23 UTC, oliverguenther commented on db/migrate/20210825183540_make_user_preferences_json.rb
> +    add_column :user_preferences, :settings, :jsonb
~~Unfortunately, it is still needed, as the default is only applied on saving the record. If you build a new preference, `settings` would be nil. The `serialize` ensures that it is always a Hash so we won't need the default value~~

I was wrong, fixed as you mentioned

2021-08-26 13:11 UTC, ulferts requested changes
Works as expected and migration is also looking fine. And hooray for getting rid of another legacy spec file.

2021-08-26 13:11 UTC, ulferts commented on db/migrate/migration_utils/utils.rb
> +      batches = ENV["OPENPROJECT_MIGRATION_AGGREGATE_JOURNALS_BATCH_SIZE"]&.to_i || default_batch_size
We should rename this env var to something like `OPENPROJECT_MIGRATION_BATCH_SIZE` since it is no longer specific to the aggregated journals.

2021-08-26 13:11 UTC, ulferts commented on db/migrate/20210825183540_make_user_preferences_json.rb
> +      pref.save!(validate: false)
Why the `save!` (with the bang) if you use `validate :false`? Is there some `before_*` hook I am not aware of?

2021-08-27 07:52 UTC, ulferts commented on db/migrate/migration_utils/utils.rb
> +      batches = ENV["OPENPROJECT_MIGRATION_AGGREGATE_JOURNALS_BATCH_SIZE"]&.to_i || default_batch_size
I made that fix myself.

2021-08-27 07:53 UTC, ulferts commented on db/migrate/20210825183540_make_user_preferences_json.rb
> +      pref.save!(validate: false)
I'll merge without altering the code here. It should not do any harm having the bang version. In case I am wrong, it can still be changed later on.

2021-08-27 08:15 UTC, ulferts approved these changes

2021-08-27 08:15 UTC, merged