[#38833] BCF API Comments Service
opf/openproject pull request #9684
Opened 2021-09-17 15:02 UTC by Kharonus

- https://community.openproject.org/work_packages/38833
- added requests tests
- added check for expected body length
- added representer and api for bcf_comments
- added create and set attributes service for bcf_comments
- added migration for comment hierarchy
- added create and update service for journals

In this PR the Comments endpoints of the BCF API v2.1 are added to our stack. In addition, some lightweight changes were made, when the added code interfered with existing api code.

2021-09-17 20:22 UTC, oliverguenther requested changes
Mostly LGTM 👏  I only have a few remarks.

2021-09-17 20:22 UTC, oliverguenther commented on modules/bim/app/models/bim/bcf/non_existent_comment.rb
> +  class NonExistentComment < Comment
To avoid this from being saved to the DB by accident, add a method

```ruby
def readonly?
  true
end
```

2021-09-17 20:22 UTC, oliverguenther commented on modules/bim/app/models/bim/bcf/non_existent_viewpoint.rb
> +  class NonExistentViewpoint < Viewpoint
Same here

2021-09-17 20:22 UTC, oliverguenther commented on modules/bim/app/contracts/bim/bcf/comments/update_contract.rb
> +        errors.add :base, :error_unauthorized unless @user.allowed_to?(:manage_bcf, model.issue.work_package.project)
You can move all these validations into the base contract and avoid duplicating them between the create and update contracts

2021-09-17 20:22 UTC, oliverguenther commented on modules/bim/app/controllers/bim/bcf/api/v2_1/comments/api.rb
> +              @issue.viewpoints.find_by(uuid: viewpoint_uuid) || ::Bim::Bcf::NonExistentViewpoint.new
I'm a bit torn with this approach. I can see why you did it: You get validations in the contract and get all errors returned to the user whereas failing the finder would fail the API request with a single error instead.

But you have to instantiate a new record subclass that feels a bit unnecessary. I don't have a better idea, however.

2021-09-17 20:22 UTC, oliverguenther commented on modules/bim/app/controllers/bim/bcf/api/v2_1/comments/api.rb
> +            @comment = all_comments.find_by!(uuid: params[:comment_guid])
Prefer to use `declared_params[:comment_guuid]` as that implies you have declared and validated it. It makes no difference within an `after_validation` block but will prevent errors in case of careless refactorings.

2021-09-17 20:22 UTC, oliverguenther commented on modules/bim/app/services/bim/bcf/comments/update_service.rb
> +                                      contract_class: ::EmptyContract)
Why do you need the EmptyContract here?

2021-09-20 08:12 UTC, Kharonus commented on modules/bim/app/models/bim/bcf/non_existent_comment.rb
> +  class NonExistentComment < Comment
done, good catch

2021-09-20 08:17 UTC, Kharonus commented on modules/bim/app/contracts/bim/bcf/comments/update_contract.rb
> +        errors.add :base, :error_unauthorized unless @user.allowed_to?(:manage_bcf, model.issue.work_package.project)
`BaseContract` is a quite generic class. So, how would you extract the logic? passing specific information as a parameter, like

```
def user_allowed?(permission, entity)
  errors.add :base, :error_unauthorized unless @user.allowed_to?(permission, entity)
end
```

2021-09-20 08:20 UTC, Kharonus commented on modules/bim/app/controllers/bim/bcf/api/v2_1/comments/api.rb
> +              @issue.viewpoints.find_by(uuid: viewpoint_uuid) || ::Bim::Bcf::NonExistentViewpoint.new
I could fail here but then I would kind of circumvent the role of the contract for this route. This is mostly a design decision. From functionality I (and the API by specification) could live with both.

2021-09-20 08:34 UTC, Kharonus commented on modules/bim/app/controllers/bim/bcf/api/v2_1/comments/api.rb
> +            @comment = all_comments.find_by!(uuid: params[:comment_guid])
right, thanks for pointing out. changed!

2021-09-20 08:36 UTC, Kharonus commented on modules/bim/app/services/bim/bcf/comments/update_service.rb
> +                                      contract_class: ::EmptyContract)
Updating a journal's notes requires no further validation that could be put into a contract. The alternative is having an empty class `::Journals::UpdateContract` to satisfy the default convention. Giving an empty contract to the update service call make it more clear IMHO, that this does not need further validation.

2021-09-20 09:16 UTC, Kharonus commented on modules/bim/app/contracts/bim/bcf/comments/update_contract.rb
> +        errors.add :base, :error_unauthorized unless @user.allowed_to?(:manage_bcf, model.issue.work_package.project)
extracted to base contract

2021-09-24 18:07 UTC, oliverguenther approved these changes

2021-09-24 18:07 UTC, merged