Implement workdays for reminder emails
opf/openproject pull request #9720
Opened 2021-09-30 15:07 UTC by oliverguenther

[OP#38708](https://community.openproject.org/wp/38708)

2021-10-01 13:11 UTC, ulferts requested changes
Mostly just nitpicking in the code. 

Continuing nitpicking, the margins 
* between the heading and the first checkbox 
* between the checkboxes
* to the left of the checkboxes (although I don't understand where these should be indented)

![image](https://user-images.githubusercontent.com/617519/135625126-a106df51-d62d-4885-8333-656679f5fce2.png)

are way smaller than in the specification. Those styling changes can also be done in a separate PR where we give the whole page another polish.

The functionality itself is looking solid.

2021-10-01 13:11 UTC, ulferts commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +            workday = Time.now.in_time_zone(z).to_date.cwday
The local time is already calculated a few lines up so this can be shortened to
```
workday = local_time.to_date.cwday
```

2021-10-01 13:11 UTC, ulferts commented on config/schemas/user_preferences.schema.json
> +                },
The type of the array elements could also be specified in here:
```
"items": {
  "type": "integer",
  "minimum": 1,
  "maximum": 7
}

2021-10-01 13:11 UTC, ulferts commented on spec/contracts/user_preferences/update_contract_spec.rb
> +    end
The positive case should be included in the default values.

2021-10-01 13:11 UTC, ulferts commented on spec/features/notifications/reminder_mail_spec.rb
> +describe "Reminder email sending", type: :feature, js: true do
This spec is now duplicated in spec/features/notifications/settings/reminder_email_settings_spec.rb. I assume that is the result of a rebase/merge.

2021-10-04 06:47 UTC, oliverguenther commented
I fixed everything except for the margins, as I'd also vote for a separate PR that does the styling as in here I just want to use the existing components

2021-10-04 07:35 UTC, ulferts approved these changes

2021-10-04 07:35 UTC, merged