Pause reminders functionality
opf/openproject pull request #9730
Opened 2021-10-05 10:08 UTC by oliverguenther

2021-10-12 08:54 UTC, HDinger reviewed
The frontend part looks good to me. I only have two remarks:

1. When setting, a date range, I cannot save the page. I get the following error:
<img width="570" alt="Bildschirmfoto 2021-10-12 um 10 43 04" src="https://user-images.githubusercontent.com/7457313/136924314-b6031ae3-33d1-46a6-92b5-d8638095a29e.png">

2. I have stumbled several times over the fact that I first have to select the checkbox before I can open the datepicker. Maybe we can link this so that a click in the input field opens both the datepicker and the checkbox.

2021-10-12 08:58 UTC, HDinger commented
One other thing, I just noticed: In theory, I can save an empty value by enabling the checkbox but not selecting a date. I don't know if the code handles that case already, as I cannot save even with a date set.

2021-10-12 14:37 UTC, wielinde commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +          times.map do |time|
The indention of that block looks wrong

2021-10-12 14:43 UTC, wielinde commented on spec/contracts/user_preferences/update_contract_spec.rb
> +  describe 'puase_reminders' do
```suggestion
  describe 'pause_reminders' do
```

2021-10-12 15:11 UTC, wielinde commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +            # to compare them with pause_reminder dates which are derived from UTC
Regarding the comment: why are pause_reminder datest derived from UTC? A user thinks in their specific time zone and thus saves them as those.

2021-10-12 15:13 UTC, wielinde commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +            utc_date = local_time.utc.to_date
@oliverguenther I have pretty strong doubts that converting to UTC is the right thing to do. I assume here thate the  pause range saved in user preferences are meant to be in the local time of that user. Here in `times_for_zones` we convert all possible time slots into local times. For all those local time slots we should check if the local date falls within the local pause range. Let's talk about it again, please.

2021-10-12 17:45 UTC, oliverguenther commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +            utc_date = local_time.utc.to_date
The issue with just storing the dates as they are selected in the frontend happens when the selected timezone does not match the actual local timezone of the browser.

This means you select a date X, but your user preference timezone might result in the date being X-1 or X+1. If we normalize the date to UTC, this does not happen. However if you then want to show the local selected date again, this will also fail.

Initially, I wanted to store datetimes in the local timezone to ensure it's what the user wanted. But this would mean the comparison logic to be more complex

2021-10-13 08:29 UTC, machisuji commented on app/models/users/scopes/having_reminder_mail_to_send.rb
>                (user_preferences.settings->'daily_reminders'->'enabled')::boolean
`->>'enabled'` required for pg 9.6 here.

This has been broken since before your PR but still needs to be fixed, please!

2021-10-13 08:29 UTC, machisuji commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +              OR (user_preferences.settings->'pause_reminders'->'enabled')::boolean = false
`->>'enabled'` required for pg 9.6 here too.

2021-10-13 08:29 UTC, machisuji commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +          .flat_map { |zone| build_local_times(times, zone) }
💘

2021-10-13 11:20 UTC, machisuji reviewed
Other than my two comments the backend part looks fine to me! Tested it too.

2021-10-13 11:22 UTC, machisuji commented
One more remark: It's not possible to just pause reminders for 1 day.

2021-10-14 13:17 UTC, machisuji approved these changes
👍

2021-10-14 13:18 UTC, machisuji commented
I'm happy to merge this. If @HDinger and @wielinde are happy too now we can go ahead.

2021-10-15 06:03 UTC, HDinger approved these changes
LGTM 👍

2021-10-18 14:23 UTC, wielinde requested changes
The scope looks great now. However, I believe a couple of indexes might be a good idea for checking if pausing is enabled and if a certain date is within a the user's pause date range. We might alos consider using PostgreSQL's  `daterange` with `@>` contains operator as these ranges are static per user and thus are indexable.

2021-10-18 14:23 UTC, wielinde commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +              (user_preferences.settings->'daily_reminders'->>'enabled')::boolean
I believe it makes sense to create an index on `(user_preferences.settings->'daily_reminders'->>'enabled')::boolean` so that this query becomes faster?

2021-10-18 14:23 UTC, wielinde commented on app/models/users/scopes/having_reminder_mail_to_send.rb
> +               NOT BETWEEN (user_preferences.settings->'pause_reminders'->>'first_day')::date
To improve this query's performance I believe it also makes sense to create an index on a `daterange` on `first_day` and `last_day`, including both extremes of the range.

2021-10-19 11:54 UTC, wielinde commented
> The scope looks great now. However, I believe a couple of indexes might be a good idea for checking if pausing is enabled and if a certain date is within a the user's pause date range. We might alos consider using PostgreSQL's `daterange` with `@>` contains operator as these ranges are static per user and thus are indexable.

Maybe ranges together with "contains" operator `<@` are not the best choice as we actually need the negation of it. And AFAIK there is no `!<@` operator. Maybe staying with `NOT BETWEEN` and having simple indexes on the first_day and last_day are the better choice after all. 

I tried creating those indexes but failed with the syntax. Maybe someone else can spot the issue?

```ruby
require_relative './migration_utils/utils'

class AddIndexesForEmailReminderPause < ActiveRecord::Migration[6.1]
  include ::Migration::Utils

  def up
    add_index :user_preferences,
              "(user_preferences.settings->'pause_reminders'->'enabled')::boolean",
              name: :index_user_prefs_settings_pause_reminders_enabled

    add_index :user_preferences,
              "(user_preferences.settings->'pause_reminders'->>'first_day')::date",
              using: :gin,
              name: :index_user_prefs_settings_pause_reminders_first_day

    add_index :user_preferences,
              "(user_preferences.settings->'pause_reminders'->>'last_day')::date",
              using: :gin,
              name: :index_user_prefs_settings_pause_reminders_last_day
  end

  def down
    remove_index_if_exists :user_preferences, :index_user_prefs_settings_pause_reminders_enabled
    remove_index_if_exists :user_preferences, :index_user_prefs_settings_pause_reminders_first_day
    remove_index_if_exists :user_preferences, :index_user_prefs_settings_pause_reminders_last_day
  end
end
```
This produces me this error:
```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: ...preferences.settings->'pause_reminders'->'enabled') as boole...
```

2021-10-26 06:17 UTC, oliverguenther commented
> > The scope looks great now. However, I believe a couple of indexes might be a good idea for checking if pausing is enabled and if a certain date is within a the user's pause date range. We might alos consider using PostgreSQL's `daterange` with `@>` contains operator as these ranges are static per user and thus are indexable.
> 
> Maybe ranges together with "contains" operator `<@` are not the best choice as we actually need the negation of it. And AFAIK there is no `!<@` operator. Maybe staying with `NOT BETWEEN` and having simple indexes on the first_day and last_day are the better choice after all.
> 
> I tried creating those indexes but failed with the syntax. Maybe someone else can spot the issue?
> 
> ```ruby
> require_relative './migration_utils/utils'
> 
> class AddIndexesForEmailReminderPause < ActiveRecord::Migration[6.1]
>   include ::Migration::Utils
> 
>   def up
>     add_index :user_preferences,
>               "(user_preferences.settings->'pause_reminders'->'enabled')::boolean",
>               name: :index_user_prefs_settings_pause_reminders_enabled
> 
>     add_index :user_preferences,
>               "(user_preferences.settings->'pause_reminders'->>'first_day')::date",
>               using: :gin,
>               name: :index_user_prefs_settings_pause_reminders_first_day
> 
>     add_index :user_preferences,
>               "(user_preferences.settings->'pause_reminders'->>'last_day')::date",
>               using: :gin,
>               name: :index_user_prefs_settings_pause_reminders_last_day
>   end
> 
>   def down
>     remove_index_if_exists :user_preferences, :index_user_prefs_settings_pause_reminders_enabled
>     remove_index_if_exists :user_preferences, :index_user_prefs_settings_pause_reminders_first_day
>     remove_index_if_exists :user_preferences, :index_user_prefs_settings_pause_reminders_last_day
>   end
> end
> ```
> 
> This produces me this error:
> 
> ```
> ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near ")"
> LINE 1: ...preferences.settings->'pause_reminders'->'enabled') as boole...
> ```

The index lines are missing an extra quotation around the cast. However, casting requires to be immutable for the index to work (postgres raises an error like this otherwise: `PG::InvalidObjectDefinition: ERROR:  functions in index expression must be marked IMMUTABLE`). For this to work with datetimes, we would have to create a function which is why I hesitated. Read more at https://stackoverflow.com/a/29761984/420614

I'll commit the index on the boolean

2021-10-26 07:44 UTC, merged