Feature/38933 new notification banner
opf/openproject pull request #9762
Opened 2021-10-18 13:32 UTC by b12f

Closes https://community.openproject.org/projects/openproject/work_packages/38933/activity

2021-10-19 11:20 UTC, HDinger requested changes
I have some remarks which needs to be addressed imho:
* When the toaster pops up, the list flickers. I assume because the elements are reloaded. 
![flicker](https://user-images.githubusercontent.com/7457313/137898042-f236448a-df94-4b25-b154-f3e2b4bebcbf.gif)

* The icon of the toaster looks different than specified.
<img width="357" alt="Bildschirmfoto 2021-10-19 um 13 06 13" src="https://user-images.githubusercontent.com/7457313/137897567-a4ed20f3-b84f-44b6-9205-6c9e0af3bbc8.png"> **vs**
<img width="220" alt="Bildschirmfoto 2021-10-19 um 13 06 32" src="https://user-images.githubusercontent.com/7457313/137897614-55f0dc3b-eb88-4943-ae4b-417c38101440.png">

* I have concerns regarding the long waiting intervals in the tests as they  blow up the execution time heavily. We worked hard in the past to shorten the runt time of tests, and should take care that we don't make them too long unnecessarily. So please have a look wether this long intervals are really necessary.

2021-10-19 11:20 UTC, HDinger commented on spec/features/notifications/notification_center/notification_center_spec.rb
> +        sleep 15
Why is necessary in addition to the waiting interval that is already in the functions?

2021-10-19 11:20 UTC, HDinger commented on spec/support/pages/notifications/center.rb
> +        expect(page).to have_no_selector('.notification-box.-info', wait: 20)
Waiting intervals are always a ad things in tests as they extend the runtime in most cases unnecessarily. 20 seconds (or 30 as below) are a comparable long distance, so you should only use those if absolutely necessary.
I don't quite get where these numbers came from, should 10 be sufficient? And at least for those methods that wait for the toast to appear, a `retry_block` is the solution we use in other places.

2021-10-19 13:31 UTC, b12f commented on spec/features/notifications/notification_center/notification_center_spec.rb
> +        sleep 15
Specifically here, we have to wait for the 10 second bell interval to trigger. 12 seconds should probably also be enough. If we can somehow trigger this to continue when we know the bell fetched the request that should also be fine.

We have to be absolutely sure the bell fetched the latest number of notifications before we do this check, otherwise it'll always return true.

2021-10-19 13:32 UTC, b12f commented on spec/support/pages/notifications/center.rb
> +        expect(page).to have_no_selector('.notification-box.-info', wait: 20)
I took the same numbers as above in the same file. This test only runs long if it is broken, in a normal run the notification box will not be there and there will have to be no waiting.

2021-10-19 13:32 UTC, b12f commented on spec/support/pages/notifications/center.rb
> +        expect(page).to have_no_selector('.notification-box.-info', wait: 20)
Not sure why I bumped below to 30, probably to do some testing. I can reduce that again.

2021-10-22 07:25 UTC, HDinger approved these changes
There is one special case that does not work 100% fine: If I have the split screen of a WP open in the center and a new notification concerning that WP arrives, the blue banner appears and the center reloads correctly. However the split screen itself remains unchanged, resulting in missing data.. 
Since this is an edge case and probably not easily fixable, I am  okay with merging that PR for now and handle this case separately.

2021-10-25 10:20 UTC, merged