fix_css_display_problem
opf/openproject pull request #9777
Opened 2021-10-26 08:30 UTC by lnsane

before

![Snipaste_2021-10-26_16-20-01](https://user-images.githubusercontent.com/20310872/138840324-91df95fb-ac2c-44f8-b933-2bd6c0f3c063.png)

after

![Snipaste_2021-10-26_16-21-11](https://user-images.githubusercontent.com/20310872/138840512-cd4d2be6-904b-484e-a85a-e712136dc341.png)

this is Gantt display problem

2021-10-26 09:25 UTC, b12f commented
Hi @lnsane and thanks for your contribution! I'm unable to reproduce the original issue, could you tell me which browser you encountered it on?

2021-10-26 09:28 UTC, lnsane commented
> Hi @lnsane and thanks for your contribution! I'm unable to reproduce the original issue, could you tell me which browser you encountered it on?

i'm using Microsoft Edge
version 95.0.1020.30  (64 bit)

2021-10-26 10:36 UTC, HDinger requested changes
Hi @lnsane 

thanks a lot for your effort and sharing your solution! I can also not reproduce the issue, maybe you can provide some more information on your setup (operating system, OpenProject version, etc)?
Regardless of that, your solution increases the Gantt header which leads to problems as it overlaps the first row. Instead of increasing the row height, you should try to align the text in the available space. 
<img width="884" alt="Bildschirmfoto 2021-10-26 um 12 26 10" src="https://user-images.githubusercontent.com/7457313/138861244-27a0ea2c-f280-4c55-bede-02129913fe44.png">

2021-10-26 11:17 UTC, lnsane commented
@HDinger 

My OS is Windows10 
i'm using Microsoft Edge version 95.0.1020.30 (64 bit)
openproject version is openproject/community:11 for docker

2021-11-08 07:24 UTC, HDinger commented
I found an older ticket referring to the same problem: https://community.openproject.org/projects/openproject/work_packages/37567/activity

2021-11-11 14:59 UTC, HDinger commented
Since none of us can reproduce the issue, it makes it hard to provide a fix by ourselves. @lnsane did you have the chance to take another look at this?

2021-11-15 09:00 UTC, lnsane commented
@HDinger what can I do for you? 🙂🙂

2021-11-15 10:10 UTC, b12f commented
A couple of questions: 

* Are you experiencing the same issues in e.g. Firefox?
* What is the size of the browser window when this occurs?
* Do you have any assistive technology enabled or are you zoomed in on the page?
* Do you have any browser extensions installed that might interfere with layouting?
* Is the correct font loaded?

I've tried reproducing this on windows 10 in FF, Chrome and Edge and was unable to.

2021-11-16 04:23 UTC, lnsane commented
@b12f 

Q1: 
![微信截图_20211116121850](https://user-images.githubusercontent.com/20310872/141912639-2ca7224f-521f-47bf-9d03-c13263259697.png)
Q2: 100%
Q3: No 
Q4: No
Q5: Yes

i'm Edge version is 95.0.1020.53 64bit

2022-02-15 06:36 UTC, closed without merging