Project index export as CSV, XLS
opf/openproject pull request #9782
Opened 2021-10-27 12:57 UTC by oliverguenther

- [x] Extract common logic from work package exporters where possible
- Add exporter functionality to Projects
  - [x] Add custom fields handling without columns on projects
  - [x] CSV export
  - [x] XLS export
- [x] Add representation formats to projects API

[OP#37674](https://community.openproject.org/wp/37674)

2021-11-03 16:44 UTC, ulferts requested changes
With the PR having the size it has I focused on testing the functionality which seems to work mostly fine with the following exceptions:

- [x] Sorting of projects
Regardless of the order applied to the project table in the UI, the export will always have a fixed order which is the default order of the table (id + hierarchy):
![image](https://user-images.githubusercontent.com/617519/140102942-022b60b3-a3c0-4d48-932a-d5346eed4f13.png)

- [ ] The name of the export file is weird containing a random hash (this has been the case before so it can be ignored unless it is a drive by fix)
![image](https://user-images.githubusercontent.com/617519/140103209-efde2638-540f-403a-8419-f05992bcf871.png)

- [ ] The export contains archived projects by default. This only changes after the filter has been applied specifically. Because of that, the list deviates from the list in the UI.

- [ ] The columns "Latest activity at" and "Required disk storage" are always empty

- [x] The column "Public" uses the values true/false while a bool custom fields uses Yes/No. Google tells me that Excel seems to prefer true/false.

- [x] The export seems to suffer from an N+1 query
![image](https://user-images.githubusercontent.com/617519/140104674-f6dccf7a-4bc0-4d00-8288-c7dd7b2f3802.png)

2021-11-03 16:44 UTC, ulferts commented on app/models/exports/formatters/custom_field.rb
> +      # Checks if this column is applicable for this column
With this comment present a couple of times, it should make sense :)

2021-11-03 16:44 UTC, ulferts commented on lib/api/v3/work_packages/work_package_collection_representer.rb
> +            representation_format_xls_relations,
👍 for cleaning that up

2021-11-04 09:00 UTC, oliverguenther commented
>  The export contains archived projects by default. This only changes after the filter has been applied specifically. Because of that, the list deviates from the list in the UI.

I can't reproduce that. If no filters are present in the query, it uses the default set which is active=true

2021-11-04 09:05 UTC, ulferts commented
> I can't reproduce that. If no filters are present in the query, it uses the default set which is active=true

You are right. I double checked and it is looking fine. Sorry for the false claim.

2021-11-04 09:14 UTC, oliverguenther commented
>  The name of the export file is weird containing a random hash (this has been the case before so it can be ignored unless it is a drive by fix)

That's output from the tempfile that's used to store the export. I added a commit that fixes the filename, but the underlying stored file still has that name and is used by the content-disposition (We have a `filename` column in attachments that's never used apparently). I'd probably want to address this in a subsequent PR and for all attachments if we want to go that way

2021-11-04 09:15 UTC, oliverguenther commented
@ulferts I addressed the remarks except for the filename

2021-11-04 12:58 UTC, ulferts approved these changes
👍

2021-11-04 12:58 UTC, merged