[#39144] Get viewpoint returns too much data
opf/openproject pull request #9783
Opened 2021-10-27 13:38 UTC by Kharonus

- https://community.openproject.org/work_packages/39144
- removed components from get viewpoint payload
- fixed linter issues in several bcf services (added types)
- added interface models for bcf viewpoint api
- fixed parsing of attributes when posting viewpoints
- added getter for viewpoint visibility and selection

Still draft, for running of tests.

2021-10-28 08:42 UTC, Kharonus commented on frontend/src/app/features/bim/bcf/api/viewpoints/bcf-viewpoint.paths.ts
> +          // no expected response payload after delete
is there a better way to turn an observable into `void`? I didn't find it.

2021-10-28 10:13 UTC, b12f requested changes
LGTM otherwise, one nitpick

2021-10-28 10:13 UTC, b12f commented on frontend/src/app/features/bim/bcf/api/viewpoints/bcf-viewpoint.paths.ts
> +        map(() => { }),
I think you can remove the whole pipe call here

2021-10-28 10:13 UTC, b12f commented on frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
> +    return forkJoin({
Out of scope for this PR, but we're starting to roll out a new state management solution in the frontend.

We use [akita](https://datorama.github.io/akita/docs/store/) as the store implementation, and are now creating separate global stores for each data type. For example [the in-app-notification store](https://github.com/opf/openproject/tree/dev/frontend/src/app/core/state/in-app-notifications). Requests to the same resource are shared. There is currently unfortunately no written documentation yet, I'll try to get that going.

2021-10-28 12:07 UTC, Kharonus commented on frontend/src/app/features/bim/bcf/api/viewpoints/bcf-viewpoint.paths.ts
> +        map(() => { }),
Sadly, the return type of `request` is defined by the generic type given to the service, no matter if get, post, put or delete. So, unless we want a return type that is never met (because delete seems to always return `null` on success?), I have to somehow convert the `Observable<BcfViewpointData>` to `Observable<void>`.

2021-10-28 12:51 UTC, Kharonus commented on frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
> +    return forkJoin({
How would it affect the very piece of code you commented on here? Asking from curiosity. ^^

2021-10-28 13:22 UTC, b12f commented on frontend/src/app/features/bim/bcf/api/viewpoints/bcf-viewpoint.paths.ts
> +        map(() => { }),
In that case it might be better to make it explicit: `() => void`

2021-10-28 13:36 UTC, b12f commented on frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
> +    return forkJoin({
You'd send a request [via the resource store/service](https://github.com/opf/openproject/blob/dev/frontend/src/app/core/state/in-app-notifications/in-app-notifications.service.ts#L52), which automatically caches/adds the [request including parameters](https://github.com/opf/openproject/blob/dev/frontend/src/app/core/state/in-app-notifications/in-app-notifications.service.ts#L64) to the global store.

Usually, you also have [feature-based store](https://github.com/opf/openproject/blob/dev/frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts#L62) so that you're one layer of abstraction away from the actual resource store. In the more localized store, you can have data that concerns the feature, but you [can also query the resource store, and fetch the entity collection that is associated with a particular request](https://github.com/opf/openproject/blob/dev/frontend/src/app/features/in-app-notifications/center/state/ian-center.query.ts#L30)

This achieves a couple of things;

1. We move away from HalResource to plain JS Objects for all stateful data
2. All stateful data is immutable by default, and has to go through a `store.update` call to be changed
3. Resources and their collections are deduplicated and cached in the frontend
4. If one part of your application reloads the same collection, all query listeners will get an update
5. The whole state management stays within Observables, preferably until we reach the template and then only use the async pipe

For inter-feature communication, we use the action dispatch pattern, where you [define actions](), [dispatch them](https://github.com/opf/openproject/blob/dev/frontend/src/app/features/in-app-notifications/center/state/ian-center.service.ts#L122), and then [handle them](https://github.com/opf/openproject/blob/dev/frontend/src/app/core/state/in-app-notifications/in-app-notifications.service.ts#L131).

The whole thing ensures one-way dataflow:

1. You have UI event callbacks (e.g. the user clicks something)
2. You call a store method for your local feature (or dispatch an action)
3. This method can do anything with side-effects, usually you update the local store, or ask the global resource services to do something with their store
4. Store updates are then handled by akita, the new immutable state is passed to all query observers
5. The templates rerender

2021-10-28 13:47 UTC, Kharonus commented on frontend/src/app/features/bim/bcf/api/viewpoints/bcf-viewpoint.paths.ts
> +        map(() => { }),
but you cannot use a type keyword to actually return void data. `() => {}` is a lambda that returns a void type. but you cannot return `void` as a keyword.

2021-10-28 13:52 UTC, Kharonus commented on frontend/src/app/features/bim/bcf/helper/viewpoints.service.ts
> +    return forkJoin({
sounds like a really nice way to cache data and create an abstraction between data consumer and fetching the data from API.

Is the store cleared from time to time, or would the cached resources pile up? because this specific resource (a viewpoint with all related data, except the binary snapshot) can grow up to 800 KB each in a very normal use case.

In addition: do you know, when we will be ready to successively implement the store for the existing services?

2021-11-01 10:48 UTC, b12f approved these changes
LGTM frontend-wise

2021-11-01 14:35 UTC, oliverguenther approved these changes

2021-11-01 14:35 UTC, merged