Fix direct upload with a whitelist present that does not contain binary
opf/openproject pull request #9790
Opened 2021-11-03 11:47 UTC by oliverguenther

For IFC models, we bypassed the whitelist so that IFC models can be uploaded regardless of the system's whitelist. For direct upload, however, this was missing.

Also a return was missing in case the attachment could not be found on the S3 upload success call.

2021-11-03 12:54 UTC, wielinde commented
@oliverguenther Sorry, I am lacking some context here. What is the problem you are solving? Currently on production we can upload IFC files a let them get processed to XKT. This is using direct uploads. So what issue/bug did you find that I don't know of?

2021-11-03 13:18 UTC, oliverguenther commented
@wielinde Try to set a whitelist to something like `*.jpg` and try to upload an IFC again. This should fail as the prepare service does not bypass the whitelist and has a `application/binary` content type set to it.

2021-11-03 15:36 UTC, wielinde commented
Hey @oliverguenther thank you for spotting and fixing this bug. Unfortunately when testing locally with direct upload enabled and with an attachment white list present, the IFC conversion does not work anymore (When I remove the whitelist it works). With a whitelist set I can still download the IFC file using its API path in my browser (ie. http://192.168.0.21:4200/api/v3/attachments/66/content). So the file is uploaded. Somehow `ifc_model.ifc_attachment.file.local_file` doesn't have the file. I tried poking around in the fog_file_uploader, however, I wasn't successful.

2021-11-03 15:37 UTC, wielinde requested changes
IFC to XKT conversion fails when using FOG :-/

2021-11-03 16:16 UTC, oliverguenther commented
I don't think that issue is related to this PR, but I'll take a look

2021-11-04 08:34 UTC, oliverguenther commented
@wielinde @machisuji I spotted two issues wrt ifc conversion and direct uploads:

1. In some cases, the ifc conversion will start before Attachments::FinishDirectUploadJob has finished and will fail due to not being able to access the diskfile.
2. The Attachments::FinishDirectUploadJob did not allow customizing the whitelist on call and would always use the default one.

I pushed a fix for each of them

2021-11-04 09:52 UTC, machisuji commented on app/workers/attachments/finish_direct_upload_job.rb
> +    contract.valid?
This doesn't do or change anything.

2021-11-04 10:11 UTC, machisuji commented on modules/bim/app/workers/bim/ifc_models/ifc_conversion_job.rb
> +        return retry_job(wait: 1.minute) if attachment_missing?(ifc_model)
Will this retry indefinitely or give up at some point when the direct upload actually failed for some reason?

2021-11-04 10:12 UTC, machisuji commented on modules/bim/spec/workers/ifc_conversion_job_spec.rb
> +            .and_return ServiceResult.new success: true
I disagree with this whitespace!

2021-11-04 10:13 UTC, machisuji requested changes
I have some minor comments. Could you please have a look?

2021-11-04 10:14 UTC, machisuji commented
> @wielinde @machisuji I spotted two issues wrt ifc conversion and direct uploads:
> 
> 1. In some cases, the ifc conversion will start before Attachments::FinishDirectUploadJob has finished and will fail due to not being able to access the diskfile.
> 2. The Attachments::FinishDirectUploadJob did not allow customizing the whitelist on call and would always use the default one.
> 
> I pushed a fix for each of them

Thanks for looking into and fixing these issues! 👍

2021-11-04 14:45 UTC, machisuji approved these changes
👍

2021-11-04 15:24 UTC, merged